### ISSUE TITLE
No video after renegotiation from audio only call to video call in Video Room plugin

### ISSUE THREAD

**Issue by marcino1** [meetecho/janus-gateway#1206] opened 2018-04-13 12:57 UTC
I have a scenario where two persons enter video room without camera, only with audio. When first person wants to add video I'm renegotiating it, then second person gets video track in onTrack event, but nothing is displayed in video control.
I think that problem may be in SDP exchange, because first person sends SDP with correct video entries but second person gets strange remote SDP with `a=mid:(null)` in video section. 

This problem can be easily reproduced on public janus server with small changes in videoroomtest.js 
To enter room without video I set `videoSend: false` when creating first offer.
And to renegotiate adding video I execute this code: 
```
sfutest.createOffer(
{
	media: { addVideo: true },
	success: function(jsep) {
		Janus.debug(jsep);
		sfutest.send({message: {request: "configure" }, "jsep": jsep});
	},
	error: function(error) {
		bootbox.alert("WebRTC error... " + JSON.stringify(error));
	}
});
```

**Comment by lminiero** [comment] 2018-04-18 09:34
Sorry, missed this issue apparently. I'll have a look and let you know.

**Comment by lminiero** [comment] 2018-04-18 14:25
Looks like the problem is in the SSRC, actually... while it's try that `mid` is not correctly set, as you pointed out, the SSRCs are wrong too:

```
a=ssrc:0 cname:janusvideo
a=ssrc:0 msid:janus janusv0
a=ssrc:0 mslabel:janus
a=ssrc:0 label:janusv0
```

I'll have a look to see what may have caused this.

**Comment by lminiero** [comment] 2018-04-18 15:00
This patch fixes that issue (please let me know if that's not the case for you). Anyway, it causes video to be very delayed (almost a second) when added after the renegotiation, something I'll have to look into.

**Comment by lminiero** [comment] 2018-04-19 13:05
The desync only happens with Chrome, it works fine with Firefox.

**Comment by marcino1** [comment] 2018-04-19 14:07
Thanks, your patch fixed my issue. But I also noticed the delay, and it was even longer (few seconds) when I removed and added video couple of times.

**Comment by lminiero** [comment] 2018-04-19 14:09
Yeah, not sure what's causing it, as if you create a new subscriber the delay isn't there. Besides, it works just fine in Firefox, which makes me think it's a Chrome thing. I added a TODO note to check this in the next few days.

**Comment by lminiero** [comment] 2018-04-19 14:09
Closing this issue in the meanwhile, as the original issue has been fixed.

**Closed by lminiero** 2018-04-19 14:09 UTC

**Comment by lminiero** [comment] 2018-05-14 14:47
Just FYI, I fixed the delay issue, it was a stupid typo in the code... https://github.com/meetecho/janus-gateway/commit/3cbe856a63f42086f8b9b0d42806dd65c59c5f2a
