### ISSUE TITLE
Race conditions when accessing callids and identities hash tables

### ISSUE THREAD

**Issue by cppdev-1** [meetecho/janus-gateway#2818] opened 2021-11-26 08:59 UTC
callids and identities hash tables is not always protected by a mutex. For example,

```
static void janus_sip_session_free(const janus_refcount *session_ref) {
...
if(session->master == NULL && session->account.identity) {
		g_hash_table_remove(identities, session->account.identity);
		g_free(session->account.identity);
		session->account.identity = NULL;
}
...
if(session->callid) {
		g_hash_table_remove(callids, session->callid);
		g_free(session->callid);
		session->callid = NULL;
}
...
```
That leads to race conditions when accessing them.

**Comment by lminiero** [comment] 2021-11-26 09:25
Good catch, thanks! Even though I should check if using mutexes there may cause deadlocks: in fact, in some hashtables we use the object's unref function as a callback when it's removed from the table, so we may be holding the lock when the reference finally gets to 0, which means attempting to do it again would cause a deadlock. I'll have a look later.

**Comment by lminiero** [comment] 2021-11-29 11:25
Yeah as I suspected both `identities` and `callids` are protected by `sessions_mutex`, the same that protects the `sessions` hashtable. As such, adding the mutexes there would definitely lock the plugin if we ended up in `janus_sip_session_free` right after a `janus_sip_session_destroy`, for instance, as that would be called when removing the session from `sessions` and so when we're already holding the lock.

Not sure what the best approach might be here: a simple fix may be, as I said in my previous comment, to just move those two removals to `janus_sip_session_destroy` instead, when we're holding the lock; at that point the session is not valid anymore. At the same time, though, it might be more correct to have those tables hold a reference to the session themselves, like the more recent `messageids` does: in that case the problem would be "who removes the related properties from those tables?", as we'd have to ensure the loop is still running to do that, and an existing event cleans those up.

I guess the former might be an easier way to do that: I'll publish it as a pull request, so that people using the SIP plugin in production can test it and ensure there's no regressions or other problems that may appear because of that.

**Comment by cppdev-1** [comment] 2021-11-29 16:22
Is it guaranteed that in `janus_sip_session_destroy` `janus_sip_session_free` will be called i.e. `session->ref.count` equals `1` right before the line `janus_refcount_decrease(&session->ref);` ?

**Comment by lminiero** [comment] 2021-12-01 12:55
Yes, because we add at least 1 reference when we add a session to the table, and that reference must be removed by `janus_sip_session_destroy` itself (which is the callback automatically invoked when a session is removed from that table).

**Comment by cppdev-1** [comment] 2021-12-01 16:04
@lminiero Just to clarify my previous question: is it possible that `janus_sip_session_destroy` won't execute `janus_sip_session_free` because `session->ref.count` equals e.g. `3` and session will be freed (i.e. `janus_sip_session_free` will be executed) somewhere else?

**Comment by lminiero** [comment] 2021-12-01 16:05
Yes: `janus_sip_session_destroy` only marks as destroyed and decreases a reference, but `janus_sip_session_free` will only be called when the refs get to 0.

**Comment by cppdev-1** [comment] 2021-12-01 16:14
So, is it correct to do
```
if(session->master == NULL && session->account.identity)
	g_hash_table_remove(identities, session->account.identity);
if(session->callid)
	g_hash_table_remove(callids, session->callid);
```
in case session will be freed somewhere else?

**Comment by lminiero** [comment] 2021-12-01 16:17
I believe so, because once a session is destroyed its call-IDs are now invalid: notice the identity and callid properties are still allocated, we're just removing the related voices from the hashtables. But that's the main reason I put it as a PR rather than a commit, to give people time to test this is indeed not breaking anything.

**Comment by cppdev-1** [comment] 2021-12-01 19:27
Basically, my concerns are about removing records from hashtables when session is still alive (not freed yet) but session destroyed flag has been set. Let's wait then.

**Comment by lminiero** [comment] 2021-12-07 09:27
Since I received no feedback on the PR, I merged it.

**Closed** 2021-12-07 09:26 UTC
