### ISSUE TITLE
Videocall: Remote video with poor quality/bitrate

### ISSUE THREAD

**Issue by oscarvadillog** [meetecho/janus-gateway#1861] opened 2019-11-08 11:29 UTC
I'm testing Janus demos and have detected an issue with the quality of the video on one side.

The user who initiates the call sees the remote video with a poor quality (low bitrate ~30kbps). However, it doesn't happen on the other side, the peer who accepts the call has no problem with the remote video. I've tried different computers and networks, it happens all the time.

What could have changed in Janus to cause this? Previous releases didn't have this problem.

Tested here: https://janus.conf.meetecho.com/videocalltest.html

![videocall-issue](https://user-images.githubusercontent.com/4169970/68473039-3506c080-0222-11ea-8326-5cd331027cd2.JPG)

**Comment by lminiero** [comment] 2019-11-08 15:37
We currently support sender-side bandwidth estimation on the PeerConnection that sends the offer (the caller), not on the other side. Good chances are that this is the cause. We already have an open issue to track this requirement, but we don't know yet if and when we'll add support for BWE in Janus, as it's a very complex task. Closing.

**Comment by oscarvadillog** [comment] 2019-11-08 16:10
Thanks @lminiero 

I've tried the [demos ](https://janus.conf.meetecho.com/videocalltest.html) again and now the bitrate is good on both sides. What do you think was the problem? This morning I tried with different computers, networks and Janus servers. 

Do you think it can be improved by using the "set" request to configure the BW limit value (e.g: 256000) in the onremotestream event?

**Comment by oscarvadillog** [comment] 2019-11-09 01:09
This afternoon it worked well for me, but now I have the same problem again.
Why does it sometimes work and sometimes it doesn't? Remote video at 30kbps is very poor and laggy. Don't you think it's something important and makes the Videocall plugin unusable? I've been using the latest version of Chrome...

**Comment by oscarvadillog** [comment] 2019-11-11 08:52
I've tested in several browsers and it only happens in Chrome 78 (the latest stable version).
FF has always worked well for me.
Any idea what's going on @lminiero? Thanks!

**Comment by oscarvadillog** [comment] 2019-11-12 08:15
> We currently support sender-side bandwidth estimation on the PeerConnection that sends the offer (the caller), not on the other side. Good chances are that this is the cause. We already have an open issue to track this requirement, but we don't know yet if and when we'll add support for BWE in Janus, as it's a very complex task. Closing.

@lminiero I can't find the open issue you mentioned. I think this problem affects all users who use Videocall with Chrome...

**Comment by oscarvadillog** [comment] 2019-11-12 10:34
Below some stat charts using chrome insternals:

![Janus1-packetlost](https://user-images.githubusercontent.com/4169970/68664239-4e6c7d00-0540-11ea-95b8-169ba4834e29.JPG)

![janus2-outbound-video-nacks](https://user-images.githubusercontent.com/4169970/68664240-4e6c7d00-0540-11ea-9397-683f2031fd45.JPG)

![janus3-streamtrack-sender](https://user-images.githubusercontent.com/4169970/68664241-4f051380-0540-11ea-8164-d9fa9b2701b4.JPG)

![janus4-inboud-videostream](https://user-images.githubusercontent.com/4169970/68664236-4e6c7d00-0540-11ea-8355-6fd0d6e792d2.JPG)

**Comment by oscarvadillog** [comment] 2019-11-12 11:28
It seems a [bug](https://bugs.chromium.org/p/webrtc/issues/detail?id=10462) using Chrome 78.
With Chrome 80 (Dev/Canary) I haven't been able to reproduce the issue.

**Comment by lminiero** [comment] 2019-12-05 17:56
@oscarvadillog the PR above should make sure the issue you were encountering doesn't happen anymore. Please let me know if that's the case or not.

**Comment by lminiero** [comment] 2019-12-10 10:10
Re-opening so that I don't get 100 issues opened that ask the same thing.

**Comment by lminiero** [comment] 2019-12-10 10:11
Long story short: #1889 fixes it.

**Comment by lminiero** [comment] 2020-02-05 13:46
We merged the PR, so I'm closing the issue.

**Closed by lminiero** 2020-02-05 13:46 UTC

**Comment by oscarvadillog** [comment] 2020-02-05 15:08
@lminiero thinking to tag for a new release soon? hehe

**Comment by lminiero** [comment] 2020-02-05 15:15
I just tagged 0.8.2 yesterday...

**Comment by oscarvadillog** [comment] 2020-02-06 12:35
@lminiero which version/branch are you using in your demo platform?
https://janus.conf.meetecho.com/videoroomtest.html
Using Chrome I am getting ~30-40kbps on the videoroom demo
