### ISSUE TITLE
leave a room bug

### ISSUE THREAD

**Issue by jevian-ma** [meetecho/janus-gateway#1312] opened 2018-07-24 14:19 UTC
this bug is a plugin --- janus.plugin.videoroom
when I send '{"request" : "leave"}', your would returned value is '{videoroom: "event", room: xxxx, leaving: "ok"}'
, but when I send '{"request" : "join", ...}' join a room again. the returned value is '{videoroom: "event", error_code: 425, error: "Already in as a publisher on this handle"}'.
I cann't join a room again, I must destroy janus object and create new a janus object.

**Comment by lminiero** [comment] 2018-07-24 14:21
Not a bug. You can't rejoin in the VideoRoom using the same handle, you have to create a new one. Closing.

**Closed by lminiero** 2018-07-24 14:21 UTC

**Comment by fega** [comment] 2018-07-27 14:50
@lminiero Hello! I was looking in the videoroom plugin docs but there is no mention about this:

> Not a bug. You can't rejoin in the VideoRoom using the same handle, you have to create a new one. Closing.

**Comment by lminiero** [comment] 2018-07-27 14:53
Good point, I'll update the docs later today :+1:
