### ISSUE TITLE
Crash in iceloop with Streaming Demo, while using Alpine distribution

### ISSUE THREAD

**Issue by nswarnkar** [meetecho/janus-gateway#907] opened 2017-05-26 14:18 UTC
Hi,
I am using Alpine distribution(inside docker environment). While every stuff works with Ubuntu docker, but with Alpine I am getting crash always.

Following is backtrace.
https://pastebin.com/embed_js/RUPVgySh

I have taken latest janus code dated 26-May-2017.
I have taken glib 2.44 release, libnice being latest.

Here is sample build scripts(inside docker), which I used:

https://pastebin.com/7B5UvT1p

Please suggest or if any more information is needed, please let me know.

**Comment by lminiero** [comment] 2017-05-26 14:24
As explained in the guidelines, please DO NOT paste huge bunches of text inline. That's what gist/pastebin are for. It's also written clearly in the text you deleted to write your own...

**Comment by nswarnkar** [comment] 2017-05-26 14:36
Done. Thanks for pointing it out....

Please suggest, the logs above.

**Comment by lminiero** [comment] 2017-05-31 16:39
I'm personally not familiar with Alpine, but I do know somebody in our team was experiencing a similar problem when playing with Alpine and Raspberry Pi. Probably some system-specific issue that's causing the problem only there. We'll try and replicate the issue in the next few days.

**Comment by nswarnkar** [comment] 2017-06-01 10:27
Thanks for revert, I will wait.

**Comment by nswarnkar** [comment] 2017-06-07 11:42
Hi Iminiero, did you or team get chance to look into this issue? Thanks in advance.

**Comment by lminiero** [comment] 2017-06-08 10:41
Somebody's looking into that. Will come back with more details if any are found.

**Comment by atoppi** [comment] 2017-06-08 13:21
Hi nswarnkar,
we can replicate the issue on a Alpine Docker with v0.1.13 libnice, both apk package and source compiled.
The core dump seems OK (no invalid pointer and things like this).
I tried removing some CFLAGS on Janus and libnice without success.
This must be further investigated because the issue is clearly related to the specific OS, but unfortunately we're not so familiar with this Linux distro.

**Comment by nswarnkar** [comment] 2017-06-08 20:03
Thanks Toppi for the revert.

Alpine using MUSL instead of standard libc, I doubt that may be creating problem.
Also the crash comes when STUN/TURN phase passes successfully, i.e. during setting up ICE.
could it be that software dependencies(libraries) of Janus are not accurately getting satisfied.?
We also tried with GLIB 2.0, assuming MUSL is working ok. But no luck so far.

**Comment by atoppi** [comment] 2017-06-09 08:51
I tried with previous versions of Alpine, glib and gcc too, without success.
Looking at the core dump the crash happens here in libnice:
`for (i = agent->streams; i; i = i->next)`
so the access to `agent->streams` is causing the issue.
What is strange is that using the debugger (gdb) that value can be safely read and de-referenced.
Maybe something at runtime is making illegal the access to that pointer. I am not an expert in Linux Kernel security features, but it could be possibile that some security enhancements in Alpine may interfere with the current code.

**Comment by atoppi** [comment] 2017-06-09 10:18
I have executed the unit tests on libnice 0.1.13. These are the outputs:

- on Ubuntu 16.04 workstation https://pastebin.com/Librgnen
- on Alpine 3.3.3 Docker instance https://pastebin.com/CEueUzHY

As you can see on Ubuntu everything is OK, while on Alpine there are many seg faults. In particular look at the test-send-recv, line 398.

If you are interested in doing the tests by yourself just issue:
`make check`
in your local libnice repo.

At this point I think the issue is not specific to Janus, but strictly related to libnice.

**Comment by lminiero** [comment] 2017-06-09 10:21
Closing as not a Janus issue.

**Closed by lminiero** 2017-06-09 10:21 UTC
