### ISSUE TITLE
Janus takes the wrong "apisecret" when it's specified within config file and command line

### ISSUE THREAD

**Issue by v-morlock** [meetecho/janus-gateway#1738] opened 2019-08-14 14:33 UTC
Hello! 

When specifying an "apisecret" using command line (-a) and config file, Janus only accepts the one specified within the config file, although the docs say "Options passed through the command line have the precedence on those specified in the configuration file.". 

As soon as the secret is removed from the config file, the one from the command line starts being accepted.

Thanks!
Valentin

**Comment by lminiero** [comment] 2019-08-15 06:55
Currently on vacation, I'll look into this when I'm back.

**Comment by atoppi** [comment] 2019-08-23 15:30
The configuration in Janus is handled like a linked list and the _append_ for the cmd argument is the last one to occur. The issue is that while looking for a configuration option Janus starts traversing the list from the head, so it is using the first option matching the requested name (e.g. _api_secret_), in this case the one in the cfg file.
The fix should be quite easy, however the same error might happen in other parts of the code, so I'll wait for @lminiero to discuss the best approach to adopt here.

**Comment by lminiero** [comment] 2019-08-30 10:02
Apologies for the late reply, I've just come back from my vacation. I'll take a look later today or on Monday.

**Comment by lminiero** [comment] 2019-08-30 13:47
Alessandro is correct, this probably started happening after our refactoring to support the new format. We use `janus_config_add` to store the new value, but that results in a simple `g_list_append`, which means stuff is _added_ to the configuration, but the old values are still there and are not replaced.

One solution might be doing an implicit remove of whatever property has the same name in `janus_config_add`: this should fix it, but would also mean we can't have properties with the same name in the same group (which I feel makes sense, it was always conceived to be that way). I'll have a look at how hard that might be.

**Comment by lminiero** [comment] 2019-08-30 13:56
@v-morlock can you check #1753? That should fix it.

**Comment by lminiero** [comment] 2019-09-03 10:09
Merged the fix, closing.

**Closed by lminiero** 2019-09-03 10:09 UTC
