### ISSUE TITLE
Crash when publish about 1100 streams in multiple rooms

### ISSUE THREAD

**Issue by winlinvip** [meetecho/janus-gateway#2626] opened 2021-04-08 00:34 UTC
Janus [v0.10.10](https://github.com/meetecho/janus-gateway/releases/tag/v0.10.10) on CentOS7.

I create some rooms for benchmark by config `janus.plugin.videoroom.jcfg`  https://pastebin.com/qPkB5cxg

> Limit to about 1000 publishers for each room.

Run janus by:

```bash
cd /usr/local && gdb --args `pwd`/bin/janus --debug-level=3
```

> Reduce the detail log by level3.

Then I publish about 2k streams to room by [benchmark](https://github.com/ossrs/srs-bench/tree/feature/rtc#janus):

```bash
./objs/srs_bench -sfu=janus -pr  webrtc://xxx:8088/1000/livestream -sa a.ogg -sv v.h264 -fps 25 -sn 500 -delay 1200 > /dev/null 2>&1 &
./objs/srs_bench -sfu=janus -pr  webrtc://xxx:8088/2000/livestream -sa a.ogg -sv v.h264 -fps 25 -sn 500 -delay 1200 > /dev/null 2>&1 &
./objs/srs_bench -sfu=janus -pr  webrtc://xxx:8088/3000/livestream -sa a.ogg -sv v.h264 -fps 25 -sn 500 -delay 1200 > /dev/null 2>&1 &
./objs/srs_bench -sfu=janus -pr  webrtc://xxx:8088/4000/livestream -sa a.ogg -sv v.h264 -fps 25 -sn 500 -delay 1200 > /dev/null 2>&1 &
```

> We start about 500 publishers for each room(limit to 1000 publishers).

Use the command to show the threads of janus:

```bash
for((;;)); do 
    cat /proc/$(ps aux|grep janus|grep local|grep -v gdb|awk '{print $2}')/status|grep Threads
    sleep 1
done
```

I found that when threads is about 1000~1200, janus crashed, the logs https://pastebin.com/4BeVuR9b

**Comment by tmatth** [comment] 2021-04-08 00:58
From the line numbers it looks like this isn't the latest Janus, can you try with the latest HEAD? 

Otherwise I'm guessing it's crashing here:
https://github.com/meetecho/janus-gateway/blob/e674f1a808dbd75b762f79de1e1f11080d12e2fd/transports/janus_http.c#L1107

which could probably benefit from error handling should `json_dumps` return NULL, which could happen on error (see https://jansson.readthedocs.io/en/2.8/apiref.html#c.json_dumps), especially as this is parsing a response from some http endpoint that is not part of Janus. That goes for a lot of the other `json_dumps` calls in this transport as well.

**Comment by winlinvip** [comment] 2021-04-08 00:59
@tmatth Thanks, I will try latest release [v0.11.1](https://github.com/meetecho/janus-gateway/releases/tag/v0.11.1), is this version OK?

**Comment by tmatth** [comment] 2021-04-08 01:02
> @tmatth Thanks, I will try latest release [v0.11.1](https://github.com/meetecho/janus-gateway/releases/tag/v0.11.1), is this version OK?

Yeah as it's 2 days old and I don't think any of the related components have changed since that's reasonable. Also if you need to paste large amounts of text/backtraces, please follow this guideline:
> 4. Do **NOT** paste large amounts of text inline in the issue or comments: it makes the exchanges much harder to follow. If you need to provide logs or code snippets, either use a service like [pastebin](http://pastebin.com/) and [gist](https://gist.github.com/), or use the `details` and code block Markdown features to collapse them.

**Comment by winlinvip** [comment] 2021-04-08 01:27
@tmatth I change the config and backtrace to pastebin. And I tried the [janus 0.11.1](https://github.com/meetecho/janus-gateway/releases/tag/v0.11.1), it still exsits https://pastebin.com/UhXZfJDS

The threads number arise up to 1400, then session timeout and threads decrease to about 1100 https://pastebin.com/VauWc0Tv

**Comment by atoppi** [comment] 2021-04-08 06:01
@winlinvip have you tried increasing the mhd connection limit?
https://github.com/meetecho/janus-gateway/blob/master/conf/janus.transport.http.jcfg.sample

**Comment by lminiero** [comment] 2021-04-08 06:55
I don't think the test as made makes sense. 1000 publishers all in the same room means a hurricane of notifications to other participants, growing in an exponential way. That's very likely why it's crashing in HTTP, which is signalling, and is probably caused by the excessive amount of data that is being pushed to many participants at the same time.

Not sure what scenario you were trying to replicate, but if it is simple injestion, then the proper way to use Janus there is to use a separate VideoRoom for each publisher, since they won't subscribe to each other.

**Comment by atoppi** [comment] 2021-04-08 10:16
@winlinvip as @tmatth suggested check in the core file if `response_text` is `NULL`.

That response is not coming from another endpoint. It is a message containing the updated participant list being sent to the other publishers in the same room.

**Comment by tmatth** [comment] 2021-04-08 12:01
> That response is not coming from another endpoint. It is a message containing the updated participant list being sent to the other publishers in the same room.

Oh good call, I should've read closer.

**Comment by winlinvip** [comment] 2021-04-09 00:05
@atoppi Thanks, I will increase the `mhd_connection_limit` and do the benchmark again.

@lminiero It's a benchmark, to get the maximum streams that Janus supports, might not be the "right" scenario, but I think it's ok because it's  a benchmark test.

**Comment by winlinvip** [comment] 2021-04-09 00:33
I modified the [`md_connection_limit`](https://github.com/meetecho/janus-gateway/blob/master/conf/janus.transport.http.jcfg.sample) https://pastebin.com/djc3JM4m and here is the benchmark result:

1. No crash, threads increase to about 1400, it's better :)
2. Threads increase to about 1400, then decrease to about 1300 https://pastebin.com/tqLvy5nX
3. New warnings `ICE failed for component 1 in stream 1` https://pastebin.com/2MrpCdHg
4. Then lots of `Invalid HTTP connection`  https://pastebin.com/W7p1WDc3
5. CPU is limit to about 500% (on 8 CPUs machine), bandwidth limit to about 97MBps (about 1300 publishers) https://pastebin.com/pMEAwXbE

**Comment by winlinvip** [comment] 2021-04-09 01:08
I tried again:

1. Crashed about 200 threads/publishers https://pastebin.com/eSx9crvL
2. Crashed about 1190 threads/publishers https://pastebin.com/qzUt3CEu
3. Crashed about 1200 threads/publishers https://pastebin.com/FVHeRDG6

**Comment by tmatth** [comment] 2021-04-09 02:54
@winlinvip can you try with this patch? https://github.com/meetecho/janus-gateway/pull/2629

It's basically the bare minimum safety check so I'm wondering if something else will blow up down the line.

**Comment by winlinvip** [comment] 2021-04-09 04:26
@tmatth Thanks, I will try it.

**Comment by atoppi** [comment] 2021-04-09 07:50
Thanks for the effort @tmatth !

Anyway I'm still interested in understanding what's going on here.

@winlinvip have you checked in the core dump the variable that is making janus segfault? Is it NULL or a wild pointer?
Could you please test again with libasan enabled?

**Comment by lminiero** [comment] 2021-04-12 10:40
Apparently you're just using this issue to [make us look bad](https://github.com/arut/nginx-rtmp-module/issues/605#issuecomment-817031363) in comparison with your work. Apart from the fact that this is shitty behaviour in the open source ecosystem, it's also completely unacceptable, considering you're basically stress testing using an approach that makes no sense (as I've explained in previous posts), especially if the purpose is broadcasting. You're completely neglecting updates, dependencies, tuning of the server, and so on, just to get numbers that make your magical program look so much better than the others.

I'm not going to play that game, and since it's obvious you have no interest at all in getting this issue fixed, I'm closing this.

**Closed by lminiero** 2021-04-12 10:40 UTC

**Comment by winlinvip** [comment] 2021-04-13 05:23
I'm sorry, it's my fault. 

The test scenario is not very common in traditional meeting scenario, but in modern meeting scenario, it's a possible path, for example, [ZOOM](https://zoom.us/) supports 1000+ participants.

I did do some compares and got some data between some open-source SFU or media server, but I did not just want show how bad is Janus, sorry for the link automatically created from NGINX-RTMP.

I'm really sorry for that.

**Comment by RSATom** [comment] 2021-04-13 05:59
@winlinvip are you sure it's correct compare Zoom with proprietary protocol inside with something WebRTC based? Does Zoom do encryption for every connection?

**Comment by winlinvip** [comment] 2021-04-13 06:04
@RSATom ZOOM does not use WebRTC, but I think it's possible to support 1000+ participates in a room, with encryption. For SFU server, it's ability to support forward as much as possible streams.

**Comment by RSATom** [comment] 2021-04-13 06:16
Maybe it's even possible support 10000+ participants, but the question is how much CPU power it will require to encrypt every connection. And it's not correct compare app encrypting every connection with app which doesn't (or using less strong encryption). That's why I'm asking if Zoom supports encryption. Also, the question is who exactly do encryption, sender or server or both...

**Comment by winlinvip** [comment] 2021-04-13 06:37
Yep, you're right.

1. Why publish 1000 streams to a room?

> Not to publish 1000 streams to a room. The benchmark can publish 10 streams to a room, and benchmark 100rooms, it's also about 1000 streams.

1. With encryption or which algorithm?

> We use the same encryption algorithm, DTLS+SRTP. Sure, we did not compare Janus to ZOOM. I said even 1000 participants, it's a possible scenario, but it's NOT the benchmark scenario.

1. Why compare to other SFUs?

> I did not want to only compare Janus to other SFUs, I just want to do some benchmark about SFU for WebRTC.

OK, If it's not the goal of Janus, I think it's OK to close this issue, and sorry for my fault.

**Comment by RSATom** [comment] 2021-04-13 06:40
@winlinvip If Janus crashes in some usage scenario - it's definitely a bug, and it should be fixed. So this issue still has a meaning...

**Comment by winlinvip** [comment] 2021-04-19 00:56
> @winlinvip can you try with this patch? #2629
> 
> It's basically the bare minimum safety check so I'm wondering if something else will blow up down the line.

I test it, NO crash now, thanks~

https://github.com/meetecho/janus-gateway/pull/2629#issuecomment-822100268
