### ISSUE TITLE
libsrtp 2.4.1 breaks SRTCP for janus

### ISSUE THREAD

**Issue by tmatth** [meetecho/janus-gateway#2767] opened 2021-09-13 12:05 UTC
When testing libsrtp 2.4.1, e.g., the janus videoroom demo page participants' streams will not be viewable. The following error gets logged repeatedly:
```
[ERR] [ice.c:janus_ice_cb_nice_recv:2918] [1379975606905978]     SRTCP unprotect error: srtp_err_status_auth_fail (len=28-->28)
```

The error is always for SRTCP and always `leh=28-->28`).

@lminiero adds:

@tmatth I think I found the issue: there's a typo in the PR you mentioned, as in the new `full_key_length()` helper method there's a typo:

```
    case SRTP_AES_GCM_256:
        return SRTP_AES_ICM_256_KEY_LEN_WSALT;
```

which should be `SRTP_AES_GCM_256_KEY_LEN_WSALT` instead. As it is, for AES-GCM-256 it's requiring the whole key to be `32+14` bytes long instead of `32+12` (which is the correct length). We tried fixing the typo in a local build and it works as expected.

_Originally posted by @lminiero in https://github.com/meetecho/janus-gateway/issues/1507#issuecomment-918077641_

**Comment by lminiero** [comment] 2021-09-13 12:27
I added a comment on the libsrtp PR to notify them about the typo. If they confirm that's where the issue is, we can close this.

**Comment by lminiero** [comment] 2021-09-14 08:59
My PR with the fix for the typo has been merged, so we can close this. Thanks for catching the issue, that was fast! :smile:

**Closed by lminiero** 2021-09-14 08:59 UTC

**Comment by alexamirante** [comment] 2021-09-14 09:57
As a side note, please bear in mind that libsrtp `v2.4.1` is still broken and cannot be used. The fix has been merged in master and will soon be in the `v2_4_x_throttle` branch. I hope they'll tag a v2.4.2 ASAP.

**Comment by mjhowell** [comment] 2021-09-21 17:43
I had the same problem in my environment with libsrtp 2.4.1. FWIW, 2.4.2 is now tagged, and working for me.
