### ISSUE TITLE
Missing media receiving after removing and immediate readding video

### ISSUE THREAD

**Issue by JanFellner** [meetecho/janus-gateway#2807] opened 2021-11-15 13:30 UTC
I have an issue where janus is missing to send me a media receiving event in the videoroom.
I maybe just need a hint where and how to solve it. This ticket as is reporting the core issue.

I have a settled peerConnection containing audio and video. webrtcup and media receiving received for both the audio and the videotrack.

If i now disable and enable the video i would expect janus to send me the media receiving flag as the media actually has changed but janus seems to have stored the flag internally and not have reset it as i remove the video (by a=inactive).

Thus i do not reliably get the information that media is transported.

original SDP https://pastebin.com/eEq2Rf97 (after that everything is settled)
inactivate video SDP: https://pastebin.com/92khiwXx
reenabled video SDP: https://pastebin.com/mV5GA9je

**Comment by JanFellner** [comment] 2021-11-15 13:39
reopened as i the original ticket did not contain the description...

**Comment by JanFellner** [comment] 2021-11-15 13:41
The issue in the businesslogic is that when disabling i reset my internal status as i know there won´t be any media any longer. I do not wait for any media receiving false from janus.
But on the other hand after reenabling i would need that event.

So i understand that janus is caching that info to not send it all the time but the cache should get cleared once sdp is exchanged.

**Comment by lminiero** [comment] 2021-11-15 13:48
Janus has timers to detect missing media: I think for the `receiving:false` event we need to have one second without receiving any media. This means that if the renegotiation is quick enough, you won't get it.

**Comment by JanFellner** [comment] 2021-11-15 14:16
Do you think its feasable to intercept the sdp handshake here and to enforce a resend when sdp for that media has changed?

I have seen that issue in the past and tried to overcome it with checking the stats but that tries to tackle something in a roundabout fashion... (Cause on the one side you have the media flag and on the other the stats that will always delay everything)

**Comment by JanFellner** [comment] 2021-11-16 11:56
The PR fixes the issue. Check comments in the PR for what has changed

**Comment by lminiero** [comment] 2021-11-16 13:06
To be honest, I still don't understand exactly what the problem is, so it's hard for me to review your PR, or know what to review. It seems to be you may be expecting too much from an event that is not meant to be immediate nor particularly informative: it's actually quite slow, since it will typically only notify you about a second later or so. As a consequence, from a quick glance I feel the PR changes too much for me to be really comfortable with it, especially if this can be solved with less changes and a more trivial approach.

Can you please elaborate on exactly what happens, what changes, and what you expect to happen, to see if I can replicate it somehow?

**Comment by JanFellner** [comment] 2021-11-16 15:19
In the end i need to know whether a peerConnection transports media or not. I need to know that from the server side as i handle everything serverside. So i rely on the media event from janus which is working reliabily but not if changes on the peerConnection happen fast.

If my client disables video the sdp is handed over to my server which hands it to janus. As i know that the media was removed (a=inactive) i update my status instantly (there won't be any media) as the client removed it. If the client now enables video again. (as seen in the original SDP messages above simply by changing a=sendonly i wait for janus to tell me about the state change that media is now available. But it is not coming as the change was happening too fast.

In the end i have a very simple state engine with 4 states:
- idle
- initiating
- stable
- failed

When the client starts to publish media the state changes from idle to initating and once janus reports receiving to stable.
If i remove media the state changes to idle with the removing.
If the client now triggers the publish again i go again to initiating but i never reach stable cause the event from janus that media is transported is missing.

I do not care whether the event come synchronous or asynchronous. It just needs to be reliable which currently is sadly not the case and the PR solves it.

That was the prosa words.
Now (as i also like it :)) the 100% answers to your questions.

Can you please elaborate on exactly what happens,
* I have a settled peerconnection. (including audio / video)
* I remove video by a=inactive
* I add video by a=sendonly (within 1 to 1.5 seconds)

Expectation is now that i get a media receiving information from janus as the sdp has changed
The current situation is that i get nothing 😖

I guess that you should also be able to see that in the samples if you disable and reenable the camera quick enough.
The media receiving event is missing.

**Comment by lminiero** [comment] 2021-11-16 15:25
> Expectation is now that i get a media receiving information from janus as the sdp has changed
> The current situation is that i get nothing confounded

But in that case, considering the change is fast, I think that's expected. The `media` event will tell you if Janus received no audio or video at all in the last second: if within that second you were first sending it (original SDP), then media briefly stopped (a=inactive) and then flows again (new SDP), then as far as that monitor is concerned, sending video was true at time=N-1, and is still true at time=N, which means media is still flowing and that's why it won't notify you. That event is only meant to tell you when more than a second passed without receiving any media at all: if will not tell you if within a second there were moments with no media.

If you need finer grain notifications you may want to rely on event handlers instead.

**Comment by JanFellner** [comment] 2021-11-16 15:47
If you don´t align with the proposed PR what about adding a poll mechanism that allows me to fetch the media state.

The problem is still that if you have a second entity that persist it´s own state (i just saw the janus node adoption you started some days ago which would ease such implementations...) This entity cannot work with the current approach. And i simply search for a way to overcome that problem.

Should i in the second entitiy persist the media receiving flag even if my client says me there won´t be any media (It does not really make sense...)

If you say event handlers are the solution i am back at the point where i on the one side get a media event and on the other side have statistics i need to analyse and map with each other.

The change i made is really super simple. If the sdp changes from active to inactve or vice versa i enforce a resend of the media status after 2 seconds. Thats it. (No rocket science, just a stupid resend and only in case the sdp was touched, no change in the other handling)

**Comment by JanFellner** [comment] 2021-11-16 15:56
I don´t care about any timining, i don´t need it granular or faster, the issue i have is that if i disable it, i reset my state, enable it again and wait for janus to tell me. Hey i have media which is missing as the ice state is not "resetted" if i exchanged new sdp.

**Comment by lminiero** [comment] 2021-11-16 16:10
Got it. I think my main issue with this is semantic, since with this new approach you can be in a scenario where the last message you received was "receiving:true" (media was flowing), and then after a while you get a new "receiving:true" (the one triggered after the two renegotiations) without going through a "receiving:false" first, which seems "wrong" to me (even though I understand whay you mean and why you need it).

I guess that the "proper" way to fix that would be to trigger a "receiving:false" notification when we handle a negotiation that disables incoming media (a bit like we can issue a "receiving:true" right away, and not after a second, when we switch to the active state because of an incoming packet), so that when media starts flowing again after the renegotiation we can notify you right away, but there we have timing issues due to the fact that the thread handling the SDP update is different from the ICE loop, and besides, the endpoint may still be sending media until an SDP update becomes definitive (which could incorrectly revert a "receiving:false" we just sent). I guess that one possible approach may be queueing an event on the event loop to schedule a "receiving:false" for the affected medium, which in that case wouldn't race with the incoming traffic: I'll have to think if there can be any drawback in that case (and more importantly, I need to prepare a small function to replicate the renegotiation scenario you're using).

**Comment by JanFellner** [comment] 2021-11-16 19:12
Okay, so from the problem situation we have an alignment that the current implementation causes issues.

I was thinking about the receiving:false beeing kind of implicit because the client said i don´t want to send it to you any longer.
So receiving=false would have been some implicit logic like as if i get a hangup the receiving:false would also not get send.

But if you have a good idea how to solve it differently i am super (!) happy cause this issue is causing me trouble since a year and i always tried to circumnavigate it with side effects.

Sending the receiving false with the sdp might definetly be a challenge but i think the state enum inside the janus_ice_stats_info improves it cause you can also implement some going down going up if the sdp changes. Maybe that does not require a que.

**Comment by JanFellner** [comment] 2021-11-23 15:45
Is there anything i can do? Prep a multistreaming sample to get janus to behave as described?

**Comment by lminiero** [comment] 2021-11-23 15:48
Nothing you need to do at this stage, thanks! The ball is on my side, now, as I need to check if there may be a different and more trivial way of doing the same thing, that could be automatically be ported to multistream as well when merged. I'm just busy on a few too many things at the same time, so I couldn't find time for that yet: I'll try to do this by the end of the week and keep you posted :+1:

**Comment by JanFellner** [comment] 2021-11-30 13:30
solved by https://github.com/meetecho/janus-gateway/pull/2824 👍

**Closed** 2021-11-30 13:34 UTC
