### ISSUE TITLE
[1.x] GLib Error

### ISSUE THREAD

**Issue by dnish** [meetecho/janus-gateway#2882] opened 2022-02-11 15:08 UTC
**What version of Janus is this happening on?**
Latest git commit (Janus v1.0.0)

**Was this working before?**
Error is new

**Is there a gdb or libasan trace of the issue?**
https://pastebin.com/j1eWaDdA

**Comment by lminiero** [comment] 2022-02-11 15:10
Data is insufficient. Everything works fine here.

**Comment by tmatth** [comment] 2022-02-11 15:11
Reminiscent of https://groups.google.com/g/meetecho-janus/c/xW3iFdJTP_Q

**Comment by lminiero** [comment] 2022-02-15 14:50
Without info on which hashtable lookup caused the problem, there's nothing we can do. Debugging via either libasan or gdb should clear that out.

**Comment by lminiero** [comment] 2022-02-17 10:38
@dnish any update?

**Comment by lminiero** [comment] 2022-02-21 15:27
I'll assume you're not interested in a fix anymore, so I'll close it as a potential duplicate of #2896. Check the discussion there if you're using the Streaming plugin too.

**Closed by lminiero** 2022-02-21 15:27 UTC
Labels: needinfo, multistream
