### ISSUE TITLE
[sip] Even when call is declined

### ISSUE THREAD

**Issue by saghul** [meetecho/janus-gateway#267] opened 2015-06-26 14:08 UTC
(I thought I'd open an issue before making a patch this time around)

The SIP plugin emits an event of type "ack" when the user uses the "decline" command to reject an incoming call: https://github.com/meetecho/janus-gateway/blob/master/plugins/janus_sip.c#L1234

This is kind-of weird, since the initial decline command already got an "ack" response. @lminiero what do you think about emitting a "declined" event instead? It could also be a "hangup" event with reason "Call Declined".

**Comment by saghul** [comment] 2015-06-26 14:13
(Once agreed I volunteer to write the patch)

**Comment by lminiero** [comment] 2015-06-26 14:28
Closing as duplicate of #268

**Comment by lminiero** [comment] 2015-06-26 14:28
Ops sorry they are different issues... my bad!

**Comment by lminiero** [comment] 2015-06-26 14:32
This makes sense, as all other events have ad-hoc names (see "calling", "hangingup", etc.). Since an event to notify the actual end of the session is notified anyway later or, and this only acts as an ack to the message, I'd be more for a "declining" than a "declined" event, though (but that's semantics).

**Comment by saghul** [comment] 2015-06-26 15:56
But hangingup is always followed by a hangup, whereas in this case there
would be no declined event after the declining, AFAIS. I'll make a patch
and we can discuss further details with the code in front :-)

**Closed** 2015-06-30 08:26 UTC
