### ISSUE TITLE
SIP Plugin: Chrome Janus to Chrome Janus call with Video fails SDP Parse Error in Browser

### ISSUE THREAD

**Issue by shrhoads** [meetecho/janus-gateway#509] opened 2016-04-29 17:48 UTC
Whenever calling another Janus Extension using the SIP Plugin and Video is enabled, SDP parsing fails:

```
adapter.js:367 Uncaught (in promise) Failed to parse SessionDescription.  Failed to parse video codecs correctly.
(anonymous function) @ adapter.js:367
(anonymous function) @ adapter.js:359
webkitRTCPeerConnection.(anonymous function) @ adapter.js:358
prepareWebrtcPeer @ janus.js:1579
pluginHandle.handleRemoteJsep @ janus.js:854
janus.attach.onmessage @ siptest.js:263
handleEvent @ janus.js:444
o @ jquery.min.js:2
p.fireWith @ jquery.min.js:2
w @ jquery.min.js:4
d @ jquery.min.js:4
janus.js:939 Message sent!
```

I did this test using the https://janus.conf.meetecho.com/siptest.html demo site and latest Chrome on 2 different boxes (but I think you can get the same error from 2 chrome tabs on the same machine).  It only seems to occur on Video calls.  If you want to try it out with my sip registration server I can send you credentials.

**Comment by saghul** [comment] 2016-04-29 19:20
Can you paste the SDPs? If you're using Chrome 50 with H264 enabled it
creates a not so compatible SDP, as the profile-level-id is missing.

**Comment by shrhoads** [comment] 2016-04-30 00:23
I actually was out of date with version 49, I loaded 50 and I did see a new error, not sure if I missed it before:

```
adapter.js:367 Uncaught (in promise) DOMException: Failed to set local answer sdp: Failed to push down transport description: Offerer must use actpass value for setup attribute.(anonymous function) @ adapter.js:367
janus.js:939 Message sent!
```

The invite SDP that janus sent out looked like this:

```
v=0
o=- 5507759260079626829 878133599412532685 IN IP4 67.205.67.144
s=-
t=0 0
m=audio 10034 RTP/AVP 111 103 104 9 0 8 106 105 13 126
c=IN IP4 67.205.67.144
a=rtpmap:111 opus/48000/2
a=fmtp:111 minptime=10; useinbandfec=1
a=rtpmap:103 ISAC/16000
a=rtpmap:104 ISAC/32000
a=rtpmap:9 G722/8000
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:106 CN/32000
a=rtpmap:105 CN/16000
a=rtpmap:13 CN/8000
a=rtpmap:126 telephone-event/8000
a=rtcp-fb:111 transport-cc
a=maxptime:60
m=video 20030 RTP/AVP 100 101 116 117 96 97 98
c=IN IP4 67.205.67.144
a=rtpmap:100 VP8/90000
a=rtpmap:101 VP9/90000
a=rtpmap:116 red/90000
a=rtpmap:117 ulpfec/90000
a=rtpmap:96 rtx/90000
a=fmtp:96 apt=100
a=rtpmap:97 rtx/90000
a=fmtp:97 apt=101
a=rtpmap:98 rtx/90000
a=fmtp:98 apt=116
a=rtcp-fb:100 ccm fir
a=rtcp-fb:100 nack
a=rtcp-fb:100 nack pli
a=rtcp-fb:100 goog-remb
a=rtcp-fb:100 transport-cc
a=rtcp-fb:101 ccm fir
a=rtcp-fb:101 nack
a=rtcp-fb:101 nack pli
a=rtcp-fb:101 goog-remb
a=rtcp-fb:101 transport-cc
```

**Comment by saghul** [comment] 2016-04-30 06:57
> I actually was out of date with version 49, I loaded 50 and I did see a new error, not sure if I missed it before:

That looks related to a datachannel connection.

> The invite SDP that janus sent out looked like this:

The SDP looks fine to me :-S

**Comment by lminiero** [comment] 2016-04-30 09:30
That can't be what Janus sent to the browser, I see neither DTLS nor ICE stuff, and other stuff we typically add is missing as well. Unless you mean that's what Janus sent to the SIP endpoint? Which again doesn't help here, as it's the browser that's complaining about something it received, so we need the WebRTC side of things.

Please post (and not inline, but on pastebin/gist/whatever that doesn't make these messages needlessly long) the SDP that Janus is sending to the browser, as apparently the problem is happening there.

**Comment by shrhoads** [comment] 2016-04-30 12:25
Right that was SDP that was sent in the SIP INVITE.  This is what the browser saw after Janus processed the SIP INVITE SDP and passed it to the browser:

http://pastebin.com/39mfDQeC

**Comment by shrhoads** [comment] 2016-04-30 12:36
I don't know if this is it, but I found this discussion:

https://bugs.chromium.org/p/webrtc/issues/detail?id=2782

> So a variant of pc1_sdp_munge.html is available at http://hancke.name/tmp/updatefails
> It has two JS functions, 'works()' and 'fails()'.
> The difference is that (which is a bug on my side) my offer contains an a=setup:active line. fails() therefore replaces the a=setup:actpass with a=setup:active

**Comment by lminiero** [comment] 2016-05-10 07:36
Sorry for the late reply. I don't see anything weird in the SDP (apart from the rtx retransmission stuff we should remove, as we currently don't support the separate SSRC for retransmissitted packets). I only see VP8 and VP9 in there, which should both be supported by the latest Chrome.

That said, are you using the latest Janus? The differences are normal, as we mostly recreate the SDP from scratch when passing it to a plugin and then outside again: only the codec stuff remains, everything else (ICE, DTLS, WebRTC semantics) are regenerated.

**Comment by shrhoads** [comment] 2016-05-11 14:31
Still fails, rather than pasting the logs, it's easy to reproduce, if anyone is interested, just log in with 2 computers with the Janus https://janus.conf.meetecho.com/siptest.html page with these credentials:

sip:v18.icoa.com   sip:5998@v18.icoa.com  5998   Register using plain secret
sip:v18.icoa.com   sip:5999@v18.icoa.com  5999   Register using plain secret

Then click "use video" and call from one to another.  If you want to test extensions 6010-6079 are also available for testing.

**Comment by lminiero** [comment] 2016-05-11 14:35
Thanks for the info. I'm currently abroad, I'll test when I'm back home.

**Comment by lminiero** [comment] 2016-05-13 12:11
Not sure what's causing the failure, but one thing I noticed is that Chrome answers with all the codecs in there, while Sofia SIP in the SIP plugin seems to only leave one codec in there, both for audio and video. Anyway, although it only leaves one codec in the m-line, the stack still leaves all the rtpmap and other stuff related to now removed payload types in there. I don't know if that may be what's confusing Chrome, although if so it's a way too strict behaviour.

I'll check if that's the cause of the problem. I see two possible solutions here:

1. figure out why Sofia SIP is taking decisions on dropping the other codecs in the list, and make it stop (it shouldn't be its call);
2. fix this at the Janus core level, where we should make sure that SDP attributes related to missing payload types should be removed.

**Comment by lminiero** [comment] 2016-05-13 13:16
Found [SOATAG_RTP_SELECT](http://sofia-sip.sourceforge.net/refdocs/soa/soa__tag_8h.html#a220eb035c9fc32c104e4c81aab32a113), that disciplines which codecs are to be included in an offer, and changed the default (single, best common codec) to `SOA_RTP_SELECT_ALL` (all codecs). This does what it says, but I still get the same error in Chrome, which means that's not what caused the problem in the first place.

I'll check again later to see if I can find something else.

**Comment by saghul** [comment] 2016-05-13 14:48
Please don't do that by default. Manay SIP endpoints don't know how to deal with an answer with multiple codecs. Or at least make it optional letting the current behavior as the default. Sad but true.

**Comment by lminiero** [comment] 2016-05-13 14:53
Yeah, it doesn't seem to solve anything anyway! The main problem we have with the "single" codec stuff is that Sofia SIP doesn't also remove the attributes referencing payload types that have been removed, only the numbers from the m-line.

Apart from that, I think that when you leave the other codecs in your answer, you're supposed to leave the door open to changing the codec on the fly while in the call. Not sure if anybody ever does that, or if browsers even support that, though.

**Comment by saghul** [comment] 2016-05-13 15:07
> The main problem we have with the "single" codec stuff is that Sofia SIP doesn't also remove the attributes referencing payload types that have been removed, only the numbers from the m-line.

I see. Now, I'd expect endpoints to ignore them, since they are not in the m line...


> Apart from that, I think that when you leave the other codecs in your answer, you're supposed to leave the door open to changing the codec on the fly while in the call. Not sure if anybody ever does that, or if browsers even support that, though.

Yeah. I tried it with regular SIP endpoints in the past, no luck.

**Comment by lminiero** [comment] 2016-05-13 16:47
Ok, fixed the problem cleaning up the video-related SDP from some stuff that we don't care about or don't support. I'll clean the code up a bit and commit.

**Comment by lminiero** [comment] 2016-05-13 16:51
Closing the issue as I can't replicate it anymore with the SIP data you provided: feel free to reopen if still an issue.

**Closed by lminiero** 2016-05-13 16:51 UTC

**Comment by lminiero** [comment] 2016-05-13 17:06
(as a side note, the janus.conf.meetecho.com instance hasn't been updated yet, so please test with your own Janus)

**Comment by shrhoads** [comment] 2016-05-15 18:53
I pulled the latest and rebuilt and tried it again, but I still get an SDP parse error:  http://pastebin.com/HGP2QsvB

I'm testing with Chrome on windows to Chrome on Mac, so don't know if that's also a contributing factor or not.

**Comment by lminiero** [comment] 2016-07-07 09:21
@shrhoads can you check if this commit fixes it for you?
