### ISSUE TITLE
[1.x] Strange segmentation fault on hangup media

### ISSUE THREAD

**Issue by petarminchev** [meetecho/janus-gateway#3124] opened 2022-12-13 17:22 UTC
Have upgraded to Multistream Janus 1.1.1 a week ago. Maybe it is just a coincidence and the issue was already in previous versions. But today have received one segmentation fault, which cannot fully understand -> libasan: https://pastebin.com/Bjj1XK4r

Line 3391 seems to be the **json_object_set_new** and error happened inside **json_string**:
			if(ps->description)
				json_object_set_new(m, "feed_description", json_string(ps->description));
				
We do not set any description for feeds, so it is strange it goes inside the **if** clause in the first place.				

What is your opinion on this? Is it possible Janus sets description erroneously to some internal value or frees the field twice?

Thank you in advance for the help!

**Comment by lminiero** [comment] 2022-12-13 17:26
The snippet you shared is not the libasan dump, but a gdb stacktrace. Do you have the actual libasan output instead? That should tell you why it crashed in there, e.g., if it was because the property had been freed already (and in case where).

**Comment by lminiero** [comment] 2023-01-04 13:32
Any update on this?

**Comment by lminiero** [comment] 2023-02-17 10:20
@petarminchev we have reasons to suspect #3154 is a duplicate of the issue you originally reported: we managed to gather more information from the logs they shared, and so the PR above attempts to provide a fix to that. Whether you can reproduce the problem or not (apparently it didn't happen to you anymore), I still encourage you to test that branch, since we want to ensure it fixes the problem and at the same time doesn't introduce any regression.

**Comment by lminiero** [comment] 2023-05-16 07:59
Closing as I haven't seen further reports here, and the other referenced issue is still open.

**Closed by lminiero** 2023-05-16 07:59 UTC
Labels: needinfo, multistream
