### ISSUE TITLE
Upload speed goes too high and video sharing not worked.

### ISSUE THREAD

**Issue by dev-mraj** [meetecho/janus-gateway#145] opened 2015-01-27 16:33 UTC
Hi,

its centos 7 server with lots of ram and cpu.
here is config i am using.
http://pastebin.com/G0BPNeh6
and in console there are lots of
[WARN] Skipping PID to NACK
and 
[2905577093] Missed sequence number XXX, going to NACK it

and when video start publishing, uploading speed get doubled every second, and it reached 250KB/s when just published one stream, and there is something thats why receviver also didn't get any video just black screen.

i still didn't figured out what i am missing.

here is log of console.
http://77.68.42.112/d/newcamup.log

**Comment by dev-mraj** [comment] 2015-01-27 16:55
and also same code worked before on virtual box's centos 7 guest os

**Comment by dev-mraj** [comment] 2015-01-28 09:21
googNacksReceived keep increasing and finaly after a little while it Lost connection to the gateway.

**Comment by lminiero** [comment] 2015-01-28 10:36
Looks like a connectivity issue on either the client or server side. Janus is sending NACKs because it's not receiving all the packets it's expecting from the browser, which obviously reflects on viewers as well as they're not receiving the same missing packets either (black screen). Not sure whether the cause are just missing packets or if the browser is actually not sending anything. You'll have to look at the admin API and check the statistics for the publishing handle to figure that out.

**Comment by dev-mraj** [comment] 2015-01-28 21:02
finally figured out problem it happens only when when using custom group without telling any bitrate,

like in my app i can't stick to config files for groups, i am calling create api to make group dynamically but if i don't specify bit-rate for group then this problem happens.

for now i am not making dynamic group instead i managing groups via node signalling server and putting all in one group, and managing feed ids on my own. and increase publishers to few large number (let me will this work?)

**Comment by lminiero** [comment] 2015-01-29 13:13
You can specify the bitrate for the room also when you create it dynamically (bitrate field in the create request). Closing as not an issue then, feel free to reopen otherwise.

**Closed by lminiero** 2015-01-29 13:13 UTC
