### ISSUE TITLE
SSL error (DTLSv1_get_timeout)

### ISSUE THREAD

**Issue by leonuh** [meetecho/janus-gateway#132] opened 2015-01-13 17:38 UTC
The Janus drops an error after SSL update.

Current version (works):
https://launchpad.net/ubuntu/+source/openssl/1.0.1f-1ubuntu2.7

Newer version (Janus drops an "DTLSv1_get_timeout:..." error):
https://launchpad.net/ubuntu/+source/openssl/1.0.1f-1ubuntu2.8

**Comment by lminiero** [comment] 2015-01-14 14:56
Not sure whether there were such breaking changes in the library, especially considering we use it at a very hight level. I'm currently abroad with limited connectivity, so I can't tell you which version of openssl we're using right now and check it ourselves.

**Comment by jridgway** [comment] 2015-01-16 19:21
I can confirm this. i just downgraded and everything works again.

**Comment by jridgway** [comment] 2015-01-17 03:01
Hey @leonuh, how did you properly downgrade? I did so by manually installing the older deb package, but it looks like I am no longer able to ssh into my server.

**Comment by jridgway** [comment] 2015-01-17 04:56
Never mind I worked it out. :)

**Comment by gatecrasher777** [comment] 2015-01-17 20:11
Made a new build on a new server using same code that was working 99% previously. Only using videoroom plugin. No media data is being transmitted.

I'm getting:  

[dtls.c:janus_dtls_srtp_incoming_msg:311:] [2395092422] Handshake error: error:1413C138:SSL routines:DTLS1_CHECK_TIMEOUT_NUM:read timeout expired

Is this the same error?

**Comment by lminiero** [comment] 2015-01-18 12:07
Apparently the DTLS stack in openssl is not handling messages that it is indeed receiving for some reason. I'll check with a new Ubuntu host myself in the next few days to see if it may be something we do (which doesn't explain why it worked before though).

**Comment by gatecrasher777** [comment] 2015-01-18 15:57
I'm not sure my DTLS timeouts are due to openssl since I have the same openssl version on both machines. OpenSSL 1.0.1f 6 Jan 2014.  Debug level 7 is just filled with DTLSv1_get_timeout messages. Not sure where to even begin overcoming this.

**Comment by lminiero** [comment] 2015-01-18 16:00
As I already said somewhere else (not sure whether on github or the group), tons of DTLSv1_get_timeout messages with high level of logging are completely normal: it's just a printout of when the retransmission timer for DTLS is going to fire if no reply is received in time.

**Comment by gatecrasher777** [comment] 2015-01-18 19:54
All the SDP can offer/answers seem fine.  From the admin consoles on each server, the only significant difference when connecting and transmitting video/audio as a publisher is in the DTLS:

Older build on working server:   

"dtls": {
                        "fingerprint": "C5:5F:DA:7D:84:47:B1:BF:6B:55:16:62:48:31:3E:D3:F1:7B:25:89:92:4A:4B:4D:4D:D9:D5:AF:EA:D8:15:44",
                        "remote-fingerprint": "E7:C4:E4:29:58:E6:E4:6E:86:48:82:C4:8D:17:90:D8:41:9D:A2:CD:E1:F6:0C:5E:1F:74:5D:5A:86:9F:F5:F5",
                        "dtls-role": "active",
                        "dtls-state": "connected",
                        "valid": 1,
                        "ready": 1
                    }

New build on new server:

"dtls": {
                        "fingerprint": "C5:5F:DA:7D:84:47:B1:BF:6B:55:16:62:48:31:3E:D3:F1:7B:25:89:92:4A:4B:4D:4D:D9:D5:AF:EA:D8:15:44",
                        "remote-fingerprint": "C2:1C:6C:A3:4D:21:E5:57:5F:A6:44:00:B5:34:A7:57:95:6A:0B:AA:7D:92:DC:14:F9:4A:42:0F:62:6A:7D:29",
                        "dtls-role": "active",
                        "dtls-state": "trying",
                        "valid": 0,
                        "ready": 0,
                        "in_stats": {
                            "audio_bytes": 0,
                            "video_bytes": 0,
                            "data_bytes": 20040
                        },
                        "out_stats": {
                            "audio_bytes": 0,
                            "video_bytes": 0,
                            "data_bytes": 2561
                        }
                    }

Apart from the newer janus code, everything is configured identically.

**Comment by lminiero** [comment] 2015-01-18 19:59
The exchanged data amount (which includes handshake stuff) seems to indicate that data is indeed being received, but not correctly handled by the stack in the new version of DTLS. Anyway, tose are just assumptions, as I haven't met the issue yet and had no time to replicate myself as of yet either.

**Comment by Will-I4M** [comment] 2015-01-19 07:31
From : https://groups.google.com/forum/#!topic/meetecho-janus/-2TNqQ38IHI 
"This may be related to https://github.com/meetecho/janus-gateway/issues/132"


Maybe, I can't confirm it, there is not enough debug information here. He's getting and error in the handshake process, but I never get errors from Openssl, only timeout. 
At this step in the handshake, the server has to write on the socket, not wait.

Today i'll try downgrading the all server (Ubuntu server 14.04 -> debian ??). I'll let you know how it works.. 

I tried with openssl 1.1.0-dev xx XX xxxx (built from sources) and janus refused to init -> 
		JANUS_LOG(LOG_FATAL, "Certificate error, does it exist?\n");
		JANUS_LOG(LOG_FATAL, "  %s\n", server_pem);
In dtls.c line 123, 124. The certificate was not valid for this version (same certificate since the begining, the one provided with git clone). So I generated a new certificate. After that, janus was able to init, but fall in the same behaviour, no way to handshake properly...

With OpenSSL 1.0.1f 6 Jan 2014 -> no pb IN  SSL_CTX_use_certificate_file with the certificate provided with janus.  weird ;)
If you need more info, let me know quickly, as i'm going to reinstall a new system on the server. 
WM.

**Comment by Will-I4M** [comment] 2015-01-19 07:40
gatecrasher777, are you using ubuntu ? Witch ver ? is libssl-dev (not openssl) is the same ver on the two servers ?

**Comment by chest3x** [comment] 2015-01-19 10:11
Will-I4M I most likely have the issue(https://github.com/meetecho/janus-gateway/issues/134) as you. Please keep us updated on your downgrade test.
I tested Ubuntu 14.04 and debian xy (one of the new releases) unsuccessfully.

Btw. I have one dumb Q. I'm using default certificates. Is there anything wrong with it?

**Comment by Will-I4M** [comment] 2015-01-19 12:21
Just before downgrading the system, i tried with libssl-dev 1.0.0e, open-ssl 1.0.0e but same result. The truth is out there  ...

**Comment by awsmsrc** [comment] 2015-01-19 14:26
@lminiero just confirming that im seeing this one too

**Comment by willbarrett** [comment] 2015-01-19 15:27
@Will-I4M we've been messing about all morning, changing the openssl version on a test server and recompiling. How did you go about downgrading? Was it only openssl or were other packages involved? We're seeing the same issue after downgrading openssl, and would love some more specifics on how you got it working.

**Comment by Will-I4M** [comment] 2015-01-19 16:31
No, it didnt worked for me. I tried removing openssl libssl-dev. afterwhat i installed openssl and libssl-dev v 1.0.0e, and rebuilt janus, but i got the same result. (unable to Handshake). On debian 7 64 bit, same thing, unable to handshake as described in the google group.

**Comment by gatecrasher777** [comment] 2015-01-19 21:14
Will-I4M,  Both machines are Ubuntu 14.04LTS, both libssl-dev are 1.0.1f-1ubuntu2.8

**Comment by gbilic** [comment] 2015-01-19 22:03
I experienced the exact same behavior today. Ubuntu 14.04.1LTS, libssl 1.0.1f
The handshake gets stuck after the "server hello done", never reaching the client key exchange.
My first try was to setup an Asterisk 13 with webrtc support and a sipjs client, i ended up giving a try to janus. The problem with Asterisk was exactly the same, dtls handshake failed. I will try tomorrow another libssl version. By the way, is the handshake handled by libssl or libsrtp (which can be build without openssl enabled) ?
.

**Comment by Will-I4M** [comment] 2015-01-20 03:42
Ok, i got it. 

Open dtls.c and just after line 135, add : 	SSL_CTX_set_read_ahead(ssl_ctx,1) ; 

make, make install and try. It works very well for me. 
The handshake complete ! Waaw ;)

**Comment by Will-I4M** [comment] 2015-01-20 04:03
Some additional infos: 
It seems to be not related to a particular version of openssl. I tried with a very similar system on 2 different arch. The result was different. 
Ok on amd64, but ko for x86_64. 
libs opened by janus (lsof) was exactly the same version and size on both servers 

lib/x86_64-linux-gnu/ld-2.19.so
lib/x86_64-linux-gnu/libc-2.19.so
lib/x86_64-linux-gnu/libcrypto.so.1.0.0
lib/x86_64-linux-gnu/libdl-2.19.so
lib/x86_64-linux-gnu/libgcrypt.so.11.8.2
lib/x86_64-linux-gnu/libglib-2.0.so.0.4002.0
lib/x86_64-linux-gnu/libgpg-error.so.0.10.0
lib/x86_64-linux-gnu/liblzma.so.5.0.0
lib/x86_64-linux-gnu/libm-2.19.so
lib/x86_64-linux-gnu/libpcre.so.3.13.1
lib/x86_64-linux-gnu/libpthread-2.19.so
lib/x86_64-linux-gnu/libresolv-2.19.so
lib/x86_64-linux-gnu/librt-2.19.so
lib/x86_64-linux-gnu/libselinux.so.1
lib/x86_64-linux-gnu/libssl.so.1.0.0
lib/x86_64-linux-gnu/libuuid.so.1.3.0
lib/x86_64-linux-gnu/libz.so.1.2.8
usr/lib/libgssdp-1.0.so.3.0.0
usr/lib/libgupnp-1.0.so.4.0.0
usr/lib/libsofia-sip-ua.so.0.6.0
usr/lib/libsrtp.so.0.0
usr/lib/libusrsctp.so.1.0.0
usr/lib/libwebsock.so.1.0.4
usr/lib/x86_64-linux-gnu/gconv/gconv-modules.cache
usr/lib/x86_64-linux-gnu/libbasicobjects.so.0.0.0
usr/lib/x86_64-linux-gnu/libcollection.so.2.1.0
usr/lib/x86_64-linux-gnu/libevent-2.0.so.5.1.9
usr/lib/x86_64-linux-gnu/libevent_core-2.0.so.5.1.9
usr/lib/x86_64-linux-gnu/libevent_openssl-2.0.so.5.1.9
usr/lib/x86_64-linux-gnu/libffi.so.6.0.1
usr/lib/x86_64-linux-gnu/libgio-2.0.so.0.4002.0
usr/lib/x86_64-linux-gnu/libgmodule-2.0.so.0.4002.0
usr/lib/x86_64-linux-gnu/libgnutls.so.26.22.6
usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0.4002.0
usr/lib/x86_64-linux-gnu/libgupnp-igd-1.0.so.4.1.0
usr/lib/x86_64-linux-gnu/libini_config.so.3.0.0
usr/lib/x86_64-linux-gnu/libjansson.so.4.5.0
usr/lib/x86_64-linux-gnu/libmicrohttpd.so.10.22.0
usr/lib/x86_64-linux-gnu/libnice.so.10.2.0
usr/lib/x86_64-linux-gnu/libogg.so.0.8.1
usr/lib/x86_64-linux-gnu/libopus.so.0.5.0
usr/lib/x86_64-linux-gnu/libp11-kit.so.0.0.0
usr/lib/x86_64-linux-gnu/libpath_utils.so.1.0.0
usr/lib/x86_64-linux-gnu/libref_array.so.1.1.0
usr/lib/x86_64-linux-gnu/libsoup-2.4.so.1.7.0
usr/lib/x86_64-linux-gnu/libsqlite3.so.0.8.6
usr/lib/x86_64-linux-gnu/libtasn1.so.6.2.0
usr/lib/x86_64-linux-gnu/libxml2.so.2.9.1
usr/lib/x86_64-linux-gnu/pkcs11/gnome-keyring-pkcs11.so
usr/lib/x86_64-linux-gnu/pkcs11/p11-kit-trust.so

Same build of janus and plugins but same result (hs never complete). 
I think it is related to the arch x86_64 and openssl-1.*.* 

Openssl seems to stop reading before the end of the Server hello Done, maybe a buffering issue ?

**Comment by gatecrasher777** [comment] 2015-01-20 04:12
"Open dtls.c and just after line 135, add : SSL_CTX_set_read_ahead(ssl_ctx,1) ;"

Good job, Will-I4M!  Works now.

**Comment by ploxiln** [comment] 2015-01-20 04:27
For linux, amd64 and x86_64 are the same. Does openssl treat those as two different architectures or something? Or do you mean x86/i386/i686/32-bit for one of them?

**Comment by Will-I4M** [comment] 2015-01-20 04:31
It's just a workaround, as the read ahead feature may conflict with the use of ssl_pending (but i don't know for BIO_ctrl_pending line 590...) 
 

cf openssl sources : 
 /* SSL_pending cannot work properly if read-ahead is enabled
       * (SSL_[CTX_]ctrl(..., SSL_CTRL_SET_READ_AHEAD, 1, NULL)),
       * and it is impossible to fix since SSL_pending cannot report
       * errors that may be observed while scanning the new data.
       * (Note that SSL_pending() is often used as a boolean value,
       * so we'd better not return -1.)
       */

**Comment by gatecrasher777** [comment] 2015-01-20 05:18
"are you using a x86_64 arch ?"  Yes.

**Comment by Will-I4M** [comment] 2015-01-20 05:38
@lminiero 

It is another issue, (but can lead to a similar behaviour). 
 
https://bugzilla.mozilla.org/show_bug.cgi?id=1052610#c40 is related to https://code.google.com/p/chromium/issues/detail?id=406458 referenced in dtls.c line 235. 
Maybe the use of SSL_CTX_set_ecdh_auto(ctx, 1) will be enough for both ?

**Comment by lminiero** [comment] 2015-01-20 09:29
@Will-I4M not sure if you're the same William that posted on meetecho-janus, anyway the solution should be a missing ``` SSL_CTX_set_read_ahead```:

https://groups.google.com/forum/#!topic/meetecho-janus/-2TNqQ38IHI

I'll commit a fix right away for you all to try: let me know if that fixes it indeed for you and I'll close the issue.

**Comment by lminiero** [comment] 2015-01-20 09:32
Ops just got up to date by reading the pending messages in here, you indeed already posted about the solution :)

About the pending stuff, we do not make use of it so it shouldn't be an issue: unless BIO_ctrl_pending implicitly calls SSL_pending, which AFAIK shouldn't as it only refers to the fake transport and not the crypto stuff.

**Comment by lminiero** [comment] 2015-01-20 09:37
As to ```SSL_CTX_set_ecdh_auto```, the google code issue says it's a new method only available in openssl 1.0.2, and so would not be available on 1.0.1 which is the most commonly available around.

**Closed** 2015-01-20 09:48 UTC

**Comment by basl12** [comment] 2023-08-21 22:37
> يسقط Janus خطأ بعد تحديث SSL.
> 
> الإصدار الحالي (يعمل): https://launchpad.net/ubuntu/+source/openssl/1.0.1f-1ubuntu2.7
> 
> إصدار أحدث (يسقط Janus خطأ "DTLSv1_get_timeout: ..."): https://launchpad.net/ubuntu/+source/openssl/1.0.1f-1ubuntu2.8
