### ISSUE TITLE
Video freeze with bandwidth limit

### ISSUE THREAD

**Issue by lieff** [meetecho/janus-gateway#1419] opened 2018-10-18 14:54 UTC
I tried latest master videoroomtest.html demo: 2 users enters the room and network traffic shaper limits bandwidth at 1.5mbps (users set at 2mbps or unlimited, reported bandwidth ~1.7mbps) for one user.
Video from that user (and to user) is freezes.
I tried enable rfc_4588 nacks (works in chrome, do not works in firefox) and change codec to h264. I see many nacks send when shaper is active, but it do not helps.
I also tried 1% loss instead of bandwidth limit. With 1% loss video not freezes, but becomes very stuttery/laggy.

**Comment by lminiero** [comment] 2018-10-18 14:59
Question for the [group](https://groups.google.com/forum/#!forum/meetecho-janus), not here. Closing.

**Comment by lieff** [comment] 2018-10-18 15:03
>If you think you found a bug, please open an issue on github instead
I think it's a bug.

**Comment by lminiero** [comment] 2018-10-18 15:21
I don't think so. Janus has bandwidth estimation on the publisher side (via TWCC) but it won't do anything for the viewer side. As such, when you put those limitations, for publishers the bandwidth value acts as a cap, but TWCC limits the send data. The same doesn't apply to the viewer side, who needs to have enough bandwidth or freezes will occur: it's up to the application to force publishers to limit themselves to accomodate one or more viewers.

Have you checked if the same thing happens when you use "no limit" or configure the room with bitrate=0?

**Comment by lminiero** [comment] 2018-10-18 15:22
> Janus has bandwidth estimation on the publisher side (via TWCC)

To clarify, Janus does NOT have bandwidth estimation itself, but it does provide feedback back to browsers via the TWCC specification, which is what browsers use to estimate the bandwidth on the sender side.

**Comment by lieff** [comment] 2018-10-18 15:45
>Have you checked if the same thing happens when you use "no limit" or configure the room with bitrate=0?

Yes, I tried both 2mbps and "no limit" variants, I've noticed that bitrate=0 enables REMB.

OK, may be bandwidth limit variant needs additional estimator on receiver side to become working, but 1% loss case still looks suspicious. Does NACKs should cover such loss? I tried local traffic as well, so RTT is very low and bunch of retransmits can be made in 1 second. I try to play with max_nack_queue value.

**Comment by lminiero** [comment] 2018-10-18 15:50
Are you using master? We made a lot of fixes to retransmissions in the past weeks, so if you're using something older good chances are you're on a bugger version.

That said, yes, NACKs should cover losses, but you have to take into account that both NACKs and retransmissions contribute to the traffic, and are subject to the same overall limitations. This means that NACK feedback may be lost, and so might retransmissions. In our experience and setups, retransmissions work as they should. You should also check what "1% loss" means, in terms of how it is implemented: not all tools implement it in a realistic way.

**Comment by lieff** [comment] 2018-10-18 15:56
Current master 17 commits ahead my test, so yeah, I will re-test with latest master.

I'm using MS Network Emulator on windows and wondershaper on linux.

**Comment by lieff** [comment] 2018-10-19 12:54
I re-tried latest master and same issue remains. With 1% loss there constant freezes up to ~3 seconds.

**Comment by lminiero** [comment] 2018-10-19 13:53
I used the [comcast](https://github.com/tylertreat/comcast) tool to force a bandwidth limitation (e.g., 1mbit) and the effect of the BWE there was immediate, which is the main target of that algorithm. I think occasional losses like the ones you're simulating, instead, don't impact the bandwidth estimation done by browsers, which is why they keep on sending data as before: packets are occasionally lost, a NACK is sent, and a retransmission is sent too. This seems confirmed by some tests we made simulating a percentage of packet loss, even high: we could see a lot of NACKs, and many successful retransmissions, which means eventually the actual number of lost packets (between packets originally lost and never recovered) is considered not enough to warrant a bitrate reduction in browsers.

The fact that you have short freezes very likely means that those losses affected a frame part of keyframe, and you need either that to be recovered, or a new keyframe to be sent, to see something again.

Notice that the bandwidth estimation I mentioned is available in Chrome only: Firefox doesn't have it.

**Comment by lieff** [comment] 2018-10-19 14:09
Yes, I use Chrome for test and noticed that Firefox even do not supports NACKs.
I will try to dump packets and look what happens on packet  level.
Another reason why I think it's suspicious - when I connect 2 webrtc p2p there no such problem.

**Comment by lminiero** [comment] 2018-10-19 14:10
> Yes, I use Chrome for test and noticed that Firefox even do not supports NACKs.

They do support NACKs, and retransmissions too: what they don't support is retransmissions via rtx (RFC4588).

**Comment by lminiero** [comment] 2018-10-19 15:13
Reopening as @atoppi thinks it might have to do with a fix we made some time ago in the calculation of lost packets, e.g., https://github.com/meetecho/janus-gateway/commit/55348a39e97778af21f4de20dd943b69be1e0c36#diff-c40fb57535974b0488f21216654ca253

**Comment by lminiero** [comment] 2018-10-24 15:36
Made a few changes thanks to some tests @atoppi made and now it should perform much better. Forcing packet loss will now correctly decrease the bitrate after a while, that is as soon as the browser figures out something's wrong: how soon depends on what the REMB cap is, as if it's missing (no limit) it will take longer as it will start decreasing from an estimate of 6mbps, while the actual bitrate will never exceed 2mbps (hence the slow reaction). You'll probably still experience some freezes if your simulated packet loss is not contextual: e.g., if you force 5% of packet loss no matter the bitrate, then reducing the bitrate will never help. This will probably only increase when we'll start working on FEC support, for which we don't have a specific plan yet.

Closing, thanks for bringing this back to our attention!

**Closed by lminiero** 2018-10-24 15:36 UTC

**Comment by lminiero** [comment] 2018-10-24 15:49
As a side note, was `transport_wide_cc_ext` set to `yes` or `true` for your VideoRoom? By default, the bandwidth estimation part is not done by Chrome unless you configure that property.

**Comment by lieff** [comment] 2018-10-24 23:47
Thanks :) I will re-test with latest changes, transport_wide_cc_ext was default=no in my test.

**Comment by lieff** [comment] 2018-10-25 14:28
I've made new test with latest master and transport_wide_cc_ext=yes. Now it works much better: one side works as expected in both scenarios, bandwidth limit and 1% loss. But other side still have long freezes.
Here scheme: [user1]<>Janus<>[shaper(limit or loss), user2].
User1 receives video from User2 normally in all cases.
User2 have stutters as before.

I've look at pcap dumps, both user1->janus and user2->janus have all packets arrived (user1 - because of no shaper, user2 have retransmits), both streams janus->user1 and janus->user2 have retransmits and following differences:
janus->user1 retransmits(in different payload) have sequential sequence numbers(sn):
```
#       ts        wall  ts-wall       sn[size]      gap ts (hex)    delay
-------------------------------------------------------------------------
       0     0.00    0.000    0.000    20118[1102] 061a3ba6                                       
       0             0.002   -0.002    20119[1103] 061a3ba6                                       
       1    28.30   28.336   -0.033    20120[1175] 064119ec                                       
       2    28.48   28.443    0.037    20121[1094] 06415826                                       
       3    29.39   29.360    0.031    20122[1155] 0642986c                                       
       4    29.57   29.553    0.014    20123[1195] 0642d64c                                       
       5    29.68   29.640    0.039    20124[1119] 0642fdac                                       
       6    29.74   29.698    0.045    20125[1121] 0643142c                                       
       7    30.11   30.134   -0.023    20126[1121] 0643958c                                       
       8    31.01   31.044   -0.037    20127[1104] 0644d08c                                       
       9    31.49   31.453    0.034    20128[1105] 0645794c                                       
      10    32.34   32.316    0.019    20129[1146] 0646a36c        
```
janus->user2 retransmits have non-sequential sequence numbers:
```
       0              0.00    -0.00        9[1037] 004e6600                                       
       1     0.84     0.79     0.04       23[1171] 004f8be8 gap=  13 ( 0.8)                       
       2     0.87     0.80     0.06       24[1085] 004f9728                                       
       3     0.84     1.01    -0.17       41[1170] 004f8be8 gap=  16 (47721.8) del=   2 ( 0.0)       
       3              1.01    -0.17       42[1170] 004f8be8                 del=   1 ( 0.0)       
       4     1.14     1.03     0.10       44[1054] 004ff560                 del=   1 ( 0.0)       
       5     1.27     1.14     0.13       50[1170] 005023c8 gap=   4 ( 0.1)                       
       6     1.40     1.26     0.14       54[1039] 00505398 gap=   3 ( 0.1)                       
       7     1.44     1.27     0.17       57[1122] 00505ed8 gap=   2 ( 0.0)                       
       8     1.47     1.30     0.17       60[1086] 00506a18 gap=   1 ( 0.0)                       
       9     1.27     1.34    -0.07       63[1170] 005023c8                 del=   1 ( 0.2)       
      10     1.50     1.34     0.17       64[1068] 005076c0                                       
      10              1.40     0.11       66[1069] 005076c0 gap=   1 ( 0.0) del=   1 ( 0.0)       
      11     1.37     1.47    -0.10       68[1052] 005046f0                 del=   2 ( 0.1)       
      12     1.40     1.47    -0.06       70[1039] 00505398 gap=   1 ( 0.0) del=   1 ( 0.1)       
      13     1.60     1.47     0.13       72[1018] 005099e8                                       
      14     1.50     1.57    -0.06       86[1068] 005076c0 gap=  13 (47721.8) del=   1 ( 0.1)       
      15     1.70     1.57     0.13       88[1112] 0050bd10                                       
      16     1.77     1.87    -0.10      124[1037] 0050d390 gap=  34 ( 0.0) del=   2 ( 0.0)       
      16              1.87    -0.10      125[1037] 0050d390                 del=   1 ( 0.0)       
      17     1.50     1.87    -0.37      127[1069] 005076c0                                       
      18     1.97     1.88     0.09      133[1037] 005119e0 gap=   5 ( 0.5)                       
      19     1.44     1.98    -0.54      139[1122] 00505ed8 gap=   5 (47721.3) del=   8 ( 0.5)       
      19              1.98    -0.54      140[1123] 00505ed8                 del=   7 ( 0.5)       
      19              1.97    -0.54      141[1123] 00505ed8                 del=   6 ( 0.5)       
      20     1.60     1.97    -0.37      142[1018] 005099e8                 del=   5 ( 0.4)       
```

**Comment by lminiero** [comment] 2018-10-25 14:44
If you're not using RFC4588, retransmits are not supposed to have monotonically increasing sequence numbers: it will just be a retransmission of the same exact packet that was lost originally.

**Comment by lieff** [comment] 2018-10-25 14:49
Hmm, user1 - llinux, user2 - windows. Can it be that Chromium 70.0.3538 supports RFC4588 and windows Chrome 70.0.3538 do not supports it?

**Comment by lieff** [comment] 2018-10-25 14:56
From admin I see rfc4588-rtx: true from winows chrome, so I guess rfc4588 should be enabled? Still non-sequential retransmits sequence numbers to windows.

**Comment by atoppi** [comment] 2018-10-25 15:08
@lieff to double-check those `janus -> user2` packets are on the `rtx` channel, look at the SSRC in the headers. They have to be different from the one used to send media.

**Comment by lieff** [comment] 2018-10-25 19:14
Yep, sure. I'm already do not have one above, but can record new one this weekend.

**Comment by lieff** [comment] 2018-10-29 11:19
Sorry for the delay. Here the dump:
https://mega.nz/#!Ux1FBKKD!dDhomeka5G6ZSxoRm11ZmAXfMCCrcro1DqbSOl__B3Y

janus-text2pcap-1324996400.pcap U1_to_janus
janus-text2pcap-2410081320.pcap janus_to_U2
janus-text2pcap-909231768.pcap U2_to_janus
janus-text2pcap-1170478079.pcap janus_to_U1
U1 - linux
U2 - winows
1% loss started after 180s.

**Comment by atoppi** [comment] 2018-10-29 12:06
@lieff Is the conditioner still acting between Janus and U2 ? Has the loss been applied in both direction (J -> U2 and U2 -> J) ?

**Comment by lieff** [comment] 2018-10-29 12:24
Yes, there 1% loss on both directions.

**Comment by atoppi** [comment] 2018-10-29 12:29
do you have the negotiated SDPs ?

**Comment by lieff** [comment] 2018-10-29 13:02
Here json dump from admin without remote/local candidates:
[sdp.zip](https://github.com/meetecho/janus-gateway/files/2525284/sdp.zip)

**Comment by atoppi** [comment] 2018-10-29 16:41
I've been focusing on the U2 to Janus dump, **filtering out the first 220 seconds**.
On this dump `10.1.1.1 = Janus` and `10.2.2.2 = Windows Chrome`.
Take in mind that the capture is from Janus perspective, while your network conditioner is acting on the Chrome machine, so you're seeing every packet going in/out to/from Janus.

In this scenario you're not using the `twcc` (disabled in room cfg?) but `rfc4588` aka `rtx` is enabled.
Using this filter `((ip.src == 10.1.1.1 && rtcp.rtpfb.fmt == 1) || (rtp.p_type == 108))` you're able to isolate the NACKs sent from Janus and the associated re-transmissions from Chrome.
What I have noticed is that for many NACKs sent by Janus, only a small part of those has been replied by Chrome (hint: to get the original seqno in a `rtx` read the first 2 bytes of the payload).
Janus sends NACKs for 9 different packets: `25675`,`25694`...`26336`,`26661`, but it only receives the `rtx` for `original_seq=26661`, and the `rtx` packet has `seq=2`.
This means that for ~1000 packets sent from U2, Janus hasn't received 9 of them (exactly 1%) because we have 9 NACKs in a range [26661,25675].
But U2 seems to have received just 2 of these NACKs, hence the `seq=2` in the `rtx`, and the first `rtx` has been lost in the way, and so it does not appear in the dump. This pattern of many NACKs and few `rtx` seems to reiterate.

It might be Janus dropping incoming RTP on `rtx` before dumping, do you have any **`SRTP unprotect error`** ?
It might be your network shaper not working like you think. We should originally loss 1% of RTP data, then loss 1% of NACKs requests (but Janus send them twice per packet), then loss just 1% of `rtx` re-transmitted packets. The numbers on `rtx` show 45% packet loss for that RTP stream, and this is not inline with the 1% profile.
Finally, focusing on the plain video RTP from U2 to Janus, just 2 packets on 17578 are getting lost. There are some out-of-orders packets, but the stream is not lossy at all. Where is the 1% we're expecting? The `rtx` is a separate SSRC, and Wireshark should not be able to consider as recovered the missing packets in the original SSRC.
Meanwhile the audio RTP shows a perfect 1% loss (50 over 4719).

To conclude, verify that Janus is not dropping incoming RTP data because the dropping occurs before the text2pcap. Then try to understand why the audio RTP has 1% loss, while the video has not. Maybe try with another shaping tool (e.g. we use comcast, very nice tool).

**Comment by lieff** [comment] 2018-10-30 10:19
>In this scenario you're not using the twcc (disabled in room cfg?) but rfc4588 aka rtx is enabled.

transport_wide_cc_ext = yes in janus.plugin.videoroom.cfg, rfc_4588 = yes in janus.cfg.

>just 2 packets on 17578 are getting lost. There are some out-of-orders packets, but the stream is not lossy at all
>Meanwhile the audio RTP shows a perfect 1% loss (50 over 4719).
>try to understand why the audio RTP has 1% loss, while the video has not.

May be they are seen by the Janus as reordered because they are retransmitted with the same SSRC and PT, i.e. two retransmission mechanisms used.

Here what wireshark shows U2(win)->J
![image](https://user-images.githubusercontent.com/10080078/47709666-cb80c900-dc41-11e8-8546-d6f14a335a6d.png)
Only 2 packets lost and 20 retransmissions in different payload which looks wired. My opinion that it uses non-sequential sn, that`s why wireshark shows 44% loss. However, the video stream (PT=107) here have lots of reordered packets (not shown in the table), which indicate retransmissions with the same SSRC & PT.

J->U1(linux)
![image](https://user-images.githubusercontent.com/10080078/47710085-e7d13580-dc42-11e8-821e-bc19b0869fdb.png)
There 197 retransmissions in different payload which looks and uses sequential sn. 
So that’s why U1 saw good video: U2->J good retransmits within same SSRC/PT + non-working retransmits within different SSRC/PT. J->U1 - Working retransmits within different SSRC/PT and no retransmits within same SSRC/PT.

U1->J
![image](https://user-images.githubusercontent.com/10080078/47710493-ef450e80-dc43-11e8-9f88-1d938ab5ca68.png)

J->U2
![image](https://user-images.githubusercontent.com/10080078/47710515-fa983a00-dc43-11e8-94ed-e87c12c375d1.png)
Retransmits with the same SSRC and PT not used here, because video stream do not have duplicated packets (which happens during retransmit) - that’s why U2 have stutter video.
Note that retransmits within different SSRC/PT also have non sequential sn and wireshark shows 49% loss. But this packets recorded on janus from perfect U1->J stream. That's why I think it's not shaper issue and just non-sequential sn's.

Of course all it's needs re-checking. I will try different shaper and windows/linux combinations later.

**Comment by atoppi** [comment] 2018-10-30 16:14
> transport_wide_cc_ext = yes in janus.plugin.videoroom.cfg, rfc_4588 = yes in janus.cfg.

To isolate the TWCC feedbacks use the filter `rtcp.rtpfb.fmt == 15`.
TWCC seems to be disabled on J <-> U2 streams.

> two retransmission mechanisms used

This would mean Windows Chrome is using both mechanisms together, it sounds weird to me. However we do not test browsers on Windows so frequently, so I'll wait some other feedbacks.

> My opinion that it uses non-sequential sn

I don't think the browser is sending non-sequential seq numbers on the `rtx`. My guess is that Janus is dropping the packets before the dump ([here](https://github.com/meetecho/janus-gateway/blob/bbd875633a5449abb39f8980b26c1cba6c20bb46/ice.c#L2219)), or the bowser is not sending the packets at all (shaper involved?).

**Comment by lieff** [comment] 2018-10-30 18:40
Thanks :) I'll check TWCC feedbacks and srtp errors.

**Comment by lieff** [comment] 2018-11-01 14:20
About srtp erros:
Sometimes I get errors here:
```
[ERR] [../ice.c:janus_ice_cb_nice_recv:2566] [5837090462912412]     SRTCP unprotect error: err_status_replay_fail (len=98-->98)
```
and here:
```
[ERR] [../ice.c:janus_ice_outgoing_stats_handle:3671] [8386408197519551] Got 12 SRTP/SRTCP errors in the last few seconds (last error: err_status_replay_fail)
```
Usually there no unprotect errors during test.
Even if I comment `if(res != srtp_err_status_replay_fail && res != srtp_err_status_replay_old)`, I cannot get errors [here](https://github.com/meetecho/janus-gateway/blob/bbd875633a5449abb39f8980b26c1cba6c20bb46/ice.c#L2219).

**Comment by lieff** [comment] 2018-11-01 15:07
But guess is that Janus is dropping packets before the dump seems correct, if I look at encrypted traffic - there no such ~50% loss in retransmission PT. Also in encrypted traffic I see that all packets from widows chrome duplicated 4 times (it happens not immediately but at some point). This is really can be issue with MS Network Emulator.
