### ISSUE TITLE
session_id and handler_id are too large

### ISSUE THREAD

**Issue by mzanetti** [meetecho/janus-gateway#1010] opened 2017-09-22 13:50 UTC
the session/handler ids are long integer values. This imposes an issue with some json parsers.

The JSON standard says that one should use the format of JavaScript numbers. The JavaScript standard says that all numbers should be stored as double-precision floating points... but this format doesn't have enough precision to store 64-bit integers.

In my case this causes QJsonDocument to sometimes introduce rounding errors in the in session/handler id. At first I thought this is an issue in Qt, but doing a bit of research it seems that even though Qt could behave smarter, it's not the only lib falling for it.

[1] https://forum.qt.io/topic/66153/qjsondocument-loses-accuracy-on-long-long-int64-data/9
[2] https://cdivilly.wordpress.com/2012/04/11/json-javascript-large-64-bit-integers/

**Comment by lminiero** [comment] 2017-09-25 09:56
We know, and we generate lower numbers already for JavaScript's sake when asked to generate a random 64 bit identifier: https://github.com/meetecho/janus-gateway/blob/master/utils.c#L84
This definitely fixed issues we had when working on the Janus API from nodejs, for instance. Not sure why that's not working in your case though.

**Comment by mzanetti** [comment] 2017-09-25 10:22
Just did a test with one of the id's that failed here:
The code: ```    QByteArray data = "{\"id\": 5808437681602035}";
    QJsonDocument jsonDoc = QJsonDocument::fromJson(data);
    qDebug() << "Input:" << data;
    qDebug() << "converted to variantmap:" << jsonDoc.toVariant().toMap();
    qDebug() << "To longlong:" << jsonDoc.toVariant().toMap().value("id").toLongLong();
```
and its output:```Input: "{\"id\": 5808437681602035}"
converted to variantmap: QMap(("id", QVariant(double, 5.80844e+15)))
To longlong: 5808437681602036```

**Comment by lminiero** [comment] 2017-09-25 10:28
Looks like an issue in the QT JSON parser, then, since we already return numbers lower than 2^53 as your second link points out. If its tolerance is lower than that, you may want to tweak `janus_random_uint64` in your deployments so that it is even more constraining for the time being, until the issue is solved. As an alternative solution, you may want to use a different JSON library as well (Jansson, the one we use in Janus, doesn't seem to suffer from this issue).

**Comment by lminiero** [comment] 2017-09-25 10:29
Closing as I don't believe it's an issue in Janus.

**Closed by lminiero** 2017-09-25 10:29 UTC

**Comment by mzanetti** [comment] 2017-09-25 10:47
FWIW, the lowest number I could reproduce the failure with is: 4503599627370497

Using a different parser sure would be possible, but each new library dependency makes the deployment more complex... so I'd rather not prefer doing so.

Also ideally I would like to avoid patching janus as much as possible as I'd eventually like to use the upstream janus version coming with the distribution instead of shipping my own packages.

Is there a reason why those numbers need to be that high? I would think with some lower numbers there surely is still enough entropy for not having collisions, also, if this is just random numbers, why not just increasing acounter for each session and start counting at 1 or something?

I agree that this is in theory is probably not a "bug" in that sense, but I hope you can see how it might benefit janus too trying to play nice with other established toolkits out there :)
