### ISSUE TITLE
Streaming mountpoint stats

### ISSUE THREAD

**Issue by marchaase** [meetecho/janus-gateway#485] opened 2016-03-14 19:23 UTC
I'd like to be able to tell if a remote RTP stream is "active".  I have a remote RTP stream that is sometimes active and sometimes not.  Currently if I try to stream that mountpoint it will attempt it and from the client's perspective it just never loads the video.  I don't see any easy way to detect that the remote RTP stream is active or not from the client's perspective.

I was wondering if it would make sense to add some statistics for mountpoints.  Something that could be queried with plugin message API to allow a client to have some logic to detect if a stream is active.  It looks like something could be added to the struct janus_streaming_mountpoint.  The mountpoint receiving thread could update information into the struct to allow the message handling thread to dole out that information.

I've hacked together something really quickly to see how easy it would be and made the receiving thread update a new struct member with the value of last_ts.  I then changed the message API to just add this information alongside the mountpoint info in the "list" command.

last_ts doesn't seem ideal for use here as it looks like it's for keeping the timestamp sensible if source streams are switched.  Potentially the sequence number might work.

I think the biggest question I have is what types of data would be the easiest to add that could cover all of the different stream types.  Maybe mirroring the admin API for the stats giving bytes/packets for audio/video/data would be a good target for stats covered.  Getting bytes seems easy and would work for network or 'live' file sources, but wouldn't work too well with 'ondemand' though as you have multiple clients with different stats.

I think there is a question about where in the message API this would fit best as well.  'list' makes the most sense to me to fit into the existing messages, but is this too much information for that response?  Should there be another message like 'info' that could give you more detailed info on the mountpoint?

Thoughts?

**Comment by marchaase** [comment] 2016-03-14 19:25
Maybe as this is an enhancement idea this is better suited for the for the google forum?  You can close this if you like and I'll post there.

**Comment by amnonbb** [comment] 2016-03-14 20:56
Here 
https://github.com/cargomedia/janus-gateway-rtpbroadcast
i found some extended modified stream plugin.
but did not check yet

**Comment by lminiero** [comment] 2016-03-15 09:19
I think having an issue here as a "desiderata" is not a bad thing, so no need to move it to the group. Feel free to post there to talk about it there as well, if not just to point to the issue here and see if anybody else is interested.

That said, I'd rather not duplicate stuff the Admin API already provides. There probably are lighter ways to detect and report when a stream is active or not. First of all, there's the "enabled" flag in mountpoints which, whether media is available or not, decides if users are going to get anything at all. Then, file-based streams are by definition always available (a file is going to be used as a basis). The issue is more with RTP based mountpoints, as there you can't simply rely on a packet being received to mark it as active, since you may receive media for a while and then find out the source went away. This means involving some kind of timeouts. Your idea of using timestamps (last_ts) is actually not that bad, and I don't think we have to worry about switching: switching is a user moving from one mountpoint to the other, which has nothing to do with whether one of those mountpoints is alive or not; if a mountpoint is receiving data, last_ts is updated, otherwise it's not. To make it less RTP-related, we can simply put a monotonic or real time in there (timing info of when the last packet was received), and maybe a "now" time as well, so that one can programmaticaly compute how long it has passed since the last packet was received. I guess there should be both audio and video there, since a mountpoint that has both may be receiving, for instance, video and not audio, meaning it's still incomplete.

As to per-mountpoint info, I guess there's no harm in having one along with the more generic "list" (which returns them all).

I'll add these suggestions to the TODO list, but not sure when I'll be able to start working on this as we're quite busy these days.

**Comment by marchaase** [comment] 2016-03-15 16:44
It looked like it would be pretty easy to add in there, I might try to drop a pull request if I have time to get to it.

I would say it's kind of a grey area in terms of overlap with the Admin API.  Especially since the focus is so narrow on RTP streams.  For RTP streams the enabled flag goes high as soon as any packet (audio or video) has been received, and stays high from then on.

Using the idea of time made sense to me as well - a timestamp of time received and a 'now' timestamp as the client may not have the same time as the server.  Then you could calculate clientside what you determine as an RTP stream being unavailable.

The only potential problem I see is since the RTP stream and API message functions are separate threads and you need to share state between them it would have to use the mutexes to protect concurrent access, and I am afraid of blocking on a mutex in the RTP relay thread as you would want that to shuffle out data as quick as possible.  Though that's not as much of an issue for me as I don't have any clients really on my server it might be more of an issue with lots of clients accessing the streaming plugins messaging API and/or having many RTP streams.  I could add a pthread_mutex_timedlock macro to mutex.h to allow a timeout on the lock aquisition in the relay thread for that.

**Comment by lminiero** [comment] 2016-03-15 16:50
I don't think you have to worry about locking anything: only the RTP thread will ever write the "last updated" value, while the handler only ever reads it, so no conflict there. The "now" value will only be set by the message handler (it doesn't need to be a property of the mountpoint).

**Comment by marchaase** [comment] 2016-03-15 17:23
Yeah I guess that makes sense, but couldn't the read hit it right in the middle of a write since if I use the utils.c time functions they are 64-bit and non-atomic for reads/writes on all architectures?

**Comment by lminiero** [comment] 2016-03-17 10:50
Merged your contribution, and added a new request called "info" that acts like "list" but for a specific mountpoint: https://github.com/meetecho/janus-gateway/commit/d35c88238788069057a8ff01d23794dcea5ddcee

**Closed by lminiero** 2016-03-17 10:50 UTC
