### ISSUE TITLE
Janus force closes after long activity.

### ISSUE THREAD

**Issue by mattvv** [meetecho/janus-gateway#261] opened 2015-06-15 23:16 UTC
Logs:

```
Sending WebSocket response (51 bytes)...
  -- Sent 51/51 bytes
[WSS-0x1156df0] Got 72 bytes:
Thread pool, serving request
[WSS-0x1156df0] WS connection closed
[WSS-0x1156df0] Destroying WebSocket client
[WSS-0x1156df0]   -- closed
GLib (gthread-posix.c): Unexpected error from C library during 'pthread_mutex_lock': Invalid argument.  Aborting.
```

Let me know if you need more info, it's pretty easy to reproduce. Just start a server and have a client connect via WebSockets for an extended period of time (30-40hours).

**Comment by lminiero** [comment] 2015-06-16 09:52
It won't be easy to replicate, but I'll try. Have you checked if the cause was memory exhaustion or something like it? Please also provide a stacktrace if you have it available.

**Comment by mattvv** [comment] 2015-06-16 16:15
This is a different log, but with the same event, a full crash and force quit:

```
[1559408018] Adding event to queue of messages...
[1559408018] Handle detached (error=0), scheduling destruction
[WSS-0x1f355a0] WS connection closed
[WSS-0x1f355a0] Destroying WebSocket client
[WSS-0x1f355a0]   -- closed
janus: ../nptl/pthread_mutex_lock.c:350: __pthread_mutex_lock_full: Assertion `(-(e)) != 3 || !robust' failed.
Thread pool, serving request
```

I can confirm it's not memory exhaustion, I have this on a very large amazon instance and it's not even scraping at the available memory or cpu pool.
I'll work on getting a stack trace.

**Comment by arjenveenhuizen** [comment] 2015-07-01 07:51
It appears that I have a related issue. After 20+ hours the websocket connection is closed (typically during the night (GMT+1 timezone) and Janus shuts down. I am running on a heavy Amazon EC2 instance as well. 
According to my application logging, I am not so sure if this problem is purely Janus related. Besides the Janus WS connection being dropped, I also notice that my WS connections between other applications are lost. Furthermore I use ZeroMQ to do some inter-process data communication. This communication is dropped as well without the possibility to reconnect. 

My hunch would be that "something" happens on the network interface on Amazon. I will try to run the same setup on a local laptop here as well and see what happens.

Note that in my case I do not see a force close or SEGFAULT.

**Comment by mattvv** [comment] 2015-07-21 17:15
Hey @arjenveenhuizen - I'm not using docker at all, but I was able to narrow this issue down more. I turned off WS support and went back to default long polling and the issue does not happen, so it's 100% related to WebSockets.

**Comment by lminiero** [comment] 2015-07-22 05:53
Have you checked the new modular-transports branch? If not, please do, as it will be the default in a short while, and we changed a bit the way signalling is handled on the server side.

**Comment by mattvv** [comment] 2015-07-22 13:35
Thanks @lminiero - I'll try this out today and update this ticket with results.

**Comment by mattvv** [comment] 2015-07-22 13:58
Enabled websockets on the new modular-transports branch. I was doing some dev work and quickly opening/closing a connection by quitting the browser window and was able to reproduce a websockets crash.

```
[WSS-0x1594980] WS connection closed
[WSS-0x1594980] Destroying WebSocket client
Thread pool, serving request
[WSS-0x1594980]   -- closed
GLib (gthread-posix.c): Unexpected error from C library during 'pthread_mutex_lock': Invalid argument.  Aborting.
```

**Comment by lminiero** [comment] 2015-07-22 14:36
I need a backtrace to know what's wrong. That info is unfortunately not enough.

**Comment by lminiero** [comment] 2015-08-03 11:09
Is it still an issue on the latest Janus and/or modular transports branch?

**Comment by lminiero** [comment] 2015-09-03 09:00
A WebSocket close issue was fixed just yesterday, could you check if that's still an issue for you?

**Comment by lminiero** [comment] 2015-10-13 08:38
Any update on this?

**Comment by mattvv** [comment] 2015-10-13 16:46
My apologies for late reply.
Unfortunately still having issues with websockets. I had to turn them off on the client and use long polling as Janus would crash. Since my app is in production now I can't afford any crashes :(

**Comment by lminiero** [comment] 2015-11-26 12:22
@mattvv have you tried the latest version of Janus? We since merged the famous modular-transports, so WebSockets code has changed quite a lot.

**Comment by bhakimi** [comment] 2015-11-27 22:02
my application runs for hours and hours before it closes, i can lets you guys know if i experience this issue

**Comment by mattvv** [comment] 2015-11-28 05:26
@lminiero - I'll test this out this weekend with the latest build and let you know how I go

**Comment by lminiero** [comment] 2016-02-16 15:04
Closing as too much has changed in the meantime, and we have other pull requests pending review/testing. Feel free to reopen if still an issue.

**Closed by lminiero** 2016-02-16 15:04 UTC
