### ISSUE TITLE
Admin API WS crash

### ISSUE THREAD

**Issue by denisicun** [meetecho/janus-gateway#1330] opened 2018-07-31 15:36 UTC
Hi,

Our team tried to upgrade the version of Janus in our app from commit '7fef0fba7e155a38fdd318ba16f402c180977695' (Dec 2017) to commit '77ff007f61294fd19dad388632019a2806ea0f79' (Jun 2018 - latest at the time of the upgrade) and we experienced some weird crashes with the media server.

**Background**
We have a signalling server that is connected to multiple janus media servers. This server is connected to each janus admin api via WS. 
We use the admin API to check how many streams are currently streaming to the media server (internal load balancing) and also as a keep alive message for the janus service.

NOTE - We know this might not be the the best way to do this, if you have any suggestions on a better practice for this we would be more than happy to hear.

We call the admin API every 3 seconds.
The signalling server is a Java server that uses jetty WS with version 9.4.7.v20170914.

**The issue**
After we upgraded to the latest version,  after some time, the janus admin api service would get stuck and wouldn't even write logs to file and all the streams got stuck. 
- Our signalling server just tried to connect to janus admin api without getting any acknowledgement or timeout.
- We saw in one case that the service was just stopped for about 2 hours - no logs, no streams, no admin api.

When it happened,  janus service was running and listening on the configured ports for streaming and  admin api, but wasn't doing anything - like janus was on HOLD.
 
Only when we restarted the janus service - everything got back to work - Our signalling server succeeded to connect to janus admin api.

The media server is running on an AWS machine with ubuntu OS.

At first we thought that this is related to the libwebsocket version (this is how we found [this](https://github.com/meetecho/janus-gateway/issues/1327) issue) , but this issue still occurred after we got back to version 2.4.2 of libwebsocket.

After we down-graded back to the version of janus that we were using, we didn't experience this issue.

Unfortunately we don't have logs to provide since the media server was running fine until it would suddenly freeze and didn't even write logs.

We would be more than happy if you would take a look at this, this upgrade caused us a lot of problems, and eventually we had to revert the upgrade.

Thanks!

**Comment by lminiero** [comment] 2018-07-31 15:44
I'm assuming you're querying the Admin API via WebSockets and not HTTP? If so, my guess is that you hit the same problem discused in #1263 or #1274, for which we recently committed a fix: https://github.com/meetecho/janus-gateway/commit/f3349008d4c4756fbd61b6c6d7cd3bac68ed9f7f#diff-6ca56c577ffd63a1476114e13b6f89f3
As such, you may want to try with master to see if that helps, as the commit you're on precedes that.

Anyway, if all you're using the Admin API for is tracking streams, the [Event Handlers](https://archive.fosdem.org/2017/schedule/event/janus/) are probably a better way of doing that, as it's a way to get asynchronous notifications from Janus, rather than having to poll on a regular basis yourself.

**Comment by AndreaGvA** [comment] 2018-08-17 14:26
Could this fix resolve our problem in [#1334](https://github.com/meetecho/janus-gateway/issues/1334)?

**Comment by lminiero** [comment] 2018-08-28 12:20
If it's working fine in some versions of Janus and not others, you may want to try a `git bisect` to find the commit that introduced the issue. Of course, please also let us know if the issue is solved in master by any chance.

**Comment by lminiero** [comment] 2018-09-04 08:38
Any update?

**Comment by lminiero** [comment] 2018-09-24 12:46
Closing for lack of feedback, so I assume this is fixed. Feel free to provide more info to reopen, if it's not.

**Closed by lminiero** 2018-09-24 12:46 UTC
