### ISSUE TITLE
janus streaming rtsp fail （5s passed with no media, trying to reconnect the RTSP stream）

### ISSUE THREAD

**Issue by yuexiajiayan** [meetecho/janus-gateway#2335] opened 2020-08-25 09:03 UTC
i'm test it rtsp://wowzaec2demo.streamlock.net/vod/mp4:BigBuckBunny_115k.mov 
but con't see any video config like this：
rtsp-test: {
	type = "rtsp"
	id = 99
	description = "RTSP Test"
	audio = false
        video = true
	url = "rtsp://wowzaec2demo.streamlock.net/vod/mp4:BigBuckBunny_115k.mov"  
	#rtsp_user = "username"
	#rtsp_pwd = "password"
       #secret = "adminpwd"
}

**Comment by atoppi** [comment] 2020-08-25 10:35
I'm not able to play that URL even on VLC.

**Comment by yuexiajiayan** [comment] 2020-08-25 13:13
> I'm not able to play that URL even on VLC.

it wait 15s can open  .

**Comment by atoppi** [comment] 2020-08-25 13:57
It seems that specific server is having some troubles when asked to send media over UDP.

We tried:
- VLC (use UDP transport) -> Fail
- Janus (use UDP transport) -> Fail
- MPV (use TCP interleaved transport) -> **Success**

The failure is caused by the server abruptly closing the TCP connection used for RTSP signalling, immediately after having received a RTSP SETUP requesting UDP transport.
Nothing we can do, as Janus does not currently support TCP transport for RTSP connections.

I'm attaching the packet captures obtained during the tests (remove txt extension).
[mpv-rtsp.pcapng.txt](https://github.com/meetecho/janus-gateway/files/5124118/mpv-rtsp.pcapng.txt)
[vlc-rtsp.pcapng.txt](https://github.com/meetecho/janus-gateway/files/5124119/vlc-rtsp.pcapng.txt)
[janus-rtsp.pcapng.txt](https://github.com/meetecho/janus-gateway/files/5124120/janus-rtsp.pcapng.txt)

**Closed** 2020-08-25 13:57 UTC

**Comment by yuexiajiayan** [comment] 2020-08-26 01:22
o thinks
