### ISSUE TITLE
"No such feed" alert appears in VideoRoom demo, but it's not an error

### ISSUE THREAD

**Issue by soulfly** [meetecho/janus-gateway#719] opened 2016-12-27 11:41 UTC
Hi there, 

Tested VideoRoom demo here https://janus.conf.meetecho.com/videoroomtest.html
and found one case.

**Steps to reproduce:**
1. UserA joined video room
2. UserB joins and quickly presses 'Stop' button.

**Result:**
UserA receives "No such feed" alert
https://www.evernote.com/l/ANjLb4Z_MSVH5b5HJMOCy5846sQaGuM3SLsB/image.png

As I understand, UserA tries to joins as listener to UserB's feed, but the feed does not exist.

From my understanding, it's normal situation, not an error.
and we should not show here this error alert, maybe just print log warning.

**Comment by lminiero** [comment] 2016-12-28 09:41
There's nothing we can do with pictures. Next time please attach a log with gist/pastebin so that we can try and check what's leading to the error/warning in the first place.

Anyway, I don't believe this shouldn't be an error: we can't possibly know in advance it's a normal situation like this, the cause of the issue may be more severe. Anyway, more checks can definitely be done on the client side to be sure of what's happening (e.g., if it received a notification of the user going away, and then a "no such feed" error related to another request), it can ignore the error and print a warning instead. That said, nothing that belongs to the demos, probably, as they're only meant to be a simple example of what the plugins can do, and not to cover every possible scenario.

Closing as not really an issue, feel free to discuss this on the group if you think this deserves more attention.

**Closed by lminiero** 2016-12-28 09:41 UTC
