### ISSUE TITLE
Audiobridge deadlock.

### ISSUE THREAD

**Issue by IvRRimum** [meetecho/janus-gateway#919] opened 2017-06-04 15:21 UTC
I am using websockets, i recompiled libwebsockets with LWS_MAX_SMP=1 and i still managed to get the deadlock.

But here's the weird behaviour of the deadlock: I am using 2 plugins in my janus installation:

audiobridge
videoroom.
When a deadlock happens on audioroom, i can still access and use videoroom. I don't know if this is related tho.
Also i wanted to add that i am using janus-gateway version from Dec 20, 2016.
I ran the LOCK/DEADLOCK script and i got these: https://pastebin.com/zAa4iNLC

How to reproduce: Create 6 chrome tabs and join a single room. Do the same on pc 2. and connect from 3rd device(in my case its mobile app). Run automation script that refresh -> join room -> unmute for 2 seconds -> refresh -> join....

After a while the audiobridge will deadlock.

**EDIT**: After further crashing, the first lines of the LOCK/UNLOCK script change, depending on the situation where it deadlocked(next time its not in my room_helper:radio_thread, but in list_rooms, etc). So that probably means it deadlocks before and then tries to lock again on already locked mutex.

I will update this issue with more info.

**Comment by lminiero** [comment] 2017-06-05 10:25
Not sure what `janus_audiobridge_radio_thread` is. If you made changes to the plugin, we won't be able to help you, sorry.

**Comment by lminiero** [comment] 2017-06-05 10:26
I see 52 locks in a method called `janus_audiobreidge_sync_endpoints_list_rooms` that is not in our plugin either. Closing as likely caused by your own modifications.

**Closed by lminiero** 2017-06-05 10:26 UTC

**Comment by IvRRimum** [comment] 2017-06-08 13:59
Update: Locks like `janus_audiobreidge_sync_endpoints_list_rooms` are inconsistent. A locks that stay pretty mutch on each deadlock scenario are:

```
  '0x7f2ce4027bb8':
   { locks: 1,
     line: '[ice.c:janus_ice_cb_nice_recv:1965:] LOCK 0x7f2ce4027bb8' },
  '0x7f2cd400a328':
   { locks: 1,
     line: '[ice.c:janus_ice_cb_nice_recv:1965:] LOCK 0x7f2cd400a328' } }
```

and 

```
{ '0x7f2d040101d8':
   { locks: 1,
     line: '[ice.c:janus_ice_handle_attach_plugin:981:] LOCK 0x7f2d040101d8' },
  '0x7f2d24046198':
   { locks: 1,
     line: '[ice.c:janus_ice_handle_attach_plugin:981:] LOCK 0x7f2d24046198' },
  '0x7f2d4416e988':
   { locks: 1,
     line: '[ice.c:janus_ice_handle_attach_plugin:981:] LOCK 0x7f2d4416e988' },
  '0x7f2d00011148':
   { locks: 2,
     line: '[ice.c:janus_ice_handle_find:966:] LOCK 0x7f2d00011148' },
  '0x7f2d3c01b9d8':
   { locks: 1,
     line: '[ice.c:janus_ice_handle_attach_plugin:981:] LOCK 0x7f2d3c01b9d8' },
  '0x7f2d64019998':
   { locks: 1,
     line: '[ice.c:janus_ice_handle_attach_plugin:981:] LOCK 0x7f2d64019998' },
  '0x7f2d640196b8':
   { locks: 1,
     line: '[ice.c:janus_ice_handle_attach_plugin:981:] LOCK 0x7f2d640196b8' },
  '0x7f2cec028dd8':
   { locks: 1,
     line: '[ice.c:janus_ice_handle_attach_plugin:981:] LOCK 0x7f2cec028dd8' },

```

**Comment by IvRRimum** [comment] 2017-06-08 14:02
Also, here's my LOCK/UNLOCK script update(if somebody finds it useful). It takes all the janus.out.10/9/8/.. and looks for deadlocks in all of them.

```
if(process.argv.length <= 2) {
	console.log("Missing filename...");
	console.log("Usage: " + process.argv[0] + " " + process.argv[1] + " logfile");
	process.exit(1);
}
var filename = process.argv[2];
console.log("Parsing log file " + filename + " for LOCK/UNLOCK evaluation...");

var locks = {};
var backup = 10;

while(backup >= 0) {
  if(backup == 0) {
    var temp_filename = filename;
  } else {
    var temp_filename = filename + "." + backup;
  }

  console.log(temp_filename);
  if (!require('fs').existsSync(temp_filename)) {
    backup -= 1;
    continue; 
  }

  var lineReader = require('readline').createInterface({
    input: require('fs').createReadStream(temp_filename)
  });
  lineReader.on('line', function(line) {
    if(line.indexOf("LOCK") < 0)
      return;
    // Found a line: is it a lock or an unlock? what for?
    var unlock = line.indexOf("UNLOCK") > -1;
    var mutex = line.split("LOCK ")[1];
    if(unlock) {
      delete locks[mutex];
    } else {
      var count = locks[mutex] ? locks[mutex].locks : 0;
      locks[mutex] = {
        locks: count+1,
        line: line
      }
    }
  });
  lineReader.on('close', function() {
    console.log("");
    console.log("");
    console.log("");
    console.log("Locks still taken:");
    console.log(locks);
  });

  backup -= 1;
}
```
