### ISSUE TITLE
Codec errors when using Video Room from iOS 11 Safari Beta

### ISSUE THREAD

**Issue by chrisuehlinger** [meetecho/janus-gateway#964] opened 2017-08-02 20:32 UTC
I'm not sure if you're taking on bugs in Safari 11 yet, or if this might be a result of a Safari bug that they'll squash later, but I figured I'd report this for good measure anyway.

When using iOS 11 Safari on my iPad, the Echo Test and Video Call demos work fine (between iOS devices, and even between an iOS device and desktop Chrome).

However, when I try to make an iOS device join a Video room, their local video keeps saying "Publishing...", other viewers will see a "No Remote Video" sign, and the server logs display the following:

```
Creating new session: 4827082839023762
Creating new handle in session 4827082839023762: 5433299104750275
[5433299104750275] Creating ICE agent (ICE Full mode, controlled)
[WARN] Couldn't find codec we needed (vp8) in the offer, rejecting video
[WARN] [5433299104750275] Skipping disabled/unsupported media line...
[WARN] [5433299104750275]     Missing valid SRTP session (packet arrived too early?), skipping...
```

If a non-iOS device joins the room, their feed won't show up on the iOS device, and Safari throws an error box saying: 

```
[Error] WebRTC error: – OperationError (DOM Exception 34): Failed to set remote offer sdp: Session error code: ERROR_CONTENT. Session error description: Failed to set remote video description send parameters..
OperationError (DOM Exception 34): Failed to set remote offer sdp: Session error code: ERROR_CONTENT. Session error description: Failed to set remote video description send parameters..
	error
	error (videoroomtest.js:497)
	promiseReactionJob
```

Other than this, Janus is working great with iOS 11 Safari's newfound WebRTC support!

**Comment by lminiero** [comment] 2017-08-02 20:50
Answering quickly as I'm about to start my holidays, and won't touch any code for the next 2-3 weeks. I guess the SDP offer we generate for the H264 publisher contains a m-line for video with port 0, and that causes viewers to barf, so that will need to be fixed. Anyway, have a look at this commit: https://github.com/meetecho/janus-gateway/commit/a9b6dcee5ae19ffe8502231d9b72877f34ce9099#diff-f302a3ccc39e037fccf44e207332553c
as it allows you to only subscribe to part of the media a publisher is sending (in your case, you'll want to only subscribe to audio). That should fix the error. As an alternative, set the room videocodec to H.264 and that should cover all browsers (something I hate to advice, as I'm not a fan of proprietary codecs at all).

If you want to keep this issue open, please beware I won't touch it until I get back.

**Comment by chrisuehlinger** [comment] 2017-08-03 18:08
I took a look at `janus.plugin.videoroom.cfg.sample` and set the videocodec to h264. Video room now works, so that workaround should be enough for now. I'll leave this issue open though as a reminder about the SDP offer problem you mentioned, have fun on vacation!

**Comment by lminiero** [comment] 2017-09-04 10:01
I recently made a fix that makes sure that if video is actually disabled in the publisher, we don't offer it at all for viewers (who would only get an audio m-line then). Could you check if this fixes the issue you had?

**Comment by lminiero** [comment] 2017-09-04 10:11
PS: by disabled I also mean "publisher only does H.264 but room is VP8", so your case I guess.

**Comment by lminiero** [comment] 2017-09-04 10:21
Just tested with a Safari Technology Preview and it seems to be working as expected for me. There's still the issue of the Safari viewer complaining about the Chrome publisher (due to the use of VP8 video) but that can be blamed on the broken way of negotiating media in the browser (it should reject video, not fail), and can be fixed anyway on the client side using the "only subscribe to audio, not video" request. Closing the issue, let me know if you believe this should be reopened.

**Closed by lminiero** 2017-09-04 10:21 UTC

**Comment by vitlage** [comment] 2018-02-08 16:54
Hello, I've issue reproducing (version 11.0.2), the same error, on safari, the rest browsers works fine

**Comment by mcastilloz** [comment] 2018-08-05 03:09
Hello I've similar error. work fine (between iOS devices, and even between an iOS device and desktop Chrome). but not on the iphone (not showing video),  the others in the room can see  my  video and hear the audio, but on my iphones  the video is black.
