### ISSUE TITLE
Janus SIP plugin hangs up when there is issue SIP signalling

### ISSUE THREAD

**Issue by nbansalvox** [meetecho/janus-gateway#484] opened 2016-03-14 11:12 UTC
While doing some basic testing with Janus SIP plugin, I noticed that for certain call flows, Janus SIP plugin starting spitting the following error and becomes unresponsive:
`[plugins/janus_sip.c:janus_sip_relay_thread:2883] [SIP-click2vox] Error polling: POLLERR.`
It seems that issue is reproducible, here is the SIP call flow resulting in the error:
Janus     SIP INVITE --------> Remote end point
Janus     2xx       <----------    Remote end point (2xx contain Record  Route header address)
Janus    ACK      ------------> SIP address in Contact header of 2xx
Issue in this case is that  ACK should have been sent to the address in Record-Route header rather than IP address in Contact header of 2xx.
This SIP signalling always triggers the above said issue with Janus.

**Comment by saghul** [comment] 2016-03-14 11:57
I believe there is some problem with Sofia SIP or with how we use it. Do you get the same issue if you specify the proxy? (do so by using an IP address, if you put a domain it will make a query for each request)

**Comment by lminiero** [comment] 2016-03-14 12:03
That's what I suggested [here](https://groups.google.com/forum/#!topic/meetecho-janus/dbmAkHaug3w), referring you your comment in #451, I don't know if the POLLERR thing also happens when doing that. My guess is that the missing ACK leads to the local RTP/RTCP sockets being closed by the code somewhere, but the media loop stays up: I don't know if that's the case though.

**Comment by nbansalvox** [comment] 2016-03-14 12:37
The issue doesn't happen when I use configure the proxy IP address while sending REGISTER reqeust to Janus. 
But in the failing case, I think error isn't handled graceful, it stays in the loop of POLLERR, whereas I think it should just hangup the call gracefully

**Comment by lminiero** [comment] 2016-03-14 12:48
That's what the patch I made last weekend should do: https://github.com/meetecho/janus-gateway/commit/48967c3e69d5cbbdeff6e3f96d3640bc0129ae10
Have you tried if that commit fixed the issue for you?

**Comment by lminiero** [comment] 2016-03-14 14:56
Can this have anything to do with it? https://sourceforge.net/p/sofia-sip/mailman/message/8147409/
I'm not a 100% expert on SIP, but I guess they're saying you have to use the Contact address whenever you get one (which is what is happening in the 200 OK, at least in my dumps), unless strict routing is involved (in your case it's lr instead).

**Comment by lminiero** [comment] 2016-03-14 14:59
In that case, I guess the problem may be in how the proxy is filling the Contact part (why 7070 instead of 5060?). But again, this is just guess work on my side at the moment.

**Comment by nbansalvox** [comment] 2016-03-14 16:03
I haven't tried the patch yet, I'll let you know when I'll let you know whenever I rebuild Janus again.
For the issue ref Record-Routing, it is not the same issue as mentioned in the URL. Our issue is that:
Sofia SIP doesn't send the ACK to IP Address in Record-Route header, it is sending the ACK to IP Address in Contact header, which isn't correct. 
As per RFC 'When we receive a SIP 2xx with Record-Route, next SIP message in dialog should go to IP address of 
record-route header.'

**Comment by nbansalvox** [comment] 2016-03-14 16:10
If you want to reproduce the issue, you can do it yourself, as mentioned on the mailing list:, just dial the following SIP URI ''sip:+883510000000091@inum.net', don't use inum.net as proxy address, this domain belongs to the remote end point.
I used 'sip:click2vox@voxbone.com' as the caller identity (it doesn't matter as in this case, call is going directly from Janus to inum.net), register as a guest, skip the proxy address.

**Comment by lminiero** [comment] 2016-03-14 16:45
> Our issue is that:
> Sofia SIP doesn't send the ACK to IP Address in Record-Route header, it is sending the ACK to IP Address in Contact header, which isn't correct.

If it is indeed a broken behaviour (I still have some doubts, isn't an incoming Contact supposed to have priority for in-dialog messages?), I'm not sure there's much we can do, as it's something the Sofia SIP stack itself does, and not anything we can interfere with, I guess. The only possibly related thread I found is [this](https://sourceforge.net/p/sofia-sip/mailman/message/6518320/), and it doesn't shed much light on the matter. Invoking the wisdom of @saghul here!

**Comment by lminiero** [comment] 2016-03-14 16:56
Nevermind that, thinking about it the Contact should only be used to set the Request-URI at max, but for the actual transport the Record-Route should be used instead. That said, my guess now is that the cause may be the "guest" registration: not sure if doing a REGISTER fills in something we're not doing otherwise. Again, we'd have to check how to tell Sofia SIP to do things differently, as it's something it does by itself.

**Comment by nbansalvox** [comment] 2016-03-15 09:06
Record-Route was designed to keep the SIP proxies in loop, it overrides the Contact IP address and forces a SIP UA to send SIP requests to Record-Route IP address. It is possible that it might have something to do witth REGISTER as Guest. I think it shouldn't be too hard to fix, if you could get some more logs from Sofia-SIP, it will become easier to fix

**Comment by lminiero** [comment] 2016-05-27 06:43
I think that, with the referenced patch, we can close this issue for now. Feel free to reopen if it's still a problem.

**Closed by lminiero** 2016-05-27 06:43 UTC
