### ISSUE TITLE
Audio conference audio is very delayed (in audiobridge)

### ISSUE THREAD

**Issue by mattvv** [meetecho/janus-gateway#242] opened 2015-05-20 23:45 UTC
Steps to reproduce

1. Join a call using audioconf, in my case using 48000hz has the mixing.
2. Talk and observe that both parties can hear eachother without delay
3. Wait a few minutes
4. Observe delay of voice is increasing
5. Wait 10-15 minutes
6. Observe delay increase again

I've had the delay go to 30+ seconds from speaking in some of my tests.

**Comment by nowylie** [comment] 2015-05-21 00:11
I'm guessing you mean `48000hz`, which could introduce lag if the mixing thread is taking more then 20ms to mix streams. 

AFAIK this is caused by the way that the audiobridge demo plugin buffers/unbuffers packets before mixing. I also noticed the delay before I started work on my own plugin.

**Comment by mattvv** [comment] 2015-05-21 00:18
Yep you're right. I can also reproduce this on 24000hz. I'm running janus on an ec2 c4.large instance.

**Comment by lminiero** [comment] 2015-05-21 08:44
I never experienced anything like that, and I've tested it for quite a long time on my "crappy" laptop, so something much less powerful than a large ASW instance... Are you using the latest version?

**Comment by lminiero** [comment] 2015-05-21 09:12
Just did one more test for about 15 minutes in a 48khz room and it worked fine for me. Make sure you're using the latest version of Janus.

**Comment by mattvv** [comment] 2015-05-23 16:57
Upgraded to latest version of Janus and tried exact same situation with same person for 3+hour call. No delay. Thank you @lminiero again! Closing.

**Comment by willbarrett** [comment] 2015-06-22 19:27
@lminiero we're seeing this issue as of 76a4d5cce831bc77ff09cd25c778132831debf59 - what commit do you believe resolved the problem?

**Comment by lminiero** [comment] 2015-06-22 19:48
@willbarrett not sure as I could never replicate the issue, or at least it wasn't there anymore when I tried.

**Comment by willbarrett** [comment] 2015-06-22 19:48
OK. We have multiple reports of audio delays from folks using our platform. What information can we get you that would help figure out the cause of this?

**Comment by lminiero** [comment] 2015-06-22 19:53
I don't think there's any piece of info that could pin down the issue as of now.

For progressive delays, I guess the queues might be at fault here. Is this happening in rooms with a lot of participants? Or on servers that are mixing a lot? Or is it just random?

Tomorrow I'll try to add the queues length info to the admin API, so that you can poll that when it happens: a normal behaviour should be a low and constant queue size; if the queues keep on increasing instead it might mean the mixer can't keep up with the packets for some reason.

**Comment by willbarrett** [comment] 2015-06-22 19:55
OK, thanks. Let me know when that change is in and we'll put it into production on our side. We'll keep an eye out for server conditions when it happens.

**Comment by tommoor** [comment] 2015-06-22 19:58
@lminiero we've had it reported from specific users that seem to get it and others on the same server don't seem to have the issue (I don't think we've ever noticed it internally).

**Comment by lminiero** [comment] 2015-06-22 20:02
@willbarrett @tommoor one thing you might want to check is the number of audio NACKs for the users experiencing the issue. Many retransmissions (e.g., in case of network problems or packets being dropped) might result in audio being reproduced slightly later, according to how the browser handles that. Not sure if Chrome buffers internally when that happens.

I'm more inclined towards the queues issue, though... do you know if all users in the same room experience the same?

**Comment by mattvv** [comment] 2015-07-21 17:47
@tommoor Did you get any resolve from this?

@lminiero - I'm still having this issue with some users. It's harder to reproduce now but its definitely still occuring. One note is I'm not using WebSockets and i'm using long polling only (due to a websockets crash in janus). Would that have anything to do with it?

**Comment by lminiero** [comment] 2015-07-22 07:32
Signaling and media plane are not related. Could you let me know what the admin API has to say for the users in the room who have delayed audio? Actually, even better, for all users in the room with delayed audio, and if this affects all of them or only some of them.

**Comment by lminiero** [comment] 2015-08-03 11:09
Still waiting... :wink:

**Comment by willbarrett** [comment] 2015-08-28 19:00
Hi Lorenzo. User reports suggest that this affects all users in the same room. I've shot you an email with a very specific user report that may provide more insight.

**Comment by willbarrett** [comment] 2015-08-28 19:01
Not sure if this helps, but the video plugin doesn't suffer from the same issue on the same hardware.

**Comment by lminiero** [comment] 2015-08-30 08:50
The video plugin doesn't mix, it only relays: the browser handles timing from timestamps and discards too late packets. I guess we might want to do something similar in the audiobridge plugin.

**Comment by lminiero** [comment] 2015-08-31 16:27
Check this version of the audiobridge and let me know if it helps.

**Comment by lminiero** [comment] 2015-09-02 18:17
Closing since @willbarrett confirmed #317 fixed this for him.
@mattvv @nowylie feel free to repoen if that's not the case for you guys.

**Closed by lminiero** 2015-09-02 18:17 UTC
