### ISSUE TITLE
There is no way for a plugin to completely  disconnect session from the gateway.

### ISSUE THREAD

**Issue by sdrsdr** [meetecho/janus-gateway#940] opened 2017-07-03 07:52 UTC
There are `close_pc` and  `end_session` but this are all related to the connection to the plugin. The connection to the gateway stays and there is no way for the plugin to disconnect the remote end completely. This makes the janus gateway trivial to DOS just connect few thousand clients  until open file limit is reached. Having a way for the plugin to disconnect sessions will not help much as you can simply connect to the gateway and not request any plugin. Anyway a plugin must have a way to fully reject connection to the gateway if the client fails to meet some criteria.

**Comment by lminiero** [comment] 2017-07-03 09:12
"Connection" doesn't make much sense in the Janus world. What is a connection? With modular transports, that's not an easy concept to grasp. While there is a connection in WebSockets which is tightly related to a session, the same can't be said for any of the other transports we provide.

What you ask is probably more linked to the discussion in #905. We plan to work on that, but I'm very busy right now on other activities, so not sure when I'll be able to start. In the meanwhile, if you need better protection you may want to either proxy the requests to Janus (via something you can control to reject requests) or wrap the Janus API and only allow your servers to talk to Janus (again, would shift access control to your application and hide Janus from the outside).

**Comment by sdrsdr** [comment] 2017-07-03 10:59
I was thinking also about this and how  the core of janus need not understand the specific needs of the plugins it uses. On the other hand there is no way for the plugins to communicate to each other via janus core. You could probably create a interface akin to ioctl where all the plugins,transport or application, can do "calls" and listen and response for such calls over janus_plugin_session. Thus application plugin can talk to transport plugin about filtering/closing connections from specific peers without  janus core loosing it's simple generic idea of just passing messages around

**Comment by lminiero** [comment] 2017-07-07 08:52
It's still not going to work, because there's no way plugins can tell transports to keep some people out. How would they do it? Transports are too wildly different from each other. The discussion I linked would be the closest to something like what you'd want, and would be a pre-filtering/authorization of requests.

If you have anything else to add to this, please do it there: closing this issue for now.

**Closed by lminiero** 2017-07-07 08:52 UTC

**Comment by sdrsdr** [comment] 2017-07-07 11:33
I think it is possible to implement a message bus from transport, to application plugin via event handler plugin. You just have to "register" with a message providing a callback addres  and then you can broadcast to all registered with another message that the event plugin will distribute to all registered. :)

**Comment by lminiero** [comment] 2017-07-07 11:39
The problem is not the bus, that's the easy part: it's how to convey transport information. How do I tell the transport to block "Bob"? Who's Bob? His session+handle, which is the only thing the plugin can (implicitly) refer to via their plugin session pointer? They can just refresh the page and create a new one. His "connection"? What's a connection? His IP address? A rabbit queue? Whatever will popup in a month from now when someone else will implement a brand new transport that uses a brand new protocol? It's just impossible, and the only way to implement true access control right now is doing it yourself in a wrapper.

**Comment by sdrsdr** [comment] 2017-07-07 11:52
What if I start from websocket transport plugin and evolve it to listen to such events. and I have a plugin emitting this  events. I can disable the "unsecure" plugins and have the janus run the way I want it with minimal effort. The transport can figure out the best way to block offenders, there is TCP reset as start, iptables for the refreshing type of pests and all kinds of DDOS attack mitigations if you like to go that way. My issue is/was that there were no "standard" way to tall along the stack and that you have to resolve to "hacks" to get the job done :) but it is possible so meh!
