### ISSUE TITLE
Media from Janus doesn't reach Subscriber/Listener 

### ISSUE THREAD

**Issue by ramprakash110109** [meetecho/janus-gateway#1944] opened 2020-02-12 14:03 UTC
Hi Lorenzo, I was testing video room plugin  and found a peculiar issue. Sometimes, While janus sends the stream of a publisher to the subscriber, the subscriber doesn't receive the stream and the frame was stuck. 

I confirmed this in admin page that the janus was still sending stream (through outgoing bytes ) to the subscriber. I also noticed that the RTCP receiver report from the subscriber doesn't reach janus (again confirmed through admin page , no rtt value changed for the subscriber).

While this may be caused by a variety of network issues, it would be better if we can somehow identify this and notify to user (or some controlling server). With this, we can restart or create new plugin to subscribe.

My thought is storing the value of last received RR report from subscriber and compare this in "janus_ice_outgoing stats_handle" in ice.c and send the notification . 

Can you plz  tell me whether this approach will work  or suggest me any better solution for this ?

**Comment by lminiero** [comment] 2020-02-17 11:32
Sounds like a connectivity issue, not a bug. Packets go over UDP, so they can (and sometimes will) get lost. That's what retransmissions are for. If the channel is gone for good, the recurring connectivity checks should detect this, and trigger an ICE `failed` event, so I don't think we need other means to notify the application. Closing.

**Closed by lminiero** 2020-02-17 11:32 UTC

**Comment by ramprakash110109** [comment] 2020-02-17 13:18
I also thought the same. Though this issue occurs rarely (1 out of 30 sessions), if occurs,  "ICE FAILED" event was not getting triggered. Janus was sending packets to the subscriber, but the subscriber was not receiving any data (should be connection issue as you suggested) . But the problem is i had waited for more than 4 mins and there was no disconnection from either side (no ICEfailed signals). There is no mechanism currently present to detect whether janus receives RR  continuously from the subscriber. Hence suggested this as this will find this connection issue quicker

**Comment by atoppi** [comment] 2020-02-17 13:36
I agree with @lminiero.
The connection probing should be in charge of the ICE transport through the periodic STUN-based keep-alives. If no failure event has been fired on both Janus and browsers but the image is stuck, this means that the periodic checks are fine but the media stream is seriously compromised (e.g. due to congestion).
