### ISSUE TITLE
pfsocket transport with SOCK_SEQPACKET gets into a broken state when a session times out

### ISSUE THREAD

**Issue by mzanetti** [meetecho/janus-gateway#1009] opened 2017-09-22 08:06 UTC
Connecting to the pfsocket transport with SOCK_SEQPACKET and creating a session works fine, but if the session times out after 60 seconds, something goes very wrong on the connection. First, it fails to actually send the timeout message over the socket, but it also doesn't completely close the socket. Here's the log:

```Got new Unix Sockets Janus API client: 8
Message from client 8 (147 bytes)
{
    "janus": "create",
    "transaction": "eu-west-1:a84a5187-2dd6-4820-8407-a88e92b10df1/listeningPeer/dummy_device_key/C2D_dummy_device_key"
}

Got a Janus API request from janus.transport.pfunix (0x7fe32c0008c0)
Transport task pool, serving request
Creating new session: 2743378674134852
Sending Janus API response to janus.transport.pfunix (0x7fe32c0008c0)
Written 193/193 bytes on 8
<snip>
Message from client 8 (54 bytes)
{
    "janus": "ping",
    "transaction": "pingety"
}

Got a Janus API request from janus.transport.pfunix (0x7fe32c0008c0)
Transport task pool, serving request
Sending Janus API response to janus.transport.pfunix (0x7fe32c0008c0)
Written 51/51 bytes on 8
Timeout expired for session 2743378674134852...
Written -1/60 bytes on 8
[janus.c:janus_cleanup_session:407] Cleaning up session 2743378674134852...
Destroying session 2743378674134852
Detaching handle from JANUS Guh.io plugin
Removing Guh.io session...
No WebRTC media anymore
[WARN] No ws_client?
[5032895223401387] Sending event to transport...
[5032895223401387] Handle detached (error=0), scheduling destruction
Checking 1 old Guh.io sessions...
Cleaning up handle 5032895223401387...
[5032895223401387] WebRTC resources freed
[5032895223401387] Handle and related resources freed
Checking 1 old Guh.io sessions...
Freeing old Guh.io session
Message from client 8 (54 bytes)
{
    "janus": "ping",
    "transaction": "pingety"
}

Got a Janus API request from janus.transport.pfunix (0x7fe32c0008c0)
Transport task pool, serving request
Sending Janus API response to janus.transport.pfunix (0x7fe32c0008c0)
Written -1/51 bytes on 8
```

As you can see, the session establishment works, then ping/pong work fine too, it receives the ping, answers with pong. Next thing, the session times out. The first thing that seems wrong to me is already the "Written -1/60 bytes on 8" which I think should be the timeout message it should send to notify my code of the timeout. Starting from that point on, I can still send ping commands, and it actually gets them and prints them in the log, but it fails to reply because th socket is semi-closed or something.

The oddest thing about this is that on my end I couldn't find any way to detect this state so I'm never sure when it is ok to clean up the session on my end.

**Comment by mzanetti** [comment] 2017-09-23 10:44
I found this line in janus_pfunix_session_over():

        /* FIXME Should we really close the connection in case of a timeout? */

To me it seems closing the socket at this stage is not what it should be. First, I think there is no reason to close the socket at all during the lifetime of janus. Or is there another reason why a new socket connection should be established on every session?
Even if the socket should be closed after the session, this place seems a bit too early. As you can see in the above log, it closes the socket here and then fails to actually notice the client of the session timeout.

In the meantime I've been able to establish a successful WebRTC connection and when the session is over, the same issue happens. Janus cleans up the session and fails to inform the client about it printing this error message again:

```Detaching handle from JANUS Guh.io plugin
Removing Guh.io session...
No WebRTC media anymore
[5698535727386669] Sending event to transport...
[5698535727386669] Handle detached (error=0), scheduling destruction
[5698535727386669] ICE thread ended!
Written -1/60 bytes on 8
```

**Comment by lminiero** [comment] 2017-09-23 10:58
Will look into this on Monday (still abroad with limited connectivity). Anyway, wrong management of timeout notifications apart, you should use keepalive requests to avoid timeouts on the transport in the first place, as the Janus core cannot know whether no request came in 60s because the transport became unavailable, or simply because the application isn't sending anything: we use the "keepalive" request as an application level mechanism for keeping the session up and running.

**Comment by mzanetti** [comment] 2017-09-24 11:29
Thanks Lorenzo. Yes, I've seen the keepalive message, will use that when appropriate.

In the meantime I've commented out the socket destruction in anus_pfunix_session_over() and now I correctly get the session timeout. This also means that in my patch janus never disconnects the socket and so far I am having great success with that... The connection between janus and our service remains stable and is used to control multiple webrtc sessions.

**Comment by lminiero** [comment] 2017-09-25 10:07
The problem is that we cannot just keep the channel open, as it may be a leak. What if the connection has actually been lost (e.g., client went away without closing properly) which is what our application level timeout may have detected? If we don't close the channel, it will be a leak because we'll have a connection there that nobody will use anymore.

The real issue here seems to be ensuring that, whatever the transport (pfsocket, websockets, etc.), we don't close before we send the timeout event (which anyway may get lost nevertheless, especially if the transport really timed out and is unavailable). So it's perfectly normal for the connection to be closed in case of a timeout: it's up to you that it doesn't happen (keepalives).

**Comment by mzanetti** [comment] 2017-09-25 11:06
Yes, closing the channel before informing the client about it is the real issue... I think if that's handled properly, all the rest can have a proper flow implemented.

One thing I'm wondering tho: 
If I connect to the socket and then don't do anything, the socket connection stays open forever. I don't need to send keepalive messages or anything. At this point the socket connection to the janus api seems to be unrelated to any ongoing webrtc sessions.
Then, when I establish a webrtc session the and when the session is destroyed, it will close the socket too. At this point now as socket connection seems to be tied to a webrtc session. What if during one webrtc session we establish a second one through the same socket connection? Will tearing down the first session close the socket (and with that probably destroy the second connection)?
I guess what I'm really asking is why there is this relation between the socket connection and a webrtc session? To me those seem like 2 unrelated things but still tied together somehow with the session teardown.

So if I understand correctly, your suggestion is that I can set up the socket connection directly on startup, but then, when a webrtc session starts, I need to start sending the keepalive messages, and when the session ends my socket will be closed and I just reopen it, correct?

**Comment by lminiero** [comment] 2017-09-25 13:31
That's correct: we only monitor session activity, at an application level, so if your connection doesn't have any session active we can't track it. The reason why is that sessions are much easier to track, since that's what requests address. On a general note, in fact, it's usually almost safe to assume that there's always a session per connection.

**Closed** 2017-11-28 18:20 UTC

**Comment by lminiero** [comment] 2017-11-28 18:22
Apologies if this took a while: this should be fixed now, as when we get a `session_over` we don't close right away, but simply wake the socket management thread up. Tested this briefly and it seems to work for me, but please let me know if that's not the case.
