### ISSUE TITLE
Video Room kick bug?

### ISSUE THREAD

**Issue by izemize** [meetecho/janus-gateway#836] opened 2017-03-30 09:32 UTC
Hi,

Can i kick anyway "listener" from Video Room? I only can kick myself (local cam publishing stop after kicked) but remote stream is playing continous. That's wrong. When user is kicked (removed) from room, how can play remote video stream?

Bonus:

I can't receive any "kicked" onmessage event, only for that:

janus: "hangup"
reason: "DTLS alert"
sender: 7698404874165238
session_id:6006349252239339

Thanks

**Comment by lminiero** [comment] 2017-03-30 12:16
You can only kick publishers (and not only yourself, any publisher if you know the secret). Closing as not a bug. Please refer to the meetecho-janus-group for discussing this.

**Closed by lminiero** 2017-03-30 12:16 UTC
