### ISSUE TITLE
ICE error in text-room, but not in video-room - Mozilla only

### ISSUE THREAD

**Issue by gjovanov** [meetecho/janus-gateway#998] opened 2017-09-08 18:01 UTC
Hi,
in our case we connect to Janus with a single session and we have multiple handles:
- H1 text-room - data channel for chat
- H(2-N): video-room - publishing/subscribing to video/audio/screen

As iceServers we are using single TURN server via TCP (coturn).

ICE outcome:
- video-room
   - Chrome - succeeds every time
   - FF - succeeds every time
- text-room
    - Chrome - succeeds every time
    - FF - fails every time

This also happens in the Janus HTML examples:

https://live.xplorify.net:8083/videoroomtest.html - ICE success
vs
https://live.xplorify.net:8083/textroomtest.html - ICE error

Also you can check our demo:
https://hello.xplorify.net/open-video-room/7539594940945330/15/true/true

The same janus server is behind live and hello subdomains, so you can check the admin logs:

https://live.xplorify.net:8083/admin.html

For example:

1. here is the video-room handle admin log:
- https://pastebin.com/Sk1LRCKy

2. here is the text-room handle admin log:
- https://pastebin.com/HZG85fgQ

Client
- webrtc-adapter/5.0.3/adapter.min.js
- janus.nojquery.js - last version from source code from yesterday

Server
- https://github.com/xplorify/janus - docker image
- ubuntu 16.04

Assistance is much appreciated.
Tnx.

/GJ

**Comment by lminiero** [comment] 2017-09-11 10:01
Mh, that's weird, as one of our internal applications (a simple conference bridge based on VideoRoom+TextRoom that we use for calls) definitely works on Firefox for us. Which version of Firefox is breaking for you? I'll check later if any of my Firefox instances fail.

**Comment by lminiero** [comment] 2017-09-11 13:06
Just tested with both Firefox 55 and 57 and the TextRoom works just fine for me.
I noticed from your Admin API dumps though that you're using TURN *within* Janus? As explained in the [FAQ](https://janus.conf.meetecho.com/docs/FAQ#turn) that's not needed at all (unless you have a custom deployment that requires it).

**Comment by gjovanov** [comment] 2017-09-11 18:16
Thanks for your input Lorenzo. 

TURN i janus.cfg we used because the VM with Janus docker image was behind NAT. In this case it's not behind NAT, but the same .cfg file remained, so the TURN setting can be omitted. And I've tried with/without TURN/STUN in janus.cfg and the result is the same - ICE for video-room plugin succeeds and ICE for the text-room plugin fails. It seems that is something with data channels related. But still don't know what.

Regarding FF, I used latest FF - 55.0.3 (32-bit). Interestingly enough this only happens to me and for our colleagues it's working (but they are in a different network).

Also what is interesting is:
a) When I run the HELLO demo on my laptop (nodejs serves https with self-assigned cert) and use FF, then ICE for Data Channel succeeds to the same Janus server.

b) when I try from laptop to the deployed HELLO demo and use FF,  then ICE for DC fails (again same Janus server).

c) finally, when I try from my laptop to your demo:
- https://janus.conf.meetecho.com/textroomtest.html
and use FF, then ICE for DC succeeds and I'm able to chat.
And in your demo no iceServers are setup on the client side.

I've also completely turned off Kaspersky and all its protection that might affect this ICE process.

Needless, to say, still don't know what might be causing this.

I will try to open a DC on the video-room and see if in FF ICE suceedes and the DC.ondataopen gets called.

Will let you know.

**Comment by gjovanov** [comment] 2017-09-12 18:18
Even with Data Channel in the Video-room, ICE fails.

It's seems to be related to FF and DC.

I've compared the ICE candidates for:
- VIDEO-ROOM
   - CHROME vs FIREFOX
- TEXT-ROOM
   - CHROME vs FIREFOX
which can be found at this paste bin: https://pastebin.com/4bGecC7a

And the candidates differ much between browsers as well as between plugins.

For example in Chrome, there is always a relay ICE candidate for both public IP addresses (client/server):
- 138.201.48.14 47734 typ relay raddr 80.110.127.22.
- 138.201.48.14 41059 typ relay raddr 80.110.127.22

Unlike Chrome, in FF the relay ICE candidate is a combination of the server public IP address:
- 138.201.48.14 40449 typ relay raddr 138.201.48.14
- 138.201.48.14 44517 typ relay raddr 138.201.48.14

@lminiero Do you thing this a mainly an issue with our TURN server or you some other possibility?
Tnx.

**Comment by lminiero** [comment] 2017-09-12 18:45
Have you checked if there's any exception on the JS console, e.g., something preventing `setRemoteDescription` to happen? What does `about:webrtc` say on Firefox? That said, try without TURN, and try capturing with Wireshark to see if you can spot why ICE fails for you.

**Comment by gjovanov** [comment] 2017-09-12 19:17
Here is about:webrtc gist:
https://gist.github.com/gjovanov/ab2ff3f9aa8a57cb89f65757e735953b.

I've also debugged the janus.js on:
https://live.xplorify.net:8083/textroomtest.html

and it enters in setRemoteDescription (Remote description accepted!) as well it does setLocalDescription (Got SDP!) and sends ack to the textroom.

Regarding wireshark, did you mean to track traffic of my machine or turn/janus machine?

**Comment by gjovanov** [comment] 2017-09-13 19:07
In about:webrtc https://gist.github.com/gjovanov/fdf31a9312318a44e1140446763cbe0d:

for video/audio rtc connection, two candidates succeed and one gets selected:

- 138.201.48.14:42270/udp(relayed-tcp) | 172.17.0.3:10062/udp(host) | succeeded | 33530706332222464 | true | true --> **THIS ONE GETS SELECTED**
- 138.201.48.14:42270/udp(relayed-tcp) | 138.201.48.14:46950/udp(relayed) | succeeded | 33530702641234944 | true |  

for  data channel connection, the same two candidates end up frozen:
- 138.201.48.14:43704/udp(relayed-tcp) | 172.17.0.3:10098/udp(host) | frozen | 33530706332222464 |   |  
- 138.201.48.14:43704/udp(relayed-tcp) | 138.201.48.14:40540/udp(relayed) | frozen | 33530702641234944

The same thing happens for FF and screen share.

Any idea why this might be the case?

**Comment by lminiero** [comment] 2017-09-14 14:27
> Regarding wireshark, did you mean to track traffic of my machine or turn/janus machine?

Doing both might help, as it would allow you to check if there are connectivity checks/responses you send that don't get to Janus or viceversa, but capturing the server side is more important.

Not sure where the issue is, considering it seems very specific to your setup.

**Comment by lminiero** [comment] 2017-09-25 10:46
Any news?

**Comment by gjovanov** [comment] 2017-09-25 17:44
We have done multiple iterations of TSHARK, Janus, Coturn and About:webrtc tracings and still can't figure out what is the cause. Wireshire STUN connections seem to work.

For example, here is the last one:
[logs.zip](https://github.com/meetecho/janus-gateway/files/1330213/logs.zip)

In this scenario, via my laptop I connect to: https://hello.xplorify.net/video-room/59b69146f68752014b4612d3/8825884329551233/15/true/true

which opens 2 handles (1 to video-room with audio/video; 1 to text-room with data channel).

You can see two separate logs:
- about-webrtc-textroom.log for Firefox about:webrtc
- about-webrtc-videoroom.log for Firefox about:webrtc
- admin-textroom.log via the Janus Admin UI log
- admin-videoroom.log via the Janus Admin UI log
- tshark.log - Wireshark log
- coturn.log - TURN server log
- janus.log - Janus level 5 logs

This is what we have noticed so far:
1. about-webrtc-textroom.log and about-webrtc-videoroom.log have the same ICE candidate succeeded but only the videoroom one is nominated and selected, whereat the textroom one remains stuck in succeeded.

2. Also admin-textroom.log and admin-videoroom.log show the same ICE candidates but textroom doesn't have a selected one

3. coturn.log shows many successful connections. There are several unauthorized messages:
 e.g.
session **006000000000000026**: realm <live.xplorify.net> user <>: incoming packet message processed, error 401: Unauthorized

but this is normal part of the session negotiation and thus these are followed by success message for the same session number:
15071: IPv4. Local relay addr: 138.201.48.14:44289
15071: session **006000000000000026**: new, realm=<live.xplorify.net>, username=<XplorifyAdmin>, lifetime=3600
15071: session **006000000000000026**: realm <live.xplorify.net> user <XplorifyAdmin>: incoming packet ALLOCATE processed, success

4. tshark.log has many STUN binding indication packets followed by several TCP packets which I believe RTC packets not recognized as such but as TCP - since our turn on the client side is with "transport=tcp"

5. janus.log libnice has many this kind of errors:
libnice-stun-DEBUG: STUN error: RTP or other non-protocol packet!



Here is the  client/server configuration

**My laptop**:
- public IP: 80.110.127.22
- private IP: 192.168.0.143 (subnet: 192.168.0.0/24, gateway: 192.168.0.1)

**Coturn docker container**:
- public IP: 138.201.48.14, port: 3479
- not behind NAT (public IP only)

**Janus docker container**:
- public IP: 138.201.48.14
- private IP: 172.17.0.3 (subnet: 172.17.0.0/16, gateway: 172.17.0.1)
- janus.cfg:
[nat]
stun_server = 138.201.48.14
stun_port = 3479
nice_debug = true
; ice_lite = true
ice_tcp = true

As we are still being stuck with this one. Any help is highly appreciated.

**Comment by lminiero** [comment] 2017-11-06 14:16
Any news on this? Just noticed the `ice_tcp = true` there: you may want to disable that, as it won't work without `ice_lite` (which you can't use as the server is NATted).

Anyway, one thing I might add is that you may be encountering a weird behaviour of the docker netfilter NAT logic, which can end up acting as some sort of weird symmetric NAT at times, that apparently works fine with Chrome but not with Firefox. I'm not an expert on this, but I remember discussing this with my colleagues, which is one of the reasons we use [pipework](https://github.com/jpetazzo/pipework) to assign public addresses to our docker instances instead. This may be unrelated, considering it works fine for you in other demos except for the TextRoom, but I thought I'd share it anyway.

**Comment by gjovanov** [comment] 2017-11-07 13:25
Thanks for the info Lorenzo.
Honestly we have given up using datachannels for chat/whiteboard due to this issue and decided to use WS instead, which work just fine.

Over the weekend I can give it a try one more time, even with public addresses on containers and let you know. 

Otherwise, you can close this issue as it seems related to the way firefox handles the ICE candidates behind these kind of networks.

Needless, I will let you know after the trial.

**Comment by lminiero** [comment] 2017-11-07 13:32
Thanks for the update! Closing then, we can always reopen later on.

**Closed by lminiero** 2017-11-07 13:32 UTC

**Comment by gjovanov** [comment] 2017-11-23 12:33
Just for the info, suddonly after updating the webrtc-adapter version to 6 and with the latest Mozilla version, the datachannel ICE candidates started working.

We didn't change anything in our Janus setup nor the networking has changed. Everything is the same... Just newer version of adapter and mozilla.

Love when issues get fixed on their own, although hate not to learn from them :)
