### ISSUE TITLE
Unexpected websocket disconnect during ICE trickle

### ISSUE THREAD

**Issue by arjenveenhuizen** [meetecho/janus-gateway#243] opened 2015-05-21 12:29 UTC
We just updated our janus gateway to the latest version (making the transition to libwebsockets, our previous version was of Februari 2015) and currently we face the issue that during ICE trickle phase, the websocket connection between client (iOS) and server is suddenly dropped. 

Log can be found here: http://pastebin.com/5P7eSrC0

The interesting stuff happens around line 1626:
(....)
[3113378435] Trickle candidate (video): candidate:1379757665 2 udp 41886206 52.17.34.161 62922 typ relay raddr 193.110.235.126 rport 18237 generation 0
[3113378435] Got a video candidate but we're bundling, ignoring...
Sending WebSocket response {
   "janus": "ack",
   "session_id": 234494785,
   "transaction": "B2A1A511-47C4-460A-B2FD-30283F20BC1F-283-0000001C3EF719E9"
} (128 bytes)...
  -- Sent 128/128 bytes
Sending WebSocket response {
   "janus": "ack",
   "session_id": 234494785,
   "transaction": "5DD77DC2-0544-4753-9CE6-DBAE84041C22-283-0000001C3EF1A491"
} (128 bytes)...
  -- Sent 128/128 bytes
[WSS-0x19bbd60] WS connection closed
[WSS-0x19bbd60] Destroying WebSocket client
[WSS-0x19bbd60]   -- closed
(...)

Janus, libwebsockets and libnice are on GIT HEAD.

Any clue?

**Comment by lminiero** [comment] 2015-05-21 12:37
You should check who closes the connection.

**Comment by arjenveenhuizen** [comment] 2015-05-21 12:46
Thanks for your reply! We have been investigating that up-close and we are 100% sure that it is not the client who closes the connection. If we use the February Janus build, everything works without a problem. To me it looks like a regression.

**Comment by lminiero** [comment] 2015-05-21 12:52
February is way too old... we fixed tons of stuff on websockets since. Please use the latest revision.

**Comment by lminiero** [comment] 2015-05-21 12:52
Ops sorry, thought you said you're using the February version.

**Comment by lminiero** [comment] 2015-05-21 12:53
That said, I'm not aware of any issue related to WebSockets: I've been using them intensively for a project I'm working on that involves Janus, and they've been quite stable. The old version using libwebsock was not reliable at all, unfortunately.

**Comment by lminiero** [comment] 2015-05-21 12:55
Have you checked with something like Wireshark if it's really Janus that is closing it?

**Comment by arjenveenhuizen** [comment] 2015-05-21 13:12
Not yet, good suggestion. Could it have something to do with the fact that we send a TCP offer? (e.g. line 719 in the pastebin). Lateron it says that Janus is dropping the TCP offer but perhaps it still causes the crash? We're gonna check this by removing the TCP offer. Keep you posted.

**Comment by arjenveenhuizen** [comment] 2015-05-21 13:27
Just ran wireshark and we can see that it is Janus who drops the connection (TCP->reset flag is set) from the server side...

**Comment by arjenveenhuizen** [comment] 2015-05-21 14:00
Update: it looks like it has something to do with the number of ICE offers we send from client to server and in what order they are sent. Sometimes the negotiation succeeds and everything is fine. 
Here is a log when the ICE negotiation fails (9 out of 10 times): http://pastebin.com/beACdLNn
Here is a log when the ICE negotiation succeeds (1 out of 10 times): http://pastebin.com/6DfjXEQA

**Comment by arjenveenhuizen** [comment] 2015-05-22 06:17
It appears that the issue was largely related to the local network. When deployed on Amazon things appear to run OK. My best guess is that an error in libnice triggers janus to drop the websocket connection (wireshark confirmed that it is not the client that drops the connection). Interesting thing is that janus does not loose connection to libnice. Libnice reaches some kind of limbo state where it is still trying to process offers of a connection which is no longer there. 
Anyway, thanks for the support!

**Comment by lminiero** [comment] 2015-05-22 07:42
But that should never happen anyway. An error in libnice can instruct Janus to tear down the PeerConnection, but that's about it. The handle the PC belongs to lives on, and so does the session. We most definitely do not issue a shutdown of the communication channel because of this. The only time we do that is when we detect a timeout (e.g., you're not sending keepalives or haven't sent messages for a while) on the session itself.

Besides, I don't see any "WS connection closed" in the "9 out of 10 failed" log. I only see an attempt to negotiate a PeerConnection that is proceeding (there are a couple of pairs that have succeeded apparently) while a destroy is received on a videoroom, which results in the handles of all participants (including their PeerConnections) being destroyed, followed by a shutdown of the whole server.

As you noticed, TCP candidates are not relevant. They're ignored if you're using an older version of libnice, and have lower priority when enabled instead. They're there to increase chances of getting connectivity, and can't do anything else. As such, I really don't think ICE has anything to do with this issue, which can be probably ascribed to a different problem.

Let us know if you can find additional info on this.

**Comment by arjenveenhuizen** [comment] 2015-05-22 11:22
Thanks for the clarification. Perhaps it has something to do with the fact that we send 28 candidates in under 30 msec causing an overflow somewhere?

**Comment by lminiero** [comment] 2015-05-22 11:25
About that, you can send multiple candidates in a single request, if you send a trickle with an array of candidate objects called "candidates", instead of a single candidate instance. Anyway, not sure that should be an issue either, since libwebsockets is single thread, but I'll try to do some test in that direction.

**Comment by rayvbr** [comment] 2015-05-22 12:01
We actually tried sending multiple candidates in a single request, but that didn't work. On http://janus.conf.meetecho.com/docs/rest.html it says that you can send an array in the JSON 'candidate' element, but I now understand it should be 'candidates'. Maybe that was the reason why we didn't get a response from Janus (note: we didn't get an error either).

**Comment by lminiero** [comment] 2015-05-22 12:07
Yes, it's ```candidates```, I'll update the docs, sorry about that.

**Comment by rayvbr** [comment] 2015-05-22 12:09
Thanks! We'll check and see if sending the candidates in a small number of batches solves the earlier problem.

**Comment by Computician** [comment] 2015-05-22 15:28
I am actually having this exact same problem using the janus.js API wrapper.

**Comment by lminiero** [comment] 2015-05-23 08:59
Next week I'll try to replicate this, e.g., by shooting the same candidate multiple times from JavaScript. If it is a problem with too frequent requests/responses, we'll find out that way.

**Comment by lminiero** [comment] 2015-05-26 11:03
See this comment: https://github.com/meetecho/janus-gateway/issues/245#issuecomment-105489520
I couldn't replicate this. If you have a way (sample page) to systematically replicate the issue it would help.

**Comment by lminiero** [comment] 2015-05-26 15:00
@arjenveenhuizen @rayvbr can you check if the latest commit (which addresses a typo @Computician found in issue #245 ) solves it for you? Just in case that was the cause of your problem as well.

**Comment by arjenveenhuizen** [comment] 2015-06-02 12:04
Finally found the time to check git head and this issues appears to be resolved. Thx!

**Comment by lminiero** [comment] 2015-06-02 12:07
Cool, thanks for the feedback!

**Closed** 2015-06-02 12:07 UTC
