### ISSUE TITLE
Videocall Plugin low quality in Chrome

### ISSUE THREAD

**Issue by apoltar** [meetecho/janus-gateway#1890] opened 2019-12-06 10:13 UTC
Hello, 
I'm testing video call plugin for peer-to-peer calls, and I found out that in Chrome, a video stream from answering party is extremely low - about 30-40 kbit, at the same time video stream from caller has 1mbit + / sec. 
When I'm using other browsers - Firefox or Opera in the same network, same hardware and, etc., both participants have a good video stream quality.

Tested in your instance https://janus.conf.meetecho.com/videocalltest.html
and different Chrome versions including the latest 78.0.3904

**Comment by lminiero** [comment] 2019-12-06 10:14
Duplicate of #1473 and #1861, see #1889.

**Closed by lminiero** 2019-12-06 10:14 UTC
