### ISSUE TITLE
Datachannel - sctp_sendv error - when sending too fast

### ISSUE THREAD

**Issue by petergerten** [meetecho/janus-gateway#1007] opened 2017-09-15 19:17 UTC
When I am sending too fast to a datachannel, I get "sctp_sendv error" messages and the data never goes through the channel. This seems to be related to usrsctp. If I only "slowly" send data, everything works as expected. Is there a way to throttle the throughput or increase the buffer size to get around this?

**Comment by petergerten** [comment] 2017-09-15 20:09
I inserted this in sctp.c and it helps:
```
	int usrsctp_bufsize = 1<<24;
	if (usrsctp_setsockopt(sock, SOL_SOCKET, SO_SNDBUF, &usrsctp_bufsize , sizeof(int)) < 0) {
	  JANUS_LOG(LOG_ERR, "[%"SCNu64"] setsockopt error: SO_SNDBUF\n", handle_id);
	  g_free(sctp);
	  sctp = NULL;
	  return NULL;
	}
```
It does not feel like a good approach though. Any thoughts?

**Comment by lminiero** [comment] 2017-09-18 11:47
It's been a long time since I messed with usrsctp, so I honestly have no idea if it's possible to throttle or increase the buffer size. I'll be away all week so can't look into this until I get back, though. If you find something that can help with this in the meanwhile, it will be welcome!

**Comment by lrs0304** [comment] 2017-10-08 03:00
I meet this problem today, and I notice that  webrtc works fine though it uses libusrsctp too.

**Comment by lminiero** [comment] 2017-11-28 17:02
Looked a bit around, and AFAIK there's no way to throttle or provide feedback on the bandwidth limitations. This is usually up to the application, e.g., via chunking, acks and the like, and one of the reasons the IETF is looking into QUIC as an alternative for datachannels apparently. As such, not sure there's anything we can or should do in Janus.

**Comment by mquander** [comment] 2017-12-05 02:06
(This problem happens to me too.)

**Comment by lminiero** [comment] 2017-12-05 09:34
Yeah but as I wrote, no idea what we can do considering datachannels themselves don't provide a way to do that. I guess you can try playing with how datachannels are created on the client side, e.g., [here](https://github.com/meetecho/janus-gateway/blob/master/html/janus.js#L1399). By default we create them unordered, byt maybe playing with the settings there (e.g., ordered and reliable channel) SCTP itself takes care of the rest. Just guessing as I'm not familiar with it at all.

**Comment by lminiero** [comment] 2018-02-13 09:50
Closing since, as explained, I don't believe there's anything we can do on that.

**Closed by lminiero** 2018-02-13 09:50 UTC

**Comment by jeremyarr** [comment] 2018-05-01 06:13
This problem happens to me too

**Comment by petergerten** [comment] 2018-05-01 07:03
unfortunately I could not solve it either. Does anyone have a application level solution for a reliable transmission using datachannels?

**Comment by jeremyarr** [comment] 2018-05-01 07:57
What did inserting that snippet into sctp.c do?

I am thinking  of requiring the receiver to send an ack back to the sender before the sender sends another message. While this is slow and inefficient, it would be pretty reliable.

**Comment by lminiero** [comment] 2018-05-01 08:02
You can force a reliable data channel from JavaScript (it's part of the
standard), editing the code in janus.js. Can't remember the syntax on the
top of my head so you'll have to look around, sorry.

Il mar 1 mag 2018, 09:58 Jeremy arr <notifications@github.com> ha scritto:

**Comment by petergerten** [comment] 2018-05-01 08:10
@lminiero I think passing `ordered: true` does that. But it won't help if there are too many "sctp_sendv error". End-to-end it is still unreliable.

**Comment by petergerten** [comment] 2018-05-01 08:11
@jeremyarr the snippet increased the buffer size, which seems to improve things for me. But still not reliable.

**Comment by biodranik** [comment] 2021-03-04 09:35
Any other ideas on that? Reproduces consistently with videoroom plugin in the current master:

```
[Thu Mar  4 10:22:06 2021] [ERR] [sctp.c:janus_sctp_send_text_or_binary:817] [11489077436854] sctp_sendv error (2)
[Thu Mar  4 10:22:06 2021] [ERR] [sctp.c:janus_sctp_send_text_or_binary:817] [11489077436854] sctp_sendv error (2)
[Thu Mar  4 10:22:06 2021] [WARN] [1737697525037842] Couldn't send all pending messages, queueing new message
[Thu Mar  4 10:22:06 2021] [WARN] [4117808773945154] Couldn't send all pending messages, queueing new message
[Thu Mar  4 10:22:06 2021] [WARN] [4117808773945154] Couldn't send all pending messages, queueing new message
[Thu Mar  4 10:22:06 2021] [WARN] [1737697525037842] Couldn't send all pending messages, queueing new message
[Thu Mar  4 10:22:06 2021] [ERR] [sctp.c:janus_sctp_send_text_or_binary:817] [11489077436854] sctp_sendv error (2)
[Thu Mar  4 10:22:06 2021] [ERR] [sctp.c:janus_sctp_send_text_or_binary:817] [11489077436854] sctp_sendv error (2)
[Thu Mar  4 10:22:06 2021] [WARN] [1737697525037842] Couldn't send all pending messages, queueing new message
[Thu Mar  4 10:22:06 2021] [WARN] [4117808773945154] Couldn't send all pending messages, queueing new message
[Thu Mar  4 10:22:06 2021] [WARN] [4117808773945154] Couldn't send all pending messages, queueing new message
[Thu Mar  4 10:22:06 2021] [WARN] [1737697525037842] Couldn't send all pending messages, queueing new message
[Thu Mar  4 10:22:06 2021] [ERR] [sctp.c:janus_sctp_send_text_or_binary:817] [11489077436854] sctp_sendv error (2)
[Thu Mar  4 10:22:06 2021] [WARN] [1737697525037842] Couldn't send all pending messages, queueing new message
[Thu Mar  4 10:22:07 2021] [WARN] [1737697525037842] Couldn't send all pending messages, queueing new message
[Thu Mar  4 10:22:07 2021] [ERR] [sctp.c:janus_sctp_send_text_or_binary:817] [11489077436854] sctp_sendv error (2)
[Thu Mar  4 10:22:07 2021] [WARN] [4117808773945154] Couldn't send all pending messages, queueing new message
[Thu Mar  4 10:22:07 2021] [WARN] [4117808773945154] Couldn't send all pending messages, queueing new message
[Thu Mar  4 10:22:07 2021] [ERR] [sctp.c:janus_sctp_send_text_or_binary:817] [11489077436854] sctp_sendv error (2)
[Thu Mar  4 10:22:07 2021] [WARN] [1737697525037842] Couldn't send all pending messages, queueing new message
[Thu Mar  4 10:22:07 2021] [WARN] [1737697525037842] Couldn't send all pending messages, queueing new message
[Thu Mar  4 10:22:07 2021] [WARN] [1737697525037842] Couldn't send all pending messages, queueing new message
[Thu Mar  4 10:22:07 2021] [WARN] [4117808773945154] Couldn't send all pending messages, queueing new message
[Thu Mar  4 10:22:07 2021] [WARN] [4117808773945154] Couldn't send all pending messages, queueing new message
[Thu Mar  4 10:22:07 2021] [ERR] [sctp.c:janus_sctp_send_text_or_binary:817] [11489077436854] sctp_sendv error (2)
[Thu Mar  4 10:22:07 2021] [ERR] [sctp.c:janus_sctp_send_text_or_binary:817] [11489077436854] sctp_sendv error (2)
[Thu Mar  4 10:22:07 2021] [WARN] [1737697525037842] Couldn't send all pending messages, queueing new message
[Thu Mar  4 10:22:07 2021] [WARN] [4117808773945154] Couldn't send all pending messages, queueing new message
[Thu Mar  4 10:22:07 2021] [WARN] [4117808773945154] Couldn't send all pending messages, queueing new message
[Thu Mar  4 10:22:07 2021] [ERR] [sctp.c:janus_sctp_send_text_or_binary:817] [11489077436854] sctp_sendv error (2)
[Thu Mar  4 10:22:07 2021] [WARN] [1737697525037842] Couldn't send all pending messages, queueing new message
[Thu Mar  4 10:22:07 2021] [WARN] [1737697525037842] Couldn't send all pending messages, queueing new message
[Thu Mar  4 10:22:07 2021] [ERR] [sctp.c:janus_sctp_send_text_or_binary:817] [11489077436854] sctp_sendv error (2)
[Thu Mar  4 10:22:07 2021] [ERR] [sctp.c:janus_sctp_send_text_or_binary:817] [11489077436854] sctp_sendv error (2)
[Thu Mar  4 10:22:07 2021] [WARN] [1737697525037842] Couldn't send all pending messages, queueing new message
```

**Comment by le-chat** [comment] 2021-07-30 14:58
We get `sctp_sendv error (2)` from sctp.c:janus_sctp_send_text_or_binary (https://github.com/meetecho/janus-gateway/blob/dca2068beb8df3aaed64cb6f91ffce6078d75f61/sctp.c#L818) when the client is disconnected (for example, the browser is closed). I think it is not related with sending too fast, because before disconnection data flows through channel well.

As I understand, errno 2 (No such file or directory) means that `sctp->sock` is invalid and will never become valid. Does it make sense to close data channel in this case?

And how can I achieve this, is it appropriate to call `janus_sctp_association_destroy` here?

Also comments in `janus_sctp_send_deferred_messages` seem to indicate places where similar check should be done.
