### ISSUE TITLE
[Help] Libsrtp > 1.4 Centos 7

### ISSUE THREAD

**Issue by hangocanh2303** [meetecho/janus-gateway#2022] opened 2020-03-26 03:56 UTC
Hi 
When I install janus in centos 7. It show error message like this: 
configure: error: libsrtp and libsrtp2 not found. See README.md for installation instructions
I followed install 
wget https://github.com/cisco/libsrtp/archive/v2.2.0.tar.gz
tar xfv v2.2.0.tar.gz
cd libsrtp-2.2.0
./configure --prefix=/usr --enable-openssl
make shared_library && sudo make install
But error still the same. 
I already try many many times. But it's still not working 
export PKG_CONFIG_PATH=/usr/lib64/pkgconfig
export PKG_CONFIG_PATH=/usr/lib/pkgconfig
--libdir=/usr/lib64
How do I installed libsrtp in centOS 7 working with janus ?

**Comment by lminiero** [comment] 2020-03-26 12:10
Duplicate of #2019

**Closed by lminiero** 2020-03-26 12:10 UTC
