### ISSUE TITLE
Video streaming issue in Janus WebRTC Gateway for RTSP streaming source(For janus_streaming plugin)

### ISSUE THREAD

**Issue by Nileshwagh22** [meetecho/janus-gateway#487] opened 2016-03-16 06:01 UTC
I have installed Janus WebRTC Gateway on Ubuntu Server 14.04.4 LTS, and deployed web samples on apache2 http server. I am trying existing Streming demo sample which come with Janus gateway. I have enabled(By default it is disabled) rtsp streaming support in 'janus.plugin.sip.cfg.*' config file by below settings.

> [rtsp-test]
> type = rtsp
> id = 99
> description = RTSP Test
> audio = no
> video = yes
> url=rtsp://127.0.0.1:8554/mystream

Now I am getting one more channel(option in dropdown) in Streaming demo page i.e. 'RTSP Test(live)'. When I will click on Watch or Listen button, below error occurred on console and showing waiting symbol:

On Chrome:
**Failed to parse SessionDescription. Expect line: v=**

On Firefox:
**InvalidParameterError: Empty or null SDP provided to setRemoteDescription**

Please help me to resolve this issue or suggest me any idea/code changes to play rtsp to WebRTC stream using Janus Gateway.

**Comment by lminiero** [comment] 2016-03-16 09:05
The issue is pretty clear, there's no SDP being sent to the browser, probably because either the stream is not available or not producing any. Closing as not an issue, and because you opened a post on the meetecho-janus as well.

**Closed by lminiero** 2016-03-16 09:05 UTC
