### ISSUE TITLE
Janus not including track SSRC in answer SDP

### ISSUE THREAD

**Issue by tobiasfriden** [meetecho/janus-gateway#1483] opened 2018-12-25 16:05 UTC
Im am trying to connect with Janus using the python library `aiortc`.
However, it requires that the track SSRC is included in the answer sdp, which seems to not be the case with janus.

Outgoing SDP: https://pastebin.com/3m885fVg
Received SDP from Janus: https://pastebin.com/079markx

More discussion here: https://github.com/jlaine/aiortc/issues/114

**Comment by lminiero** [comment] 2018-12-25 18:34
If we're not going to send anything (I see recvonly in the Janus SDP) we don't advertise any SSRC. Not a bug, closing.

**Closed by lminiero** 2018-12-25 18:34 UTC
