### ISSUE TITLE
[0.x] janus.plugin.streaming: Already watching a stream

### ISSUE THREAD

**Issue by tmatth** [meetecho/janus-gateway#3105] opened 2022-11-17 17:04 UTC
We believe we're seeing some spurious "Already watching a stream..." errors in the `janus.plugin.streaming` plugin in production, but AFAICT for this to be true 2 conditions must be met:

1. there's a dangling viewer in the `mp->viewers` list (or a race condition on removing/adding a viewer to this list)
2. since the `viewers` list is checked using `g_list_find`, it's possible that a new `viewer` is being assigned the same address (i.e. by malloc) as a previously allocated viewer that never got removed from the list, and so it's being rejected there.

For the second condition, I was thinking it might be more robust to use `g_list_find_custom` instead of just `g_list_find` and check some other unique-ish identifier like `session->sdp_sessid` or even `session->handle` (although this would potentially have the same drawback).

So instead of:

```
// Assume mp->viewers consisting of one viewer 0x1234 
// Assume mp->viewers gets freed but is not removed from the list for some reason
// Assume new session is allocated also with address 0x1234
g_list_find(mp->viewers, session);  // oh no, collision! 
```
we do
```
g_list_find_by_custom(mp->viewers, session, viewer_comparator)
```
where viewer_comparator checks some other field for safety.

**What version of Janus is this happening on?**
0.x (commit 34e3f4abc87ac546d22aeea3dc1bb1af0959cfe7)

**Have you tested a more recent version of Janus too?**
No.

**Was this working before?**
No.

**Is there a gdb or libasan trace of the issue?**
Not Yet

**Additional context**
Since we're at a loss for how to reproduce this, we may just start by submitting PRs to get more context/confirm our suspicion. We've been looking over all the viewer list access synchronization to see if there's an issue there but so far it's not obvious.

Just to clarify I doubt that this is specific to 0.x but we haven't been able to try 1.x in the same context so we can't be sure.

**Comment by lminiero** [comment] 2022-11-18 15:36
I'm not sure I'm fond of the `g_list_find_by_custom`, which seems more work and slower, as it requires dereferencing a pointer in the traversal of the list where right now it's a simple comparison. I'd rather try and figure out if there's indeed circumstances where a pointer may not be removed from the list when it should. If it's a matter of re-used pointers, as you said, it could be a race condition of some sort, which should then be fixed properly, where I see `g_list_find_by_custom` more as a temporary patch.

**Comment by tmatth** [comment] 2022-11-18 15:42
> I'm not sure I'm fond of the `g_list_find_by_custom`, which seems more work and slower, as it requires dereferencing a pointer in the traversal of the list where right now it's a simple comparison. I'd rather try and figure out if there's indeed circumstances where a pointer may not be removed from the list when it should. If it's a matter of re-used pointers, as you said, it could be a race condition of some sort, which should then be fixed properly, where I see `g_list_find_by_custom` more as a temporary patch.

Yeah I should have framed it as using `g_list_find_by_custom` will help confirm that it is a dangling pointer issue that, once fixed, would remove the need for a deeper comparison.

**Comment by atoppi** [comment] 2022-11-22 09:56
> since the viewers list is checked using g_list_find, it's possible that a new viewer is being assigned the same address (i.e. by malloc) as a previously allocated viewer that never got removed from the list, and so it's being rejected there.

I would not exclude the same address hypothesis.
FWIW, I wrote a quick test and found out that on my machine `g_malloc` is reusing exactly the same memory address after a free.

```c
#include <stdio.h>
#include <stdlib.h>
#include <glib.h>
#include <math.h>

int main(void) 
{ 
	const size_t iterations = 1 << 15;
	const size_t malloc_size = 64;
	printf("iterations = %zu, size = %zu\n", iterations, malloc_size);

	GHashTable *table = g_hash_table_new(NULL, NULL);
	for (size_t i = 0; i < iterations; ++i) {
		char *ptr = (char *)g_malloc(malloc_size);
		printf("ptr = %p\n", ptr);
		g_hash_table_insert(table, ptr, ptr);
		g_free(ptr);
	}
	
	guint nelem = g_hash_table_size(table);	
	double entropy = 0.5+log2((double)(nelem));
	printf("\nentropy = %.2f\n", entropy);
	
	return 0; 
}
```

```
gcc test-malloc-entropy.c $(pkg-config --cflags glib-2.0) $(pkg-config --libs glib-2.0) -lm
```

```
ptr = 0x5642fa06a110
ptr = 0x5642fa06a110
ptr = 0x5642fa06a110
ptr = 0x5642fa06a110
ptr = 0x5642fa06a110
ptr = 0x5642fa06a110
ptr = 0x5642fa06a110

entropy = 0.50
```

**Comment by lminiero** [comment] 2022-11-22 11:25
The consistency with which those pointers are re-used is quite baffling, even though this test is making new allocations immediately after a previous free, whereas I'd picture this to be less likely in Janus, where we often allocate stuff: as such, it shouldn't be as easy for two pointers in the very same space and context (plugin sessions in this case) to actually have the same pointer, considering different allocations have probably happened in the meanwhile. It's also fair to assume, though, that the fact they have the same size probably means they end up being allocated in the same place more likely than resources that have a different size instead. That said, I still think that if this is causing a problem, it's because of a mismanagement of those lists in the first place, rather than the fact we're using those pointers as indexes. Looking forward to more info to figure out what's going wrong in those cases!

**Comment by tmatth** [comment] 2022-11-22 12:52
> > since the viewers list is checked using g_list_find, it's possible that a new viewer is being assigned the same address (i.e. by malloc) as a previously allocated viewer that never got removed from the list, and so it's being rejected there.
> 
> I would not exclude the same address hypothesis. FWIW, I wrote a quick test and found out that on my machine `g_malloc` is reusing exactly the same memory address after a free.
> 
> ```c
> #include <stdio.h>
> #include <stdlib.h>
> #include <glib.h>
> #include <math.h>
> 
> int main(void) 
> { 
> 	const size_t iterations = 1 << 15;
> 	const size_t malloc_size = 64;
> 	printf("iterations = %zu, size = %zu\n", iterations, malloc_size);
> 
> 	GHashTable *table = g_hash_table_new(NULL, NULL);
> 	for (size_t i = 0; i < iterations; ++i) {
> 		char *ptr = (char *)g_malloc(malloc_size);
> 		printf("ptr = %p\n", ptr);
> 		g_hash_table_insert(table, ptr, ptr);
> 		g_free(ptr);
> 	}
> 	
> 	guint nelem = g_hash_table_size(table);	
> 	double entropy = 0.5+log2((double)(nelem));
> 	printf("\nentropy = %.2f\n", entropy);
> 	
> 	return 0; 
> }
> ```
> 
> ```
> gcc test-malloc-entropy.c $(pkg-config --cflags glib-2.0) $(pkg-config --libs glib-2.0) -lm
> ```
> 
> ```
> ptr = 0x5642fa06a110
> ptr = 0x5642fa06a110
> ptr = 0x5642fa06a110
> ptr = 0x5642fa06a110
> ptr = 0x5642fa06a110
> ptr = 0x5642fa06a110
> ptr = 0x5642fa06a110
> 
> entropy = 0.50
> ```

Yeah @lionelnicolas put me onto this library which can be dynamically loaded or statically linked:
https://github.com/microsoft/mimalloc
which will randomize pointer addresses as predictable pointer addresses is considered an attack vector. That said, using something like this would just hide the underlying issue (as @lminiero points out) of why the pointer is presumably being left in the list after being freed in the first place.

There are minor things I noticed while investigating #3108 like this reference count decrement happening AFTER removing `s` from the list of viewers: 
https://github.com/meetecho/janus-gateway/blob/696b19e8dfd3cf2b9c61c543ff72b070f752a457/src/plugins/janus_streaming.c#L4723

Generally the pattern is to remove shared entities from lists before any potential deallocation to avoid having them be visible by other threads at the moment they are deallocated. That said this hardly seems like a smoking gun.

Same here:
https://github.com/meetecho/janus-gateway/blob/696b19e8dfd3cf2b9c61c543ff72b070f752a457/src/plugins/janus_streaming.c#L5600

It seems like the problem is in one or more of the 2 `while(viewer)` loops and/or `janus_streaming_hangup_media_internal`.

**Comment by lminiero** [comment] 2023-01-04 15:07
Did you end up finding more about this issue, or has it stopped happening?

**Comment by tmatth** [comment] 2023-01-04 16:46
> Did you end up finding more about this issue, or has it stopped happening?

We've been working around the problem but are set to do some loadtesting this week so I will update here if we find anything new.

**Comment by tmatth** [comment] 2023-03-30 19:40
> Did you end up finding more about this issue, or has it stopped happening?

So we did see this issue today under load (even with mimalloc enabled), the distribution of errors was as follows:

```
0x4c8b6124e80 in 6ebfa973-a3e8-4659-92e3-5b892c2412a4's viewers)...  (67 occurrences)
0x4c8b6127f80 in 6ebfa973-a3e8-4659-92e3-5b892c2412a4's viewers)...  (54 occurrences)
0x4c8b6154e80 in 6ebfa973-a3e8-4659-92e3-5b892c2412a4's viewers)...  (68 occurrences) 
0x4c8b615ea40 in 6ebfa973-a3e8-4659-92e3-5b892c2412a4's viewers)...  (55 occurrrences)
0x4c8b6192800 in 6ebfa973-a3e8-4659-92e3-5b892c2412a4's viewers)...  (103 occurrences)
0x4c8b619cc80 in 6ebfa973-a3e8-4659-92e3-5b892c2412a4's viewers)...  (87 occurrences)
```

**Comment by atoppi** [comment] 2023-03-31 09:04
Interesting @tmatth 

Those addresses seems suspiciously "close" in terms of address distance.
Granted that `mimalloc` is doing its job, we have hundreds of collisions in a small space of 3 bytes 
```
0x4c8b6 A B C 
```  
I can only a see these possible explanations:
1) `mimalloc` is not working or it is randomizing in a reduced address space
2) `mimalloc` is working, but your process is using a huge amount of memory (leaking), leaving just a specific free area for some reason
3) In addition to the previous conditions, those are not "spurious" errors but "spurious" requests from clients. The repetition of the same collision so many times might suggest this behavior.

How are you coping with those errors? Is retrying the request enough to get the feed?

**Comment by tmatth** [comment] 2023-03-31 14:11
> Interesting @tmatth
> 
> Those addresses seems suspiciously "close" in terms of address distance. Granted that `mimalloc` is doing its job, we have hundreds of collisions in a small space of 3 bytes
> 
> ```
> 0x4c8b6 A B C 
> ```
> 
> I can only a see these possible explanations:
> 
>     1. `mimalloc` is not working or it is randomizing in a reduced address space

It is enabled but we are considering using `libmimalloc_secure.so` instead since this better randomizes addresses (but has a performance cost).

> 
>     2. `mimalloc` is working, but your process is using a huge amount of memory (leaking), leaving just a specific free area for some reason

AFAIK this isn't the case.

> 
>     3. In addition to the previous conditions, those are not "spurious" errors but "spurious" requests from clients. The repetition of the same collision so many times might suggest this behavior.
> 
> 
> How are you coping with those errors? Is retrying the request enough to get the feed?

It had occurred to me that it is suspicious that we keep hitting the exact same error (with the same pointers) so repeatedly, I suspect there's something in our retry logic that is maybe not doing as much of a "fresh start" as it should be, although @lionelnicolas had observed: 
> the session_id is different each time I refresh the page and click on "play" so I don't understand why it's complaining about already watching

The other thing worth mentioning is that we saw  `Can't start: no mountpoint set (code 455)` coinciding with this issue, which I think is probably an important clue.

**Comment by atoppi** [comment] 2023-04-03 08:19
> The other thing worth mentioning is that we saw Can't start: no mountpoint set (code 455) coinciding with this issue, which I think is probably an important clue.

In general that means you are requesting to `start` a stream (with an attached JSEP answer) on a session that did not successfully completed a `watch` or `switch` request.

https://github.com/meetecho/janus-gateway/blob/9e4c1be13c971290675db53efece6187bc5310cb/plugins/janus_streaming.c#L5125-L5130

That is probably due to the `Already watching a stream` errors, since `session->mountpoint` is being set after that check

https://github.com/meetecho/janus-gateway/blob/9e4c1be13c971290675db53efece6187bc5310cb/plugins/janus_streaming.c#L4864-L4875

If your client is submitting a `start` after a `watch` that got an error, then this is an expected behavior from Janus and probably something to fix in the client.

>  the session_id is different each time I refresh the page and click on "play" so I don't understand why it's complaining about already watching

I noticed that plugin session lookup is being done on a handle basis just after the message handler pops a request out from the message queue. 

https://github.com/meetecho/janus-gateway/blob/9e4c1be13c971290675db53efece6187bc5310cb/plugins/janus_streaming.c#L4707-L4716

A couple of things to notice here:
1) If any clash of pointers is happening here, it is on a handle basis since the session lookup uses a handle ptr as a key
2) Consider that the message handling is being performed asynchronously, whenever the thread will fetch the request from the FIFO. In overloaded environment, as you have mentioned, I would expect a request to be managed in a delayed time. In that time frame I guess the handle associated to the original request (`msg->handle`) could be removed. That is the purpose of these checks

https://github.com/meetecho/janus-gateway/blob/9e4c1be13c971290675db53efece6187bc5310cb/plugins/janus_streaming.c#L4716-L4727

However, if we take as possible pointer collisions, then everything might happen in case of re-used handle ptrs.
In general the message handler could lookup a totally different session and will manage the original request in an unexpected context leading to unforeseen consequences (that might include your spurious errors).

In order to verify this situation I guess we should add some logs to `janus_streaming_create_session` and `janus_streaming_destroy_session` to track the pointers of handles/sessions being added and removed.

**Comment by atoppi** [comment] 2023-07-18 14:49
We have encountered the same issue in the last few days.
Probing the mp through the admin API shows that a viewer is being left in the list:
```
{
    "janus": "success",
    "transaction": "x7R3Im3kc9hT",
    "response": {
        "streaming": "info",
        "info": {
            "id": 2709026103886970,
            "name": "mp-3e11ac6d-2ee2-4c7a-8487-56da8d62b48b",
            "description": "",
            "secret": "adminpwd",
            "enabled": true,
            "viewers": 1,
            "audio": true,
            "audiopt": 111,
            "audiortpmap": "opus/48000/2",
            "type": "live",
            "collision": 2000,
            "threads": 2,
            "audioport": 10000,
            "audiortcpport": 0,
            "audio_age_ms": 148705
        }
    }
}
```
So the root cause might be leaking viewers followed by "collision" of pointers.

**Comment by atoppi** [comment] 2023-07-24 16:28
We also suspect that a deadlock occurring due to a `session->mutex` not being released by a thread before exiting could have the same root cause.
@lionelnicolas @tmatth did you also observe any deadlock issues by any chance?

**Comment by tmatth** [comment] 2023-07-24 18:41
> We also suspect that a deadlock occurring due to a `session->mutex` not being released by a thread before exiting could have the same root cause. @lionelnicolas @tmatth did you also observe any deadlock issues by any chance?

IIRC the API was no longer responsive (possibly due to deadlock?) in these instances

**Comment by atoppi** [comment] 2023-08-21 08:48
closing since #3246 has been merged

**Closed by atoppi** 2023-08-21 08:48 UTC
Labels: legacy
