### ISSUE TITLE
Race condition in janus.c

### ISSUE THREAD

**Issue by ramprakash110109** [meetecho/janus-gateway#2461] opened 2020-12-01 07:54 UTC
In janus.c,  plugin messages are handled asynchronously inside "janus_transport_requests" method using a thread pool, while the session level messages are handled synchronously.

In my case, I am trying to destroy the room in audiobridge plugin followed by destroying the session.
But, as per code logic, destroy session request is handled first and session got destroyed at this point.
So, while processing "room destroy request from the thread pool" inside the audiobridge plugin, I am getting session not found error. As a result, the audiobridge mixer thread is not getting closed properly.

Could you provide a feedback on this?

**Comment by lminiero** [comment] 2020-12-01 08:17
That's expected, at the moment, exactly because of how messages are handled. Since the core doesn't know in advance whether or not a plugin message will be handled synchronously or not, we handle it asynchronously in the core; that's also because plugin messages may contain a JSEP SDP, which might trigger the creation of a new PeerConnection that takes a bit of time, and we don't want that to block everything else. As such, not really an issue, but by design.

You're free to experiment handling everything synchronously (including plugin messages), and let us know if you notice API responsiveness issues under load. If not, we can consider changing the current behaviour.

**Comment by ramprakash110109** [comment] 2020-12-01 08:46
Yeah, earlier I have experienced API responsiveness issue, when all requests are handled synchronously. "Attach" request took more time to complete , blocking other requests.
So, compared to handling all the request synchronously,  this thread pool logic is a better approach.

As a work around for my case, I will try to send the session destroy request, with few seconds of delay from my application side, so that race condition won't occur. Let me also check, if I can do something in janus core to avoid this race condition.

Thanks for your feedback.

**Comment by lminiero** [comment] 2020-12-01 08:50
I guess there might be one more check in the core: handle a message asynchronously if it's "message" AND there's a JSEP attached. If a request is handled asynchronously by a plugin, it returns almost right away nevertheless with an ack. This might cause issues if the plugin deadlocks handling a synchronous request, though, or if it takes a long time (e.g., "create" takes longer than it should). So yep, if you can experiment a bit there to see if you can find a reasonable tradeoff that would be helpful.

**Comment by atoppi** [comment] 2020-12-01 12:31
@ramprakash110109 is there any particular reason for not waiting a room destroyed notification before actually sending a session destroy request ?

**Comment by ramprakash110109** [comment] 2020-12-02 10:44
I configured the orchestration server in such a way that, requests like "destroy mountpoint" and "destroy room" etc..   followed by "hangup" and "destroy session" ,  to be act in fire and forget mode.
This makes the resources need not be holded until the destroyed response returns back from janus server. 

As a work around, I have planned to allow "destroy session" request to work via thread pool and check whether the race condition can be solved. I will try this and update you regarding the performance too.

**Comment by lminiero** [comment] 2021-01-28 11:22
Closing as this was more of a question than a bug.

**Closed by lminiero** 2021-01-28 11:22 UTC
