### ISSUE TITLE
Circular Reference Count Between Plugin Session Handles and Core Handles

### ISSUE THREAD

**Issue by dbeaudoinfortin** [meetecho/janus-gateway#2348] opened 2020-09-02 18:20 UTC
We are encountering an issue in our production environment where we are leaking eventfd file descriptors. I've traced the creation of the eventfds to the g_main_context_new() call. Note that we are not using static event loops. From what I can tell by stepping through the code, g_main_context_unref() is never being called. It should be called by janus_ice_handle_free() but that never seems to be called.

It seems like there might be a circular reference counting problem. The plugin session references the handle and the handle references the plugin session. janus_ice_handle_free() only decreases the session reference count when the handle reference count goes to zero but, at the same time, janus_ice_plugin_session_free only decreases the handle reference count when the session reference count goes to zero. The end result is that janus_ice_plugin_session_free() and  janus_ice_handle_free() are never called.

I think this issue might have been introduced in https://github.com/meetecho/janus-gateway/commit/e9d6af00df7dc7f7ecb0109dff78ea81d2c5e7a5

**Comment by atoppi** [comment] 2020-09-03 14:36
@dbeaudoinfortin which plugin are you using?

**Comment by lminiero** [comment] 2020-09-03 14:47
Closing as we can't debug issues caused by third party plugins, sorry.

**Closed by lminiero** 2020-09-03 14:47 UTC
