### ISSUE TITLE
about 15 seconds without audio when janus receive a "Discovered new remote candidate for component"

### ISSUE THREAD

**Issue by carcharothellobo** [meetecho/janus-gateway#3070] opened 2022-09-16 19:51 UTC
Hi guys I have a weird behavior, I dont know if it is a bug or a missconfiguration. I have an established call between Janus and Client. All candidates have been negotiated properly. About ten seconds aftes this call start I see in my Janus Server this message:
```
[Fri Sep 16 18:10:23 2022] [7484132791308546] Discovered new remote candidate for component 1 in stream 1: type=prflx
[Fri Sep 16 18:10:23 2022] [7484132791308546] Stream #1, Component #1
[Fri Sep 16 18:10:23 2022] [7484132791308546]   Address:    179.41.7.237:13508
[Fri Sep 16 18:10:23 2022] [7484132791308546]   Priority:   1853824767
[Fri Sep 16 18:10:23 2022] [7484132791308546]   Foundation: remote1
[Fri Sep 16 18:10:23 2022] [7484132791308546]  Adding remote candidate component:1 stream:1 type:prflx 179.41.7.237:13508 --> 179.41.7.237:13508
[Fri Sep 16 18:10:23 2022] [7484132791308546]  Transport: UDP
[Fri Sep 16 18:10:23 2022] [7484132791308546] Queueing candidate 0x62100019fe60
[Fri Sep 16 18:10:23 2022] [7484132791308546] Component state changed for component 1 in stream 1: 3 (connected)
[Fri Sep 16 18:10:23 2022] [7484132791308546] Processing candidate 0x62100019fe60
[Fri Sep 16 18:10:23 2022] [WARN] [7484132791308546] Failed to add some remote candidates (added 0, expected 1)
[Fri Sep 16 18:10:23 2022] [7484132791308546] Component state changed for component 1 in stream 1: 4 (ready)
```
when I have this log for the next 15 or 20 seconds Janus still send audio to the previous candidate. This new candidate only changes the port number. 
After this time, Janus starts sending audio to the new candidate with no problem.

Thanks in advance

**Comment by lminiero** [comment] 2022-09-20 08:16
I don't think there's anything we can do: ICE management is done by libnice, and you're getting a late prflx candidate that libnice eventually reacts to. I doubt Janus is sending any audio as you say before the log you shared above, since that's when it gets to "connected" (our trigger for DTLS and eventually media).

**Comment by lminiero** [comment] 2022-09-29 11:14
Closing as this feels like it's working as intended.

**Closed by lminiero** 2022-09-29 11:14 UTC
