### ISSUE TITLE
janus cann't connect to freeswitch with error report "DTLS timeout".

### ISSUE THREAD

**Issue by richard1219** [meetecho/janus-gateway#2296] opened 2020-07-23 15:09 UTC
I push janus stream to freeswitch, I got DTLS timeout error, It's their DTLS not match?

Janus log:
_Component is ready enough, starting DTLS handshake...
Component state changed for component 1 in stream 1: 3 (connected)
ice selected pair, local candidate: 1 1 udp host 10.49.96.8 52181 , remote candidate: 4525124919 1 udp host 10.191.4.21 28654
...
[WARN] session hangup because of a (DTLS timeout)_

Freewitch log:
_[ERR] switch_rtp.c:950 Invalid STUN/ICE packet received 28 bytes
[ERR] switch_rtp.c:6033 RTCP UNPROTECT ERR
[WARNING] switch_rtp.c:6954 INVALID RTCP PACKET TYPE 96 VER 2 LEN 9044
[WARNING] switch_rtp.c:850 No audio stun for a long time!_
[WARNING] switch_rtp.c:850 No audio stun for a long time!_

**Comment by lminiero** [comment] 2020-07-23 15:12
If you're sending both audio and video at the same time, then that's the cause: we bundle both on the same port, while IIRC Freeswitch uses different ports, which we don't support anymore. As such, the second DTLS handshake never happens and you get that error. For some ways to get Freeswitch and Janus to talk to each other check the presentations by Giacomo Vacca and Luca Pradovera from the last edition of [JanusCon](https://januscon.it/2019).

Closing.

**Closed by lminiero** 2020-07-23 15:12 UTC
