### ISSUE TITLE
videoroom plugin + RTP forward not working for video at all

### ISSUE THREAD

**Issue by nu774** [meetecho/janus-gateway#1372] opened 2018-09-17 04:59 UTC
Currently Janus doesn't forwarding video RTP packet to the specified UDP port at all.
Easily checkable using wireshark or something.

It seems the following lines In janus_videoroom_incoming_rtp() is the offender:
```
/* First of all, check if we're simulcasting and if we need to forward or ignore this frame */
if(video && !rtp_forward->simulcast && rtp_forward->substream != sc) {
    /* This is video, we're not simulcasting, and it's not our layer: ignore */
    continue;
```
Without simulcasting, it seems to always flow into the continue line, since rtp_forward->substream is zero and sc is -1.

**Comment by lminiero** [comment] 2018-09-17 09:07
Mh, looks like a regression introduced by #1359, I'll have a look and fix in case. Thanks for spotting this!

**Comment by lminiero** [comment] 2018-09-17 11:00
The above commit should fix it for all cases (no simulcasting, simulcasting to different ports, simulcasting to single port), so I'm closing this issue. Feel free to reopen if it's still an issue for you.

**Closed by lminiero** 2018-09-17 11:00 UTC
