### ISSUE TITLE
After enabling full_trickle, call did not connect

### ISSUE THREAD

**Issue by venkateshcontus** [meetecho/janus-gateway#3410] opened 2024-07-24 10:02 UTC
What version of Janus is this happening on?
[1.2.3](https://github.com/meetecho/janus-gateway/commit/77f2cb86466ba29199fd5fdef08bbd5a453f2bc1)

Have you tested a more recent version of Janus too?
Yes.

Was this working before?
No

https://github.com/meetecho/janus-gateway/issues/3363

@lminiero After enabling full_trickle, call did not connect. So we have added the below code (given below iOS code snippet)

// peerConnection.add(RTCIceCandidate(sdp: candidate, sdpMLineIndex: sdpMLineIndex, sdpMid: sdpMid))
// candidate,sdpMLineIndex,sdpMid => Received from Janus.

When joining with multiple users (4 users) in a call at the same time ICE Connected state was never triggered randomly for at least one of the user in the call. Ice connection was never successful for that User., but the candidates are received from the server. This is happening in 3 out of 10 calls.

**Comment by atoppi** [comment] 2024-08-19 10:07
Closing since this is a duplicate of #3415 (which contains decent troubleshooting data at least).

**Closed by atoppi** 2024-08-19 10:07 UTC
Labels: multistream
