### ISSUE TITLE
unsure why im getting these errors

### ISSUE THREAD

**Issue by bhakimi** [meetecho/janus-gateway#1032] opened 2017-10-12 23:53 UTC
any idea why im getting this?

```
[Thu Oct 12 16:51:51 2017] [ERR] [ice.c:janus_ice_send_thread:3479] [7593902327546858] Got 1 SRTP/SRTCP errors in the last few seconds (last error: err_status_replay_fail)
[Thu Oct 12 16:51:53 2017] No WebRTC media anymore
[Thu Oct 12 16:51:54 2017] [7593902327546858] WebRTC resources freed
[Thu Oct 12 16:51:54 2017] [ERR] [ice.c:janus_ice_send_thread:3479] [1062342781942434] Got 1 SRTP/SRTCP errors in the last few seconds (last error: err_status_replay_fail)
[Thu Oct 12 16:51:56 2017] [ERR] [ice.c:janus_ice_send_thread:3479] [1062342781942434] Got 2 SRTP/SRTCP errors in the last few seconds (last error: err_status_replay_fail)
[Thu Oct 12 16:51:58 2017] [ERR] [ice.c:janus_ice_send_thread:3479] [6558928693043619] Got 1 SRTP/SRTCP errors in the last few seconds (last error: err_status_replay_fail)
[Thu Oct 12 16:52:00 2017] [ERR] [ice.c:janus_ice_send_thread:3479] [3935214855554418] Got 1 SRTP/SRTCP errors in the last few seconds (last error: err_status_replay_fail)
[Thu Oct 12 16:52:00 2017] [ERR] [ice.c:janus_ice_send_thread:3479] [1062342781942434] Got 2 SRTP/SRTCP errors in the last few seconds (last error: err_status_replay_fail)
[Thu Oct 12 16:52:00 2017] [ERR] [ice.c:janus_ice_send_thread:3479] [6558928693043619] Got 1 SRTP/SRTCP errors in the last few seconds (last error: err_status_replay_fail)
[Thu Oct 12 16:52:02 2017] [ERR] [ice.c:janus_ice_send_thread:3479] [1062342781942434] Got 1 SRTP/SRTCP errors in the last few seconds (last error: err_status_replay_fail)
[Thu Oct 12 16:52:04 2017] [ERR] [ice.c:janus_ice_send_thread:3479] [1062342781942434] Got 1 SRTP/SRTCP errors in the last few seconds (last error: err_status_replay_fail)
[Thu Oct 12 16:52:06 2017] [ERR] [ice.c:janus_ice_send_thread:3479] [1062342781942434] Got 2 SRTP/SRTCP errors in the last few seconds (last error: err_status_replay_fail)
[Thu Oct 12 16:52:10 2017] [ERR] [ice.c:janus_ice_send_thread:3479] [1062342781942434] Got 1 SRTP/SRTCP errors in the last few seconds (last error: err_status_replay_fail)
[Thu Oct 12 16:52:10 2017] [ERR] [ice.c:janus_ice_send_thread:3479] [5784948572345683] Got 1 SRTP/SRTCP errors in the last few seconds (last error: err_status_replay_fail)
[Thu Oct 12 16:52:11 2017] [ERR] [ice.c:janus_ice_send_thread:3479] [6558928693043619] Got 1 SRTP/SRTCP errors in the last few seconds (last error: err_status_replay_fail)
[Thu Oct 12 16:52:12 2017] [ERR] [ice.c:janus_ice_send_thread:3479] [1062342781942434] Got 2 SRTP/SRTCP errors in the last few seconds (last error: err_status_replay_fail)
[Thu Oct 12 16:52:13 2017] [ERR] [ice.c:janus_ice_send_thread:3479] [6558928693043619] Got 1 SRTP/SRTCP errors in the last few seconds (last error: err_status_replay_fail)
[Thu Oct 12 16:52:14 2017] [ERR] [ice.c:janus_ice_send_thread:3479] [3935214855554418] Got 1 SRTP/SRTCP errors in the last few seconds (last error: err_status_replay_fail)
[Thu Oct 12 16:52:14 2017] [ERR] [ice.c:janus_ice_send_thread:3479] [1062342781942434] Got 1 SRTP/SRTCP errors in the last few seconds (last error: err_status_replay_fail)
[Thu Oct 12 16:52:15 2017] [ERR] [ice.c:janus_ice_send_thread:3479] [6558928693043619] Got 1 SRTP/SRTCP errors in the last few seconds (last error: err_status_replay_fail)
[Thu Oct 12 16:52:15 2017] [WARN] [2257892125290179] Didn't receive audio for more than 1 seconds...
[Thu Oct 12 16:52:16 2017] Creating new session: 4577557940113695
[Thu Oct 12 16:52:16 2017] Creating new handle in session 4577557940113695: 7494271320071577
[Thu Oct 12 16:52:18 2017] [WARN] [2257892125290179] Big sequence number jump 4624 -> 4818 (audio stream)
[Thu Oct 12 16:52:18 2017] [ERR] [ice.c:janus_ice_send_thread:3479] [1062342781942434] Got 1 SRTP/SRTCP errors in the last few seconds (last error: err_status_replay_fail)
[Thu Oct 12 16:52:20 2017] [ERR] [ice.c:janus_ice_send_thread:3479] [1062342781942434] Got 2 SRTP/SRTCP errors in the last few seconds (last error: err_status_replay_fail)
[Thu Oct 12 16:52:21 2017] [ERR] [ice.c:janus_ice_send_thread:3479] [6558928693043619] Got 1 SRTP/SRTCP errors in the last few seconds (last error: err_status_replay_fail)
[Thu Oct 12 16:52:22 2017] [ERR] [ice.c:janus_ice_send_thread:3479] [1062342781942434] Got 1 SRTP/SRTCP errors in the last few seconds (last error: err_status_replay_fail)
[Thu Oct 12 16:52:23 2017] [ERR] [ice.c:janus_ice_send_thread:3479] [6558928693043619] Got 1 SRTP/SRTCP errors in the last few seconds (last error: err_status_replay_fail)
[Thu Oct 12 16:52:25 2017] [WARN] [2257892125290179] Didn't receive audio for more than 1 seconds...
[Thu Oct 12 16:52:26 2017] [ERR] [ice.c:janus_ice_send_thread:3479] [1062342781942434] Got 1 SRTP/SRTCP errors in the last few seconds (last error: err_status_replay_fail)
[Thu Oct 12 16:52:27 2017] [ERR] [ice.c:janus_ice_send_thread:3479] [6558928693043619] Got 1 SRTP/SRTCP errors in the last few seconds (last error: err_status_replay_fail)
[Thu Oct 12 16:52:28 2017] [WARN] [2257892125290179] Big sequence number jump 5133 -> 5318 (audio stream)
[Thu Oct 12 16:52:28 2017] [ERR] [ice.c:janus_ice_send_thread:3479] [1062342781942434] Got 1 SRTP/SRTCP errors in the last few seconds (last error: err_status_replay_fail)
[Thu Oct 12 16:52:29 2017] [ERR] [ice.c:janus_ice_send_thread:3479] [6218175448369475] Got 1 SRTP/SRTCP errors in the last few seconds (last error: err_status_replay_fail)
[Thu Oct 12 16:52:30 2017] [ERR] [ice.c:janus_ice_send_thread:3479] [1062342781942434] Got 1 SRTP/SRTCP errors in the last few seconds (last error: err_status_replay_fail)
[Thu Oct 12 16:52:30 2017] [7494271320071577] Creating ICE agent (ICE Full mode, controlled)
[Thu Oct 12 16:52:31 2017] [ERR] [ice.c:janus_ice_send_thread:3479] [6218175448369475] Got 1 SRTP/SRTCP errors in the last few seconds (last error: err_status_replay_fail)
[Thu Oct 12 16:52:31 2017] [WARN] [7494271320071577] ICE failed for component 1 in stream 1, but we're still waiting for some info so we don't care... (trickle pending, answer received, alert not set)
[Thu Oct 12 16:52:32 2017] [7494271320071577] The DTLS handshake has been completed
[Thu Oct 12 16:52:32 2017] WebRTC media is now available
[Thu Oct 12 16:52:32 2017] [ERR] [ice.c:janus_ice_send_thread:3479] [1062342781942434] Got 1 SRTP/SRTCP errors in the last few seconds (last error: err_status_replay_fail)
[Thu Oct 12 16:52:33 2017] [ERR] [ice.c:janus_ice_send_thread:3479] [6558928693043619] Got 1 SRTP/SRTCP errors in the last few seconds (last error: err_status_replay_fail)
[Thu Oct 12 16:52:34 2017] [ERR] [ice.c:janus_ice_send_thread:3479] [1062342781942434] Got 1 SRTP/SRTCP errors in the last few seconds (last error: err_status_replay_fail)
[Thu Oct 12 16:52:35 2017] [ERR] [ice.c:janus_ice_send_thread:3479] [6558928693043619] Got 1 SRTP/SRTCP errors in the last few seconds (last error: err_status_replay_fail)
```

**Comment by lminiero** [comment] 2017-10-13 09:42
Unless you're aware of problems with audio, occasional SRTP errors like that are nothing to worry about: `err_status_replay_fail` means the same packet (e.g., same sequence number, same timestamp, same ssrc) has been sent twice in a short span, which is something SRTP prevents. We print the error but nothing is sent, and it shouldn't be an issue as it means the original packet was encrypted and sent already. Are you using a recent version of Janus, or an older one?

**Comment by tugtugtug** [comment] 2017-10-13 14:06
I'm seeing these as well, when the publisher toggles e audio/video off and back on again. It doesn't always happen, but can reproduce for sure (may need to wait a bit before turn back on?).

**Comment by tugtugtug** [comment] 2017-10-16 14:44
Uploaded a log at https://mega.nz/#!tLhwwJra!1yPI3b-v3EicIf3qyCuBCZj99RrmPni_d94w8JDNIp8

Quite easy to reproduce, toggled audio off/on twice.

**Comment by bhakimi** [comment] 2017-10-16 15:57
This maybe effect the audio path from what our clients state. I think they
are loosing connectivity after this happens due to a rtp timeout on our
asterisk box

**Comment by tugtugtug** [comment] 2017-10-17 14:38
I have identified one bug and fixed it with 0a07b8cc06cdc3dff9ef5baec6f5964e583c9e08

**Comment by lminiero** [comment] 2017-10-17 14:48
> I have identified one bug and fixed it with here

Good catch, looks like due to a leftover or copy/paste error we were still using the network-format version of the sequence number, instead of the host one, which probably messed things up... It's correctly set in the "SSRC changed" branch instead. I'll push a commit with this fix right away :+1:

**Comment by lminiero** [comment] 2017-10-17 14:53
Pushed this commit here: https://github.com/meetecho/janus-gateway/commit/266053e4acfa4795c244f8c9fe3de4feee5da418
Please let me know if it does indeed fix the issue as @tugtugtug suggested, and in case close.

**Comment by tugtugtug** [comment] 2017-10-17 15:00
@lminiero , great!:+1:

**Comment by bhakimi** [comment] 2017-10-18 00:08
great job!! lorenzo can you please comment on this that its pushed to
master before closing this ticket? thank you

**Comment by lminiero** [comment] 2017-10-18 08:25
@bhakimi you may first want to check if this fixes your issue. This particular fix is used when sequence number resets are done, which are typically requested by plugins like the VideoRoom, while I don't think the SIP plugin uses them (unless I'm mistaken).

**Comment by bhakimi** [comment] 2017-10-18 15:43
understood, thank you

**Comment by lminiero** [comment] 2017-11-06 14:07
@bhakimi is this still an issue with master? We made some changes with respect to how we rewrite RTP headers, especially for context switches but not only.

**Comment by bhakimi** [comment] 2017-11-07 14:20
Sorry been MIA due to a fractured hand, will test ASAP

**Comment by lminiero** [comment] 2017-11-07 14:21
Oh, sorry to hear that, hope it's all ok now!

**Comment by lminiero** [comment] 2018-02-13 09:52
Any update? Is this still an issue or can we close this?

**Comment by bhakimi** [comment] 2018-02-13 18:02
Close it please

**Comment by lminiero** [comment] 2018-02-13 18:04
Ack, thx for the feedback!

**Closed by lminiero** 2018-02-13 18:04 UTC
