### ISSUE TITLE
LibreSSL support

### ISSUE THREAD

**Issue by seirotis** [meetecho/janus-gateway#603] opened 2016-09-01 16:20 UTC
For many, neither OpenSSL nor BoringSSL is an option (BoringSSL doesn't even build on ARMv7).

When built against LibreSSL, Janus reports the following error when trying to use any of the demos:
`[ERR] [dtls.c:janus_dtls_srtp_incoming_msg:562] [3492779334074589] Handshake error: error:14102410:SSL routines:DTLS1_READ_BYTES:sslv3 alert handshake failure`

**Comment by lminiero** [comment] 2016-09-01 20:06
Not familiar with LibreSSL, sorry. Have you tried checking the handshake with wireshark/tcpdump to see what's causing the failure? Most of the times it's missing stuff in the features that are advertized. The [same thing happens](https://groups.google.com/forum/#!topic/meetecho-janus/1-u2rQM5dUo) with OpenSSL < 1.0.1g, for instance, so if LibreSSL is based on older code that does not support elliptic curves then DTLS will not work there.

**Comment by saghul** [comment] 2016-09-02 07:56
@seirotis out of curiosity: why are they not an option? Are you on OpenBSD? I agree it would be nice to have it working in all 3.

**Comment by seirotis** [comment] 2016-09-05 08:21
LibreSSL is a version of the TLS/crypto stack forked from OpenSSL in 2014, with goals of modernizing the codebase, improving security, and applying best practice development processes. 
LibreSSL @ Github: https://github.com/libressl-portable/

LibreSSL _does_ support ECC.
I'm using Ubuntu 14.04.5 LTS.

**Comment by lminiero** [comment] 2016-09-05 08:47
Then you'll have to look at a dump of the exchange to see what's going wrong.

**Comment by seirotis** [comment] 2016-09-05 12:29
I'm not really experienced with Wireshark.
Can you help please?
Does the error maybe occur due to missing SSLv3 support?  `... routines:DTLS1_READ_BYTES:sslv3 ...`
IIRC Libressl has removed support for that protocol.

**Comment by lminiero** [comment] 2016-09-06 13:33
Not sure, but I don't think so, the handshake is supposed to have the two parties agree on the protocol to use as well I believe. Capturing with Wireshark or tcpdump will allow you to inspect the messages you and Janus exchange, and more specifically the DTLS handshake that occurs. Hopefully this will hightlight what the browser asks for that Janus (via LibreSSL) is not providing.

There are several tutorials around on Wireshark/tcpdump, so it should be easy enough to figure out how to do a capture. After that it's just a matter of only filtering DTLS packets and looking at the parsed content.

**Comment by lminiero** [comment] 2016-09-06 15:47
Nevermind that, I managed to install LibreSSL for testing and could replicate the issue. I just made a capture with the EchoTest where the browser immediately returns an error after the Hello Janus sends. I'll check the differences between this Hello and one that works fine, and hopefully this will shed some light.

**Comment by lminiero** [comment] 2016-09-06 15:52
As I guessed initially, the cause is the lack of elliptic curves in the Hello Janus sends. Snippet from a diff:

```
[..]
@@ -79,121 +74,23 @@
             Compression Methods Length: 1
             Compression Methods (1 method)
                 Compression Method: null (0)
-            Extensions Length: 40
-            Extension: ec_point_formats
-                Type: ec_point_formats (0x000b)
-                Length: 4
-                EC point formats Length: 3
-                Elliptic curves point formats (3)
-            Extension: elliptic_curves
-                Type: elliptic_curves (0x000a)
-                Length: 10
-                Elliptic Curves Length: 8
-                Elliptic curves (4 curves)
+            Extensions Length: 13
             Extension: SessionTicket TLS
[..]
```

So it fails for the same reason OpenSSL < 1.0.1g fails.

**Comment by seirotis** [comment] 2016-09-09 10:34
So how can this be fixed?

**Comment by lminiero** [comment] 2016-09-09 13:59
This is not something that needs to be fixed in Janus, but in LibreSSL.

Il 09/set/2016 12:34, "seirotis" <notifications@github.com> ha scritto:

**Comment by lminiero** [comment] 2016-09-19 16:59
Closing as not an issue in Janus.

**Closed by lminiero** 2016-09-19 16:59 UTC
