### ISSUE TITLE
Janus + RabbitMQ

### ISSUE THREAD

**Issue by stormbkk87** [meetecho/janus-gateway#455] opened 2016-02-02 04:25 UTC
When using Janus in an Upstart script on Ubuntu 14.04 LTS, Janus always starts before RabbitMQ on reboot. This will produce a socket error in the Janus log. Here's a proposed update to the Janus Upstart script for those having the same issue. I also added 'expect fork'. Seemed appropriate as per the documentation for Upstart. Any issues?

    description "janus"

    start on rabbitmq-server-running
    stop on rabbitmq-server-stopped

    limit nofile 50000 50000
    limit core unlimited unlimited

    expect fork
    respawn
    respawn limit 10 5

    exec /opt/janus/bin/janus

**Comment by ploxiln** [comment] 2016-02-02 05:06
janus does not fork unless you use the `--daemon` option. it's better to not fork if the thing starting/supervising janus supports non-forking processes.

**Comment by lminiero** [comment] 2016-02-02 08:59
If the problem is that daemonizing the application returns before checking if everything started, PR #443 should help fix that. As a side note, why reboot the RabbitMQ server? We use it in some deployments and always just restart Janus there.

**Comment by stormbkk87** [comment] 2016-02-02 09:44
No problems. Just disaster recovery checklist. If the server itself must be restarted for whatever reason, then the Janus instance isn't reconnecting to RabbitMQ when it comes back up due to the differences between RabbitMQ startup (sysvinit) and Janus startup (upstart).  

I rewrote the upstart script you have on your FAQs to support waiting for RabbitMQ to start. RabbitMQ emits "rabbitmq-server-running" and "rabbitmq-server-stopped".

Just thought it would be helpful for others who experienced the same. And to make sure I didn't introduce any other side effects.

**Comment by lminiero** [comment] 2016-02-02 11:47
Thanks for the clarification! Anyway, I don't think we need to add that to the example as many Janus deployments do not use RabbitMQ. I can add these considerations to the docs, though, e.g., as an example of how you can wait for an event before moving to starting Janus.

**Comment by lminiero** [comment] 2016-02-02 11:57
Just updated the docs to reflect that: https://janus.conf.meetecho.com/docs/service
Do you think this is enough feedback for Upstart users?

**Comment by lminiero** [comment] 2016-02-02 11:58
PS: I haven't mentioned the ```fork``` thing as per Pierce's feedback.

**Comment by stormbkk87** [comment] 2016-02-02 13:27
I think it's enough. Plenty of help on Google regarding upstart. Took a bit of digging to find that RabbitMQ already emits the required events to hook into. Will save someone an hour of trying less elegant solutions. ;)

@ploxiln In my janus.cfg I have "daemonize = true" and have the log file set. Wouldn't that allow janus to fork?

**Comment by lminiero** [comment] 2016-02-02 13:31
Cool, closing then! The documentation links to this issue here so any interested user can add.

**Closed by lminiero** 2016-02-02 13:31 UTC
