### ISSUE TITLE
can't make janus last version

### ISSUE THREAD

**Issue by externuz** [meetecho/janus-gateway#550] opened 2016-05-29 13:43 UTC
```
postprocessing/pp-webm.c:83:53: note: each undeclared identifier is reported only once for each function it appears in
make[2]: Leaving directory `/opt/janus-src'
make[2]: *** [postprocessing/janus_pp_rec-pp-webm.o] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
make[1]: Leaving directory `/opt/janus-src'
```

**Comment by lminiero** [comment] 2016-05-29 13:48
That's not the whole error: please don't just nitpick the parts of the log
that you think cause problems, but always provide the whole result as a
gist or pastebin link.

Anyway, I guess the cause is that your ffmpeg doesn't support some codecs,
as VP9 for instance (can't say for sure as that part is missing from your
dump). I'll add another check to fix that tomorrow, and add warnings for
when you try to process recordings you don't support.

L.
Il 29/mag/2016 15:44, "Vladislav Kolesnikov" <notifications@github.com> ha
scritto:

**Comment by lminiero** [comment] 2016-05-29 14:14
Found some time to do it now, fixed in https://github.com/meetecho/janus-gateway/commit/1c8871eefe131f16720f66b9ef7c842786f94719

**Closed by lminiero** 2016-05-29 14:14 UTC
