### ISSUE TITLE
Many switch requests make delay in video (videoroom)

### ISSUE THREAD

**Issue by amnonbb** [meetecho/janus-gateway#1463] opened 2018-12-07 19:38 UTC
As title say.
I use latest master and tried videoroom-skew-detection branch.
I tried to see in janus log level 5 and saw that delay is equel to line appear:
"Got a PLI from a subscriber, forwarding it to"
Sometime this line was spamed 6-7 times when switched video feed actually start play

**Comment by lminiero** [comment] 2018-12-07 20:43
That branch is outdated, and we don't plan to merge it, at least not soon.

**Comment by amnonbb** [comment] 2018-12-08 06:08
Just tried it to see difference with latest master.

**Comment by amnonbb** [comment] 2018-12-09 19:49
I moved Janus to new server with better hardware. The delay occur less. What can I check to find source of issue?

**Comment by atoppi** [comment] 2018-12-10 10:33
**Context**: Janus modifies incoming RTP header data in order to feed the plugins with a virtual RTP stream that has always the same SSRC and seqnum/timestamp range. To accomplish this, Janus needs to handle the SSRC changes, and `switch` is one of the scenarios that triggers such a change.
**Issue**: The delay is probably caused by the algorithm that Janus does use to estimate the time passed between different SSRCs. By design the algorithm is very susceptible to network delays or out-of-order / out-of-time packets, so if the first packet of the new incoming SSRC comes not at the right time, there is an error in the estimation. Unfortunately, as of now, this error can not be recovered and so it gets propagated to the clients in the form of wrong RTP timestamps in either RTP and RTCP, thus leading to a delayed or out-of-sync video.

We are aware of the issue, and we have already discussed internally about the improvements needed in Janus to better handle the SSRC changes but we are very busy in these weeks due to a major refactoring under way. So don't expect this to change in the short term.
In case you had the time and the skills, [here is a pointer](https://github.com/meetecho/janus-gateway/blob/master/rtp.c#L488) to the aforementioned code. Maybe you could come up with a reliable solution to the issue, we'll be more than happy to review any contribution.

**Comment by amnonbb** [comment] 2018-12-10 15:48
I understood that you are busy with refactoring and find workaround in my application: partially use switch and making new handles. But I wanted to know where really the source of issue. Thanks for detailed replay. I'll try to look into that with some skilled help.

**Comment by lminiero** [comment] 2019-11-16 08:43
Closing as most of the discussion on A/V sync in general is happening in the issue referenced above.

**Closed by lminiero** 2019-11-16 08:43 UTC
