### ISSUE TITLE
autogen.sh must be run twice.

### ISSUE THREAD

**Issue by yan-foto** [meetecho/janus-gateway#290] opened 2015-07-22 13:29 UTC
For some reason the first run of `autogen.sh` does not copy `ltmain.sh` and exits with the following error message:

> required file './ltmain.sh' not found

After the first failing attempt, running `libtoolize` or `autogen.sh` copies the missing file. I have found similar issues in two different repositories ([here](https://github.com/akheron/jansson/issues/182) and [here](https://github.com/google/protobuf/issues/149)). According the the discussion of the former issue, I found out that adding `AC_CONFIG_AUX_DIR([.])` to `configure.ac` solves the problem. However, my lack of knowledge regarding `autoconf` doesn't let me know if this is a good idea or not! 

**UPDATE**

Adding `AC_CONFIG_AUX_DIR([.])` might solve the `autogen.sh` problem but is causes `./configure` to fail with the following error:

> configure: error: cannot run /bin/bash /config.sub

So I suppose running `autogen.sh` twice is still the better solution!

---

The complete log (for `auotgen.sh`) is as follows:

```
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force -I m4
autoreconf: configure.ac: tracing
autoreconf: running: libtoolize --copy --force
libtoolize: putting macros in AC_CONFIG_MACRO_DIR, `m4'.
libtoolize: copying file `m4/libtool.m4'
libtoolize: copying file `m4/ltoptions.m4'
libtoolize: copying file `m4/ltsugar.m4'
libtoolize: copying file `m4/ltversion.m4'
libtoolize: copying file `m4/lt~obsolete.m4'
autoreconf: running: /usr/bin/autoconf --force
autoreconf: configure.ac: not using Autoheader
autoreconf: running: automake --add-missing --copy --force-missing
configure.ac:7: installing './compile'
configure.ac:12: installing './config.guess'
configure.ac:12: installing './config.sub'
configure.ac:4: installing './install-sh'
configure.ac:12: error: required file './ltmain.sh' not found
configure.ac:4: installing './missing'
Makefile.am: installing './depcomp'
autoreconf: automake failed with exit status: 1
```
---

I am running Ubuntu **15.04** 64 bit.

**Comment by lminiero** [comment] 2015-07-22 13:33
I never got this issue. I'm not an expert of autoconf either, so I wouldn't know about its impact or availability in all versions (which is worries me most). I'll look into this when the conference ends, next week.

**Comment by yan-foto** [comment] 2015-07-22 13:43
I really appreciate it. To reproduce please clone a fresh copy from GitHub and then run the script :+1:

**Comment by lminiero** [comment] 2015-07-22 14:35
Well, that's what I meant by "never got the issue": it does NOT happen to me, never did :-)
If I do that now, it works as expected. It must be an issue on specific environments, like yours (especially if you say it seems to be happening on other repos as well).

**Comment by yan-foto** [comment] 2015-07-22 14:43
Those two external issued are filed by other people, so I thought there is something to be configured to get it working correctly. If the problem cannot be reproduced, you can just close the issue :dancer: 

If I happen to find out the root of the problem, I'm going to reopen this issue :-)

**Comment by lminiero** [comment] 2015-07-22 14:52
No worries, keep it open anyway, especially if other people are affected. WhenI get back I'll add some info to README and docs about the possible need for an additional call to ```./autogen.sh```, if an error occurs.

**Comment by saghul** [comment] 2015-07-22 16:04
FWIW, I have the same environment (Ubuntu 14.04, 64bits) and I cannot
reproduce it. Did you install all the autotools stuff from the official
repositories?

**Comment by yan-foto** [comment] 2015-07-22 16:09
Sorry, My bad! the description said 14.04 whereas I actually have 15.04. And yes I got everything from the official repo. no custom builds!

**Comment by lminiero** [comment] 2015-07-27 10:37
I added the macro as it seemed harmless enough, and worked normally for me. Let me know if that's actually breaking things for you. Closing until then.

**Closed by lminiero** 2015-07-27 10:37 UTC

**Comment by yan-foto** [comment] 2015-07-27 11:44
:+1: that did the trick. No errors (configure, make) whatsoever. Thanks.
