### ISSUE TITLE
100% CPU usage after releasing an audio call to TCP turn server

### ISSUE THREAD

**Issue by cjaeg** [meetecho/janus-gateway#1626] opened 2019-05-16 13:01 UTC
Using the sip plugin I make a call from a PBX deskphone to my web client.
This call does thru a turn server in TCP mode. If the web client is ending the call everything looks fine but if janus is ending the call the CPU usage bombs to 100%.

When I use the turn server in UDP mode I can not reproduce such issue, it looks so linked to TCP. 

Top during the call :
----------------------
rainbow@rainbow-mgw-134:~$ top -Hbn1 -p 5890
top - 12:36:35 up 1 day, 20:37,  1 user,  load average: 0.00, 1.12, 3.08
Threads:  20 total,   0 running,  20 sleeping,   0 stopped,   0 zombie
%Cpu(s): 73.4 us, 26.0 sy,  0.0 ni,  0.6 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
KiB Mem :  2047992 total,  1741048 free,   106076 used,   200868 buff/cache
KiB Swap:        0 total,        0 free,        0 used.  1784640 avail Mem

  PID USER      PR  NI    VIRT    RES    SHR S %CPU %MEM     TIME+ COMMAND
 5890 janus     16  -4 1358180  22496  17484 S  0.0  1.1   0:00.16 janus
 5900 janus     16  -4 1358180  22496  17484 S  0.0  1.1   0:00.00 log
 5914 janus     16  -4 1358180  22496  17484 S  0.0  1.1   0:00.00 janus
 5915 janus     16  -4 1358180  22496  17484 S  0.0  1.1   0:00.00 janus
 5916 janus     16  -4 1358180  22496  17484 S  0.0  1.1   0:00.00 janus
 5917 janus     16  -4 1358180  22496  17484 S  0.0  1.1   0:00.00 janus
 5918 janus     16  -4 1358180  22496  17484 S  0.0  1.1   0:00.00 sip handler
 5919 janus     16  -4 1358180  22496  17484 S  0.0  1.1   0:00.00 nosip handler
 5920 janus     16  -4 1358180  22496  17484 S  0.0  1.1   0:00.13 ws thread
 5929 janus     16  -4 1358180  22496  17484 S  0.0  1.1   0:00.00 hloop 172088641
 5931 janus     16  -4 1358180  22496  17484 S  0.0  1.1   0:00.00 sip 10899121643
 5932 janus     16  -4 1358180  22496  17484 S  0.0  1.1   0:00.00 sip 10899121643
 5935 janus     16  -4 1358180  22496  17484 S  0.0  1.1   0:00.00 hloop 430700476
 5936 janus     16  -4 1358180  22496  17484 S  0.0  1.1   0:00.00 sip 10955534473
 5937 janus     16  -4 1358180  22496  17484 S  0.0  1.1   0:00.00 sip 10955534473
 5949 janus     16  -4 1358180  22496  17484 S  0.0  1.1   0:00.35 hloop 809415252
 5950 janus     16  -4 1358180  22496  17484 S  0.0  1.1   0:00.00 pool
 5951 janus     16  -4 1358180  22496  17484 S  0.0  1.1   0:00.00 sip 10270887088
 5952 janus     16  -4 1358180  22496  17484 S  0.0  1.1   0:00.00 sip 10270887088
 5955 janus     16  -4 1358180  22496  17484 S  0.0  1.1   0:00.04 siprtp 10270887

Top after end of the call  :
----------------------------
rainbow@rainbow-mgw-134:~$ top -Hbn1 -p 5890
top - 12:36:49 up 1 day, 20:37,  1 user,  load average: 0.08, 1.08, 3.03
Threads:  19 total,   1 running,  18 sleeping,   0 stopped,   0 zombie
%Cpu(s): 73.4 us, 26.0 sy,  0.0 ni,  0.6 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
KiB Mem :  2047992 total,  1740900 free,   106208 used,   200884 buff/cache
KiB Swap:        0 total,        0 free,        0 used.  1784504 avail Mem

  PID USER      PR  NI    VIRT    RES    SHR S %CPU %MEM     TIME+ COMMAND
 5949 janus     16  -4 1358180  22500  17484 R 99.9  1.1   0:07.62 hloop 809415252
 5890 janus     16  -4 1358180  22500  17484 S  0.0  1.1   0:00.16 janus
 5900 janus     16  -4 1358180  22500  17484 S  0.0  1.1   0:00.00 log
 5914 janus     16  -4 1358180  22500  17484 S  0.0  1.1   0:00.00 janus
 5915 janus     16  -4 1358180  22500  17484 S  0.0  1.1   0:00.00 janus
 5916 janus     16  -4 1358180  22500  17484 S  0.0  1.1   0:00.00 janus
 5917 janus     16  -4 1358180  22500  17484 S  0.0  1.1   0:00.00 janus
 5918 janus     16  -4 1358180  22500  17484 S  0.0  1.1   0:00.00 sip handler
 5919 janus     16  -4 1358180  22500  17484 S  0.0  1.1   0:00.00 nosip handler
 5920 janus     16  -4 1358180  22500  17484 S  0.0  1.1   0:00.13 ws thread
 5929 janus     16  -4 1358180  22500  17484 S  0.0  1.1   0:00.00 hloop 172088641
 5931 janus     16  -4 1358180  22500  17484 S  0.0  1.1   0:00.00 sip 10899121643
 5932 janus     16  -4 1358180  22500  17484 S  0.0  1.1   0:00.00 sip 10899121643
 5935 janus     16  -4 1358180  22500  17484 S  0.0  1.1   0:00.00 hloop 430700476
 5936 janus     16  -4 1358180  22500  17484 S  0.0  1.1   0:00.00 sip 10955534473
 5937 janus     16  -4 1358180  22500  17484 S  0.0  1.1   0:00.00 sip 10955534473
 5950 janus     16  -4 1358180  22500  17484 S  0.0  1.1   0:00.00 pool
 5951 janus     16  -4 1358180  22500  17484 S  0.0  1.1   0:00.00 sip 10270887088
 5952 janus     16  -4 1358180  22500  17484 S  0.0  1.1   0:00.00 sip 10270887088

**Comment by lminiero** [comment] 2019-05-17 10:32
You should try attaching via gdb to the pid that's taking the 100% cpu, to see what's keeping it busy. My guess is that this is an issue in libnice, as we never handle the STUN/TURN connectivity ourselves. Make sure you're using a recent enough version of the library (not one of the repo provided ones).

**Comment by lminiero** [comment] 2019-05-20 13:32
@cjaeg to clarify, was the user using TURN, or did you configure TURN for Janus as well? If it's the latter, 99.9% of the times it's not needed, as explained here: https://janus.conf.meetecho.com/docs/FAQ#turn

**Comment by cjaeg** [comment] 2019-05-20 17:19
In fact, I am testing on a corporate LAN and have configure in janus.jcfg a turn_server, turn_port = 80 turn_type = "tcp" and the associate user/pwd. My web client is on the internet the WebRTC media will so  cross the TURN server.

With gdb I have identified the thread create in ice.c :

static void *janus_ice_handle_thread(void *data) {
	janus_ice_handle *handle = data;
	JANUS_LOG(LOG_VERB, "[%"SCNu64"] Handle thread started; %p\n", handle->handle_id, handle);
	if(handle->mainloop == NULL) {
		JANUS_LOG(LOG_ERR, "[%"SCNu64"] Invalid loop...\n", handle->handle_id);
		janus_refcount_decrease(&handle->ref);
		g_thread_unref(g_thread_self());
		return NULL;
	}
	JANUS_LOG(LOG_DBG, "[%"SCNu64"] Looping...\n", handle->handle_id);
==>	g_main_loop_run(handle->mainloop);

And what this thread is doing during its 100% cpu usage with strace :

poll([{fd=102, events=POLLIN}, {fd=113, events=POLLIN}, {fd=114, events=POLLIN}], 3, 14992) = 1 ([{fd=114, revents=POLLIN}])
poll([{fd=102, events=POLLIN}, {fd=113, events=POLLIN}, {fd=114, events=POLLIN}], 3, 14991) = 1 ([{fd=114, revents=POLLIN}])
poll([{fd=102, events=POLLIN}, {fd=113, events=POLLIN}, {fd=114, events=POLLIN}], 3, 14991) = 1 ([{fd=114, revents=POLLIN}])
poll([{fd=102, events=POLLIN}, {fd=113, events=POLLIN}, {fd=114, events=POLLIN}], 3, 14991) = 1 ([{fd=114, revents=POLLIN}])
poll([{fd=102, events=POLLIN}, {fd=113, events=POLLIN}, {fd=114, events=POLLIN}], 3, 14991) = 1 ([{fd=114, revents=POLLIN}])
poll([{fd=102, events=POLLIN}, {fd=113, events=POLLIN}, {fd=114, events=POLLIN}], 3, 14991) = 1 ([{fd=114, ### `revents=POLLIN}])`

**Comment by lminiero** [comment] 2019-05-20 17:22
If the user is behind the corporate firewall, but Janus is publicly reachable, then as explained in the FAQ you *DON'T* need to configure TURN for Janus as well. Only set up TURN for users, not Janus.

That said, that confirms the issue is in libnice, then, and not Janus. If you think you really need TURN for Janus (which again I don't think you do), you should open an issue on their repository instead: https://gitlab.freedesktop.org/libnice/libnice/issues

Closing as not a Janus instance.

**Closed by lminiero** 2019-05-20 17:22 UTC

**Comment by lminiero** [comment] 2019-05-20 17:23
> My web client is on the internet

Ah ok, I was reading it the other way around. Then yes, you do need TURN set up for Janus. See my suggestion about opening the issue on libnice then.
