### ISSUE TITLE
server crash after many [ERR]^[[0m [dtls.c:janus_dtls_fd_bridge:862] No handle/agent/bio, no DTLS bridge...

### ISSUE THREAD

**Issue by jackmjones25** [meetecho/janus-gateway#895] opened 2017-05-19 20:21 UTC
The server crashes a few times a week after showing a lot of this in the log:
[ERR]^[[0m [dtls.c:janus_dtls_fd_bridge:862] No handle/agent/bio, no DTLS bridge...

OS: fedora 25
Janus v0.2.3
libnice-0.1.13-7
openssl-1:1.0.2j-3

50~60 simultaneous users.

BT: https://pastebin.com/U7025fqA

#0  crypto_sha1_update (ctx=ctx@entry=0x7f4368034750, msg=<optimized out>, msg@entry=0x7f4354560d80 "\200", <incomplete sequence \310>, octets_in_msg=<optimized out>, octets_in_msg@entry=52) at crypto/hash/sha1.c:240

**Comment by lminiero** [comment] 2017-05-22 09:07
Very likely the issue #887 fixes. Please try that as we want to merge soon.

**Comment by jackmjones25** [comment] 2017-06-06 16:35
I've got the master after the merge a few days ago and still happens.
https://pastebin.com/zaggdgmq


The lastest master of today has changes on these files... I'll try it in 5 hours.

**Comment by lminiero** [comment] 2017-06-06 16:37
That's a completely different trace, so "still happens" seems incorrect. Anyway, the trace doesn't contain any helpful line, unfortunately.

**Comment by jackmjones25** [comment] 2017-06-08 14:29
sorry @lminiero, I was based on the multiple "dtls.c:janus_dtls_fd_bridge:862] No handle/agent/bio" I see on the log file just before the crash. Let me know if there is anything I can do to help.

**Comment by lminiero** [comment] 2017-06-30 11:26
We'll need a stacktrace that contains meaningful information. The one you shared unfortunately doesn't, as it says something about an abort in `crypto_sha1_final`, with no reference to anything even vaguely Janus related... Closing this issue as the original problem was fixed by the PR I shared. In case the other problem is still occurring, and you can collect better debugging information that may help us figure out the causes, please open a new issue.

**Closed by lminiero** 2017-06-30 11:26 UTC
