### ISSUE TITLE
"Error setting ICE locally" when renegotiation with new offer before connection established

### ISSUE THREAD

**Issue by solarlizard** [meetecho/janus-gateway#1332] opened 2018-08-01 08:23 UTC
Hi. I'm using noSIP plugin. Janus was built from master branch several days ago

Steps to reproduce:

1. new RtcPeerConnection ()
2. peerConnection.addStream ( audio = true, video = false) - AUDIO only stream
3. peerConnection.createOffer (offerToReceiveAudio = 1, offerToReceiveVideo = 1)
4. peerConnection.setLocalDescription
5. sending offer to Janus
6. sending ice candidates to Janus
7. peerConnection.addStream ( audio = false, video = true) - VIDEO only stream
8. peerConnection.createOffer (offerToReceiveAudio = 1, offerToReceiveVideo = 1)
9. peerConnection.setLocalDescription
10. sending NEW offer to Janus

and then:

[WARN] [3452363581478757] Agent already exists?
[ERR] [janus.c:janus_process_incoming_request:1179] Error setting ICE locally
[1533109757738-024851673046419642-8] Returning Janus API error 490 (Error setting ICE locally)

Is it an issue? or I'm doing something wrong?

**Comment by lminiero** [comment] 2018-08-01 08:35
Why are you sending two offers in a row? I don't see any answer in the middle, so it's not a renegotiation either. Closing as it's a broken usage of the JSEP API, hence not a bug.

**Closed by lminiero** 2018-08-01 08:35 UTC

**Comment by solarlizard** [comment] 2018-08-01 08:40
1. Because in usual usage of webrtc I can send another offer (with new stream) before getting an answer
2. Because even if send new offer after "offer->janus->sip->answer->janus->" I see Error setting ICE locally.

So if it's not a bug - can you tell how to decide when I can send a new offer?

**Comment by lminiero** [comment] 2018-08-01 08:44
A new offer can only be sent after an offer/answer cycle has been done. For renegotiations (adding/removing streams to an existing PeerConnection) you'll have to make sure the communications with plugins is respected as well, so that they know it's a renegotiation.

The "Error setting ICE locally" thing appears when yu're trying to create a new PeerConnection, which fails if Janus has an ICE agent already. This probably means you're not doing renegotiations properly as expected by the Janus API. That said, not a question for here: please post on our [group](https://groups.google.com/forum/#!forum/meetecho-janus) instead.
