### ISSUE TITLE
Hangup does not work between "calling" and "progress"

### ISSUE THREAD

**Issue by neelance** [meetecho/janus-gateway#2433] opened 2020-11-12 10:24 UTC
I was [asked on your mailing list](https://groups.google.com/g/meetecho-janus/c/XbZTqeO-lbk/m/H9JfoDioCgAJ) to open an issue here:

I am using the SIP plugin and it works mostly fine. However, if I start a call and hang up during the time it takes to go from the "calling" event to the "progress" event, then the hangup fails and the call is still getting connected.

I can reproduce this with your SIP demo:
- Go to https://janus.conf.meetecho.com/siptest.html
- Log in to our SIP provider
- Start a call to a phone number
- Click "Hangup" right away

What I expect to happen:
- The call terminates and does not even start ringing on the other end. I am able to do a new call.

What actually happens:
- The "Hangup" button becomes disabled, but the call continues. The phone starts ringing. I have no way to terminate the call. The JS console shows errors.

Here is a screenshot of this state:
![Janus WebRTC Server: SIP Gateway Demo 2020-11-12 11-16-19](https://user-images.githubusercontent.com/16184/98927810-4dff1d00-24d9-11eb-9133-43453fb825fd.png)

**Comment by atoppi** [comment] 2020-11-12 10:54
I've tried with a local Asterisk, sending a hangup request from JS a couple of milliseconds after starting the call and it worked as expected. How can I reproduce it ? Should I try with your SIP provider ?

**Comment by neelance** [comment] 2020-11-12 11:05
Hi @atoppi. Thanks for looking into it. Yes, the issue is probably specific to our SIP provider. We are using Placetel, which is a provider in Germany: https://www.placetel.de/

Would it be okay if I send you the login credentials via email? Then you could test it yourself.

**Comment by atoppi** [comment] 2020-11-12 11:14
Ok go on.
Please provide also an endpoint that I could use for testing (like an echo test).

**Comment by atoppi** [comment] 2020-11-12 14:43
@neelance the issue here is that the SIP server of your provider never replied to the INVITE sent by Janus.
When the user clicks "Hangup" on the UI the BYE is not sent even if `nua_bye` has been [done in the code ](https://github.com/meetecho/janus-gateway/blob/ff544327752f151f1664446b7d153fc7e264a862/plugins/janus_sip.c#L4155).
Anyway after some seconds a timeout triggers and the UI should be unlocked.

Unfortunately I was not able to enable libsofia logging in any way. That is weird since I'm using the same variables that I used before and so I could not investigate on the SIP stack status.
If you want to try, launch janus with the variables `SOFIA_DEBUG=9 SU_DEBUG=9 NTA_DEBUG=9` and share the logs obtained during a call.

**Comment by atoppi** [comment] 2020-11-12 15:00
sorted it out the issue about sofia logs, this is what happens when clicking hangup

```
[Thu Nov 12 15:59:11 2020] Got a Janus API request from janus.transport.websockets (0x604000006010)
[Thu Nov 12 15:59:11 2020] Transport task pool, serving request
[Thu Nov 12 15:59:11 2020] [6140762575332057] There's a message for JANUS SIP plugin
nua: nua_bye: entering
[Thu Nov 12 15:59:11 2020] [777094158723] Call status change: [inviting]-->[closing]
nua(0x6120000703c0): sent signal r_bye
nua: nua_stack_set_params: entering
soa_set_params(static::0x615000042200, ...) called
tport(0x616000022880): found 0x615000042c00 by name tcp/185.79.24.137:5060
nta: delayed sending CANCEL (953545487)
[Thu Nov 12 15:59:11 2020] [6140762575332057] Sending event to transport...
[Thu Nov 12 15:59:11 2020]   >> Pushing event: 0 (Success)
nta: timer N3 fired, try UDP instead for INVITE (953545487)
tport_release(0x615000042c00): 0x618000022480 by 0x6130000210c0 with (nil)
nta: INVITE (953545487) TCP times out, trying UDP
tport_tsend(0x616000022280) tpn = udp/185.79.24.137:5060
tport_resolve addrinfo = 185.79.24.137:5060
tport_by_addrinfo(0x616000022280): not found by name udp/185.79.24.137:5060
tport_vsend returned 1524
nta: sent INVITE (953545487) to udp/185.79.24.137:5060
tport_pend(0x616000022280): pending 0x618000022480 for udp/192.168.1.169:37013 (already 0)
nta: timer set next to 500 ms
```

**Comment by atoppi** [comment] 2020-11-12 15:57
Ok here are some more findings.
1) your SIP provider seems not to work on SIP/TCP, so in order to avoid slow call setups, use `force_udp: true` in the `register` message sent from the js
2) Quoting sofia docs:
```
 * By default, the nta follows "@RFC3261" semantics when CANCELing a
 * request. The CANCEL does not terminate transaction, rather, it is just a
 * hint to the server that it should respond immediately (with <i>487
 * Request Terminated</i> if it has no better response). Also, if the
 * original request was sent over unreliable transport such as UDP, the
 * CANCEL is delayed until the server has sent a preliminary response to the
 * original request.
 *
 * If NTATAG_CANCEL_2543(1) is given, the transaction is canceled
 * immediately internally (a 487 response is generated locally) and the
 * CANCEL request is sent without waiting for an provisional response.
```
So the issue is that a CANCEL may not be sent before a provisional response (1xx).
I'll prepare a change by which users will be able to create sessions that obey to RFC 2543 policy, forcing the transaction to be immediately aborted.

**Comment by atoppi** [comment] 2020-11-12 16:17
#2434 should fix it.

**Comment by neelance** [comment] 2020-11-12 16:26
@atoppi Thank you very much for fixing this so quickly! I'm looking forward to your next release to deploy this fix.

> your SIP provider seems not to work on SIP/TCP, so in order to avoid slow call setups, use force_udp: true in the register message sent from the js

This is the cherry on top 😄 
I was already wondering why the call setup took a few seconds longer than the softphone we used before. Thanks for making me aware of the `force_udp` option. I already implemented it and can confirm that call setup is faster now. :+1:

**Comment by lminiero** [comment] 2020-11-17 13:04
@neelance did you have a chance to test Alessandro's PR? Can this be merged?

**Comment by neelance** [comment] 2020-11-17 13:15
> I'm looking forward to your next release to deploy this fix.

@lminiero I thought he already tested it so there is no need for me to confirm. I am using the [debian build](https://packages.debian.org/de/sid/janus) so I would first need to somehow make a build from source if I were to test it.

**Comment by lminiero** [comment] 2020-11-17 13:16
Ack, then I'll nerge and close this. If this is still an issue for you in the future, please reopen :+1:

**Closed** 2020-11-17 13:16 UTC
Labels: pr-exists
