### ISSUE TITLE
ICE succeeds if answered immediately, fails otherwise

### ISSUE THREAD

**Issue by stormbkk87** [meetecho/janus-gateway#286] opened 2015-07-20 18:33 UTC
Hello. Great project! 
I'm running into an issue with using the siptest.html demo. Full debugging on the SIP server (Kamailio + Asterisk) shows all goes perfectly. Debugging on Janus side shows ICE failure only if I let the phone ring more than 1 ring. If I answer it immediately, ICE continues and audio flows perfectly. I also tested on your demo server using my SIP credentials and the same thing happens.

Possibly a timer issue or special timeout variable for ICE gathering? Seems it doesn't wait for the call to be answered before it times out the ICE discovery when there's no call yet. Ends with "487 Request Terminated".

Short debug below. If you need more in-depth debug info please let me know. Thank you for your help.

Failure debug info
    
    (process:1447): libnice-DEBUG: Agent 0x7fa0f8009180 :STUN transaction retransmitted (timeout 4791ms).
    (process:1447): libnice-DEBUG: Agent 0x7fa0f0003760 : bind discovery timed out, aborting discovery item.
    (process:1447): libnice-DEBUG: Agent 0x7fa0f0003760 : Candidate gathering FINISHED, stopping discovery timer.
    (process:1447): libnice-DEBUG: Agent 0x7fa0f8009180 : Retransmissions failed, giving up on connectivity check 0x7fa124004000
    (process:1447): libnice-DEBUG: Agent 0x7fa0f8009180 : pair 0x7fa124004000 state FAILED
    [ERR] [ice.c:janus_ice_cb_component_state_changed:1114] [1101710121] ICE failed for component 1 in stream 1...

When answering the call immediately I show this is the logs and SDP continues.

    [nua_r_invite]: 183 Session Progress
    [nua_i_state]: 183 Session Progress
    (process:1447): libnice-DEBUG: Agent 0x7fa0f0003760 : timer tick #801: 0 frozen, 12 in-progress, 0 waiting, 0 succeeded, 0 discovered, 0 nominated, 0 waiting-for-nom.
    [nua_r_invite]: 200 OK
    Peer accepted our call:

**Comment by stormbkk87** [comment] 2015-07-21 05:12
Solved it! Hope this helps someone else testing the SIP plugin. Insanely well done webrtc module and gateway by the way. :)

Either Asterisk 1.8.x doesn't support tickle ICE or our configuration of Kamailio + Asterisk 1.8.x doesn't like it. Adding "tickle: false" to the createOffer fixes the problem. 

    sipcall.createOffer(
		{
			media: {
				audioSend: true, audioRecv: true,		// We DO want audio
				videoSend: doVideo, videoRecv: doVideo	// We MAY want video
			},
			trickle: false,
			success: function(jsep) {
				console.log("Got SDP!");
				console.log(jsep);
				var body = { "request": "call", uri: $('#peer').val() };
				sipcall.send({"message": body, "jsep": jsep});
			},
			error: function(error) {
				console.log("WebRTC error...");
				console.log(error);
				bootbox.alert("WebRTC error... " + JSON.stringify(error));
			}
		});

**Comment by lminiero** [comment] 2015-07-21 06:48
Actually Asterisk or Kamailio should never get to see the trickle attribute or candidates stuff... all ICE stuff is handled by the Janus core transarently, and the SDP you get between the SIP plugin and your SIP server is plain, with no ICE, DTLS or other stuff.

That said, I thought the cause was that we started ICE as soon as the offer was received, and so, if the answer arrives too late (ringing takes longer) libnice switches to the failed state after about 5 seconds. This doesn't explain why disabling trickle fixes it, though. I'll look into this next week.

**Comment by stormbkk87** [comment] 2015-07-21 11:03
Hi there. Ah makes sense. Thought maybe the ICE candidates weren't getting setup correctly when using trickle ICE. Retested again with both settings and definitely works when trickle:false is set.

**Comment by lminiero** [comment] 2015-07-27 09:58
I haven't been able to replicate this with Asterisk, neither on outgoing nor incoming calls. I created an extensions that waited (ringing) for 10 seconds before starting the echo test, and the call from the SIP plugin worked. I then originated a call to the WebRTC user to then attach it to the same echo test (```channel originate SIP/myuser extension 600@demo```), waited several seconds before answering and accepting permissions, and it still worked. In both cases trickle was enabled.

My guess is your issue was something different, then. Have you checked the admin API info for the affected handle in its various steps?

**Comment by stormbkk87** [comment] 2015-07-27 10:43
No I haven't looked into the Admin API. I can create a SIP account on our proxy for you so you can replicate if that helps.

**Comment by lminiero** [comment] 2015-08-03 11:07
Sorry, don't have time to look into this myself. Please check the admin API to see if anything's wrong there when you trickle. If it's working as expected, instead, feel free to close the issue.

**Comment by lminiero** [comment] 2015-09-03 08:42
Closing the issue as unable to replicate. Feel free to repoen if you can provide new info.

**Closed by lminiero** 2015-09-03 08:42 UTC

**Comment by chadfurman** [comment] 2016-08-04 01:25
I have experienced this problem with the Videoroom plugin when trying to republish my stream.  However, it doesn't happen all the time.  Assuming that it is related to the ICE offer not being answered immediately.

**Comment by jlmari** [comment] 2017-01-09 12:19
Just in case it serves to someone, I have installed the latest version of Janus in Ubuntu 14.04 (Instance of Amazon) and Ubuntu 16.04 (My PC) and in both the same problem happens with trickle:true. At the time of accepting the camera and microphone permissions by the responder, if he takes more than exactly 15 seconds and then accepts them the call can not be started correctly although the Janus log does not give any error and it seems that the call is set correctly. However, on times lower than 15s to allow permissions the call is started correctly. 

With trickle:false the error disappears and the call can be started correctly independently of the time to accept the call and the permissions.
