### ISSUE TITLE
Segmentation fault in janus_audiobridge_incoming_rtp

### ISSUE THREAD

**Issue by peffis** [meetecho/janus-gateway#1102] opened 2017-12-07 13:09 UTC
This happens occasionally when hitting "reload" repeatedly in the browser - so we have an existing session with two users in the audiobridge plugin, once user hits reload and immediately tries to join the same room as before. participant->decoder seems to be 0. 

Stacktrace: https://pastebin.com/E0rLWPdr

**Comment by lminiero** [comment] 2017-12-11 10:45
Check what libasan has to say about the crash, e.g., if it's a usage-after-free kind of thing: https://janus.conf.meetecho.com/docs/debug

**Comment by atoppi** [comment] 2017-12-11 12:24
I can't reproduce this using latest `master` and demo audiobridge.

**Comment by peffis** [comment] 2017-12-11 14:34
It did not happen often for me either (what differs in my app compared with audiobridge is however that the time for the user to start rejoining might be shorter than in the audiobridge demo as I have no dialogue for display name). But I'll try and build my Janus with libasan and see if I can reproduce it myself.

**Comment by lminiero** [comment] 2017-12-22 17:30
Any update?

**Comment by lminiero** [comment] 2018-02-13 09:53
Closing as we didn't receive any feedback, so I assume it's solved. Feel free to reopen if you can confirm it's still an issue with the latest code and provide info to replicate.

**Closed by lminiero** 2018-02-13 09:53 UTC
