### ISSUE TITLE
ICE-connection problem with Edge

### ISSUE THREAD

**Issue by medialwerk** [meetecho/janus-gateway#586] opened 2016-07-25 13:15 UTC
Hello :-),

is it possible that edge has a problem with the current gateway? In our project we have installed janus-gatway v.0.1.1 (+audiobridge plugin) but we found out that only edge is not working (from different locations / computers). We also have the current release of adapter.js.
After that insight i tested edge against this demo page: https://janus.conf.meetecho.com/echotest.html- and the connection failed too. There is always a problem with the ice connection. Can you reproduce this issue?

![screenshot](https://s31.postimg.org/eirha9dy3/Unbenannt.png)

Thanks!

**Comment by lminiero** [comment] 2016-07-25 13:19
I haven't tested Edge in a while, since I first managed to get it working with Janus, so it's likely something has changed and now it doesn't work anymore. Not sure when I'll have time to play with it again: should you manage to find out the root cause and fix it, a PR will be more than welcome.

**Comment by Globik** [comment] 2016-08-19 11:44
Janus gateway is skipping loopback interface. One should to have an active internet connection in order to resolve pc connectivity.

**Comment by lminiero** [comment] 2016-08-19 11:54
No, you just need a local IP address.

**Comment by Globik** [comment] 2016-08-19 13:24
But in https://github.com/meetecho/janus-gateway/blob/4a389917d06654823436f7a0f7eb576dd3e2d446/ice.c in line number 2639 i see the code  skiping the flag iff_loopback

**Comment by lminiero** [comment] 2016-08-19 13:33
Yes. My comment was related to your "you need an active internet connection" part, which is false. Just assign an IP to your network interface and you'll be able to use Janus even without a connection.

**Comment by Globik** [comment] 2016-08-19 13:57
Yes, I see. And one need run from a command line chrome.exe or ff.exe or edge.exe under flag -- allow-loopback-in-peer-connection. If no internet connection on a local machine.

**Comment by Globik** [comment] 2016-08-23 05:43
In the janus.cfg.sample.in need I set interface = 127.0.0.1  ?

**Comment by Globik** [comment] 2016-08-23 12:02
Short to say, I have deleted the line 2639 frome ice.c and the janus's loopback interface works like a charme without internet connection)))) and start both chrome.exe and mozilla firefox with a flag - -allow-loopback-in-peer-connection. All in one now works without internet connection. It is good for testing and disign developing purposes. And must be! And all that works perfectly on my windows machine 7 32bit. Hurraaaah!!!))) Nice job! Thank you very much for janus webrtc gateway!

**Comment by Globik** [comment] 2016-08-23 12:04
Interface option in janus.cfg by the way has no  effect, neither with internet connection or without.

**Comment by lminiero** [comment] 2016-08-23 12:07
I already explained why we don't gather localhost in the candidates. Using Janus locally without any internet connectivity is very easy anyway. Just assign a generic local IP to your interface (e.g., 192.168.0.1) even if it's connected to nothing and it just works.

As a side note, is this related to Edge at all or have you commented on this issue randomly? :tongue:

**Comment by Globik** [comment] 2016-08-23 12:40
Yes, randomly.
192.168.0.1 is not a public address. Without internet connectivity in the janus nice debug instance this ip leads to the error: HOST_CANDIDATE_CANT_CREATE_SOCKET

**Comment by lminiero** [comment] 2016-08-23 13:20
Then please stop highjacking unrelated issues. Since this is not a code issue, please open a new post on the meetecho-janus google group instead.

@medialwerk I'm afraid I'll have to close this issue as the discussion diverted too much from the original purpose. Feel free to open a new one in case it's still an issue.

**Closed by lminiero** 2016-08-23 13:20 UTC

**Comment by Globik** [comment] 2016-08-23 17:59
Do you really think that i'm very interested in opening a new thread in the meetecho-janus google group where all my questions about janus keeping with no replies for years? Hah, oh no. You are afraid that i did this fucking janus webrtc gateway getting work on the old fucking windows machine.

**Comment by lminiero** [comment] 2016-08-23 18:15
I don't know who you think you're talking to, but I'm not your brother or a friend of yours, so I will not tolerate this kind of attitude from a stranger.

As to your delusional remarks, you're probably quite confused. First of all, because I always have the decency of answering all posts on the group myself, although I don't have to (it's a community, not the "Lorenzo solves everything" forum). And second of all, because you don't really have a choice. Github is for code issues. If you find a code issue, feel free to report it here. Highjack an issue with unrelated comments, and I'll ignore them. Open issues meant for the group, and I'll close them. Simple as that.

For what concerns Windows, I really don't see what it is I should be afraid of. Cross system support has always been a desiderata for the project, even though I have focused on Linux myself as that's where my expertise is. Helpful people have helper making Janus work with OSX, and recently the excellent contribution by Marcin has opened a way for Windows support too. I fail to understand what help you've really provided to Janus in that regard, except insulting me for not giving you free support.
