### ISSUE TITLE
[1.x] textroom plugin, Firefox, websocket, error 420 "username already taken" when join on multiple page reload

### ISSUE THREAD

**Issue by thinkawitch** [meetecho/janus-gateway#3103] opened 2022-11-14 14:04 UTC
**What version of Janus is this happening on?**
Janus version: 1101 (1.1.1) Janus commit: a10bf8c6a9dbc1f21645db64f12d934b9cc33f0e

**Have you tested a more recent version of Janus too?**
Yes, on Janus version: 1101 (1.1.1) Janus commit: ef984223dd0cfbaa07445c18748f506899678305

**Was this working before?**
Don't know, not tested on 0.9 version.

**Is there a gdb or libasan trace of the issue?**
no, the server side log the same for firefox and chrome.

**Additional context**
Textroom plugin. The client uses websocket transport. In Firefox browser multiple page reloads lead to server 420 error "username already taken". In chrome browsers (chrome, edge, vivaldi, opera) this bug not met. Checked this on clean demo too, in html/textroomtest.html (just modified to auto join user right on page load). 
Number of reloads to make issue to appear vary, no exact times, sometimes 2-3, sometimes it is 20.

**Comment by lminiero** [comment] 2022-11-14 14:08
That's probably because no disconnection was detected, and so the session and handle will only be removed when the timeout fires (60s by default). If so, not a bug.

**Comment by thinkawitch** [comment] 2022-11-14 14:46
I thinked about it, but why it is only in firefox. The server first creates new session and then disconnects old one, if server log order is correct, this is the same for all browsers.
I'll check to minimize the server timeouts, or make other crutch for firefox.

**Comment by lminiero** [comment] 2022-11-21 10:10
If the websocket connection is not closed when the page is reloaded, then Janus won't detect the disconnection and won't get rid of the session. It may be that this is what Firefox does and other browser don't, in your specific case. But again, in that case Janus is just doing what it should, keeping the session alive until a timeout expires, since as far as it's concerned the connection is still there. As such, nothing we need to fix in the code: notice you can use ping/pong in the WebSocket transport configuration for a WS-level keepalive as well that can kick in sooner than the Janus API one.

Closing this issue.

**Closed by lminiero** 2022-11-21 10:10 UTC
Labels: multistream
