### ISSUE TITLE
Nacks send loop from janus with chrome and frame-limited video stream

### ISSUE THREAD

**Issue by xadhoom** [meetecho/janus-gateway#1182] opened 2018-03-19 13:29 UTC
We noticed that since commit 5c676cf5d2611ffff86087fdea98857b3043401e (figured out with bisecting and actually testing with the previous commit which is ok) a sort of nack loop happens between janus and chrome.

First of all a picture:
![screenshot from 2018-03-19 14-12-12](https://user-images.githubusercontent.com/197981/37597363-8f95c1c0-2b7f-11e8-967d-ba4575224d31.png)

As you can see, the nacks count keeps increasing and it will until the end of the session.
On chrome side, it reports that it cannot sendto the browser udp socket, perhaps because the socket is full or maybe the packet too large (maybe chrome gets tricked into sending something too big)?

This lead to stream that freezes from time to time, for several seconds.

The nacks ramp start after 8/10 Firs.

What we discovered:
* happens from 5c676cf5d2611ffff86087fdea98857b3043401e
* only with chrome, firefox seems ok
* only if the client framerate is limited (we limit between 3~10fps if doing a screen share session)
* in my tests, happens until fps are limited to 21, from 22 onward does not happens anymore
* does not happens without janus (browser2browser, jitsi, whatever)
* happens also on online janus demo

**Comment by lminiero** [comment] 2018-03-19 13:34
Are you sure that's the commit that breaks it and not a couple before? This commit only included code style changes after we merged the larger transport-wide-CC effort, so it might actually have been something from that PR. Currently abroad so I won't have much time to debug anything until I come back in a week or so.

**Comment by lminiero** [comment] 2018-03-19 13:35
Pinging @atoppi in the meanwhile.

**Comment by xadhoom** [comment] 2018-03-19 13:36
@flaviogrossi is investingating it, but the culprit seems the change in defaults

here https://github.com/meetecho/janus-gateway/commit/5c676cf5d2611ffff86087fdea98857b3043401e#diff-f302a3ccc39e037fccf44e207332553cR1032

and there https://github.com/meetecho/janus-gateway/commit/5c676cf5d2611ffff86087fdea98857b3043401e#diff-f302a3ccc39e037fccf44e207332553cR1796

**Comment by flaviogrossi** [comment] 2018-03-19 13:41
yeah, i can confirm that it is not that commit in particular, but it shows there just because it changed the default value:
https://github.com/meetecho/janus-gateway/commit/5c676cf5d2611ffff86087fdea98857b3043401e#diff-f302a3ccc39e037fccf44e207332553cR1796

so, the bug must be in the merge of that pullreq, still trying to understand where.

**Comment by lminiero** [comment] 2018-03-19 13:44
Before that PR the property didn't exist at all: what we then changed was just making the new property false by default, instead of true (for backwards compatibility). Have you checked if revisions before merging #1118 worked fine instead?

**Comment by lminiero** [comment] 2018-03-19 13:45
PS: if it shows when changing the default value, does this mean that when transport-wide-CC is enabled for a room the issue doesn't occur instead?

**Comment by xadhoom** [comment] 2018-03-19 13:49
Yes, before #1118 everything was ok.

Then,  putting `transport_wide_cc_ext=yes` into the room config fixes it.

**Comment by lminiero** [comment] 2018-03-19 13:51
PPS: transport-wide-CC only impacts publishers, viewers are not affected. If these limitations you're doing is on the publisher side, then my guess is that this might be "normal": with transport-wide-CC, publishers use sender-side BWE, figure out there are losses and automatically decrease their bandwidth. This means way less packets are lost, and viewers can get everything. When it's disabled, publishers may send beyond their capabilities (e.g., room configured with 500kbps so that's what we send via REMB), so many packets from the publisher are lost, and viewers never receive them: they NACK the packets, but Janus doesn't have them (the publisher failed to deliver them), which may result in NACKs being sent over and over.

**Comment by flaviogrossi** [comment] 2018-03-19 14:05
yeah, but please note this also happens when both janus and the browser are on the same host (meaning the packet flow is on the loopback interface).

if you need a quick way to test it, just use the [screen sharing demo](https://janus.conf.meetecho.com/screensharingtest.html)

**Comment by xadhoom** [comment] 2018-03-19 14:05
mmmh, first of all this happens also in local network (same pc) where bandwidth is not an issue.
Also there're no viewer, only a publisher sending out 2 video streams: screen + webcam.

Then I cannot understand why it happens when limiting the publisher (using getUserMedia contraints) to less than 20fps, which should use less bw and does not happens when not limiting it.

The only change I see when enabling/disabling the wide-cc feature is:

* when enabled, googAvailableSendBandwidth is something like 6~7 Mbps
* when disabled, googAvailableSendBandwidth raises up to 1Gbps

but the encoding bitrate is the same

**Comment by flaviogrossi** [comment] 2018-03-19 15:00
ok, i think i found the change triggering this problem. It should be [this](https://github.com/meetecho/janus-gateway/commit/411fef7bf777028487e77a556210b177d0418078#diff-f302a3ccc39e037fccf44e207332553cR3072):
```diff
-			if(send_remb) {
+			if(send_remb && participant->bitrate) {
```

in our case (and in the online screesharing demo too?) the participant bitrate is not set and so the REMB message is not sent. Previously it was sent anyway, so this problem never showed up.

What is the correct way to handle this? Revert that hunk from the PR? Always set the participant bitrate?

**Comment by xadhoom** [comment] 2018-03-19 15:01
use the new algo :) ?

**Comment by lminiero** [comment] 2018-03-19 15:07
The participant's bitrate is already set, if the room bitrate is set: https://github.com/meetecho/janus-gateway/blob/master/plugins/janus_videoroom.c#L3767
If you're creating rooms with no bitrate cap, and you never set the participant's bitrate, then we don't interfere and never send a REMB, leaving it just to clients. When using transport-wide-CC, the publisher is autolimited by the feedback: when it's not used, then the publisher has no feedback and probably ends up increasing the bitrate forever (at least Chrome: Firefox probably sticks to a lower bound).

As such, if you're actually testing with `bitrate=0` for room and participants, then it's not an issue, but a browser's policy. Otherwise, there may be a bug. @atoppi is making some more tests on his side.

**Comment by flaviogrossi** [comment] 2018-03-19 15:20
Yes, we currently individually set the bitrate on the single publisher but not when sharing screen.
It makes sense then, thanks.

P.S. if you end up deciding to leave it to the user to always correctly set the bitrate, maybe [this](https://github.com/meetecho/janus-gateway/blob/6435c70839f1f1abe72f4e9ff0091f09ded8ef15/html/screensharingtest.js#L351) should be changed too after that PR

**Comment by lminiero** [comment] 2018-03-19 15:21
Yep, just did that! https://github.com/meetecho/janus-gateway/commit/16ced1c50058c36fed6d62c831b295f34d32e82e

**Comment by lminiero** [comment] 2018-03-19 15:35
Thanks for the valuable feedback guys! I think that the next step now will be to automatically enable transport-wide-CC in the core, when negotiated, and remove the configurable stuff from the VideoRoom code. This way all plugins will benefit from it. We've been using it in production for a while already, and it does seem to make things work better.

**Comment by flaviogrossi** [comment] 2018-03-19 15:54
thanks to you for the quick response and keep up the good work!

**Comment by atoppi** [comment] 2018-03-19 16:08
Investigating into this. I have successfully replicated the mentioned nacks "send loop":
- by using the localhost interface
- testing the Screen Sharing Demo (`screensharingtest.hml`)
- with and without `rfc4588` for rtx <-- maybe not relevant but worth a try

Then dumped the RTP packets on Janus and Wireshark.
At first I thought this was caused by some bug on Janus nack algorithm, then I discovered  that after a while (1-2 minutes) doing screensharing Chrome start to _skip_ some RTP packets. Sometimes a block of 10 or more of them is simply ignored from the source.
```
[Mon Mar 19 16:36:35 2018] [8554320825239722] RECEIVED sequence number 32898
[Mon Mar 19 16:36:35 2018] [8554320825239722] RECEIVED sequence number 32899
[Mon Mar 19 16:36:35 2018] [8554320825239722] RECEIVED sequence number 32900
[Mon Mar 19 16:36:35 2018] [8554320825239722] RECEIVED sequence number 32901
[Mon Mar 19 16:36:35 2018] [8554320825239722] RECEIVED sequence number 32906
[Mon Mar 19 16:36:35 2018] [8554320825239722] RECEIVED sequence number 32907
[Mon Mar 19 16:36:35 2018] [8554320825239722] RECEIVED sequence number 32908
```
Here, after 2 minutes, Chrome skipped 5 packets for no apparent reason. In the first minute of testing a variable bitrate has been sent (from 0.5 to 3 Mbps). Then after the issue arises, it is very simple to trigger it again just by generating a bitrate spike (I usually move very fast the window I'm sharing).
Firefox seems to have a similar issue too, but it actually happens way less frequently, and does not start a "nacks loop" issue, it is more like a sporadic skipping of RTP blocks.

My thought is that the issue is due to some sort of compensation acting inside the browser encoders when dealing with dynamic bitrates. Janus is simply reacting by sending NACK requests and eventually counting the packets as lost after a while.

**Comment by xadhoom** [comment] 2018-03-19 16:11
No, the browser is not skipping frames, the OS is giving back errors to the browser.

@atoppi if you start chrome in debug mode you'll see socket errors when trying to `sendto()` the socket.
seems that it fails because the socket returns `ewouldblock` , the reason is unknown... maybe packet too large or buffer full, who knows.

**Comment by atoppi** [comment] 2018-03-19 16:12
@xadhoom makes sense. Thanks for clarification.

**Comment by xadhoom** [comment] 2018-03-19 16:12
or maybe the browser "thinks" to have unlimited bw and is filling up the sendbuffer...

**Comment by flaviogrossi** [comment] 2018-03-19 16:13
@atoppi, to observe that, just start chrome from a shell with `--enable-logging --vmodule=*/webrtc/*=2,*/libjingle/*=2,*=-2`

**Comment by lminiero** [comment] 2018-03-19 16:19
Before transport-wide-CC we sent a default of ~250/300kbps via REMB for bitrate=0, so that's why it was working at the time. It wasn't truly an "unlimited" value.

**Comment by lminiero** [comment] 2018-03-20 11:30
Closing as the issue was sorted out.

**Closed by lminiero** 2018-03-20 11:30 UTC
