### ISSUE TITLE
DOMException/AddTransportInfo with content name audio

### ISSUE THREAD

**Issue by sschmidt** [meetecho/janus-gateway#950] opened 2017-07-13 14:17 UTC
Hi,

I'm having trouble receiving incoming calls with janus. Here are the steps to reproduce the error:

- head over to: https://janus.conf.meetecho.com/siptest.html
- put in sip credentials + connect
- call your sip account
- the "incoming call" dialog opens. Hit "accept".
- call will be rejected with the following error:

WebRTC error: DOMException: Failed to parse SessionDescription.  Failed to AddTransportInfo with content name: audio
error @ siptest.js:272

**Comment by lminiero** [comment] 2017-07-13 16:54
I (and others) use the SIP plugin daily successfully, so this is very likely caused by the response (SDP) you get back from whoever you're calling. Please post details on the call you're attempting (Admin API dump, SDP offers and answers) in a pastebin/gist (not inline) so that we can check what may cause the browser to barf.

**Comment by sschmidt** [comment] 2017-07-13 17:03
Thanks @lminiero . Here is the pastebin with the SDP messages as seen in the browser (x'ed out the phone numbers): https://pastebin.com/4DNTgD3Y
Can't access the Admin API, given it's your server :) I can try on a test server of mine if that helps?

**Comment by lminiero** [comment] 2017-07-13 17:13
Yeah, you should test against your server and provide dumps from there. Our server is unreliable, as we mess with it all the times for internal tests as well.

**Comment by sschmidt** [comment] 2017-07-13 18:55
Ok, here we go:
- Admin: https://pastebin.com/31bSJDXv
- Javascript Traces: https://pastebin.com/Wk51HLZ6

**Comment by sschmidt** [comment] 2017-07-14 13:27
@lminiero I think the problem is somehow related to the two audio streams in the sdp payload. One is deactivated, but I found some code in janus which might just ignore a second audio stream: https://github.com/meetecho/janus-gateway/blob/ef4a07b4c1488d628a734bb9e4b2dfdddde03e34/janus.c#L1043
Is it possible that the wrong stream gets ignored in our case?

**Comment by lminiero** [comment] 2017-07-14 13:33
Yes, we don't support multiple streams of the same kind in the same PeerConnection right now. You can have at max 1 audio + 1 video (plus datachannels, if used).

**Comment by sschmidt** [comment] 2017-07-14 14:07
Hm, any idea where the second audio stream could come from? Could I just patch janus to ignore the deactivated stream?

**Comment by lminiero** [comment] 2017-07-14 14:24
In the SIP plugin, if you get a 2nd audio stream it's because the SIP peer puts it there, the SIP plugin never takes initiatives on that. If so, you should prevent the additional media stream to be negotiated there, if possible.

**Comment by sschmidt** [comment] 2017-07-14 20:25
Thanks @lminiero . I got it working for us by essentially just cutting out the second stream before it gets processed through janus, i.e. before the `janus_sdp_preparse` here: https://github.com/meetecho/janus-gateway/blob/master/janus.c#L2739

Although working for us, I think that's not the expected/recommended behaviour (i.e. just cutting everything but first stream). The RFC says nothing specific, just found: "The semantics of multiple m= lines using the same transport address are undefined." (https://tools.ietf.org/html/rfc4566#page-22). 

Any thoughts on how janus should behave when multiple audio streams are present? Think we could come up with a quite easy fix here to adopt this.

**Comment by lminiero** [comment] 2017-07-14 21:33
There's not going to be any easy fix. This will only work when we implement multistream support, which will require a considerable refactoring, considering it needs to work even without bundle support, so potentially additional ICE streams. The trickiest part is going to be addressing those lines to/from plugins, though, and how to handle RTP/RTCP relaying in presence of multiple streams of the same kind, terminating stats for all of them, etc.. Again, not easy at all. As discussed on the group this is something we plan to do, just not exactly sure when.

**Comment by lminiero** [comment] 2017-08-01 10:55
Closing as it was not an issue (we don't support multistream yet).

**Closed by lminiero** 2017-08-01 10:55 UTC
