### ISSUE TITLE
Weakness of RTCP latching in VideoRoom RTP forwarder

### ISSUE THREAD

**Issue by gianluca-nitti** [meetecho/janus-gateway#2526] opened 2021-01-21 16:47 UTC
I'm using the RTP forward functionality of the VideoRoom plugin to relay the video of a videoroom's participant to an external service (which reads the incoming stream using ffmpeg). I need RTCP feedback to work so that the receiver can send PLI packets to request a full frame if necessary (e.g. due to packet loss, and to avoid having to wait for the first automatically sent keyframe when starting).

I managed to get it to work, but only if the receiver is already running when the RTP forwarder is started; this is due to the fact that if the receiver is started later, it never gets the two latching RTCP packets (sent [here](https://github.com/meetecho/janus-gateway/blob/master/plugins/janus_videoroom.c#L2005) when the forwarder is starting), so it has no idea of which port janus is listening on for RTCP feedback. In this case ffmpeg tries the next port number of the port the RTP is coming from.
For example if janus is sending RTP from UDP port 44708, ffmpeg assumes janus is listening for RTCP feedback on port 44709, but this is not the case as the [local RCTP port is chosen randomly](https://github.com/meetecho/janus-gateway/blob/master/plugins/janus_videoroom.c#L1881).

In my understanding, even if the receiver is started before the forwarder, the latching packets could still get lost (it's UDP after all), and thus the receiver would never be able to send RTCP feedback to janus.

Would it be possible to improve this situation? Currently there are two very basic strategies I can think of:
- binding the RTCP socket to the next port of the one the RTP socket is bound to, as [it seems to be commonly done according to Wikipedia](https://en.wikipedia.org/wiki/RTP_Control_Protocol#Protocol_functions), or
- periodically send empty "latching" RTCP packets so that receivers can determine the correct port

but maybe there are better solutions.

**Comment by lminiero** [comment] 2021-01-21 16:57
Yes, it's a known limitation, but done on purpose to avoid too many backs and forths to establish stuff. It's a bit of a "chicken and egg" situation: when you create the forwarder, there's already someone listening, so there's no easy way for the receiver to know where to send the feedback to the sender unless you latch (or do multiple requests to update stuff that I don't want to add).

> * binding the RTCP socket to the next port of the one the RTP socket is bound to, as [it seems to be commonly done according to Wikipedia](https://en.wikipedia.org/wiki/RTP_Control_Protocol#Protocol_functions), or

We're not going to do that, as it's fragile and most likely prone to errors (port may be taken).

> * periodically send empty "latching" RTCP packets so that receivers can determine the correct port

This might be an option. Thinking about it, though,

> [local RCTP port is chosen randomly](https://github.com/meetecho/janus-gateway/blob/master/plugins/janus_videoroom.c#L1881).

we might allow users to configure the local port to use. This way, if you have control of both sender and receiver and trust the port to be free when it will be needed, you can tell the receiver in advance which port RTCP will be on. That said, it's not just the port, since the receiver won't know the address to send to either (unless you know because you control the operations).

That said, this probably belongs to the [group](https://groups.google.com/g/meetecho-janus), as it's a discussion and not a bug to solve, so I'll close this.

**Closed by lminiero** 2021-01-21 16:57 UTC
