### ISSUE TITLE
No left event sent when last participant leaves AudioBridge session

### ISSUE THREAD

**Issue by Frenzie** [meetecho/janus-gateway#2499] opened 2020-12-17 09:16 UTC
We are using the sampleevh plugin to catch AudioBridge plugin events.
When an audio room participant disconnects, a `destroyed` event and a `left` event are sent with relevant information about the participant.
However, when the last participant leaves, only the `destroyed` event is sent, even if the room is kept around.

To reproduce:
1. Enable the sample event handler in `janus.eventhandler.sampleevh.jcfg`
2. Enable `sessions` and `plugins` events
2. Connect more than one participant and observe the difference when disconnecting

**Comment by lminiero** [comment] 2020-12-17 10:50
There's no `destroyed` event when the last participant leaves: we don't auto-destroy rooms, `destroyed` can only be sent in response to a `destroy`. Please be clearer in describing exactly what's leading to the issue.

**Comment by Frenzie** [comment] 2020-12-17 11:45
The issue is that there's no `left` event sent for the last participant who leaves an AudioBridge room.

**Comment by lminiero** [comment] 2020-12-17 18:07
If you're talking in response to a `destroy` (which again is not clear), I think it's expected, since `destroy` will set each participant's `room` object to `NULL`: since "left" is only sent if a `room` object exists for the participant when they leave/close the PC, that's probably because you're not getting it. Anyway, a `destroyed` event for a room should be considered an implicit indication that all its participants left (since the room doesn't exist anymore).

**Comment by Frenzie** [comment] 2020-12-18 08:49
I'm talking about in response to a participant leaving the room by clicking disconnect or by closing the window. The room itself is not destroyed.

My apologies if I confused matters by mentioning any `destroyed` events. That was just a thought I had for a potential workaround. Each individual user has their own session, and you could store which `session_id` relates to which `room` so that when that session is destroyed you know they left the room.

A `left` event with pertinent information that is sent for every leaving participant except the last one:
```
{
  "emitter": "MyJanusInstance",
  "type": 64,
  "timestamp": 1608281085272161,
  "session_id": 7139886510193975,
  "handle_id": 6560529151916107,
  "opaque_id": "audiobridgetest-9dROEGmPWAbw",
  "event": {
    "plugin": "janus.plugin.audiobridge",
    "data": {
      "event": "left",
      "room": 1234,
      "id": 7941029110332123,
      "display": "jkk"
    }
  }
}
```

The `destroyed` event for the participant's session, but for the last participant this would be the only indication that they left.
```
{
  "emitter": "MyJanusInstance",
  "type": 1,
  "timestamp": 1608281085318461,
  "session_id": 7139886510193975,
  "event": {
    "name": "destroyed"
  }
}
```

**Comment by atoppi** [comment] 2020-12-18 10:38
I'm unable to reproduce the issue.

By disconnecting the clients I get for all of them
- `destroyed` (session)
- `detached` (handle)
- `disconnected` (transport)

Meanwhile by hanging up (call hangup in the js console) I get for every participant
- `left`

**Comment by Frenzie** [comment] 2020-12-18 11:11
@atoppi Do you also get all of those events via the `sampleevh` plugin as opposed to the JS console?

**Comment by atoppi** [comment] 2020-12-18 11:30
@Frenzie the events I mentioned are the ones sent by Janus through HTTP to the sampleevh.

**Comment by Frenzie** [comment] 2020-12-18 12:04
@atoppi I can confirm that `mixertest.hangup()` results in a `left` event, but that's not a natural usage scenario such as I described in the OP.

The issue is that closing the window, interrupting the connection or using `janus.destroy()` like the demo page does when you click stop, gives you all of these expected events for every participant but the last one.

**Comment by atoppi** [comment] 2020-12-18 12:12
When I click "Stop" on the client pages, I get exactly the first scenario I described
- `destroyed` (session)
- `detached` (handle)
- `disconnected` (transport)

I'm using ws transport if that helps.

Anyway if you are analyzing the events coming from handlers, you should really consider that either
- disconnection event on a transport
- detach event on a handle

should be considered as "closing" events for a mixer session.

**Comment by Frenzie** [comment] 2020-12-18 13:08
None of those events tell me which room someone left. What I'm after is the `left` event, or at least this information:

```
    "data": {
      "event": "left",
      "room": 1234,
      "id": 7941029110332123,
      "display": "jkk"
    }
```

That information is always provided, except for the final participant in certain conditions.

The videoroom does always send an `unpublished` and `leaving` event with that information.

**Comment by lminiero** [comment] 2020-12-18 13:29
> None of those events tell me which room someone left

They don't need to. They all contain info on session/handle and opaque_id, all of which will be related to a participant that joined before. As such, you always have the info you need to do any form or correlation. If you expect all Janus events to contain all the info you need, your evend-handler based application will be quite frail.

**Comment by Frenzie** [comment] 2020-12-18 14:03
> They don't need to.

I didn't say those events should.

In the audioroom there's a `left` event that is always sent except in a highly specific real-world scenario (i.e., the connection can be interrupted for any number of reasons without a hangup). 

Besides this being inconsistent and unexpected in and of itself, the equivalent event(s) in the videoroom plugin is always sent including in that scenario. Therefore it's also inconsistent with other plugins.

**Comment by atoppi** [comment] 2020-12-18 14:12
@Frenzie like I said I was unable to reproduce with the Stop button.
Do you have a list of steps to reproduce this ?
Are you using http or ws for transport ?

**Comment by Frenzie** [comment] 2020-12-18 14:40
@atoppi I'm not entirely sure what I can add to my steps in the OP. Could you please let me know if there's anything specific that's unclear?

I purposefully wrote and tested the steps on the basis of current master + the demo files, both to make it easy to reproduce and to exclude the possibility of a mistake outside of Janus. The demo files use http by default, but behavior with regard to the `left` event is the same in ws.

**Comment by Frenzie** [comment] 2020-12-18 14:48
To summarize the slightly updated findings, the `left` event is always sent:

* On any disconnect
  * except for the last participant when the connection is broken without a hangup
* On all hangups

**Comment by atoppi** [comment] 2020-12-18 15:01
This was a race inside janus core that invalidated the session before the event could be sent.
The above commit should fix the issue.

**Comment by Frenzie** [comment] 2020-12-18 15:20
Awesome, thanks! I can confirm that it's working.

**Comment by lminiero** [comment] 2020-12-18 15:20
Closing then.

**Closed by lminiero** 2020-12-18 15:20 UTC
