### ISSUE TITLE
[1.x] Remotely added publisher sometimes hangs for 5-10 seconds before starts to play

### ISSUE THREAD

**Issue by dmitrydiavita** [meetecho/janus-gateway#3419] opened 2024-08-27 17:16 UTC
**What version of Janus is this happening on?**
v1.2.4 bae9c51982835c2d745dbe38a80eb660ac6a07e1

**Have you tested a more recent version of Janus too?**
No. It is fresh installed actually

**Was this working before?**
I don't know

**Is there a gdb or libasan trace of the issue?**
No

**Additional context**
Hello!
We are using your videoroom plugin's api for adding remote publishers. As example we have - 2 publishers in room, first one is local, and the second is added from another Janus instance (through add_remote_publisher method call). And when new subscriber opens room, local Janus instance's publisher's stream starts to playing immediately, but remotely added publisher's stream sometimes hangs up to 5-10 seconds, before starts to play, and sometimes it is also starts playing immediately. I suppose that it is somehow depends on codec's keyframes, and its interval. But you some how resolved that for local instance's publishers.
What we can do to overcome this difficulty for remotely added publishers ?

**Comment by lminiero** [comment] 2024-08-28 08:45
> you some how resolved that for local instance's publishers

Remote publishers use RTP forwarders exactly as the VideoRoom-to-Streaming approach, except it's more integrated in the plugin. I just tested it and it works as expected. My guess is you're not passing `rtcp_port` correctly, or if you do you have network constraints that prevent the RTCP latching from taking place. In both cases, it's not a bug in Janus but a configuration problem, so further discussion belongs to the [group](https://janus.discourse.group/), not here. Closing.

**Closed by lminiero** 2024-08-28 08:45 UTC
Labels: multistream

**Comment by lminiero** [comment] 2024-08-28 14:08
PS: I noticed we still didn't have any documentation for remote publishers in the docs. I just pushed them upstream, and updated them [online](https://janus.conf.meetecho.com/docs/videoroom).
