### ISSUE TITLE
janus-pp-rec conversion to mp4 makes unplayable video file

### ISSUE THREAD

**Issue by barakpp** [meetecho/janus-gateway#2968] opened 2022-05-03 20:53 UTC
**What version of Janus is this happening on?**
Janus version: 1001 (1.0.1)
501f2041a0518d5dd340b803eb3cb031d005bce9

**Have you tested a more recent version of Janus too?**
No

**Was this working before?**
No

**Additional context**
Hi, first thank you for a great tool you develop!

I'm streaming h264 video (baseline profile) file which I encoded myself using ffmpeg with this command:

```
.\ffmpeg.exe -i .\BigBuckBunny.mp4 -threads 0 -profile:v baseline -c:v libx264 -x264-params "nal-hrd=cbr" -b:v 2M -minrate 2M -maxrate 2M -bufsize 4M -r 25 base-profile.h264 to Janus videoroom.
```

When I create the room I set h264 profile id to 42e01f and make sure that the SDP which I generate (using pion library in Go) matched that profile id.

I record that stream using videoroom (When I send the "configure" request I set record true and rec_dir path).
It created mjr file successfully.

When I try to use janus-pp-rec to convert that file to mp4 I get no errors with this log:

```
Janus version: 1001 (1.0.1)
Janus commit: 501f2041a0518d5dd340b803eb3cb031d005bce9
Compiled on:  Sun Apr 10 04:08:24 UTC 2022

Logging level: 4

Source file: test.mjr
Target file: out.mp4

File is 7372284 bytes
Pre-parsing file to generate ordered index...
This is a video recording:
  -- Codec:   h264
  -- Created: 1651606069032022
  -- Written: 1651606071147138
SSRC detected: 315386376
Counted 6442 RTP packets
Counted 6442 frame packets
  -- 1280x720 (fps [90000,360000] ~ 1)
[libx264 @ 0x5561fbc7a280] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2
[libx264 @ 0x5561fbc7a280] profile High, level 3.1, 4:2:0, 8-bit
[libx264 @ 0x5561fbc7a280] 264 - core 160 r3011 cde9a93 - H.264/MPEG-4 AVC codec - Copyleft 2003-2020 - http://www.videolan.org/x264.html - options: cabac=1 ref=3 deblock=1:0:0 analyse=0x3:0x113 me=hex subme=7 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=1 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=-2 threads=18 lookahead_threads=3 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=3 b_pyramid=2 b_adapt=1 b_bias=0 direct=1 weightb=1 open_gop=0 weightp=2 keyint=250 keyint_min=1 scenecut=40 intra_refresh=0 rc_lookahead=40 rc=crf mbtree=1 crf=23.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.00
First keyframe: 0
out.mp4 is 7225164 bytes
Bye!
```

So it outputs out.mp4 file, but when I try to play this file it play with 1 fps although the original fps is 25.

I tried to use ffmpeg to extract the h264 content without re-encoding using this ffmpeg command:

```
ffmpeg -i out.mp4 -c copy -f h264 videoOnly.h264 
```

and then containerize to mp4 without re-encoding using ffmpeg command:

```
ffmpeg -i videoOnly.h264 -c copy -f mp4 it_works.mp4
```

Then I got a playable file which works.

I got the same behavior when I convert the mjr to mkv.

I will be glad for your help, I attached the mjr file. Thank you very much
[test.zip](https://github.com/meetecho/janus-gateway/files/8614352/test.zip)
.

**Comment by lminiero** [comment] 2022-05-05 08:59
It's not Janus' fault. The RTP packets have all jumps of 90000 at least, which means frames are supposed to be rendered a second after each other. If you check with the `-e` flag, for instance:

```
janus-pp-rec -e test.mjr
{"t":"v","c":"h264","s":1651606069032022,"u":1651606071147138,"extended":{"packets":6442,"duration":735.0,"codec":{"resolution":[{"ts":0.0,"width":1280,"height":720}]}}}
```

this caused the postprocessing tool to estimate a length of 735 seconds. Activating debug (`-d 5`) you can see how the timestamp, which is what we use for timing, causes this broken evaluation, while the interarrival timing of packets (addressed by `pts`) is supposedly closer to reality instead:

```
[..]
Counted 6442 RTP packets
[        89][  56] seq=1, ts=4294967295, time=0.00s pts=0.00s
[       155][1200] seq=2, ts=4294967295, time=0.00s pts=0.00s
[      1365][1200] seq=3, ts=4294967295, time=0.00s pts=0.00s
[      2575][ 374] seq=4, ts=4294967295, time=0.00s pts=0.00s
[      2959][  20] seq=5, ts=4295057295, time=1.00s pts=0.03s
[      2989][  20] seq=6, ts=4295147295, time=2.00s pts=0.07s
[      3019][  20] seq=7, ts=4295237295, time=3.00s pts=0.11s
[      3049][1200] seq=8, ts=4295327295, time=4.00s pts=0.14s
[      4259][1200] seq=9, ts=4295327295, time=4.00s pts=0.14s
[      5469][1200] seq=10, ts=4295327295, time=4.00s pts=0.14s
[      6679][1200] seq=11, ts=4295327295, time=4.00s pts=0.14s
[      7889][1200] seq=12, ts=4295327295, time=4.00s pts=0.14s
[      9099][ 911] seq=13, ts=4295327295, time=4.00s pts=0.14s
[     10020][1200] seq=14, ts=4295417295, time=5.00s pts=0.17s
[..]
```

This means that nothing is broken in Janus: the RTP stream you're sending to Janus is broken, because timestamps are wrong. Not sure if it's a problem in Pion or something caused by your application, but that's what you need to fix.

Closing as not a Janus issue.

**Closed by lminiero** 2022-05-05 08:59 UTC
Labels: multistream
