### ISSUE TITLE
Bitrate dropping on the caller side

### ISSUE THREAD

**Issue by jbboisseau** [meetecho/janus-gateway#1893] opened 2019-12-09 17:37 UTC
I'm experiencing a strange issue for about 2-3 weeks on Google Chrome 78 during video calls. The bitrate suddenly drops to 30kbits/s on the caller side few seconds after the beginning of the call and never gets higher again then. 

I was thinking of an issue on my janus instance, but I've found the same problem on the demo website.
<img width="1125" alt="videocall-bitrate-issue" src="https://user-images.githubusercontent.com/1298708/70458617-be741180-1ab2-11ea-9532-cb5d82ad2916.png">

**Comment by lminiero** [comment] 2019-12-09 17:40
Why are you folks not using the Search feature?
Duplicate of #1473, #1861 and #1890, see #1889.

**Closed by lminiero** 2019-12-09 17:40 UTC

**Comment by jbboisseau** [comment] 2019-12-09 20:29
Many thanks for your answer. Why all these issues are considered as closed, given that the PR fixing it is not merged in the main branch yet. Why not keeping one of those issues opened?
