### ISSUE TITLE
Established call get Hangup when peer receiving new call

### ISSUE THREAD

**Issue by kidandcat** [meetecho/janus-gateway#312] opened 2015-08-24 15:27 UTC
When peer1 is on an established call with peer2 and peer1 get a call from peer3, peer1 receive a hangup  (486: busy here) signal from janus server, even if you ignore it, the SIP plugin creates a dtls alert forcing to close the connection by janus server.

if i'm not wrong peer1 is not the one who should receive the hangup but peer3.

You can easily test it in the janus example https://janus.conf.meetecho.com/siptest.html

PD: there is a chance that the error is in asterisk sending sdp messages but it is not probably.

**Comment by lminiero** [comment] 2015-08-25 14:22
I can confirm it's a bug in the plugin, I could replicate it myself. I'll try to work on a fix ASAP.

**Comment by lminiero** [comment] 2015-08-25 15:07
This commit takes care of the specific issue and fixes it, at least for me.

That said, I'm not very satisfied with the fix, that looks more like a hack. Specifically, we forward hangup events whenever the ```nua_i_state``` is invoked and the state is terminated. Strangely enough, this is what was happening in this case:

1. the person in a call gets an INVITE and so replies with a 486, https://github.com/meetecho/janus-gateway/blob/master/plugins/janus_sip.c#L1474
2. ```janus_sip_sofia_callback``` is invoked with a ```nua_i_state``` stating ```486 Busy Here```, which is what we replied with https://github.com/meetecho/janus-gateway/blob/master/plugins/janus_sip.c#L1412
3. ```callstate``` equals ```nua_callstate_terminated``` (probably because, as far as that OTHER SIP session, it is a terminated session) and so, before the fix, this was interpreted as a breaking event, and a hangup was forwarded to the person in the call, thus hanging up the call for them.

The fix currently only checks if the status is 486 and if the plugin state for the user is different from "currently inviting": if it is, we ignore the event and nothing happens https://github.com/meetecho/janus-gateway/blob/master/plugins/janus_sip.c#L1419

That said, this feels a bit as a hack, as different error codes may trigger the same situation, but at the same time we definitely want to hangup if something wrong happened. I guess that some of the parameters passed to ```janus_sip_sofia_callback``` should help us discriminate the different sessions a same user may be involved in, and thus allow us to handle this the proper way. @saghul do you have any feedback on where I can look, since you're more familiar with Sofia SIP?

**Comment by kidandcat** [comment] 2015-08-25 15:13
Thanks for the fix, even if it is temporal. I think it could be an option to allow those errors to be handled in the browser client, may be for production at least, as may be errors you can fix. But while the plugin forces de hangup, the client cannot do anything.

**Comment by lminiero** [comment] 2015-08-25 15:16
That's a good point, but the idea with the SIP plugin was to make it as easy and lightweight as possible on the client side, so that you wouldn't have to worry about SIP details at all.

**Comment by saghul** [comment] 2015-08-25 15:20
With the current architecture you cannot handle more than one call simultaneously with a single plugin session, so there is not much else you can do in the client side. Maybe emit a "missed_call" event?

As for compile time flags that alter behavior, I hate them with a passion.

**Comment by kidandcat** [comment] 2015-08-25 15:21
Well, i have been working with multicalls using multiple plugin sessions, it works fine, if you take care that the last plugin session will be the one receiving the calls.

**Comment by kidandcat** [comment] 2015-08-25 15:25
Anyway i have had the needed to be modifying the spds as chrome for ubuntu was somehow ignoring media constraints when receiving a call with video packets (sdp with video from a voip yalink phone without video, damn asterisk) when we dont want video. So i modify the sdp in that case.

**Comment by saghul** [comment] 2015-08-25 15:28
> Well, i have been working with multicalls using multiple plugin sessions,

I said **single session**. 

> it works fine, if you take care that the last plugin session will be the one receiving the calls.

This means you are using a pretty poor server which cannot do parallel forking. Otherwise you'd get your incoming calls on all plugin sessions at the same time.

I mitigated this by introducing the `send_register` parameter: https://github.com/meetecho/janus-gateway/commit/735be1e97aaf37d55b18c6ec504dd47ef1b7b54d That way you can create a new plugin session for each outgoing call without registering, but keep a single (registered) plugin handle for incoming calls. This, however, doesn't solve the problem when multiple calls are received on the registered plugin.

The "missed_call" event would at least let the user know that there was a call he couldn't get. @lminiero If you like the idea I can make a patch in the following days.

**Comment by kidandcat** [comment] 2015-08-25 15:32
Thanks! I think i got the call only on the last plugin because i instatiated Janus and registered all plugin sessions with the same user. (or maybe for the 2€ vps)

**Comment by lminiero** [comment] 2015-08-25 15:33
This is an interesting idea, an event that users might definitely take advantage of. No need for a patch, I can take care of this while I work on a better fix for this issue. Right now, I'm investigating the involved ```nua_handle_t``` for the purpose: looking at the docs, the call you're in and the INVITE you just received should have different ```nua_handle_t``` pointers, as they're different sessions, so checking the values there should make it easier to discriminate.

**Comment by saghul** [comment] 2015-08-25 15:34
@lminiero yep, that sounds about right, thanks!

**Comment by saghul** [comment] 2015-08-25 15:39
> Thanks! I think i got the call only on the last plugin because i instatiated Janus and registered all plugin sessions with the same user. (or maybe for the 2€ vps)

@kidandcat In SIP you can register multiple contacts for a single Address of Record (user@domain). Then when that user is called the server will "fork" the call so all registered endpoints ring and the user can pick it wherever. Now, some notable SIP PBXs (I'm looking at you, Asterisk) don't do this and just take the last registered device.

PS: Latest versions of Asterisk can do parallel forking, but IIRC it needs specific configuration.

**Comment by kidandcat** [comment] 2015-08-25 15:42
@saghul  Oh, didn't know that asterisk face, thanks for the tip!

**Closed** 2015-08-25 15:44 UTC

**Comment by lminiero** [comment] 2015-08-25 15:55
Ok, this should be a much better fix for the issue. I also added the missed_call event, which looks something like this:

```
{
   "sip": "event",
   "result": {
      "event": "missed_call",
      "caller": "sip:laptop@192.168.1.64"
   }
}
```

I also added a handler for ```registration_failed``` which was missing in the SIP web demo (I guess we never fixed that when we changed the way registration errors are notified). Let me know if this doesn't work as expected for you.

**Comment by kidandcat** [comment] 2015-08-25 15:57
Thanks you very much!

El martes, 25 de agosto de 2015, Lorenzo Miniero <notifications@github.com>
escribió:

> Ok, this should be a much better fix for the issue. I also added the
> missed_call event, which looks something like this:
>
> {
>    "sip": "event",
>    "result": {
>       "event": "missed_call",
>       "caller": "sip:laptop@192.168.1.64 <javascript:_e(%7B%7D,'cvml','sip:laptop@192.168.1.64');>"
>    }
> }
>
> I also added a handler for registration_failed which was missing in the
> SIP web demo (I guess we never fixed that when we changed the way
> registration errors are notified). Let me know if this doesn't work as
> expected for you.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/meetecho/janus-gateway/issues/312#issuecomment-134645455>
> .
>


-- 
Gracias,
Jairo Caro-Accino Viciana.
