### ISSUE TITLE
Videocall plugin: Renegotiation not working correctly

### ISSUE THREAD

**Issue by dnish** [meetecho/janus-gateway#1592] opened 2019-04-17 21:11 UTC
I'm establishing a connection between an iPhone with iOS 12.2 and Google Chrome on MacOS. Everythings works finde until I request a renegotiation on the iPhone. This is what happens when I click on the "switch camera" button:

```
async switchCamera() {

        cameraHelper.switchCamera();

        this.videoCall.createOffer({

            media: {
                video: {
                    facingMode: cameraHelper.facingMode
                },
                replaceVideo: true
            },

            success: (jsep) => {
                this.videoCall.send({message: {request:"set"}, "jsep": jsep});
            },

  
        });  
    }
```

The local video source changes and I see the content from the rear camera. But after calling this function, all remote streams are stopped - <code>onremotestream</code> isn't fired again.  

Within my <code>onmessage</code> handler, I have the following code:

```
   case 'update':
                                                if(jsep.type === "answer") {
                                                    this.videoCall.handleRemoteJsep({jsep: jsep});
                                                } else {
                                                    this.videoCall.createAnswer(
                                                        {
                                                            jsep: jsep,
                                                            media: { video: true, audio:true},
                                                            success: (jsep) => {
                                                               this.videoCall.send({"message": {request:"set"}, "jsep": jsep});
                                                            },

                                                        });
                                                }
```

If I do the renegotiation on the Mac, everything works fine. The streams get paused for a second, after that, both remote streams are starting again. Any idea what goes wrong?

**Comment by lminiero** [comment] 2019-04-18 09:22
If it works fine on the Mac, it means we're doing the right thing, and the issue is very likely in iOS or the way the JSEP API is used there.

**Comment by dnish** [comment] 2019-04-18 09:25
@lminiero Yeah, on another project we are using simple-peer, and there renegotiation also works on iOS. I'll post some logs what happens when I negotiate again, maybe someone can see why both remote streams stop.

**Comment by lminiero** [comment] 2019-04-18 09:26
You should share the SDPs instead: original offer/answer, and subsequent offer/answer. Not pasted here, of course, but on services like gist/pastebin.

**Comment by dnish** [comment] 2019-04-18 10:22
@lminiero Yeah, I will do this this evening. I can confirm that the issue also exists on Safari (MacOS). After renegotiation, both remote streams stop, but local streams are still working fine.

**Comment by dnish** [comment] 2019-04-18 11:29
This is what I get in Safari after renegotiation:

https://gist.github.com/dnish/ae5e30cde398fb25120a894959bf293f


and Chrome shows the following information within the logs:

https://gist.github.com/dnish/6a5e3bddaba113ec8186e0a24767148e

**Comment by lminiero** [comment] 2019-04-18 11:43
I'll wait for the SDPs, no time to look at big logs now sorry.

**Comment by dnish** [comment] 2019-04-18 13:42
Okay,
this are the SDP logs I get within Safari:

https://gist.github.com/dnish/04b879f29782fdd08ab340dd6bb7899c

and here comes Chrome:

https://gist.github.com/dnish/27d1f4932481c61cd874fd6b63ac4daf

I've noticed that after wating some time (about a minute), the remote stream on Safari starts working again - but on Chrome it doesn't start again.

**Comment by lminiero** [comment] 2019-04-18 13:55
I need the original offer/answer as well, not just the renegotiation, to see if there's anything different in the second round.

**Comment by dnish** [comment] 2019-04-18 14:47
Ohh okay, hope this will help you:

Safari: https://gist.github.com/dnish/b621efe016f5f67b6989e8ea2834b6da
Chrome: https://gist.github.com/dnish/bf06da8f622347b3db53099bc54d895a

**Comment by lminiero** [comment] 2019-04-23 10:37
I don't think the "switch camera" feature you added is doing its job. In the renegotiation, the offer has `recvonly` video, which means you're telling your peer that from now on you won't send any video, but only receive it, which is why video is `sendonly` in the answer. As such, it's normal that your video disappears in the session after that.

**Comment by dnish** [comment] 2019-04-23 10:47
@lminiero But I don't have anything in the code which changes the offer to <code>recvonly</code>. Also Chrome to Chrome is working fine after renegotiation. I've also recognized that renegotiation on simple-peer also stopped working since iOS 12.2 (still works on 12.1). So probably it's an issue with Safari.

**Comment by lminiero** [comment] 2019-05-01 13:49
Whatever your client side code is doing, it's changing the direction to `recvonly`, so the way Janus reacts is the proper way to handle that. As such, it's a fix you should do on the client side instead. Closing as not a Janus issue.

**Closed by lminiero** 2019-05-01 13:49 UTC
