### ISSUE TITLE
Missing audio from receiver using SIP plugin and early media.

### ISSUE THREAD

**Issue by shalseth** [meetecho/janus-gateway#2646] opened 2021-04-22 14:02 UTC
First of all, thanks for the great work on Janus!

We have noticed and made a (probably horrible) fix for an issue we experienced after upgrading our old Janus based on 0.2.6 to current master, commit ebd34414a2e3f4a31c7c8c80481c02325e9a9953.

When placing a call between two Janus clients connected with the SIP plugin to an Asterisk server, we noticed that if Asterisk played early media ring tones, the first few seconds of audio from the receiver could not be heard by the caller.
Disabling early media on Asterisk resolves the issue, but is not a solution for us.

We isolated the commit that caused the problem, and that is commit 77bcaa7 from Dec 05, 2017.
To be more exact, the call to janus_rtp_header_update() in ice.c:
```
/* Backup the RTP header before passing it to the proper RTP switching context */
janus_rtp_header backup = *header;
if(!video) {
	if(stream->audio_ssrc_peer_orig == 0)
		stream->audio_ssrc_peer_orig = packet_ssrc;
		//janus_rtp_header_update(header, &stream->rtp_ctx[0], FALSE, 0);
		header->ssrc = htonl(stream->audio_ssrc_peer_orig);
	} else {
		JANUS_LOG(LOG_ERR,"ITX: Video stream handling - should not happen");
		if(stream->video_ssrc_peer_orig[vindex] == 0)
			stream->video_ssrc_peer_orig[vindex] = packet_ssrc;
		janus_rtp_header_update(header, &stream->rtp_ctx[vindex], TRUE, 0);
		header->ssrc = htonl(stream->video_ssrc_peer_orig[vindex]);
	}
				
```

From my logs I see that during a call with current Janus master, Audio SSRC change is triggered twice for both early media, and the stream that start after the call has been answered. The call to janus_rtp_header_update comes from janus_sip.c and ice.c.
Log from current master. Only modified log output to WARN to watch the calls to janus_rtp_header_update:

Apr 22 13:55:43 janus03-dev janus[76177]: [856185921625617] Creating ICE agent (ICE Full mode, controlled)
Apr 22 13:55:44 janus03-dev janus[76177]: [1564598416029153] Creating ICE agent (ICE Full mode, controlling)
**Apr 22 13:55:44 janus03-dev janus[76177]: [WARN] Audio SSRC changed, 0 --> 1339874220**
Apr 22 13:55:44 janus03-dev janus[76177]: [856185921625617] The DTLS handshake has been completed
Apr 22 13:55:44 janus03-dev janus[76177]: [janus.plugin.sip-0x7fd7e4013410] WebRTC media is now available
**Apr 22 13:55:44 janus03-dev janus[76177]: [WARN] Audio SSRC changed, 0 --> 2687114450**
Apr 22 13:55:46 janus03-dev janus[76177]: [WARN] [1564598416029153] Failed to add some remote candidates (added 0, expected 1)
Apr 22 13:55:46 janus03-dev janus[76177]: [1564598416029153] The DTLS handshake has been completed
Apr 22 13:55:46 janus03-dev janus[76177]: [janus.plugin.sip-0x7fd7e400afa0] WebRTC media is now available
---- Call is answered, start of actual audio stream, and end of early media. 
**Apr 22 13:55:46 janus03-dev janus[76177]: [WARN] Audio SSRC changed, 0 --> 2750142728
Apr 22 13:55:46 janus03-dev janus[76177]: [WARN] Audio SSRC changed, 0 --> 184131489**
Apr 22 13:55:50 janus03-dev janus[76177]: [janus.plugin.sip-0x7fd7e400afa0] No WebRTC media anymore
Apr 22 13:55:50 janus03-dev janus[76177]: [1564598416029153] WebRTC resources freed; 0x7fd7f4002de0 0x7fd7f40025a0
Apr 22 13:55:50 janus03-dev janus[76177]: [janus.plugin.sip-0x7fd7e4013410] No WebRTC media anymore
Apr 22 13:55:50 janus03-dev janus[76177]: [856185921625617] WebRTC resources freed; 0x7fd7f4006ee0 0x7fd7f40063a0

To quick fix this we just commented out the janus_rtp_header_update from ice.c. 
This causes janus_rtp_header_update to only be triggered from sip_plugin.c, and it solves the issue. 
I don't understand the inner working enough to explain why, but it definitely works. 
Here is the log output with the change applied:

Apr 22 13:59:18 janus03-dev janus[76314]: Creating new session: 5944134911839832; 0x7ff3b0007a20
Apr 22 13:59:18 janus03-dev janus[76314]: Creating new handle in session 5944134911839832: 4342277631473375; 0x7ff3b0007a20 0x7ff3b0007b00
Apr 22 13:59:19 janus03-dev janus[76314]: [4342277631473375] Creating ICE agent (ICE Full mode, controlled)
Apr 22 13:59:20 janus03-dev janus[76314]: [7135419827506557] Creating ICE agent (ICE Full mode, controlling)
**Apr 22 13:59:20 janus03-dev janus[76314]: [WARN] Audio SSRC changed, 0 --> 608678559**
Apr 22 13:59:20 janus03-dev janus[76314]: [4342277631473375] The DTLS handshake has been completed
Apr 22 13:59:20 janus03-dev janus[76314]: [janus.plugin.sip-0x7ff3a4011220] WebRTC media is now available
Apr 22 13:59:22 janus03-dev janus[76314]: [7135419827506557] The DTLS handshake has been completed
Apr 22 13:59:22 janus03-dev janus[76314]: [janus.plugin.sip-0x7ff3a400ae40] WebRTC media is now available
**Apr 22 13:59:22 janus03-dev janus[76314]: [WARN] Audio SSRC changed, 0 --> 221113772**
Apr 22 13:59:24 janus03-dev janus[76314]: [janus.plugin.sip-0x7ff3a400ae40] No WebRTC media anymore
Apr 22 13:59:24 janus03-dev janus[76314]: [7135419827506557] WebRTC resources freed; 0x7ff3b0006ee0 0x7ff3b00063a0
Apr 22 13:59:24 janus03-dev janus[76314]: [janus.plugin.sip-0x7ff3a4011220] No WebRTC media anymore
Apr 22 13:59:24 janus03-dev janus[76314]: [4342277631473375] WebRTC resources freed; 0x7ff3b0007b00 0x7ff3b0007a20

If you understand what is going on, and can provide a proper fix it would be great.
I'm sure our "fix" breaks a lot of others things, but our use case for Janus is WebRTC and SIP only so seems to work for us.

**Comment by lminiero** [comment] 2021-04-22 14:15
> To quick fix this we just commented out the janus_rtp_header_update from ice.c.

Very bad idea. The core needs to fix RTP headers, because what plugins may generate is incorrect, or related to different SSRCs. As such, not sure what issue you're experiencing (and if it still happens with master, since you mention 0.2.6), but that's definitely not the right solution.

**Comment by shalseth** [comment] 2021-04-22 14:23
I understand, we did this "fix" to reverse the commit that introduced the problem in the first place and verified that it solved the problem we were experiencing. 
I was positive it was not the right approach, though not sure what would be.

**Comment by shalseth** [comment] 2021-04-22 14:25
And the issue is experienced with master, yes. This issue is not present with 0.2.6, before the commit 77bcaa7f0de6cf681ea6fbdb4e55e4b02dfddd0b

**Comment by lminiero** [comment] 2021-04-22 14:31
If you can provide a way to help us replicate this (e.g., via a SIPp script + pcap file) that would help, as we don't have SIP servers to test against, and setting up some would take time we unfortunately don't currently have.

**Comment by shalseth** [comment] 2021-04-22 14:51
I'm not sure how easy it is to replicate using other tools, but we _could_ provide you with two SIP accounts for testing on one of our Asterisk servers. 

You would have to set up two Janus.js clients for a Janus instance, and each client would connect to a SIP account we provide.

To replicate, start a call between them. 
The caller will first hear the ringing sound (early media) and when switching to the actual call, the first few seconds disappear. 
If the recipient does not answer fast enough, the issue is not present. For testing we answered after about a second.

So the case is basically you answer in about a second, say hello, and caller doesn't hear the hello. 

Understand the time constraints, but we can arrange this if you feel like it's a priority.

**Comment by lminiero** [comment] 2021-04-22 15:57
No thanks, I'd rather replicate issues locally, also considering that it is indeed quite low priority IMHO. If you can't replicate via SIPp, then please provide a pcap with the SIP/RTP traffic of an affected call, and we'll have a look.

**Comment by shalseth** [comment] 2021-04-22 18:01
I have sent a pcap by email, thanks!

**Comment by lminiero** [comment] 2021-04-26 10:49
I don't see SSRC changes, so one ore more RTP contexts shouldn't matter. I do see something broken in the RTP stream, though, as after a couple of seconds (the tone sound, I guess) the SSRC remains the same and the sequence number increases as expected, while the timestamp goes back to 0 with the marker bit set. That's not proper RTP, and in fact even Wireshark says it's an "incorrect timestamp" when you debug via its Telephony Tools.

Have you checked if you have SRTP errors on the Janus logs? If so, that might explain why you don't hear anything initially, as those broken timestamps may be causing SRTP errors (encoding a packet with the same header twice in a short amount of time).

Anyway, I'll see if I can feed that pcap to Janus somehow, to try and replicate locally as well.

**Comment by lminiero** [comment] 2021-04-26 13:53
> To be more exact, the call to janus_rtp_header_update() in ice.c:

Just re-read your initial report, and I don't think it makes sense. The line you commented out applies to _incoming_ traffic, that is the one the browser sends _to Janus_: it has nothing to do with the media the SIP plugin receives from Asterisk and sends back to the browser. The fact you see the SSRC changing twice is normal: that's because it's tracking two different directions. No idea why it should make the scenario work for you, but they're definitely not related.

**Comment by lminiero** [comment] 2021-04-26 14:18
I managed to replicate the issue, and early media has nothing to do with it: with that pcap, it happens even if SIPp just answers a regular call and starts sending those packets. There's just a single RTP header context working, the one in the plugin, and in fact the work I see being done in the plugin, e.g.:

	[WARN] [SIP] 12704 / 23680 --> 148 / 23520
	[WARN] [SIP] 12705 / 23840 --> 149 / 23680
	[WARN] [SIP] 12706 / 0 --> 150 / 4294967136
	[WARN] [SIP] 12707 / 160 --> 151 / 0
	[WARN] [SIP] 12708 / 320 --> 152 / 160

is reflected exactly in the SRTP packets I see sent by Janus to the browser. We're updating packets as we should (since the source is going "back in time" with timestamps, we do the same), and I can confirm there's no SRTP error: it's the browser that doesn't like that incorrect series of timestamps for some reason, and so doesn't play them. Even dropping the packet we rewrite as `4294967136` (and so restarting from `0` as Asterisk does) fails: the browser apparently takes some time to decide it's still a valid flow, probably waiting for the timestamp in the new stream to go beyond the `23680` it received before the change (which happens 2-3 seconds later, so inline with the "we don't hear the first 4 digits" experience). 

As such, I don't think there's any issue in Janus. This sounds like an issue in Asterisk, which should not restart timestamps from 0 while keeping SSRC and sequence numbers as they should. Closing.

**Closed by lminiero** 2021-04-26 14:18 UTC

**Comment by shalseth** [comment] 2021-04-26 14:41
> > To be more exact, the call to janus_rtp_header_update() in ice.c:
> 
> Just re-read your initial report, and I don't think it makes sense. The line you commented out applies to _incoming_ traffic, that is the one the browser sends _to Janus_: it has nothing to do with the media the SIP plugin receives from Asterisk and sends back to the browser. The fact you see the SSRC changing twice is normal: that's because it's tracking two different directions. No idea why it should make the scenario work for you, but they're definitely not related.

It makes sense because Janus is active in both ends. 
The fix works when the _recipient's_ Janus is patched. The stream you see in the pcap comes from the recipient's Janus(browser to Janus), from Janus to Asterisk, and finally from Asterisk to the callers Janus instance where we have the pcap.
The problem is at the receiver's end, not the caller's, so that's where we apply the patch which solves the issue for us.

**Comment by shalseth** [comment] 2021-04-26 14:46
> I managed to replicate the issue, and early media has nothing to do with it: with that pcap, it happens even if SIPp just answers a regular call and starts sending those packets. There's just a single RTP header context working, the one in the plugin, and in fact the work I see being done in the plugin, e.g.:
> 
> ```
> [WARN] [SIP] 12704 / 23680 --> 148 / 23520
> [WARN] [SIP] 12705 / 23840 --> 149 / 23680
> [WARN] [SIP] 12706 / 0 --> 150 / 4294967136
> [WARN] [SIP] 12707 / 160 --> 151 / 0
> [WARN] [SIP] 12708 / 320 --> 152 / 160
> ```
> 
> is reflected exactly in the SRTP packets I see sent by Janus to the browser. We're updating packets as we should (since the source is going "back in time" with timestamps, we do the same), and I can confirm there's no SRTP error: it's the browser that doesn't like that incorrect series of timestamps for some reason, and so doesn't play them. Even dropping the packet we rewrite as `4294967136` (and so restarting from `0` as Asterisk does) fails: the browser apparently takes some time to decide it's still a valid flow, probably waiting for the timestamp in the new stream to go beyond the `23680` it received before the change (which happens 2-3 seconds later, so in line with the "we don't hear the first 4 digits" experience).
> 
> As such, I don't think there's any issue in Janus. This sounds like an issue in Asterisk, which should not restart timestamps from 0 while keeping SSRC and sequence numbers as they should. Closing.

Thanks for the thorough analysis. Your explanation makes sense, and possibly there's a bug in Asterisk, however we do not experience it with Janus 0.2.6 or with the change in ice.c explained in the initial report. 

We will soon update Asterisk to a new version, and maybe that will also fix the issue, and we can remove the patch.

**Comment by lminiero** [comment] 2021-04-26 14:47
No, because the code you commented out is RTP coming in on the WebRTC side, not on the Asterisk side: it's what we do for media coming from a browser. The pcap you show is Asterisk sending media to Janus, and that RTP traffic is broken: even commenting out the header update in the SIP plugin (which means we don't touch the header at all), the browser does the same, which means it's the traffc Asterisk is generating that the browser doesn't like.

**Comment by shalseth** [comment] 2021-04-26 14:50
> No, because the code you commented out is RTP coming in on the WebRTC side, not on the Asterisk side: it's what we do for media coming from a browser. The pcap you show is Asterisk sending media to Janus on the SIP plugin side, and that RTP traffic is broken: even commenting out the header update in the SIP plugin (which means we don't touch the header at all), the browser does the same, which means it's the traffc Asterisk is generating that the browser doesn't like.

You're almost correct, but remember that you're watching the dump from the caller's Janus instance. You're not seeing the dump for the receiver Janus instance, where we apply the patch to ice.c (another machine). On the receiver the change matters because it's the RTP stream that you in turn see in the pcap (after going through asterisk)

**Comment by shalseth** [comment] 2021-04-26 14:54
The fact that you identify a problem with the RTP stream coming from Asterisk is interesting, because Janus is the source of that stream, and our fix somehow resolves that RTP stream issue. I'm not sure what Asterisk does to the stream or not, but at least the change to only the receiver Janus fixes the audio delay.

**Comment by shalseth** [comment] 2021-04-26 15:09
I have now sent you the pcap from the call receiver's Janus node, if you want to take a look at the RTP stream thas Janus send to Asterisk, and compare that with what you see in the first dump. Then you should be able to tell if Asterisk or  Janus is doing something wrong with the RTP stream.

**Comment by shalseth** [comment] 2021-04-27 09:53
The issue is closed, so not sure if you're watching, but I would like to conclude that unless you find something wrong with the RTP stream from Janus to Asterisk in the latest pcap, the problem is with Asterisk and the combination of the RTP stream from Janus and Asterisk' early media generation. 

I will proceed with testing latest version of Asterisk, and if the issue is present there as well, report the problem to Asterisk developers.

If Janus master is working with latest Asterisk, I will add a new comment here to document my findings.

Thanks for the great work on Janus.

**Comment by lminiero** [comment] 2021-04-27 13:05
> unless you find something wrong with the RTP stream from Janus to Asterisk in the latest pcap

There's nothing wrong in the stream Janus is sending: it just starts from seq=1 and ts=0, rather than random values. Wireshark is perfectly happy with it as well, and can decode/play it.

**Comment by shalseth** [comment] 2021-04-27 14:20
Ok, great, then Asterisk is doing something wrong with the stream. Thanks a lot for your help!

**Comment by shalseth** [comment] 2021-04-30 09:56
A quick update here. We tried this in Asterisk 16 and found that proper RTP is generated by changing the SSRC when switching from early media to the RTP stream from Janus. 
So Asterisk 16 works with current Janus master without any changes.

Problem we experienced and reported was detected in Asterisk 1.8.28.

**Comment by lminiero** [comment] 2021-04-30 09:59
Yes, that's because an SSRC change triggers the RTP rewriting mechanism in Janus, which ensures a consistent flow as far as the recipient is concerned. In fact the issue was that your version of Asterisk was restarting timestamps but keeping the SSRC the same. Good to know it was fixed by the update then!
