### ISSUE TITLE
[0.x] Simulcast broken when data channels are used

### ISSUE THREAD

**Issue by danxuliu** [meetecho/janus-gateway#2992] opened 2022-06-02 10:41 UTC
This is a regression introduced in e111be27 and still present in latest 0.x branch (I have not tested master branch).

rids are reset [when processing the m-lines](https://github.com/meetecho/janus-gateway/blob/e111be2796fed4cc3734b4bab3a5f8bdb6189334/sdp.c#L160-L163). However, if data channels are enabled the SDP can include an _m-line_ for data channels after the _m-line_ for video. When that happens the rids set when processing the _m-line_ for video are reset when processing the _m-line_ for data channels, and `janus_sdp_process` ends as if simulcast was not offered.

This can be reproduced with Firefox and Chromium (Firefox 101 and Chromium 95, I have not tested other versions) in any combination (Firefox <-> Firefox, Chromium <->Chromium or Firefox <-> Chromium).

## How to reproduce

- Copy [_janus.js_, _settings.js_, _videoroomtest.html_ and _videoroomtest.js_](https://github.com/meetecho/janus-gateway/tree/c773796aa23cb95f5e084bce807ca9ac0c694962/html) to a directory of the web server
- Modify _videoroomtest.js_ to [enable data channels for the publisher](https://github.com/meetecho/janus-gateway/blob/c773796aa23cb95f5e084bce807ca9ac0c694962/html/videoroomtest.js#L373)
- Copy the default ([sample files](https://github.com/meetecho/janus-gateway/tree/c773796aa23cb95f5e084bce807ca9ac0c694962/conf)) for _janus.plugin.videoroom.jcfg_ and _janus.transport.http.jcfg_ in a directory
- Start Janus using that directory (`janus --configs-folder=...`)
- Start the video room test in a browser enabling simulcast (for example, _https://127.0.0.1/videoroomtest.html?simulcast=true_)
- In a private window or another browser join the test

### Expected result

The remote videos show simulcast options

### Actual result

The remote videos do not show simulcast options. The SDP answers sent by Janus to the publishers do not contain rid or simulcast attributes.

# Frozen video once packets are lost

Please note that this is not the same as #2981. That issue started in a different commit, and it can be reproduced without data channels nor simulcast.

I guess this is just a side-effect of the problem described above, but maybe there is something else, I do not know :-)

## How to reproduce

In a Linux kernel packet lost can be simulated using [netem](https://wiki.linuxfoundation.org/networking/netem). It applies certain conditions to the outgoing traffic (but it can be done too for incoming traffic with additional commands) of specific network interfaces. In my case I tested this with two virtual machines, one running Janus and one browser, and another running another browser, and applying the packet loss to the network interface of the second virtual machine that is connected to an internal network with the first virtual machine.

- Copy [_janus.js_, _settings.js_, _videoroomtest.html_ and _videoroomtest.js_](https://github.com/meetecho/janus-gateway/tree/c773796aa23cb95f5e084bce807ca9ac0c694962/html) to a directory of the web server
- Modify _videoroomtest.js_ to [enable data channels for the publisher](https://github.com/meetecho/janus-gateway/blob/c773796aa23cb95f5e084bce807ca9ac0c694962/html/videoroomtest.js#L373)
- Copy the default ([sample files](https://github.com/meetecho/janus-gateway/tree/c773796aa23cb95f5e084bce807ca9ac0c694962/conf)) for _janus.plugin.videoroom.jcfg_ and _janus.transport.http.jcfg_ in a directory
  - In order to test from a different machine I had to enable HTTPS, but it should not make any difference
- Start Janus using that directory (`janus --configs-folder=...`)
- Start the video room test in browser A running in the same machine as Janus enabling simulcast (for example, _https://192.168.57.21/videoroomtest.html?simulcast=true_)
- In browser B, running in a different machine, join the video room test also enabling simulcast
- In the machine were browser B is running apply a packet loss and then revert it:
`tc qdisc add dev {THE_NETWORK_INTERFACE} root netem loss 20%`
`tc qdisc change dev {THE_NETWORK_INTERFACE} root netem loss 0%`

### Expected result

In browser A the remote video from browser B does not freeze

### Actual result

In browser A the remote video from browser B (the one running in the machine where the packets were lost) freezes. If the test is left and joined again in browser A the video is still frozen.

Browser A receives video packets, although it does not decode anything.

Janus logs show the following when the publisher joins (both in e111be27 and latest 0.x):
```
[WARN] [7970906737858631] Peer video fallback SSRC: XXXXXXXXXX
...
[WARN] [7970906737858631] Not video and not audio? dropping (SSRC YYYYYYYYYY)...
...
```
Eventually the connection is stable and no more messages are printed. But once packets are lost the following is printed, and the message is repeated forever until the publisher leaves, no matter if the packet lost has ended:
```
[WARN] [7970906737858631] Big sequence number jump 39416 -> 28297 (video stream #0)
[WARN] [7970906737858631] Not video and not audio? dropping (SSRC XXXXXXXXXX)...
[WARN] [7970906737858631] Not video and not audio? dropping (SSRC XXXXXXXXXX)...
[WARN] [7970906737858631] Not video and not audio? dropping (SSRC XXXXXXXXXX)...
...
```
where XXXXXXXXXX and YYYYYYYYYY come from the offer SDP:
```
a=ssrc:XXXXXXXXXX cname:{275541ed-8ae0-4c51-bfe8-56512d5cf7b4}
a=ssrc:YYYYYYYYYY cname:{275541ed-8ae0-4c51-bfe8-56512d5cf7b4}
...
a=ssrc-group:FID XXXXXXXXXX YYYYYYYYYY
```

**Comment by lminiero** [comment] 2022-06-03 10:18
Is this two issues or one? I see a "Frozen video once packets are lost" that seems completely unrelated to the Simulcast issue you mentioned. If so, please open a different issue for the other problem, as I'll close this one once simulcast is addressed.

**Comment by lminiero** [comment] 2022-06-03 10:32
Ok, managed to replicate the issue with the EchoTest. The problem is not datachannels, but any m-line that is negotiated after the video m-line, which means it can also happen when video comes before audio in the SDP for instance. I just prepared a patch that seems to fix the problem for me, where I only process/update simulcast if we're processing a video m-line, and that I'll push shortly. I found a potentially similar problem for SSRCs, as we're resetting all of them as well independently of the m-line we're processing right now (which means that audio SSRCs might be forgotten as soon as we move to video, for instance); this goes unnoticed since Janus can detect SSRCs out of the mid RTP extension, but it was still a good idea not to reset those either.

As a side note, this only happens on `0.x`, since in multistream negotiation works on independent and separate `medium` instances, while in `0.x` most properties are stored in the shared `stream` object.

**Closed** 2022-06-03 10:33 UTC
Labels: legacy

**Comment by danxuliu** [comment] 2022-06-03 11:55
> Is this two issues or one? I see a "Frozen video once packets are lost" that seems completely unrelated to the Simulcast issue you mentioned. If so, please open a different issue for the other problem, as I'll close this one once simulcast is addressed.

As mentioned the frozen video issue seemed to be a side effect of clearing the rids, as it started in the same commit and happened only when simulcast and data channels were enabled, just like the main issue. Sorry if it was not clear enough in the description.

Anyway, I have tested your patch and it fixes the simulcast and frozen video issues for me as well. Thanks!

**Comment by lminiero** [comment] 2022-06-03 11:55
Excellent, thanks for the feedback!
