### ISSUE TITLE
Publish/Unpublish video issue

### ISSUE THREAD

**Issue by idubinets** [meetecho/janus-gateway#425] opened 2015-12-16 13:19 UTC
![publish_unpublish_video_issue](https://cloud.githubusercontent.com/assets/2304959/11841686/01422646-a410-11e5-8fa5-25043a3b7068.png)

I started video room testing and faced some other annoyed issue.
If you will quickly publish/unpublish video, the feature will become broken.

The steps:
1. connect to the video room in browser A (FireFox)
2. unpublish the video
3. connect to the video room in browser B (Chrome)
4. unpublish video
5. publish it and quickly unpublish again.
you will see the error like in the screen above

**Comment by lminiero** [comment] 2015-12-16 13:23
That's caused by the garbage collection mechanism we have for the WebRTC stuff in the handle. That will hopefully be fixed when we complete our work on reference counters. As of now, you have to wait about a second before you can try again.

**Comment by idubinets** [comment] 2015-12-16 13:29
yes, I have noticed that

maybe you have to introduce new event, like "processing"

1. unpublish
2. processing
3. unpublished

this way the UI could be updated accordingly

**Comment by lminiero** [comment] 2015-12-16 13:44
The problem here is that it's not a plugin limitation, it's a core one. As far as the plugin is concerned, it's unpublished when you unpublish. So no plugin-related event can help here, you'll just have to make sure the UI cannot be invoked immediately after, but wait a bit before you can make it act again. A bit of a workaround, but would help. I think we have a core-level "hangup" event, but it tells you about when the PC is over, not when you can open one again. More or less a second should be a good indication, as that's the amount of time we wait before freeing resources in the ICE loop.

**Comment by lminiero** [comment] 2016-02-02 12:00
More info in #452, closing this.

**Closed by lminiero** 2016-02-02 12:00 UTC
