### ISSUE TITLE
Janus crashes randomly when one of the participant leaves

### ISSUE THREAD

**Issue by Jeevhi** [meetecho/janus-gateway#2110] opened 2020-04-27 11:43 UTC
```
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x0000000000446710 in janus_plugin_relay_rtp (plugin_session=0x2273756e616a227b, packet=0x7ff11e3d2130) 
2058		if((plugin_session < (janus_plugin_session *)0x1000) || g_atomic_int_get(&plugin_session->stopped) ||
[Current thread is 1 (Thread 0x7ff11e3e3700 (LWP 22193))]
Missing separate debuginfos, use: dnf debuginfo-install brotli-1.0.6-1.el8.x86_64 cyrus-sasl-lib-2.1.27-0.3rc7.el8.x86_64 glib2-2.56.4-7.el8.x86_64 glibc-2.28-72.el8_1.1.x86_64 gmp-6.1.2-10.el8.x86_64 gnutls-3.6.8-8.el8.x86_64 gupnp-1.0.3-2.el8.x86_64 gupnp-igd-0.2.5-4.el8.x86_64 jansson-2.11-3.el8.x86_64 keyutils-libs-1.5.10-6.el8.x86_64 krb5-libs-1.16.1-22.el8.x86_64 libblkid-2.32.1-17.el8.x86_64 libcom_err-1.44.3-2.el8.x86_64 libconfig-1.5-9.el8.x86_64 libcurl-7.61.1-11.el8.x86_64 libffi-3.1-18.el8.x86_64 libgcc-8.3.1-4.5.el8.x86_64 libidn2-2.0.5-1.el8.x86_64 libmicrohttpd-0.9.59-2.el8.x86_64 libmount-2.32.1-17.el8.x86_64 libnghttp2-1.33.0-1.el8.x86_64 libnice-0.1.14-7.20180504git34d6044.el8.x86_64 libogg-1.3.2-10.el8.x86_64 libpsl-0.20.2-5.el8.x86_64 libselinux-2.8-6.el8.x86_64 libsoup-2.62.3-1.el8.x86_64 libssh-0.8.5-2.el8.x86_64 libtasn1-4.13-3.el8.x86_64 libunistring-0.9.9-3.el8.x86_64 libxml2-2.9.7-5.el8.x86_64 nettle-3.4.1-1.el8.x86_64 openldap-2.4.46-9.el8.x86_64 openssl-libs-1.1.1-8.el8.x86_64 opus-1.3-0.4.beta.el8.x86_64 p11-kit-0.23.14-5.el8_0.x86_64 pcre-8.42-4.el8.x86_64 pcre2-10.32-1.el8.x86_64 xz-libs-5.2.4-3.el8.x86_64 zlib-1.2.11-10.el8.x86_64
(gdb) bt
#0  0x0000000000446710 in janus_plugin_relay_rtp (plugin_session=0x2273756e616a227b, packet=0x7ff11e3d2130)
#1  0x00007ff1517bf813 in janus_videoroom_relay_rtp_packet (data=0x7ff138004600, user_data=0x7ff11e3d23b0)
#2  0x00007ff161533695 in g_slist_foreach () at /lib64/libglib-2.0.so.0
```

**Comment by lminiero** [comment] 2020-04-27 12:53
Duplicate of #2099 for which there's a pending fix already. Check existing issues before opening a new one.

**Closed by lminiero** 2020-04-27 12:53 UTC
