### ISSUE TITLE
Janus fails to generate API event when unsupported media proposed

### ISSUE THREAD

**Issue by adigeo** [meetecho/janus-gateway#1780] opened 2019-09-17 11:07 UTC
This is related to this failed attempt to fix handling invalid SDP in offer.

https://github.com/meetecho/janus-gateway/commit/a3de0812d036c07b6dc202fee609750a26d85286

The fix above just prevented Janus from crashing but did not generate an event.

The scenario below is client provided video + audio but the video codec is not supported by Janus. In such case the session should continue with audio and video m line should be rejected.

```
2019-09-17 12:21:52.866521 Packet 245286 OUTGOING, janus at tcp4:127.0.0.1:8188
{"janus": "attach", "transaction": "29a99847e5da1c4e4f2f7c6c0b328e61", "apisecret": "XXX", "session_id": 7966639571690102, "plugin": "janus.plugin.videoroom"}

2019-09-17 12:21:52.867803 Packet 245287 INCOMING, janus at tcp4:127.0.0.1:8188
{
   "janus": "success",
   "session_id": 7966639571690102,
   "transaction": "29a99847e5da1c4e4f2f7c6c0b328e61",
   "data": {
      "id": 8213455823191260
   }
}

2019-09-17 12:21:52.868267 Packet 245288 OUTGOING, janus at tcp4:127.0.0.1:8188
{"body": {"publishers": 10, "videocodec": "vp9", "room": 4057848974, "record": false, "request": "create", "rec_dir": "/var/spool/sylkserver/videoconference/recordings/muc@videoconference.sip2sip.info", "bitrate": 2016000}, "transaction": "14f1d6763797b3961b195
215055f5ad0", "handle_id": 8213455823191260, "apisecret": "XXX", "session_id": 7966639571690102, "janus": "message"}

2019-09-17 12:21:52.868865 Packet 245289 INCOMING, janus at tcp4:127.0.0.1:8188
{
   "janus": "success",
   "session_id": 7966639571690102,
   "transaction": "14f1d6763797b3961b195215055f5ad0",
   "sender": 8213455823191260,
   "plugindata": {
      "plugin": "janus.plugin.videoroom",
      "data": {
         "videoroom": "created",
         "room": 4057848974,
         "permanent": false
      }
   }
}

2019-09-17 12:21:52.869297 Packet 245290 OUTGOING, janus at tcp4:127.0.0.1:8188
{"body": {"request": "joinandconfigure", "audio": true, "video": true, "room": 4057848974, "ptype": "publisher"}, "transaction": "31a68b4419610909dd58d540c153e9d4", "handle_id": 8213455823191260, "apisecret": "XXX", "session_id": 7966639571690102, "janus": "message", "jsep": {"sdp": "v=0\r\no=- 7756025712069129405 2 IN IP4 127.0.0.1\r\ns=-\r\nt=0 0\r\na=msid-semantic: WMS 9cd32305-d88c-4b68-9dbb-15e0eebd41fb\r\na=group:BUNDLE audio video\r\nm=audio 9 UDP/TLS/RTP/SAVPF 111 103 9 102 0 8 105 13 110 113 126\r\nc=IN IP4 0.0.0.0\r\na=rtpmap:111 opus/48000/2\r\na=rtpmap:103 ISAC/16000\r\na=rtpmap:9 G722/8000\r\na=rtpmap:102 ILBC/8000\r\na=rtpmap:0 PCMU/8000\r\na=rtpmap:8 PCMA/8000\r\na=rtpmap:105 CN/16000\r\na=rtpmap:13 CN/8000\r\na=rtpmap:110 telephone-event/48000\r\na=rtpmap:113 telephone-event/16000\r\na=rtpmap:126 telephone-event/8000\r\na=fmtp:111 minptime=10;useinbandfec=1\r\na=rtcp:9 IN IP4 0.0.0.0\r\na=rtcp-fb:111 transport-cc\r\na=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level\r\na=setup:actpass\r\na=mid:audio\r\na=sendrecv\r\na=ice-ufrag:hew+\r\na=ice-pwd:R8WAGVx5pgBgzjUJtmULEW/5\r\na=fingerprint:sha-256 09:06:A7:5E:75:23:28:61:70:17:C5:E5:7E:8B:70:5A:BD:26:AC:C1:C9:EB:7F:19:D0:9D:F1:55:ED:2F:90:F7\r\na=ice-options:trickle\r\na=ssrc:1896294019 cname:bDSXo4bbg/UMHetd\r\na=ssrc:1896294019 msid:9cd32305-d88c-4b68-9dbb-15e0eebd41fb 473d550d-1704-442a-af1c-45dba3856a0d\r\na=ssrc:1896294019 mslabel:9cd32305-d88c-4b68-9dbb-15e0eebd41fb\r\na=ssrc:1896294019 label:473d550d-1704-442a-af1c-45dba3856a0d\r\na=rtcp-mux\r\nm=video 9 UDP/TLS/RTP/SAVPF 96 97 98 99 100 101 127 125 104\r\nc=IN IP4 0.0.0.0\r\na=rtpmap:96 H264/90000\r\na=rtpmap:97 rtx/90000\r\na=rtpmap:98 H264/90000\r\na=rtpmap:99 rtx/90000\r\na=rtpmap:100 VP8/90000\r\na=rtpmap:101 rtx/90000\r\na=rtpmap:127 red/90000\r\na=rtpmap:125 rtx/90000\r\na=rtpmap:104 ulpfec/90000\r\na=fmtp:96 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=640c1f\r\na=fmtp:97 apt=96\r\na=fmtp:98 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42e01f\r\na=fmtp:99 apt=98\r\na=fmtp:101 apt=100\r\na=fmtp:125 apt=127\r\na=rtcp:9 IN IP4 0.0.0.0\r\na=rtcp-fb:96 goog-remb\r\na=rtcp-fb:96 transport-cc\r\na=rtcp-fb:96 ccm fir\r\na=rtcp-fb:96 nack\r\na=rtcp-fb:96 nack pli\r\na=rtcp-fb:98 goog-remb\r\na=rtcp-fb:98 transport-cc\r\na=rtcp-fb:98 ccm fir\r\na=rtcp-fb:98 nack\r\na=rtcp-fb:98 nack pli\r\na=rtcp-fb:100 goog-remb\r\na=rtcp-fb:100 transport-cc\r\na=rtcp-fb:100 ccm fir\r\na=rtcp-fb:100 nack\r\na=rtcp-fb:100 nack pli\r\na=extmap:2 urn:ietf:params:rtp-hdrext:toffset\r\na=extmap:3 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time\r\na=extmap:4 urn:3gpp:video-orientation\r\na=extmap:5 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01\r\na=extmap:6 http://www.webrtc.org/experiments/rtp-hdrext/playout-delay\r\na=extmap:7 http://www.webrtc.org/experiments/rtp-hdrext/video-content-type\r\na=extmap:8 http://www.webrtc.org/experiments/rtp-hdrext/video-timing\r\na=extmap:10 http://tools.ietf.org/html/draft-ietf-avtext-framemarking-07\r\na=setup:actpass\r\na=mid:video\r\na=sendrecv\r\na=ice-ufrag:hew+\r\na=ice-pwd:R8WAGVx5pgBgzjUJtmULEW/5\r\na=fingerprint:sha-256 09:06:A7:5E:75:23:28:61:70:17:C5:E5:7E:8B:70:5A:BD:26:AC:C1:C9:EB:7F:19:D0:9D:F1:55:ED:2F:90:F7\r\na=ice-options:trickle\r\na=ssrc:2475400222 cname:bDSXo4bbg/UMHetd\r\na=ssrc:2475400222 msid:9cd32305-d88c-4b68-9dbb-15e0eebd41fb 6dc67b52-ac6a-4497-a65a-4681e328e1ac\r\na=ssrc:2475400222 mslabel:9cd32305-d88c-4b68-9dbb-15e0eebd41fb\r\na=ssrc:2475400222 label:6dc67b52-ac6a-4497-a65a-4681e328e1ac\r\na=ssrc:3410094110 cname:bDSXo4bbg/UMHetd\r\na=ssrc:3410094110 msid:9cd32305-d88c-4b68-9dbb-15e0eebd41fb 6dc67b52-ac6a-4497-a65a-4681e328e1ac\r\na=ssrc:3410094110 mslabel:9cd32305-d88c-4b68-9dbb-15e0eebd41fb\r\na=ssrc:3410094110 label:6dc67b52-ac6a-4497-a65a-4681e328e1ac\r\na=ssrc-group:FID 2475400222 3410094110\r\na=rtcp-mux\r\na=rtcp-rsize\r\n", "type": "offer"}}

2019-09-17 12:21:52.875327 Packet 245291 INCOMING, janus at tcp4:127.0.0.1:8188
{
   "janus": "ack",
   "session_id": 7966639571690102,
   "transaction": "31a68b4419610909dd58d540c153e9d4"
}

2019-09-17 12:21:52.876770 Packet 245292 OUTGOING, janus at tcp4:127.0.0.1:8188
{"transaction": "aa7786cda486e8f6d99f21c510397b6a", "candidate": {"sdpMid": "audio", "candidate": "candidate:1270274445 1 udp 2113937151 192.168.1.11 61489 typ host generation 0 ufrag hew+ network-cost 999", "sdpMLineIndex": 0}, "handle_id": 8213455823191260, "apisecret": "XXX", "session_id": 7966639571690102, "janus": "trickle"}

2019-09-17 12:21:52.877314 Packet 245293 INCOMING, janus at tcp4:127.0.0.1:8188
{
   "janus": "ack",
   "session_id": 7966639571690102,
   "transaction": "aa7786cda486e8f6d99f21c510397b6a"
}
```

**Comment by adigeo** [comment] 2019-09-17 11:16
Sep 17 12:22:43 node15 janus[28137]: Creating new handle in session 7966639571690102: 5154602556044453; 0x7f0f58008c50 0x7f0fa400ac10
Sep 17 12:22:43 node15 janus[28137]: [5154602556044453] Creating ICE agent (ICE Lite mode, controlled)
Sep 17 12:22:43 node15 janus[28137]: [ERR] [sdp-utils.c:janus_sdp_get_codec_pt:662] Unsupported codec 'none'
Sep 17 12:22:43 node15 janus[28137]: [WARN] Couldn't find codec we needed (none) in the offer, rejecting video
Sep 17 12:22:43 node15 janus[28137]: [ERR] [sdp-utils.c:janus_sdp_get_codec_rtpmap:763] Unsupported codec 'none'
Sep 17 12:22:43 node15 janus[28137]: [ERR] [sdp-utils.c:janus_sdp_parse:587] Invalid m= line (no payload types/formats): m=video 9 UDP/TLS/RTP/SAVPF
Sep 17 12:22:43 node15 janus[28137]: [ERR] [sdp.c:janus_sdp_preparse:40]   Error parsing SDP? Invalid m= line (no payload types/formats): m=video 9 UDP/TLS/RTP/SAVPF
Sep 17 12:22:43 node15 janus[28137]: [ERR] [janus.c:janus_plugin_handle_sdp:3152] [5154602556044453] Couldn't parse SDP... Invalid m= line (no payload types/formats): m=video 9 UDP/TLS/RTP/SAVPF
Sep 17 12:22:43 node15 janus[28137]: [ERR] [janus.c:janus_plugin_push_event:3075] [5154602556044453] Cannot push event (JSON error: problem with the SDP)
Sep 17 12:22:44 node15 janus[28137]: [WARN] [5154602556044453]     Missing valid SRTP session (packet arrived too early?), skipping...
Sep 17 12:22:44 node15 janus[28137]: [WARN] [5154602556044453]     Missing valid SRTP session (packet arrived too early?), skipping...
Sep 17 12:22:44 node15 janus[28137]: [WARN] [5154602556044453]     Missing valid SRTP session (packet arrived too early?), skipping...
Sep 17 12:22:50 node15 janus[28137]: Destroying session 2204805564591911; 0x7f0fa40021b0
Sep 17 12:22:50 node15 janus[28137]: Detaching handle from JANUS VideoRoom plugin; 0x7f0fa4002e10 0x7f0f58005c10 0x7f0fa4002e10 0x7f0fa4003fe0
Sep 17 12:22:50 node15 janus[28137]: [janus.plugin.videoroom-0x7f0f58005c10] No WebRTC media anymore; 0x7f0fa4002e10 0x7f0fa4003fe0
Sep 17 12:22:50 node15 janus[28137]: [2054791014330600] WebRTC resources freed; 0x7f0fa4002e10 0x7f0fa40021b0
Sep 17 12:22:50 node15 janus[28137]: [2054791014330600] Handle and related resources freed; 0x7f0fa4002e10 0x7f0fa40021b0
Sep 17 12:23:01 node15 janus[28137]: Detaching handle from JANUS VideoRoom plugin; 0x7f0fa400ac10 0x7f0f5800b5a0 0x7f0fa400ac10 0x7f0fa400ad50
Sep 17 12:23:01 node15 janus[28137]: [janus.plugin.videoroom-0x7f0f5800b5a0] No WebRTC media anymore; 0x7f0fa400ac10 0x7f0fa400ad50
Sep 17 12:23:01 node15 janus[28137]: [5154602556044453] WebRTC resources freed; 0x7f0fa400ac10 0x7f0f58008c50
Sep 17 12:23:01 node15 janus[28137]: [5154602556044453] Handle and related resources freed; 0x7f0fa400ac10 0x7f0f58008c50
Sep 17 12:23:01 node15 janus[28137]: Creating new handle in session 7966639571690102: 7397522929444846; 0x7f0f58008c50 0x7f0fa400ac10
Sep 17 12:23:01 node15 janus[28137]: Detaching handle from JANUS VideoRoom plugin; 0x7f0fa400ac10 0x7f0fa4004100 0x7f0fa400ac10 0x7f0fa400ad50
Sep 17 12:23:01 node15 janus[28137]: [janus.plugin.videoroom-0x7f0fa4004100] No WebRTC media anymore; 0x7f0fa400ac10 0x7f0fa400ad50
Sep 17 12:23:01 node15 janus[28137]: [7397522929444846] Handle and related resources freed; 0x7f0fa400ac10 0x7f0f58008c50

**Comment by adigeo** [comment] 2019-09-17 11:17
Sep 17 12:22:43 node15 janus[28137]: [ERR] [janus.c:janus_plugin_push_event:3075] [5154602556044453] **Cannot push event (JSON error: problem with the SDP)**

**Comment by lminiero** [comment] 2019-09-17 12:21
@adigeo next time please either post these snippets as gist/pastebin links, or in code blocks (I just edited them for you). Looking into this later.

**Comment by lminiero** [comment] 2019-09-18 13:58
I just tried having a VP8-only publisher try to publish in a H.264 only room, and negotiation works as expected, with the video m-line rejected:

    m=video 0 UDP/TLS/RTP/SAVPF 0

Are you sure you're on master, both the core and the plugin? I think @mirkobrankovic was experiencing the same issue, and it was fixed by upgrading.

**Comment by adigeo** [comment] 2019-09-18 14:04
The SDP is “fixed" alright with that patch (Janus does not crash anymore) but there is no event sent so the application has no idea that the call is rejected.

Sep 17 12:22:43 node15 janus[28137]: [ERR] [janus.c:janus_plugin_push_event:3075] [5154602556044453] Cannot push event (JSON error: problem with the SDP)

**Comment by lminiero** [comment] 2019-09-18 14:11
But that's the point: I *do* get the answer in my test, and the SDP is correct. That's why I'm wondering if you're actually using the latest stuff.

**Comment by lminiero** [comment] 2019-09-18 14:15
Maybe in your case the issue is not in the answer to the publisher's offer, but in the offer that is then sent to subscribers? Let me check...

**Comment by adigeo** [comment] 2019-09-18 14:21
We built the version from GitHub from yesterday. We called using Safari v12 to a VP9 only room. We pasted the api calls exchange in the ticket. There is a clear failure there, is the point where the application above janus should get something back but it gets nothing back from Janus and we see this in the logs at that point:

Sep 17 12:22:43 node15 janus[28137]: [ERR] [janus.c:janus_plugin_push_event:3075] [5154602556044453] Cannot push event (JSON error: problem with the SDP)

Adrian

**Comment by lminiero** [comment] 2019-09-18 14:42
Unfortunately I don't have access to a MacOS device, now, and both Firefox and Chrome negotiate all codecs, so I have no way to test that specific scenario. I was testing a GStreamer source trying to publish VP8 to an H.264 only room (so a similar setup), and the publishing part worked: what I didn't test yet, was the subscription part, that is when the _plugin_ prepares an SDP offer to send to subscribers. My guess is that the issue you're getting is happening there, but I'll need some time to replicate the problem.

**Comment by adigeo** [comment] 2019-09-18 14:45
With humble apologies. The fix does work!

It appears that we built the wrong branch, an older version.

Is our mistake, the problem is solved.

Regards,
Adrian

**Comment by lminiero** [comment] 2019-09-18 14:46
Glad to know it worked! I was really struggling to figure out where the issue might be :rofl: 
Closing then :+1:

**Closed by lminiero** 2019-09-18 14:46 UTC

**Comment by CodeHownd** [comment] 2020-09-08 22:22
I am having this issue with` Invalid m= line (no payload types/formats): m=video 9 UDP/TLS/RTP/SAVPF` and i am using the most recent master branch. the relevant sdp line from the client is `m=video 9 UDP/TLS/RTP/SAVPF 96 97 98 99 100 101 127 123 125 122 124
`
