### ISSUE TITLE
http transport break with openssl since 9.3.0

### ISSUE THREAD

**Issue by eggestad** [meetecho/janus-gateway#2458] opened 2020-11-30 18:26 UTC
In 0.9.2 there is a major rewrite off janus_http.c: "- Converted HTTP transport plugin to single thread (now requires libmicrohttpd >= 0.9.59)"

This breaks use of rest api over ssl (openssl) in every version from 0.9.2 up to 0.10.7

Suspect that it might only affect certain lib versions since I can't see no one else reporting it.  

Should be easy to reproduce, I'm on FedoraCore 31 where the following versions are used:
libmicrohttpd-0.9.71-1.fc31.x86_64
openssl-1.1.1g-1.fc31.x86_64

Not using ssl, just http everything works fine, but there seem to be missing a flush in the ssl code. 
if you do a call to /info, the first 4096 bytes come over, then the client (testing with curl) hangs awaiting more data according to  the Content-Length http header.

**Comment by lminiero** [comment] 2020-11-30 18:29
Have you checked whether it's not an issue with MHD? We don't handle traffic ourselves, the library does.

**Comment by eggestad** [comment] 2020-11-30 20:59
No, it was too much work to track it down 
I'm going to do a workaround by a switching to websockets, it was on the agenda anyway. 

You're most likely right. 

Though you would want to know.

**Comment by eggestad** [comment] 2020-12-03 16:17
FYI

Downgrading libmicrohttpd from 0.9.71 to 0.9.59 solves the problem.

**Comment by lminiero** [comment] 2020-12-03 16:28
So it is indeed an issue in libmicrohttpd? If so, I'll close the issue here, then.

**Comment by eggestad** [comment] 2020-12-04 16:07
Up to you if you want to close it. 

Just seem strange to me that they make a release where openssl don't work. 
I'd check if janus is "working" by a bug in 0.9.59 which has later been closed. 

Or at least note in the README that 0.9.71 is known to be broken and a downgrade is necessary. It would be strange if I'm the only one to run into this one.

**Comment by song-xufei** [comment] 2020-12-05 03:53
I also meet same problem that http works well but https not works well.(with the libmicrohttpd 0.9.71).
It will response client until connection timeout.
I print the suspended status in the complete callback, it is already no suspended.
so I use tcpdump to find more information, I found that there is no date between server receive request to sercer response request. 
As I understand, the connection is in the libmicrohttpd queue, but it did't handle it until timeout. 
The only difference between http and htps is SSL. I don't know why they don't handle this msg. 
btw 0.9.59 works well, but 0.9.71 have better performance.

**Comment by atoppi** [comment] 2020-12-07 10:13
FWIW `libmicrohttpd 0.9.66-1 amd64` on Ubuntu 20.04 works as expected.

**Comment by lminiero** [comment] 2020-12-07 10:19
It should be noted that [we don't recommend](http://janus.conf.meetecho.com/docs/FAQ#https) using HTTPS in Janus itself anyway: [use a proxy](https://janus.conf.meetecho.com/docs/deploy) instead (it's what we always do).

**Comment by atoppi** [comment] 2020-12-07 10:29
I guess bisecting the exact version that breaks HTTPS should be easy for people having the issue.

**Comment by lminiero** [comment] 2020-12-07 10:31
> I guess bisecting the exact version that breaks HTTPS should be easy for people having the issue.

You mean bisecting MHD, right?

**Comment by atoppi** [comment] 2020-12-07 10:32
@lminiero yeah I meant bisecting mhd

**Comment by atoppi** [comment] 2021-04-19 15:16
I'm unable to reproduce with the following environment

**Ubuntu 20.04**

**libgnutls28-dev** + **libgnutls30**

**libmicrohttpd v0.9.72** from sources, configured with
`./configure --prefix=/usr --enable-messages --enable-https`

Janus successfully replies to both HTTPS admin and REST API.

**Comment by lminiero** [comment] 2021-04-19 15:27
On Fedora 33, which ships 0.9.72 in repos, I can't replicate either, so if this was a problem in libmicrohttpd before, apparently they fixed it.

**Closed** 2021-04-19 15:28 UTC
Labels: needinfo
