### ISSUE TITLE
Video Payback issue on Safari Version 13.0.1

### ISSUE THREAD

**Issue by ForGuru** [meetecho/janus-gateway#1838] opened 2019-10-24 12:06 UTC
I have used the following link 
https://janus.conf.meetecho.com/recordplaytest.html

Recording and Playback from Safari is not working. What could be the issue ??

**Comment by lminiero** [comment] 2019-10-28 10:12
You'll have to be much more detailed than that, if you need help. Are the PeerConnections successful? What are the local and remote SDPs? Are the .mjr files empty? Have you tried post-processing them with janus-pp-rec?

**Comment by ForGuru** [comment] 2019-11-04 10:36
Sorry i have been busy. I am using following URL to test on Safari 
https://janus.conf.meetecho.com/recordplaytest.html
When I Click the Play button I see first frame of the video. What could be the issue?

Thanks

**Comment by lminiero** [comment] 2019-11-04 10:39
Then it's simply Safari messing with autoplay, I suspect. If you see the first frame, the video has definitely been recorded. Closing as not a code issue.

**Closed by lminiero** 2019-11-04 10:39 UTC

**Comment by groupboard** [comment] 2020-03-18 00:33
Anyone have a workaround (other than calling getUserMedia), or know the cause? It's not a typical autoplay issue, as it happens even though the user has interacted with the window.

**Comment by groupboard** [comment] 2020-03-18 01:42
Actually, it's explained here: https://webkit.org/blog/6784/new-video-policies-for-ios/

Solution is to catch the "pause" event on the video element, then prompt the user, and call the play() method on the video element inside the click handler.
