### ISSUE TITLE
[1.x] Remote track not being removed from remoteStream

### ISSUE THREAD

**Issue by AugustoZanoni** [meetecho/janus-gateway#3104] opened 2022-11-16 13:57 UTC
Using the most updated version

I did this test using echo plugin sample, removing the video track.
Its being removed from localstream but not from remote

![image](https://user-images.githubusercontent.com/49280362/202199002-40d3848e-848a-47ee-bc46-df6c2276cfe2.png)

ref: https://janus.conf.meetecho.com/docs/JS.html#renegotiation

**Comment by lminiero** [comment] 2022-11-21 10:18
I think it has to do with the fact we still send an `a=ssrc` attribute even when the direction is inactive. IIRC we did this to prevent problems with SSRCs during/after renegotiations, where media would be ignored by the browser. From a UI perspective, you get a "Removing remote track" event anyway, which means you can get rid of the rendering nevertheless.

**Comment by lminiero** [comment] 2023-01-05 11:09
Closing as probably working as intended.

**Closed by lminiero** 2023-01-05 11:09 UTC
Labels: multistream
