### ISSUE TITLE
When resubscribing a publisher feed in videoroom the browser signals a track with readyState ended

### ISSUE THREAD

**Issue by JanFellner** [meetecho/janus-gateway#2918] opened 2022-03-08 14:36 UTC
**What version of Janus is this happening on?**
f62c80fd (02.March.2022)

**Have you tested a more recent version of Janus too?**
no (did not see any commit that may affect this behaviour)

**Was this working before?**
sadly no clue

**Additional context**
I have a videoroom with two publishers each providing a single audio and video track into the room.
I have another party that is subscribing to audio video of both parties.
Streams are properly setup an everything looks fine.
If i now unsubscribe one of the parties and resubscribe it again i get matching track events from the peerConnection.
However the tracks in the notify are announced as ended in the peerConnection.

![image](https://user-images.githubusercontent.com/53753460/157260036-6613a602-7e31-4a93-9c35-8d15b8e6100e.png)

* Do i need to manually update the peerConnection when using multistreaming after the SDP exchange if a track is removed?
(Currently is just hand over the SDP from janus to the browser and hand back the response)

**Comment by lminiero** [comment] 2022-03-08 15:51
Sorry, you'll have to be clearer than that: I don't understand what the problem is?

**Comment by JanFellner** [comment] 2022-03-08 15:54
Sorry Lorenzo, i try to explain it differently.
If i have a subscription PeerConnection and on this peerConnection i do an unsubscribe and then subscribe the same stream again, i get, on the client side, a track event but the track is announced ended.

Is there anything i have to take care of if i just unsubscribe and subscribe again the same stream/track?

**Comment by JanFellner** [comment] 2022-03-10 10:45
I tried to reproduce it in the mvideosample and cannot reproduce it there...
Checking where this behaviour come from... Will update the ticket today.

**Comment by JanFellner** [comment] 2022-03-10 14:05
The issue is that the code stops the track while unsubscribing. If i then subscribe the publisher feed again it looks like the peerconnection is reusing the same track object as the track id in the SDP also did not change. This still is a bit strange to me so i involved @fippo if he has something in mind...

**Comment by lminiero** [comment] 2022-03-10 14:15
Then it's the same as discussed [here](https://groups.google.com/g/meetecho-janus/c/se7c_3oX04c), so not a Janus bug. Closing.

**Closed by lminiero** 2022-03-10 14:15 UTC
Labels: multistream

**Comment by fippo** [comment] 2022-03-10 14:18
What I see in the SDP is this:
```
a=msid:janus janus0
a=msid:janus janus1
a=msid:janus janus2
a=msid:janus janus3
```
in general I would avoid latching all tracks onto the same stream id -- sharing the same cname has rtp semantic implications which are troublesome at best

**Comment by JanFellner** [comment] 2022-03-10 14:21
We have no DTLS handshaking or ICE errors, everything is working as expected, just the track is announced ended.
I would assume that if the track id "would" change, the behavior might be not visible at all....

**Comment by fippo** [comment] 2022-03-10 14:28
I think you're hitting very weakly defined behavior:
1/ offer with a remote track with id 1234
2/ user calls stop on the remote track, renegotiates
3/ offer with a remote track with id 1234
Unless the remote track gets purged from the peerconnection "ended" is the expected state.
