### ISSUE TITLE
Datachannels regularly stops working after 4 weeks of uptime

### ISSUE THREAD

**Issue by agorkiy** [meetecho/janus-gateway#3028] opened 2022-07-18 10:19 UTC
**What version of Janus is this happening on?**
v1.0.1, but the same happened with previous 0.11-0.12 versions as well
Context:
This happens every 3-4 weeks - our web app stops working and this fixes just with janus restart with systemctl. But we are trying find the root cause now. So, here is workflow(according to our dev):
1. Join request is sent to janus server
2. Server tries to create a room and response with expected error that room is already created.
3. Janus sends room id to frontend.
4. Frontend is making join request to janus using websocket api.
When janus fails. screen remains blank and conference not joined. Here are screenshots:
![image](https://user-images.githubusercontent.com/41108132/179489192-e56c7c47-353d-4216-8df8-fe775d15b609.png)
![image](https://user-images.githubusercontent.com/41108132/179489222-e6f19684-e52d-47e0-ae45-62f93badfa93.png)

Here is janus log when opening&closing conference tab:
```
[Mon Jul 18 10:08:48 2022] [ERR] [plugins/janus_videoroom.c:janus_videoroom_process_synchronous_request:4210] Room 1041532594 already exists!
[Mon Jul 18 10:08:48 2022] Creating new session: 8902865288837583; 0x7effec073df0
[Mon Jul 18 10:08:49 2022] Creating new handle in session 8902865288837583: 2701272730516839; 0x7effec073df0 0x7effec075900
[Mon Jul 18 10:08:49 2022] [WARN] [2701272730516839] No stream, queueing this trickle as it got here before the SDP...
[Mon Jul 18 10:08:49 2022] [2701272730516839] Creating ICE agent (ICE Full mode, controlled)
[Mon Jul 18 10:09:08 2022] [WSS-0x7eff8c047dd0] Destroying WebSocket client
[Mon Jul 18 10:09:08 2022] Destroying session 8902865288837583; 0x7effec073df0
[Mon Jul 18 10:09:08 2022] Detaching handle from JANUS VideoRoom plugin; 0x7effec075900 0x7effec00c9e0 0x7effec075900 0x7effec00ca10
[Mon Jul 18 10:09:08 2022] [WSS-0x7eff98035c00] Destroying WebSocket client

```
Here are also janus limits:
```
Limit                     Soft Limit           Hard Limit           Units     
Max cpu time              unlimited            unlimited            seconds   
Max file size             unlimited            unlimited            bytes     
Max data size             unlimited            unlimited            bytes     
Max stack size            8388608              unlimited            bytes     
Max core file size        unlimited            unlimited            bytes     
Max resident set          unlimited            unlimited            bytes     
Max processes             30913                30913                processes 
Max open files            65536                65536                files     
Max locked memory         65536                65536                bytes     
Max address space         unlimited            unlimited            bytes     
Max file locks            unlimited            unlimited            locks     
Max pending signals       30913                30913                signals   
Max msgqueue size         819200               819200               bytes     
Max nice priority         0                    0                    
Max realtime priority     0                    0                    
Max realtime timeout      unlimited            unlimited            us     
```
And current open files:
```
root@janus:~# lsof | grep janus | wc -l
11177
```
Attached also strace which I dumped with ```strace -f -e trace=network,read,write -p 33444 -o strace-output.txt```
https://gist.github.com/agorkiy/9df6860e163858d6f4a8221dbbf13ef4
Any idea what if can be? I thought it may be on our end, but no idea where frontend can fail every month and why it's fixed exactly with janus restart...
Thanks in advance!

**Comment by agorkiy** [comment] 2022-07-19 06:56
We narrowed the issue and found that DataChannel stopped working. Webrtc connectivity is ok if no datachannel openning. But if we pass `data: true` during offer creation - webrtc will fail. In the Janus verbose logs we DON’T see the usual “DTLS handshake complete” message. It is exists for webrtc without datachannels, but is never printed for webrtc with datachannel.
![image](https://user-images.githubusercontent.com/41108132/179685714-6ef0299e-c812-429b-8851-174a5e7af89c.png)
Also, it is not multistream related. We met that issue before.

**Comment by lminiero** [comment] 2022-07-19 07:19
The Janus demos that are online have often been up and running for way more than 4 weeks, always using datachannels as part of some demos (e.g., EchoTest or TextRoom) and they never gave problems, so I doubt that's the cause.

**Comment by lminiero** [comment] 2022-07-19 07:20
@atoppi may have some ideas on how to better debug this: maybe gdb attach to the process when it stops working to find the thread that's stuck?

**Comment by atoppi** [comment] 2022-07-19 09:16
It's not clear to me what stops working, since the websocket dump is not complete (e.g. which request is missing a response from janus?). 
Anyway as suggested by Lorenzo we could take a look at the thread status through gdb

```
gdb -p $(pidof janus) --batch -ex "set set print pretty on" -ex "set pagination off" -ex "thread apply all bt full"
```
If call stacks are missing symbols recompile janus with `-O0 -g -ggdb3` flags.

**Comment by atoppi** [comment] 2022-07-19 09:22
Since you mentioned datachannels, which `usrsctp` version are you using?

It would worth trying with a fresh version of `usrsctp`, with the suggested flags
```
git clone -b master https://github.com/sctplab/usrsctp usrsctp
cd usrsctp
./bootstrap
./configure --prefix=/usr --disable-static --enable-debug --disable-programs --disable-inet --disable-inet6
make -j$(nproc)
sudo make install
```

**Comment by agorkiy** [comment] 2022-07-19 10:29
@lminiero  @atoppi Thanks for answering!
Here is gdb, but i'm not sure about missing symbols.
https://gist.github.com/agorkiy/8ec3211663aae0cb69e70fd45ebfa11d
We are using `libusrsctp-dev` package from default ubuntu 20 repo. We will surely try fresh version, but we will need to recompile&restart janus so problem will go away for a month at least. So, want to be sure that we tried&got all info from current non-working setup that will help in problem troubleshooting.

**Comment by atoppi** [comment] 2022-07-19 11:20
There is a bunch of threads waiting for the same sctp internal mutex
```
#0  __lll_lock_wait (futex=futex@entry=0x7f000b953fb0 <system_base_info+176>, private=0) at lowlevellock.c:52
#1  0x00007f000b5970a3 in __GI___pthread_mutex_lock (mutex=0x7f000b953fb0 <system_base_info+176>) at ../nptl/pthread_mutex_lock.c:80
#2  0x00007f000b8ff5e1 in sctp_inpcb_alloc () at /lib/x86_64-linux-gnu/libusrsctp.so.1
#3  0x00007f000b915843 in sctpconn_attach () at /lib/x86_64-linux-gnu/libusrsctp.so.1
#4  0x00007f000b89e349 in socreate () at /lib/x86_64-linux-gnu/libusrsctp.so.1
#5  0x00007f000b89e4e5 in usrsctp_socket () at /lib/x86_64-linux-gnu/libusrsctp.so.1
#6  0x00005628ae019f50 in janus_sctp_association_create (dtls=dtls@entry=0x7eff8001acc0, handle=handle@entry=0x7effec072d10, udp_port=udp_port@entry=5000) at sctp.c:248
#7  0x00005628adfcc343 in janus_dtls_srtp_create_sctp (dtls=dtls@entry=0x7eff8001acc0) at dtls.c:645
#8  0x00005628adfcf652 in janus_dtls_srtp_incoming_msg (dtls=0x7eff8001acc0, buf=buf@entry=0x7eff857e9880 "\026\376", <incomplete sequence \375>, len=len@entry=578) at dtls.c:924
#9  0x00005628adfe8a46 in janus_ice_cb_nice_recv (agent=<optimized out>, stream_id=<optimized out>, component_id=1, len=<optimized out>, buf=0x7eff857e9880 "\026\376", <incomplete sequence \375>, ice=0x7eff8001a800) at ice.c:2454
```

As a consequence the SCTP association will not be completed.
This is probably the reason DTLS is not succeeding when DCs are being requested.

But which thread did take the mutex? There is just one thread with a different call stack:

```
Thread 28 (Thread 0x7effc97fa700 (LWP 726165)):
#0  futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x7f000b953c68) at ../sysdeps/nptl/futex-internal.h:183
#1  __pthread_cond_wait_common (abstime=0x0, clockid=0, mutex=0x7f000b953ec0 <sctp_os_timerwait_mtx>, cond=0x7f000b953c40) at pthread_cond_wait.c:508
#2  __pthread_cond_wait (cond=0x7f000b953c40, mutex=0x7f000b953ec0 <sctp_os_timerwait_mtx>) at pthread_cond_wait.c:647
#3  0x00007f000b8afa0d in sctp_os_timer_stop () at /lib/x86_64-linux-gnu/libusrsctp.so.1
#4  0x00007f000b9308c9 in sctp_timer_stop () at /lib/x86_64-linux-gnu/libusrsctp.so.1
#5  0x00007f000b90195b in sctp_inpcb_free () at /lib/x86_64-linux-gnu/libusrsctp.so.1
#6  0x00007f000b915a01 in sctp_close () at /lib/x86_64-linux-gnu/libusrsctp.so.1
#7  0x00007f000b89c184 in sofree () at /lib/x86_64-linux-gnu/libusrsctp.so.1
#8  0x00007f000b89f810 in usrsctp_close () at /lib/x86_64-linux-gnu/libusrsctp.so.1
#9  0x00005628ae019abd in janus_sctp_association_destroy (sctp=0x7eff8c03ac10) at sctp.c:370
#10 0x00005628adfcf82d in janus_dtls_srtp_destroy (dtls=0x7eff9000bd00) at dtls.c:961
#11 0x00005628adfe3707 in janus_ice_peerconnection_destroy (pc=0x7eff90029e30) at ice.c:1682
#12 janus_ice_peerconnection_destroy (pc=0x7eff90029e30) at ice.c:1667
#13 0x00005628adfe390e in janus_ice_webrtc_free (handle=handle@entry=0x7effec0188c0) at ice.c:1604
#14 0x00005628adfef1ab in janus_ice_outgoing_traffic_handle (handle=0x7effec0188c0, pkt=<optimized out>) at ice.c:4422
#15 0x00005628adff2429 in janus_ice_outgoing_traffic_dispatch (source=0x7effec004d80, callback=<optimized out>, user_data=<optimized out>) at ice.c:479
``` 
It seems this thread is waiting for some condition in order to destroy a SCTP association due to a PC teardown.

According to apt, on Ubuntu 20.04 the version of `libusrsctp-dev` is **v0.9.3.0** (apr 2016).
I guess your best option is to upgrade the lib version and test again.

**Comment by agorkiy** [comment] 2022-07-20 08:45
@atoppi ok, thank you!
Already recompiled janus with latest usrsctp, hope I won't return here in a month with same problem.

**Comment by lminiero** [comment] 2022-07-20 08:53
Closing for the time being. Please feel free to reopen if it's still an issue.

**Closed by lminiero** 2022-07-20 08:53 UTC
Labels: needinfo, multistream
