### ISSUE TITLE
MCU audio bug when initializing with disabled audio and video

### ISSUE THREAD

**Issue by leonuh** [meetecho/janus-gateway#131] opened 2015-01-12 14:35 UTC
I tried to initialize the connection with disabled audio and video.

```
var publish = { "request": "configure", "audio": false, "video": false };
mcu.send({"message": publish, "jsep": jsep});
```

After that the audio will not work, except if I send a request at least once with video: true.
So basically it will not work, if the video wasn't enabled at least once:

```
var publish = { "request": "configure", "audio": true };
mcu.send({"message": publish, "jsep": jsep});
```

**Comment by lminiero** [comment] 2015-01-12 14:40
The audio and video you put in a ```configure``` request act as mute/unmute buttons, they don't affect the negotiation. What impacts the negotiation (whether you have an audio or video channel at all) is the media value you put in a createOffer/createAnswer call, as explained in the documentation.

**Comment by leonuh** [comment] 2015-01-12 15:09
Yes I know but still it is a bug somehow. I give you a simpler example:

Rewrite
https://github.com/meetecho/janus-gateway/blob/master/html/videomcutest.js#L313

to
```
var publish = { "request": "configure", "audio": true, "video": false };
```

The expected behaviour: Disabled video and enabled audio
The real behaviour: Disabled video and audio (it was enabled for a moment when the use leaves the room )

**Comment by lminiero** [comment] 2015-01-12 15:14
It may be a bug in the browser: I seem to recall some issues in setting up the playout when a medium was negotiated but not received (but I may be wrong). What happens if you start with both enabled, and you only disable video later using the message you specified?

**Comment by leonuh** [comment] 2015-01-12 15:28
It works. It works if I send a request with "video: true" at least once.
Browser: Chrome Stable

**Comment by lminiero** [comment] 2015-01-12 15:35
IIRC it's a browser thing, not related to Janus. No audio is
reproduced until a video packet is received, if they're both
negotiated. Try with Firefox as well just to be sure.

2015-01-12 16:28 GMT+01:00, leonuh <notifications@github.com>:

**Comment by leonuh** [comment] 2015-01-12 16:13
Yes, you are right. It works in Firefox. Thank you for your answer. Do you have any suggestion how to fix that issue in Chrome? (Eg.: Is there a way to give back dummy video with black screen)

**Comment by lminiero** [comment] 2015-01-12 16:15
If you want an audio-only viewer (or publisher) you need to pass video:false to createOffer/createAnswer. This should work as expected. If instead you want to be able to selectively mute/unmute both audio and video, start with both unmuted and then mute them as needed (e.g., shortly after it has started to overcome that bug).

Closing as it's not a bug in Janus.

**Closed by lminiero** 2015-01-12 16:15 UTC
