### ISSUE TITLE
Crash after commit a0240a1

### ISSUE THREAD

**Issue by amnonbb** [meetecho/janus-gateway#1586] opened 2019-04-12 15:06 UTC
#1459 
After [last](https://github.com/meetecho/janus-gateway/commit/a0240a17afa7a1a6377a48ad6630b5d2b54f6ed7) commit,
Janus crash if I use DataChannel in videoroom. 
In every crash the dump is same:
https://pastebin.com/63NFbkgv

It's happen (but not always) when publisher join in room.

**Comment by lminiero** [comment] 2019-04-15 13:07
Looks like it crashes when unlocking a mutex, so no idea on the cause. You should try compiling with libasan support to see if the cause is a freed pointer.

**Comment by amnonbb** [comment] 2019-04-15 18:23
https://pastebin.com/Zbs6NPuV

**Comment by lminiero** [comment] 2019-04-16 08:15
Ah ok, another unlock without a lock... I'll have to check what the path that leads to it might be.

**Comment by lminiero** [comment] 2019-04-16 09:44
I'm pretty sure this commit fixes it: https://github.com/meetecho/janus-gateway/pull/1459/commits/43aeb9134800cc724f10407f24b5ea84177963e0
There was an extra unlock that could happen inside a while (indeed related to datachannels), which could still lead to the mean unlock in the for, and I guess that's what was happening to you.

Closing, feel free to reopen if still an issue.

**Closed by lminiero** 2019-04-16 09:44 UTC
