### ISSUE TITLE
OPUS problem janus-pp-rec convert 30m audio to more than 24h

### ISSUE THREAD

**Issue by ShcherbaAlex** [meetecho/janus-gateway#1708] opened 2019-07-24 11:41 UTC
OPUS problem janus-pp-rec convert 30m audio to more than 24h

//janus-pp-rec log

Janus version: 74 (0.7.4)
Janus commit: 9fdabc45c75ed6c5d3b8f5a38a2478fdc3128c0f
Compiled on:  Wed Jul 24 09:46:23 UTC 2019

Logging level: 4

Source file: ./videoroom-664237-user-5833700000001562-1563790266492979-audio.mjr
Target file: ./videoroom-664237-user-5833700000001562-1563790266492979-audio.opus

File is 4557078 bytes
Pre-parsing file to generate ordered index...
[WARN] New .mjr header format
This is an audio recording:
  -- Codec:   opus
  -- Created: 1563790266492981
  -- Written: 1563790267605832
SSRC detected: 2681136959
Counted 42660 RTP packets
Counted 42660 frame packets
Writing .opus file header
[WARN] Lost a packet here? (got seq 118 after 114, time ~2s)
[WARN] [FILL] pos: 000114, writing silences (count=3)
[WARN] Lost a packet here? (got seq 742 after 738, time ~14s)
[WARN] [FILL] pos: 000738, writing silences (count=3)
[WARN] Lost a packet here? (got seq 1054 after 1052, time ~21s)
[WARN] [FILL] pos: 001052, writing silences (count=1)
...
...
[WARN] Lost a packet here? (got seq 41318 after 41315, time ~826s)
[WARN] [FILL] pos: 041315, writing silences (count=2)
[WARN] Lost a packet here? (got seq 41631 after 41629, time ~832s)
[WARN] [FILL] pos: 041629, writing silences (count=1)
[WARN] Lost a packet here? (got seq 42099 after 42094, time ~841s)
[WARN] [FILL] pos: 042094, writing silences (count=4)
[WARN] Lost a packet here? (got seq 42566 after 42563, time ~851s)
[WARN] [FILL] pos: 042563, writing silences (count=2)
[WARN] Lost a packet here? (got seq 42723 after 42720, time ~854s)
[WARN] [FILL] pos: 042720, writing silences (count=2)
[WARN] Lost a packet here? (got seq 42879 after 42875, time ~857s)
[WARN] [FILL] pos: 042875, writing silences (count=3)
[WARN] Lost a packet here? (got seq 0 after 42979, time ~89478s)
[WARN] [FILL] pos: 042979, writing silences (count=4430944)
./videoroom-664237-user-5833700000001562-1563790266492979-audio.opus is 365708931 bytes
Bye!

There was the same issue before, but it seems it was not solved.

**Comment by lminiero** [comment] 2019-07-24 13:31
As explained in other issues, this is usually caused by a few out of order packets at the very beginning. Use one of the optional `janus-pp-rec` command line parameters to skip those. Closing as not an issue.

**Closed by lminiero** 2019-07-24 13:31 UTC
