### ISSUE TITLE
no response on datachannel unsubscribe request (multistream)

### ISSUE THREAD

**Issue by kaqq** [meetecho/janus-gateway#2725] opened 2021-07-05 11:12 UTC
There is no WebSocket response or ACK when unsubscribe request is sent for the data channel, however, data channel messages stop flowing.
Example JSON:

```
{
  "session_id": 8045770177589365,
  "handle_id": 3618270449855223,
  "body": {
    "streams": [
      {
        "feed": 6750740208640810,
        "mid": "1"
      }
    ],
    "request": "unsubscribe"
  },
  "janus": "message",
  "transaction": "652354c1-a991-45ec-b9f6-8297b99b24de"
}
```

**Comment by lminiero** [comment] 2021-07-06 13:21
Not an issue, and expected. Unsubscribing from a publisher for data results in no renegotiation (the data channel itself survives since you may be subscribed to other people for data, or you'll need datachannels later), so you never get any updated offer, so no event either. While we may add a placeholder ack in the future, it's not there but it's not a bug. Closing.

**Closed by lminiero** 2021-07-06 13:21 UTC

**Comment by lminiero** [comment] 2021-07-06 13:30
Ack `updated` event added in case there's no SDP changes.
