### ISSUE TITLE
Streaming Plugin with H.264 RTSP stream as input freezes after a few seconds

### ISSUE THREAD

**Issue by petergerten** [meetecho/janus-gateway#479] opened 2016-03-10 03:46 UTC
Janus Gateway (git version from 2016-03-09)
Chrome 50.0.2661.11

I use the unmodified streaming-plugin demo from Janus and feed it with a H.264 High Profile RTSP stream. It works as expected but after a few seconds the video just freezes reproducibly.

I ran janus with debug level 7 but did not get any error/suspicious output. In Chrome webrtc-internals I can see that the connection is still active but "bytesReceived" does not go up anymore. There are bytes sent though. On the Janus side I keep receiving this:

    [609190047]  Got an RTCP packet (bundled stream)!
    [609190047] Incoming RTCP, bundling: this is video (no audio has been negotiated)
    Got REMB bitrate 2718768
    REMB for this PeerConnection: 2718768

So it seems to be that everything is still up but no video frames coming in anymore. I verified that there was no change in the RTSP stream and it still works if viewed externally.

Connection stats after video freezed:

    Statistics Conn-video-1-0
    timestamp	3/9/2016, 10:09:24 AM
    googActiveConnection	true
    bytesReceived	11393441
    bytesSent	28334
    packetsSent	453
    googReadable	true

**Comment by lminiero** [comment] 2016-03-10 08:29
Have you checked the info our [Admin API](http://www.meetecho.com/blog/understanding-the-janus-admin-api/) provides as well?

**Comment by petergerten** [comment] 2016-03-10 08:56
Yes, I missed saying that I started chrome with "google-chrome-unstable  --enable-features=WebRTC-H264WithOpenH264FFmpeg". I checked the Admin API and could not find any further helpful information. Everything looks ok and keeps looking ok - just bytes-received stops and therefore the video.
Is there any information of interest that might help?

I am aware that the H.264 support is highly experimental.

**Comment by lminiero** [comment] 2016-03-10 09:01
Well, you could check whether there are any outgoing audio and/or video packets (out_stats). Either refresh the handle info after a few seconds, or tick the autoupdate checkbox, that will do a new query every 5 seconds or so I think, just to make sure the out_stats info increases. If it does, Janus is forwarding the RTP packets as it should, and then the frozen video is a bug in Chrome. If no media is flowing, it means no RTP is being sent, which explains why it freezes.

That said, make sure the baseline profile is being used for H.264 (WebRTC browsers will only support that one), and that the right packetization mode is being negotiated (not sure which one Chrome expects); if not, you may have to play with the settings of your surveillance camera to make sure a compliant video is being sent. And again, also try with Firefox which has been supporting H.264 for a while longer, and so may provide you with more feedback.

**Comment by lminiero** [comment] 2016-03-24 11:44
Any update on this?

**Comment by amnonbb** [comment] 2016-03-30 10:38
I did many test with H264. (Firefox, chrome 50).
Only baseline profile work with Firefox. 
In Chrome Main profile did work. But b-frames must be 0 otherwise i get freezes.

**Comment by lminiero** [comment] 2016-04-11 10:32
Thanks for the update (and sorry for the late reply, I've been abroad for a conference). I guess we can close the issue, then, as it's not a bug in Janus but a matter of codec support in clients.

**Closed by lminiero** 2016-04-11 10:32 UTC
