### ISSUE TITLE
The screenshare demos broken on Safari.

### ISSUE THREAD

**Issue by Jaikant** [meetecho/janus-gateway#2455] opened 2020-11-29 16:13 UTC
The demos on the [webpage](https://janus.conf.meetecho.com/screensharingtest.html) are broken on Safari. I tried it on Version 14.0.1.

1) We get a black screen on Safari, when we try to view a room which was created from Chrome.
2) The error when trying to publish on Safari is below:
`WebRTC error... {"line":2366,"column":45,"sourceURL":"https://janus.conf.meetecho.com/janus.js"}`

The behaviour seen above has been replicated in my dev environment with my own Janus server. I did screen sharing with the video room plugin and Safari doesn't work.

**Comment by lminiero** [comment] 2020-11-30 12:05
Looks like the error is caused by the fact that Safari expects a user gesture to trigger `getDisplayMedia` to share a screen. While we do have a button to start the process, the connection is not direct: our button triggers a request to Janus to create a new temporary room and join it, and only when that happens we issue the `getDisplayMedia`. This means the method is actually triggered by a network event, and not a user gesture. I'll add a tweak to the code to show a further dialog just for Safari.

The black screen is an issue of autoplay policy, so can be fixed with the usual methods (plenty of discussions about this on the group).

**Comment by alexamirante** [comment] 2020-11-30 12:33
The two commits above fix both the `getDisplayMedia` and autoplay issues in Safari.

**Closed by alexamirante** 2020-11-30 12:33 UTC
