### ISSUE TITLE
Janus sends 2 end-of-candidates

### ISSUE THREAD

**Issue by tanton81** [meetecho/janus-gateway#995] opened 2017-09-07 12:19 UTC
Hello, 

I am developing a client program that opens a websocket connection to a Janus (v0.2.3). The client connects to the videoroom plugin.
The first connection is a publisher and the second one is a listener.
When the listener gets the publisher's feed, she creates a new slave handle and joins to the publisher's feed.
As a result of these actions Janus sends back a SDP offer which have the following form:

`"sdp":"v=0\r\no=- 1504774263038545 1 IN IP4 *.*.*.*\r\ns=VideoRoom 1003\r\nt=0 0\r\na=group:BUNDLE video\r\na=msid-semantic: WMS janus\r\nm=video 9 RTP/SAVPF 96\r\nc=IN IP4 92.222.241.138\r\na=sendonly\r\na=mid:video\r\na=rtcp-mux\r\na=ice-ufrag:uFSg\r\na=ice-pwd:vf4NVH5U9DQDCOEhk+mIMT\r\na=ice-options:trickle\r\na=fingerprint:sha-256 ******************************************************************************************\r\na=setup:actpass\r\na=rtpmap:96 VP8/90000\r\na=rtcp-fb:96 ccm fir\r\na=rtcp-fb:96 nack\r\na=rtcp-fb:96 nack pli\r\na=rtcp-fb:96 goog-remb\r\na=extmap:4 urn:3gpp:video-orientation\r\na=extmap:6 http://www.webrtc.org/experiments/rtp-hdrext/playout-delay\r\na=ssrc:1677205320 cname:janusvideo\r\na=ssrc:1677205320 msid:janus janusv0\r\na=ssrc:1677205320 mslabel:janus\r\na=ssrc:1677205320 label:janusv0\r\na=candidate:1 1 udp 2013266431 10.10.13.96 63140 typ host\r\na=candidate:2 1 udp 2013266431 *.*.*.* 54963 typ host\r\na=**end-of-candidates**\r\na=candidate:1 2 udp 2013266430 10.10.13.96 52523 typ host\r\na=candidate:2 2 udp 2013266430 *.*.*.* 62217 typ host\r\na=**end-of-candidates**\r\n"`

How you can see, Janus sends a SDP with 2 end-of-candidates. I think this is not OK and there should be only one end-of-candidates.

I can reproduce it each time.

Best regards, 

Anton TONEV

**Comment by lminiero** [comment] 2017-09-07 12:21
Not a bug, that's exactly how it should work. Per the standard, `end-of-candidates` applies to the m-line, not the whole SDP. Closing.

**Comment by tanton81** [comment] 2017-09-07 12:28
There is only one media line but not two.

**Comment by lminiero** [comment] 2017-09-07 12:30
Oh sorry, I just assumed you had two because it was audio+video. Just noticed that this is a video-only SDP. I'll look into that :+1:

**Closed** 2017-09-07 12:45 UTC

**Comment by lminiero** [comment] 2017-09-07 12:46
It should be fixed now, please let me know if that's not the case. Thanks for bringing this to my attention! (and for making me notice *I* was the one being wrong :smile: )

**Comment by tanton81** [comment] 2017-09-07 17:06
I test it on my system and it seems your fix works fine :)
Thank you ! :)

**Comment by tanton81** [comment] 2017-09-09 11:25
Hello again, 
there is still something not very clean with the ICE candidates.

Now, If I take the previous example, we have the following situation:

"sdp":"v=0\r\no=- 1504774263038545 1 IN IP4 *.*.*.*\r\ns=VideoRoom 1003\r\nt=0 0\r\na=group:BUNDLE video\r\na=msid-semantic: WMS janus\r\nm=video 9 RTP/SAVPF 96\r\nc=IN IP4 92.222.241.138\r\na=sendonly\r\na=mid:video\r\na=rtcp-mux\r\na=ice-ufrag:uFSg\r\na=ice-pwd:vf4NVH5U9DQDCOEhk+mIMT\r\na=ice-options:trickle\r\na=fingerprint:sha-256 ******************************************************************************************\r\na=setup:actpass\r\na=rtpmap:96 VP8/90000\r\na=rtcp-fb:96 ccm fir\r\na=rtcp-fb:96 nack\r\na=rtcp-fb:96 nack pli\r\na=rtcp-fb:96 goog-remb\r\na=extmap:4 urn:3gpp:video-orientation\r\na=extmap:6 http://www.webrtc.org/experiments/rtp-hdrext/playout-delay\r\na=ssrc:1677205320 cname:janusvideo\r\na=ssrc:1677205320 msid:janus janusv0\r\na=ssrc:1677205320 mslabel:janus\r\na=ssrc:1677205320 label:janusv0\r\na=candidate:1 1 udp 2013266431 10.10.13.96 63140 typ host\r\na=candidate:2 1 udp 2013266431 *.*.*.* 54963 typ host\r\na=candidate:1 2 udp 2013266430 10.10.13.96 52523 typ host\r\na=candidate:2 2 udp 2013266430 *.*.*.* 62217 typ host\r\na=**end-of-candidates**\r\n"

Only one 'end-of-candidates' but it seems to me that there are always two pairs of two ICE candidates knowing that we have only video, no audio stream.

a=candidate:1 1 udp 2013266431 10.10.13.96 63140 typ host\r\n

a=candidate:2 1 udp 2013266431 *.*.*.* 54963 typ host\r\n

a=candidate:1 2 udp 2013266430 10.10.13.96 52523 typ host\r\n

a=candidate:2 2 udp 2013266430 *.*.*.* 62217 typ host\r\n

a=**end-of-candidates**\r\n

So, ICE candidates for audio in SDP shouldn't be proposed in this case.

Best regards ,

Anton TONEV

**Comment by lminiero** [comment] 2017-09-09 11:44
Please post the SDP in a readable way: I can't understand it if it's all on a huge line. Will only be able to come back on Monday though.

**Comment by tanton81** [comment] 2017-09-09 14:34
Yes, you are right, it is not very easy to read it... It's done now :) 
Have a nice weekend ! 

Anton

**Comment by lminiero** [comment] 2017-09-11 09:46
You're not getting the audio candidates, all the candidates you see are for the same component. Can it be you have multiple interfaces that are resolving to the same address? libnice may be doing the gathering for both, which is why you get two of them.

**Comment by tanton81** [comment] 2017-09-11 12:48
Hi, 
I checked the configuration where my Janus server is running and it has 2 interfaces. So as you said, there should be a candidate by available interface.
According to the SDP, this is a video send only offer, there is no audio. So in this case, there should be only 2 candidates (because of the 2 network interfaces).
I think in the case of audio only,  Janus sends the right number of candidates.

Best regards, 

Anton

**Comment by lminiero** [comment] 2017-09-11 13:01
No: 2 interfaces means 4 candidates. There's the RTP component (1) and the RTCP component (2). You see less candidates only when you force bundle and rtcp-mux since the beginning, or in answers when the negotiation tells you they're supported. Before that (e.g., offers) we have to assume that's not the case, and that we'll need separate components.
