### ISSUE TITLE
[1.x] Compilation Error.

### ISSUE THREAD

**Issue by kinsleykajiva** [meetecho/janus-gateway#3044] opened 2022-08-25 09:14 UTC
![image](https://user-images.githubusercontent.com/8996252/186623700-7eb20b8c-a364-4077-a281-7b70e56bcc86.png)

**What version of Janus is this happening on?**
Above I have attached the error that I am getting  , I seen  not to be able to move from that error  , I have installed the required dependencies as described in the read me,so I think .

**Have you tested a more recent version of Janus too?**
Yes I have tested with master, 0.x , v0.11.4, currently I am on version v0.11.4 with a similar error .

Operating System is ubuntu 20 lts. host AWS.

**Was this working before?**
No its not working on a fresh installation .

**Is there a gdb or libasan trace of the issue?**
I have attached the response I am getting using a image above

**Additional context**
I have also been rebooting my server in the hope that the services and dependencies may kick in  . 
cmake version  - cmake version 3.16.3

CMake suite maintained and supported by Kitware (kitware.com/cmake).

**Comment by atoppi** [comment] 2022-08-25 09:17
Duplicate of #3039

**Closed by atoppi** 2022-08-25 09:17 UTC
Labels: multistream

**Comment by kinsleykajiva** [comment] 2022-08-25 09:41
it worked thank you , i used git clone -b v4.3.0 https://github.com/warmcat/libwebsockets.git   or as a complete install command I sed - 
```shell
git clone -b v4.3.0 https://github.com/warmcat/libwebsockets.git && cd libwebsockets && mkdir build && cd build && cmake -DLWS_MAX_SMP=1 -DLWS_WITHOUT_EXTENSIONS=0 -DCMAKE_INSTALL_PREFIX:PATH=/usr -DCMAKE_C_FLAGS="-fpic" ..  && \
make && sudo make install && \
cd .. && cd .. 

```
