### ISSUE TITLE
spurious "New video stream!" messages using streaming plugin on subsequent streams

### ISSUE THREAD

**Issue by saket424** [meetecho/janus-gateway#875] opened 2017-04-28 20:51 UTC
I am using the latest janus commit from git
Janus commit: 10ce8e83ac279cc70df6bf91085620e321084cc9
Compiled on:  Fri Apr 28 14:27:51 CDT 2017

[test1]
type = rtp
id = 14
description = test 1
audio = no
video = yes
videoport = 2323
videopt = 96
videortpmap = H264/90000
videofmtp = packetization-mode=1

test2 and test3 are similar with the only difference being the stream id=15,videoport = 2324 and id=16,videoport = 2325 respectively

Here is the ffmpeg command I am using

ffmpeg -i rtsp://217.17.220.110:554/axis-media/media.amp -an -c:v copy -bsf dump_extra -f rtp rtp://127.0.0.1:2323?pkt_size=1300
ffmpeg -i rtsp://217.17.220.110:554/axis-media/media.amp -an -c:v copy -bsf dump_extra -f rtp rtp://127.0.0.1:2324?pkt_size=1300
ffmpeg -i rtsp://217.17.220.110:554/axis-media/media.amp -an -c:v copy -bsf dump_extra -f rtp rtp://127.0.0.1:2325?pkt_size=1300

I have been experiencing stutter/freeze issues on the 2nd and 3rd stream but not the first stream. 

I also am seeing spurious new ssrc values being generated in the janus output (which may be related)
---------------------------------------------------
  Starting Meetecho Janus (WebRTC Gateway) v0.2.3
---------------------------------------------------

Checking command line arguments...
Debug/log level is 4

[test1] New video stream! (ssrc=1212215561)
[test2] New video stream! (ssrc=3702397386)
[test2] New video stream! (ssrc=3702397391)
[test3] New video stream! (ssrc=877992763)
[test2] New video stream! (ssrc=3702397397)
[test3] New video stream! (ssrc=3702397399)
[test2] New video stream! (ssrc=285435956)
[test3] New video stream! (ssrc=877992763)
[test2] New video stream! (ssrc=3702397402)
[test2] New video stream! (ssrc=285435956)
[test3] New video stream! (ssrc=3702397404)
[test3] New video stream! (ssrc=877992763)
[test2] New video stream! (ssrc=3702397407)
[test2] New video stream! (ssrc=285435956)

Any clues of why I am getting these new ssrc values only for the 2nd and 3rd streams? I have provided a publicly accessible axis-camera URL that I found on the internet, so I hope you are able to reproduce/fix this issue.

**Comment by derrell** [comment] 2017-05-02 14:23
I tracked this down. The problem is that an ffmpeg command that generates rtp like this:
```
ffmpeg -i rtsp://217.17.220.110:554/axis-media/media.amp -an -c:v copy -bsf dump_extra -f rtp rtp://127.0.0.1:2323
```
uses the specified rtp port (2323) for rtp, and (without saying so; we're just supposed to know it), it uses the subsequent port, port+1 (2324, in this case) for rtcp.

Since our tests had test1 on port 2323, test2 on port 2324, and test3 on port 2325, we would get rtcp data from test1 on test2's rtp port. The streaming plugin doesn't expect rtcp data on the rtp port on which it is listening, and it gets confused.

I think this issue can be closed.

Derrell

**Comment by lminiero** [comment] 2017-05-02 14:26
Sorry for the last reply, I'm currently abroad for an event... thanks for the update! And yes, I think we can close the issue the behaviour being as you explained :+1:

**Closed by lminiero** 2017-05-02 14:26 UTC

**Comment by saket424** [comment] 2017-05-02 14:28
Lesson learned. The streaming plugin should preferably pick even ports so as to reserve the associated odd number port(even port +1) for rtcp.

Thanks for your help in isolating this seemingly strange issue which initially implicated janus but turned out to be pilot error

**Comment by lminiero** [comment] 2017-05-02 14:32
> The streaming plugin should preferably pick even ports so as to reserve the associated odd number port(even port +1) for rtcp.

Up to a few days ago, actually, it was never the Streaming plugin that chose the port, the controlling application or the user (via configuration) did. A recent change now allows for random ports to be picked if you pass 0 via API (not possible via configuration as you wouldn't be able to get the associated port), but I think it doesn't force even ports right now.
