### ISSUE TITLE
Configure script cannot find libsrtp

### ISSUE THREAD

**Issue by Yoric** [meetecho/janus-gateway#569] opened 2016-06-29 09:03 UTC
I'm using MacPorts and I have installed port `srtp`, which provides libsrtp, in version 1.4.4.

However, `./configure` gives me the following error:
```
checking for srtp_init in -lsrtp... no
configure: error: libsrtp not found.
```

**Comment by amnonbb** [comment] 2016-06-29 09:07
you need install development packege as well

**Comment by Yoric** [comment] 2016-06-29 09:16
I'm pretty sure that `srtp` is also a development package. It provides both the headers and `libsrtp.a`.

**Comment by lminiero** [comment] 2016-06-29 09:21
I guess the problem is the fact it's a static and not a shared library, then.

**Comment by Yoric** [comment] 2016-06-30 20:30
I have just tested with the latest HEAD for libsrtp, without any change.

@lminiero with `-lsrtp`, this should be looking for the static library, rather than the dynamic one, no?

**Comment by lminiero** [comment] 2016-07-01 07:37
I guess we can close this, since it was a configure tweak.

**Closed by lminiero** 2016-07-01 07:37 UTC

**Comment by soulfly** [comment] 2016-11-22 09:59
I have the same issue on macOS Sierra 

`./configure --prefix=/opt/janus JANUS_LIBS="-L/usr/local/opt/srtp/lib/ -L/usr/local/Cellar/openssl/1.0.2j/lib" JANUS_CFLAGS="-I/usr/local/opt/srtp/include -I/usr/local/Cellar/openssl/1.0.2j/include"`

it says 

```
checking for srtp_init in -lsrtp... no
configure: error: libsrtp not found.
```

I unstalled srtp via **brew install srtp** and it lives here: **/usr/local/opt/srtp/**

Does anybody can help with this?

**Comment by anildigital** [comment] 2016-12-12 15:04
Facing similar issue.

**Comment by lminiero** [comment] 2016-12-12 15:08
Very old issue. Check #702 instead.

**Comment by anildigital** [comment] 2016-12-12 15:10
@lminiero where to pass -lsrtp .. that option is not valid for ./configure

Also tried this 
./configure --disable-libsrtp2 --prefix=/usr/local/janus PKG_CONFIG_PATH=/usr/local/opt/openssl/lib/pkgconfig

still see ```checking for srtp_init in -lsrtp... no
configure: error: libsrtp not found``` 
Am I missing anything?

**Comment by anildigital** [comment] 2016-12-12 15:23
@soulfly were you able to solve this issue for macOS Sierra? Please let me know, I am stuck.

**Comment by soulfly** [comment] 2016-12-12 15:26
@anildigital yes, 

please follow
https://github.com/meetecho/janus-gateway#building-on-macos

and when compiling **srtp** from src you should use
**./configure --prefix=/usr/local** instead of **./configure --prefix=/usr**
