### ISSUE TITLE
CAll drop with Got a cleanup notification

### ISSUE THREAD

**Issue by SaqlainGardezi** [meetecho/janus-gateway#876] opened 2017-04-29 14:35 UTC
As soon as i make a call i get Got a cleanup notification which is running from on cleanup callback.
I am using code from     https://github.com/meetecho/janus-gateway/tree/master/html

**Comment by lminiero** [comment] 2017-04-29 15:11
No information provided at all means there's nothing we can do to help. Closing as not a code issue, please use the [meetecho-janus](https://groups.google.com/forum/#!forum/meetecho-janus) group for questions like these.

**Closed by lminiero** 2017-04-29 15:11 UTC

**Comment by klanjabrik** [comment] 2018-09-22 03:59
And here is another log:
`{
   "janus": "hangup",
   "session_id": 6321292002610623,
   "sender": 5555837625527010,
   "reason": "ICE failed"
}`

We already set stun_server (stun1.l.google.com:19302) and nat_1_1_mapping (IP Public)

**Comment by klanjabrik** [comment] 2018-09-22 05:56
Apparently the problem is related with firewall, so i open all udp port incoming and outgoing. the problem is gone. Alhamdulillaah.
