### ISSUE TITLE
Fatal race condition during sdp processing

### ISSUE THREAD

**Issue by Bug-Fairy** [meetecho/janus-gateway#1710] opened 2019-07-24 17:57 UTC
Fatal race if client disconnects while Janus is generating an SDP offer. Happened on multiple systems and reproducible with testing tools.

Nice agent gets destroyed by `janus_ice_webrtc_free` while still used by `nice_agent_add_stream` (and occasionally other libnice methods in `janus_ice_setup_local`)

Just putting mutexes around `janus_ice_setup_local` seems to fix this, but causes transport failures under load.

Stack trace (from 0.6.0, but pulled 0.7.3 and it's the same behavior):
[https://pastebin.com/raw/ys2WUSAP](https://pastebin.com/raw/ys2WUSAP)

**Comment by lminiero** [comment] 2019-07-24 18:29
IIRC `janus_ice_webrtc_free` is only invoked by libnice callbacks, so that should never happen. When refactoring in/out media to always use the same loop we worked on that on purpose. Currently abroad for a conference, so won't be able to look into this until I'm back next week. Pinging @atoppi in case he can have a look sooner than that.

**Comment by lminiero** [comment] 2019-07-24 18:29
PS: please provide a stack trace from master. Even if it's the same, line numbers won't, and I will not look at traces from older code.

**Comment by atoppi** [comment] 2019-07-25 08:23
Also a `libasan` trace might help.

**Comment by atoppi** [comment] 2019-07-25 08:30
@Bug-Fairy are you using a static number of loop threads (e.g. setting or uncommenting `event_loops` in the janus cfg) ?

**Comment by atoppi** [comment] 2019-07-26 10:05
I think the problem is that `janus_ice_setup_local` can be invoked either by:
- `janus_process_incoming_request`
- `janus_plugin_handle_sdp`

In the former case the calling thread owns the `handle->mutex` thread, while in the latter this is not true. This gives an opportunity to concurrently run `janus_ice_webrtc_free` and since there is only one reference to the Nice Agent, that agent is being instantly disposed of.

**Comment by Bug-Fairy** [comment] 2019-07-27 15:40
I worded the original message incorrectly. It's not when the client disconnects, but when it explicitly destroys its session immediately after asking for an SDP offer.

Latest master (commit `9fdabc45c75ed6c5d3b8f5a38a2478fdc3128c0f`) stack traces. All caused by the same scenario. Segfault is the most common one.
 * [Segfault](https://pastebin.com/raw/9VRMG2n5)
 * [libnice:ERROR:component.c:540:nice_component_attach_socket: assertion failed: (component->ctx != NULL)](https://pastebin.com/raw/XxLi3y8g)
 * [libnice:ERROR:component.c:1036:nice_component_constructed: assertion failed: (component->agent != NULL)](https://pastebin.com/raw/j467eu2L)
 * [g_mutex_clear() called on uninitialised or locked mutex](https://pastebin.com/raw/4LFsxgDc)

> @Bug-Fairy are you using a static number of loop threads (e.g. setting or uncommenting `event_loops` in the janus cfg) ?

Default `event_loops` setting, so not static.

> I think the problem is that `janus_ice_setup_local` can be invoked either by:
> 
>     * `janus_process_incoming_request`
> 
>     * `janus_plugin_handle_sdp`
> 
> 
> In the former case the calling thread owns the `handle->mutex` thread, while in the latter this is not true. This gives an opportunity to concurrently run `janus_ice_webrtc_free` and since there is only one reference to the Nice Agent, that agent is being instantly disposed of.

It's the latter case and is exactly what's happening. Nice Agent gets disposed of by the client calling janus:destroy while an SDP offer is being generated for it.

**Comment by lminiero** [comment] 2019-07-29 10:25
> Just putting mutexes around `janus_ice_setup_local` seems to fix this, but causes transport failures under load.

Can you elaborate what you mean by this? Mutex causing considerable performance drop, or a different issue that would need to be fixed somewhere else?

**Comment by Bug-Fairy** [comment] 2019-07-29 12:20
Appears to be a performance drop, but more than expected. I'll run more tests to get some numbers.

**Comment by atoppi** [comment] 2019-07-31 09:36
@Bug-Fairy if you have a working fix, could you please submit a PR ?

**Comment by lminiero** [comment] 2019-08-30 10:55
Fix merged, closing this issue.

**Closed by lminiero** 2019-08-30 10:55 UTC
