### ISSUE TITLE
janus-pp-rec has no stdout

### ISSUE THREAD

**Issue by externuz** [meetecho/janus-gateway#496] opened 2016-04-07 08:59 UTC
There is no stdout, when using janus-pp-rec:
1) Without options
2) With --header option

Janus from "master branch"
Cloned this time

**Comment by lminiero** [comment] 2016-04-07 11:10
Works here.

```
[lminiero@lminiero janus-gateway] $ ./janus-pp-rec 
Usage: ./janus-pp-rec source.mjr destination.[opus|webm]
       ./janus-pp-rec --header source.mjr (only parse header)
       ./janus-pp-rec --parse source.mjr (only parse and re-order packets)
```
```
[lminiero@lminiero janus-gateway] $ ./janus-pp-rec --header
Usage: ./janus-pp-rec source.mjr destination.[opus|webm]
       ./janus-pp-rec --header source.mjr (only parse header)
       ./janus-pp-rec --parse source.mjr (only parse and re-order packets)
```

**Comment by externuz** [comment] 2016-04-07 11:59
Try to clone repository right now, compile and run janus-pp-rec

**Comment by externuz** [comment] 2016-04-07 12:05
Ok, it works. The reason was:
- not installed build-essentials
- not installed automake
One of them. But it wasn't errors, when building

**Comment by lminiero** [comment] 2016-04-07 12:15
Thanks for the update, I guess we can close the issue then.

**Comment by externuz** [comment] 2016-04-07 12:19
Excurse me, but there is another problem with janus-pp-red. It's really no stdout when try to use janus-pp-rec twice. I mean, first time I have stdout, but next time there is no stdout;

**Comment by lminiero** [comment] 2016-04-07 12:21
I can't seem to be able to replicate here: just tried multiple times and always works as expected for me. If you can find out about more details on what's happening and why, feel free to share here and re-open.

**Comment by externuz** [comment] 2016-04-07 12:22
`externuz@mediacompiler:~$ /opt/janus/bin/janus-pp-rec
Usage: /opt/janus/bin/janus-pp-rec source.mjr destination.[opus|webm]
       /opt/janus/bin/janus-pp-rec --header source.mjr (only parse header)
       /opt/janus/bin/janus-pp-rec --parse source.mjr (only parse and re-order packets)
externuz@mediacompiler:~$ /opt/janus/bin/janus-pp-rec
externuz@mediacompiler:~$ /opt/janus/bin/janus-pp-rec
externuz@mediacompiler:~$ /opt/janus/bin/janus-pp-rec
externuz@mediacompiler:~$ /opt/janus/bin/janus-pp-rec
externuz@mediacompiler:~$ /opt/janus/bin/janus-pp-rec
externuz@mediacompiler:~$ /opt/janus/bin/janus-pp-rec
externuz@mediacompiler:~$ /opt/janus/bin/janus-pp-rec
externuz@mediacompiler:~$ /opt/janus/bin/janus-pp-rec
externuz@mediacompiler:~$ /opt/janus/bin/janus-pp-rec
externuz@mediacompiler:~$ /opt/janus/bin/janus-pp-rec --header
externuz@mediacompiler:~$ /opt/janus/bin/janus-pp-rec --parse`

**Comment by externuz** [comment] 2016-04-07 12:29
After system reboot I can use janus-pp-rec one time, then it needs to be rebooted

**Comment by externuz** [comment] 2016-04-07 12:31
On other system too. Ubuntu 14.04 server on each of them

**Comment by lminiero** [comment] 2016-04-07 12:33
Yeah but since we can't replicate this, we need more feedback than that :stuck_out_tongue_winking_eye:
Check if the application is actually crashing one of those times, and thus causing the stdoud part to hang there (I see no newlines in your previous log). Apart from that, there's not much we can do unless you check in what's really happening on your end.

**Comment by externuz** [comment] 2016-04-07 12:36
How can I check application crashing? I am not system programmer, I am using only javascript to develop apps. Maybe I need some debugger to do that?

**Comment by externuz** [comment] 2016-04-07 12:39
log from GDB:

Starting program: /opt/janus/bin/janus-pp-rec
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff1a90700 (LWP 1564)]
[Thread 0x7ffff1a90700 (LWP 1564) exited]
[Inferior 1 (process 1560) exited with code 0377]
(gdb)

**Comment by externuz** [comment] 2016-04-07 12:42
And GDB when I try to start `janus-pp-rec` twice:

```
externuz@mediacompiler:/opt/janus/bin$ gdb ./janus-pp-rec
GNU gdb (Ubuntu 7.7.1-0ubuntu5~14.04.2) 7.7.1
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./janus-pp-rec...done.
(gdb) r
Starting program: /opt/janus/bin/janus-pp-rec
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff1a90700 (LWP 1173)]
Usage: /opt/janus/bin/janus-pp-rec source.mjr destination.[opus|webm]
       /opt/janus/bin/janus-pp-rec --header source.mjr (only parse header)
       /opt/janus/bin/janus-pp-rec --parse source.mjr (only parse and re-order packets)
[Thread 0x7ffff1a90700 (LWP 1173) exited]
[Inferior 1 (process 1169) exited with code 0377]
(gdb) r
Starting program: /opt/janus/bin/janus-pp-rec
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff1a90700 (LWP 1175)]
[Thread 0x7ffff1a90700 (LWP 1175) exited]
[Inferior 1 (process 1174) exited with code 0377]
(gdb)
```

**Comment by externuz** [comment] 2016-04-07 12:45
valgrind:

```
externuz@mediacompiler:/opt/janus/bin$ valgrind ./janus-pp-rec -v
==1523== Memcheck, a memory error detector
==1523== Copyright (C) 2002-2013, and GNU GPL'd, by Julian Seward et al.
==1523== Using Valgrind-3.10.1 and LibVEX; rerun with -h for copyright info
==1523== Command: ./janus-pp-rec -v
==1523==
==1523==
==1523== HEAP SUMMARY:
==1523==     in use at exit: 8,664 bytes in 13 blocks
==1523==   total heap usage: 14 allocs, 1 frees, 8,701 bytes allocated
==1523==
==1523== LEAK SUMMARY:
==1523==    definitely lost: 0 bytes in 0 blocks
==1523==    indirectly lost: 0 bytes in 0 blocks
==1523==      possibly lost: 272 bytes in 1 blocks
==1523==    still reachable: 8,392 bytes in 12 blocks
==1523==         suppressed: 0 bytes in 0 blocks
==1523== Rerun with --leak-check=full to see details of leaked memory
==1523==
==1523== For counts of detected and suppressed errors, rerun with: -v
==1523== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
```

**Comment by externuz** [comment] 2016-04-07 12:52
and `strace`:

http://pastebin.com/6YdwjNLs

**Comment by externuz** [comment] 2016-04-07 13:23
Ok, there is my new GDB:

```
externuz@mediacompiler:/opt/janus/bin$ gdb ./janus-pp-rec
GNU gdb (Ubuntu 7.7.1-0ubuntu5~14.04.2) 7.7.1
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./janus-pp-rec...done.
(gdb) break main
Breakpoint 1 at 0x402360: file postprocessing/janus-pp-rec.c, line 77.
(gdb) run
Starting program: /opt/janus/bin/janus-pp-rec
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

Breakpoint 1, main (argc=1, argv=0x7fffffffe678) at postprocessing/janus-pp-rec.c:77
77      {
(gdb) next
78              janus_log_init(FALSE, TRUE, NULL);
(gdb) next
77      {
(gdb) next
78              janus_log_init(FALSE, TRUE, NULL);
(gdb) next
77      {
(gdb) next
78              janus_log_init(FALSE, TRUE, NULL);
(gdb) next
77      {
(gdb) next
78              janus_log_init(FALSE, TRUE, NULL);
(gdb) next
[New Thread 0x7ffff1a90700 (LWP 1649)]
81              if(g_getenv("JANUS_PPREC_DEBUG") != NULL) {
(gdb) next
89              if(argc != 3) {
(gdb) next
90                      JANUS_LOG(LOG_INFO, "Usage: %s source.mjr destination.[opus|webm]\n", argv[0]);
(gdb) next
Usage: /opt/janus/bin/janus-pp-rec source.mjr destination.[opus|webm]
91                      JANUS_LOG(LOG_INFO, "       %s --header source.mjr (only parse header)\n", argv[0]);
(gdb) next
       /opt/janus/bin/janus-pp-rec --header source.mjr (only parse header)
92                      JANUS_LOG(LOG_INFO, "       %s --parse source.mjr (only parse and re-order packets)\n", argv[0]);
(gdb) next
       /opt/janus/bin/janus-pp-rec --parse source.mjr (only parse and re-order packets)
93                      return -1;
(gdb) next
526     }
(gdb) next
__libc_start_main (main=0x402360 <main>, argc=1, argv=0x7fffffffe678, init=<optimized out>, fini=<optimized out>,
    rtld_fini=<optimized out>, stack_end=0x7fffffffe668) at libc-start.c:321
321     libc-start.c: No such file or directory.
(gdb) next
[Thread 0x7ffff1a90700 (LWP 1649) exited]
[Inferior 1 (process 1645) exited with code 0377]
```

**Comment by externuz** [comment] 2016-04-07 13:24
it means, i'm in `if(argc != 3)` block, but there is no stdout. Maybe problem in JANUS_LOG function?

**Comment by externuz** [comment] 2016-04-07 13:50
Maybe this can help? 
```
externuz@mediacompiler:/opt/janus-gateway$ make
make  all-recursive
make[1]: Entering directory `/opt/janus-gateway'
Making all in html
make[2]: Entering directory `/opt/janus-gateway/html'
make[2]: Nothing to be done for `all'.
make[2]: Leaving directory `/opt/janus-gateway/html'
make[2]: Entering directory `/opt/janus-gateway'
  CC       postprocessing/janus_pp_rec-janus-pp-rec.o
postprocessing/janus-pp-rec.c: In function ‘main’:
postprocessing/janus-pp-rec.c:359:9: warning: ignoring return value of ‘fread’, declared with attribute warn_unused_result [-Wunused-result]
    fread(prebuffer, sizeof(char), 1, file);
         ^
  CCLD     janus-pp-rec
make[2]: Leaving directory `/opt/janus-gateway'
make[1]: Leaving directory `/opt/janus-gateway'
```

**Comment by ploxiln** [comment] 2016-04-07 19:54
@lminiero it's a race between the logging thread and the invalid-arguments exit

```c
	if(argc != 3) {
		JANUS_LOG(LOG_INFO, "Usage: %s source.mjr destination.[opus|webm]\n", argv[0]);
		JANUS_LOG(LOG_INFO, "       %s --header source.mjr (only parse header)\n", argv[0]);
		JANUS_LOG(LOG_INFO, "       %s --parse source.mjr (only parse and re-order packets)\n", argv[0]);
		return -1;
	}
```

`janus_log_destroy()` should be called before returning from `main()`

**Comment by externuz** [comment] 2016-04-07 19:58
@ploxiln problem exists not only when arguments is empty, if I run `./janus-pp-rec--header file.mjr` I have such problem -no stdout

**Comment by ploxiln** [comment] 2016-04-07 20:03
The problem is possible in all cases where janus_pp_rec returns from main or exits without calling `janus_log_destroy()` and that does include the `--header` case:

```c
		if(header_only && parsed_header) {
			/* We only needed to parse the header */
			exit(0);
		}
```

But it's not deterministic - it depends on how the threads were scheduled by the OS, which can vary based on many other subtle factors. So for some people it will usually work, and for some people it usually won't, etc.

**Comment by externuz** [comment] 2016-04-07 20:06
@ploxiln - ok, my way is to change OS now :-)

**Comment by lminiero** [comment] 2016-04-07 20:07
@ploxiln good catch, the postprocessor is missing the same atexit code we have in the core to properly close the logger. Reopening the issue, will fix when I have some time to do so (currently busy at IETF).

**Comment by externuz** [comment] 2016-04-07 20:08
@lminiero @ploxiln thank you, guys!

**Comment by externuz** [comment] 2016-04-07 20:15
Wooops! Same problem on Debian8. Is there easy way to solve issue for janus-pp-rec only? Do janus_log_destroy() before exit main?

**Comment by lminiero** [comment] 2016-04-07 20:16
@externuz as I said, I can't work on this right now.

**Comment by lminiero** [comment] 2016-04-07 20:17
But yes, janus_log_destroy before main should do it.

**Comment by externuz** [comment] 2016-04-07 20:18
@lminiero Ok, my question was about it. Not about final solve. Sorry for my bad english ;)

**Comment by lminiero** [comment] 2016-04-07 21:08
No problem, was just clarifying! If you can confirm the additional line fixes it for you I'll make the change as soon as I have 5 free minutes.

**Comment by ploxiln** [comment] 2016-04-07 21:17
@externuz try #497

**Comment by lminiero** [comment] 2016-04-07 22:55
I believe @ploxiln fixed the issue, feel free to reopen if that's not the case.

**Closed by lminiero** 2016-04-07 22:55 UTC
