### ISSUE TITLE
 ICE failed for component 1 in stream 

### ISSUE THREAD

**Issue by ancin** [meetecho/janus-gateway#1354] opened 2018-09-09 13:24 UTC
I got the errors:

 ICE failed for component 1 in stream 1, but let's give it some time... (trickle received, answer received, alert not set)
[ERR] [ice.c:janus_ice_check_failed:1499] [641340839794355] ICE failed for component 1 in stream 1...
[janus.plugin.echotest-0x7fae88004ad0] No WebRTC media anymore

But I open the 3478 port of udp and tcp.

Any ideas for this ?

thanks very much.

**Comment by lminiero** [comment] 2018-09-10 09:13
Not a bug, question for the [group](https://groups.google.com/forum/#!forum/meetecho-janus). Closing.

**Closed by lminiero** 2018-09-10 09:13 UTC

**Comment by FrankMiller9000** [comment] 2019-08-09 14:05
Did anyone solve this?

**Comment by shihabkaranchery** [comment] 2020-02-17 11:28
libwebsockets logging: 0
WebSockets server started (port 8188)...
Secure WebSockets server started (port 8989)...
[WARN] Admin WebSockets server disabled
[WARN] Secure Admin WebSockets server disabled
JANUS WebSockets transport plugin initialized!
WebSockets thread started
Creating new session: 7153905178555544; 0x7fd244004c00
Creating new handle in session 7153905178555544: 7459090747208459; 0x7fd244004c00 0x7fd244005670
Creating new session: 8203604816882479; 0x7fd24400b8c0
Creating new handle in session 8203604816882479: 1196748959220562; 0x7fd24400b8c0 0x7fd244018910
Destroying session 8203604816882479; 0x7fd24400b8c0
Detaching handle from JANUS VideoRoom plugin; 0x7fd244018910 0x7fd24400b890 0x7fd244018910 0x7fd24401f760
[janus.plugin.videoroom-0x7fd24400b890] No WebRTC media anymore; 0x7fd244018910 0x7fd24401f760
[1196748959220562] Handle and related resources freed; 0x7fd244018910 0x7fd24400b8c0
[WSS-0x7fd244008340] Destroying WebSocket client
[7459090747208459] Creating ICE agent (ICE Lite mode, controlled)





Same issue, any idea how to fix this issue??


[ERR] [ice.c:janus_ice_check_failed:1692] [7459090747208459] ICE failed for component 1 in stream 1...
[janus.plugin.videoroom-0x7fd244001e60] No WebRTC media anymore; 0x7fd244005670 0x7fd244005fe0
[7459090747208459] WebRTC resources freed; 0x7fd244005670 0x7fd244004c00
[ERR] [transports/janus_http.c:janus_http_handler:1239] Invalid url /ws/v1/cluster/apps/new-application

**Comment by josephvvdn** [comment] 2020-02-17 11:31
same idea for me any idea

**Comment by sreelakshmitvvdn** [comment] 2020-02-17 11:37
[ERR] [ice.c:janus_ice_check_failed:1692] [7459090747208459] ICE failed for component 1 in stream 1... 

Am also getting same error. Please help me to fix this issue

**Comment by lminiero** [comment] 2020-02-17 11:40
Will you please stop writing out of scope questions on a very old, and **closed**, issue? As clearly explained in the guidelines, questions related to connectivity issues belong to the [group](https://groups.google.com/forum/#!forum/meetecho-janus), **not** here. Please make sure you read the guidelines there, as it's a VERY common question.

**Comment by shehinfn** [comment] 2020-02-26 14:21
getting the same issue

**Comment by rhrn** [comment] 2020-09-27 06:49
I solve my issue by set public ip address in nat section 1-1 mapping
`janus.jcfg`
```
nat: {
  ...
  nat_1_1_mapping = "XXX.XXX.XXX.XXX"
  ...
}
```

**Comment by llspalex** [comment] 2021-04-05 20:11
Someone reports setting NAT mapping in  janus config: https://github.com/meetecho/janus-gateway/issues/1354#issuecomment-699594364 

```
nat: {
  ...
  nat_1_1_mapping = "XXX.XXX.XXX.XXX"
  ...
}
```

**Comment by aleemjamil** [comment] 2024-09-04 09:50
nat: {
  ...
  nat_1_1_mapping = "XXX.XXX.XXX.XXX"
  ...
}
public address means?

> I solve my issue by set public ip address in nat section 1-1 mapping `janus.jcfg`
> 
> ```
> nat: {
>   ...
>   nat_1_1_mapping = "XXX.XXX.XXX.XXX"
>   ...
> }
> ```

public address means where janus is setup?
