### ISSUE TITLE
[1.x] Moderate API problem (mute /unmute)

### ISSUE THREAD

**Issue by techwipes** [meetecho/janus-gateway#2956] opened 2022-04-26 09:30 UTC
**What version of Janus is this happening on?**
v 1.0.0

**Have you tested a more recent version of Janus too?**
Yes, it works correctly in versions before v 1.0.0

**Was this working before?**
All moderate API worked correctly before

**Is there a gdb or libasan trace of the issue?**
No, I haven`t

**Additional context**
I have provided information about this issue in the google group.
Have received several messages from other developers who have also encountered this problem. That's why I decided to open a question here.
I believe this is a serious bug because it crashes the janus server.
[google group link](https://groups.google.com/g/meetecho-janus/c/0_XjKptQSAo)

**Comment by lminiero** [comment] 2022-04-26 09:42
> I believe this is a serious bug because it crashes the janus server.

From the description, it looks like a potential deadlock, not a crash. I'll have a look.

**Comment by lminiero** [comment] 2022-04-26 09:50
Yep, as I thought it was a deadlock, caused by a missing mutex unlock. It's fixed now. Thanks for the heads up!

**Closed** 2022-04-26 09:49 UTC
Labels: multistream

**Comment by techwipes** [comment] 2022-04-26 09:57
Thanks Lorenzo for the quick fix! Have a nice day!
