### ISSUE TITLE
!lws_is_final_fragment(wsi) seems to not working properly.

### ISSUE THREAD

**Issue by Triuman** [meetecho/janus-gateway#1197] opened 2018-04-04 10:23 UTC
https://github.com/meetecho/janus-gateway/blob/fc97a5c955d308fa3cad0385cd0b3fc855f9c1b9/transports/janus_websockets.c#L991

Second argument is always TRUE. When I remove that, it works with no problem. Otherwise it just stuck there.

**Comment by lminiero** [comment] 2018-04-04 10:26
Seems to be working fine here, so I'm hesitant to remove that check. What version of the library are you using? You may want to open an issue on the libwebsockets github project to see if this is the expected behaviour.

**Comment by Triuman** [comment] 2018-04-04 10:27
Just cloned the latest version.

**Comment by Triuman** [comment] 2018-04-04 10:40
@lminiero Could you please check the issue that I opened in warmcat/libwebsockets? He asked something that I cannot answer :)

**Comment by lminiero** [comment] 2018-04-09 16:42
Closing as it looks like it isn't an issue, and may be specific to your setup.

**Closed by lminiero** 2018-04-09 16:42 UTC
